/****************************************************************************
** File Name:      mmieng_menutable.c	                                    *
** Author:         allen				                                    *
** Date:           2004.09.09												*
** Copyright:      2003 Spreadtrum, Incoporated. All Rights Reserved. 		*
** Description:    									               			*
*****************************************************************************
**                         Important Edit History    						*
** -------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION         						*
** 09/2004        allen            Create
** 
****************************************************************************/
#ifdef WIN32
#include "std_header.h"
#endif
#ifdef ENG_SUPPORT
#include "guimenu.h"
#include "mmi_common.h"
#include "mmi_nv.h"
#include "mmi_menutable.h"
#include "mmi_text.h"
#include "mmi_modu_main.h"
#include "mmieng_text.h"
#include "mmieng_menutable.h"
#if (defined(DM_SUPPORT) || defined(DM_ONLY_SELFREG_SUPPORT))
#include "mmidm_text.h"
#endif

#ifdef CAMERA_SUPPORT
#include "mmidc_camera_text.h"
#endif

#ifdef PIM_SUPPORT
#include "mmipim_text.h"
#endif //PIM_SUPPORT

#ifdef BROWSER_SUPPORT
#include "browser_manager_text.h"
#endif
#ifdef MMIENG_PING_SUPPORT
#include "mmiping_text.h"
#endif
/**---------------------------------------------------------------------------*
 **                         Compiler Flag                                     *
 **---------------------------------------------------------------------------*/
#ifdef __cplusplus
    extern   "C"
    {
#endif

/**--------------------------------------------------------------------------*
 **                         MACRO DEFINITION                                 *
 **--------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------*/
/*                         TYPES/CONSTANTS                                 */
/*-------------------------------------------------------------------------*/

const GUIMENU_ITEM_T menu_eng[] =
{
    {ID_ENG_HELPINFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_HELP_INFO, 0, 0, 0, MENU_NULL},
    {ID_ENG_VERSIONINFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_VERSION_INFO, 0, 0, 0, MENU_NULL},
#ifdef WRE_SUPPORT
    {ID_ENG_WRE_VERSIONINFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_WRE_VERSION_INFO, 0, 0, 0, MENU_NULL}, 
#endif
    {ID_ENG_3RDPARTY_VERSIONINFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_3RDPARTY_VERSION_INFO, 0, 0, 0, MENU_NULL},        
    {ID_ENG_NETINFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_NET_INFO, 0, 0, 0, MENU_NULL},
    {ID_ENG_NETINFO_STATISTICS, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_NETINFO_STATISTICS, 0, 0, 0, MENU_NULL},
    {ID_ENG_PHONEINFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_PHONE_INFO, 0, 0, 0, MENU_NULL},
    {ID_ENG_ADC_CALIBRATE_INFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_ADC_CALIBRATE_INFO, 0, 0, 0, MENU_NULL},
    {ID_ENG_RESTOREENG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_RESTORE_ENG, 0, 0, 0, MENU_NULL},
    {ID_ENG_PARASET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_PARA_SET, 0, 0, 0, MENU_PARAM_SET},
    {ID_ENG_APPSET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_APP_SET, 0, 0, 0, MENU_APP_SET},
     {ID_ENG_AUDIO_SETTING, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_SETTING, 0, 0, 0, MENU_AUDIO_SETTING},    

#ifdef	BLUETOOTH_SUPPORT
    {ID_ENG_BTINFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_BT_INFO, 0, 0, 0, MENU_BT_INFO},
#endif
    {ID_ENG_LAYER1MONITOR, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_LAYER1_MONITOR, 0, 0, 0, MENU_NULL},
#ifdef GPS_SUPPORT
    {ID_ENG_GPS, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_GPS_TEST, 0, 0, 0, MENU_NULL},
#endif
#ifndef CARD_LOG
    {ID_ENG_IQ_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
       TXT_ENG_IQ_MODE, 0, 0, 0, MENU_NULL},
#endif
/*[START] Jerry Liang for ENG MODE powersweep 2008/07/30*/
//    {ID_ENG_POWERSWEEP_INFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
//        TXT_ENG_POWERSWEEP_INFO, 0, 0, 0, MENU_NULL},
/*[END] Jerry Liang for ENG MODE powersweep 2008/07/30*/
#ifdef PCLINK_SUPPORT
	{ID_ENG_PCLINK, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_PCLINK, 0, 0, 0, MENU_PCLINK},
#endif
	{ID_ENG_NVCOUNT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_NVCOUNT, 0, 0, 0, MENU_NULL},
#ifdef MMI_AUTOTEST_SUPPORT	 
	{ID_ENG_AUTO_TEST_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AUTO_TEST_SET, 0, 0, 0, MENU_AUTO_TEST_SET},
#endif	 
#ifdef WIFI_SUPPORT  
    {ID_ENG_WLAN_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_WLAN_SET, 0, 0, 0, MENU_WLAN_SET},
#endif
    {ID_ENG_MONKEY_TEST_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_MONKEY_TEST_SET, 0, 0, 0, MENU_NULL},
#ifdef MMI_TORCH_LED_SUPPORT
    {ID_ENG_TORCH_LED_TEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_TORCH_LED_TEST, 0, 0, 0, MENU_NULL},
#endif
#ifdef MMI_PVTEST_SUPPORT
    {ID_ENG_LCD_PV_TEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_PVLCD_TEST, 0, 0, 0, MENU_NULL},
    {ID_ENG_VIB_PV_TEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_PVVIB_TEST, 0, 0, 0, MENU_NULL},
#endif
    {ID_ENG_SD_PRESS_TEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
		TXT_ENG_SD_PRESS_INFO, 0, 0, 0, MENU_NULL},
    {ID_ENG_SIM_PRESS_TEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
		TXT_ENG_SIM_PRESS_INFO, 0, 0, 0, MENU_NULL},	
#if defined ENG_NETWORK_SET //zhouqin
    {ID_ENG_NETWORK_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_LTE_NETWORK_SET, 0, 0, 0, MENU_NULL},
#endif      
#if defined ENG_BAND_FREQ_SUPPORT //zhouqin
    {ID_ENG_BAND_FREQ_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_BAND_FREQ_SET, 0, 0, 0, MENU_NULL},
#endif        
#ifdef SFR_SUPPORT_CUCC
     {ID_ENG_CUCC_DM_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_CUCC_DM_SET, 0, 0, 0, MENU_CUCCDM_SET},
#endif
};

#ifdef MEDIA_DEMO_SUPPORT

const GUIMENU_ITEM_T media_demo_menu_eng[] =
{
    {ID_ENG_HELPINFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_HELP_INFO, 0, 0, 0, MENU_NULL},
    {ID_ENG_MEDIA_AUDIO_DEMO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_MEDIA_AUDIO_DEMO, 0, 0, 0, MENU_NULL},
        
    {ID_ENG_MEDIA_VIDEO_DEMO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_MEDIA_VIDEO_DEMO, 0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_video_demo_info[] = 
{
    {ID_ENG_BT_ADDRESS, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_EMG_BT_ADDR_INFO, 0, 0, 0, MENU_NULL},
    {ID_ENG_ENTER_EUT_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_ENTER_BT_EUT, 0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_audio_demo_info[] = 
{
    {ID_ENG_BT_ADDRESS, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_EMG_BT_ADDR_INFO, 0, 0, 0, MENU_NULL},
    {ID_ENG_ENTER_EUT_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_ENTER_BT_EUT, 0, 0, 0, MENU_NULL}
};

#endif
//net info start 

const GUIMENU_ITEM_T menu_net_info_show[] =
{
	{ID_ENG_NW_CAP, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_NW_CAP, 0, 0, 0, MENU_NW_CAP_ENG},
};

const GUIMENU_ITEM_T menu_nw_cap_eng[] =
{
	{ID_ENG_SERVINGCELL, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SERVING_CELL, 0, 0, 0, MENU_NULL},
	 {ID_ENG_ADJACENTCELL, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_THE_ADJACENT_CELL, 0, 0, 0, MENU_NULL},
	 {ID_ENG_BETWEEN_ADJACENTCELL_2G, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_BETWEEN_ADJACENT_CELL_2G, 0, 0, 0, MENU_NULL},
	 {ID_ENG_OUTFIELD_NETWORK_INFORMATION, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_OUTFIELD_NETWORK_INFORMATION, 0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_netinfo_statistics_eng[] =
{
	{ID_ENG_NETINFO_RESELECT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_NETINFO_RESELECT, 0, 0, 0, MENU_NULL},
	 {ID_ENG_NETINFO_HANDOVER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_NETINFO_HANDOVER, 0, 0, 0, MENU_NULL},
	 {ID_ENG_NETINFO_ATTACHTIME, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_NETINFO_ATTACHTIME, 0, 0, 0, MENU_NULL},
	 {ID_ENG_NETINFO_DROPTIMES, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_NETINFO_DROPTIMES, 0, 0, 0, MENU_NULL}
};


//net info end
#ifdef	BLUETOOTH_SUPPORT
const GUIMENU_ITEM_T menu_bt_info[] = 
{
	{ID_ENG_BT_ADDRESS, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_EMG_BT_ADDR_INFO, 0, 0, 0, MENU_NULL},
	{ID_ENG_ENTER_EUT_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_ENTER_BT_EUT, 0, 0, 0, MENU_NULL},
	{ID_ENG_LEAVE_EUT_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_LEAVE_BT_EUT, 0, 0, 0, MENU_NULL}, 
	{ID_ENG_BT_SSP_DEBUG_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_BT_SSP_DEBUG, 0, 0, 0, MENU_NULL},
	{ID_ENG_BT_BQB_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_BT_BQB_MODE, 0, 0, 0, MENU_NULL},
#ifndef WIN32        
#ifdef  BLUETOOTH_SUPPORT_SPRD_BT
    	{ID_ENG_BT_VER_INFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_VERSION_INFO, 0, 0, 0, MENU_NULL}
#endif
#endif
};
#endif

const GUIMENU_ITEM_T menu_param_set[] = 
{
	{ID_ENG_POWERKEY, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_POWER_KEY, 0, 0, 0, MENU_NULL},
	{ID_ENG_VOICEPARAM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_VOICE_PARAM, 0, 0, 0, MENU_VOICE_PARAM},
	{ID_ENG_LCDPARAM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_LCD_PARAM, 0, 0, 0, MENU_LCD_PARAM},
	{ID_ENG_DEBUGPARAM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DEBUG_PARAM, 0, 0, 0, MENU_DEBUG_PARAM},
	{ID_ENG_RFPARAM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_RF_PARAM, 0, 0, 0, MENU_RF_PARAM},
	{ID_ENG_HWPARAM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_HW_PARAM, 0, 0, 0, MENU_HW_PARAM},
	{ID_ENG_ARMLOG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_ARM_LOG, 0, 0, 0, MENU_NULL},

	{ID_ENG_DSPLOG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DSP_LOG, 0, 0, 0, MENU_NULL},	 

    {ID_ENG_ARMLOG_POWER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_USB_LOG, 0, 0, 0, MENU_NULL},
#ifdef CMMB_SUPPORT
    {ID_ENG_MTV_LOG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_MTV_LOG, 0, 0, 0, MENU_MTV_LOG},
#endif
	{ID_ENG_SLEEPMODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SLEEP_MODE, 0, 0, 0, MENU_NULL},
	{ID_ENG_AUTOPOWERON, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AUTO_POWERON, 0, 0, 0, MENU_NULL},
	{ID_ENG_GPRS, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_GPRS, 0, 0, 0, MENU_NULL},
	{ID_ENG_SENSOR_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SENSOR_MODE, 0, 0, 0, MENU_NULL},
	{ID_ENG_TCPIP_DEBUG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_TCPIP_DEBUG ,0, 0, 0, MENU_TCPIP_DEBUG}, 
#ifdef NANDBOOT_SUPPORT	  
	 {ID_ENG_XSR_DEBUG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_XSR_DEBUG ,0, 0, 0, MENU_NULL}, 
#endif

	 //MS00216980 cheney
	 {ID_ENG_CMCC_TEST_FLAG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_CMCC_TEST_CONFIG ,0, 0, 0, MENU_NULL},
	 
    {ID_ENG_STANDBY_TIME,TIP_NULL,{TXT_ENG_OK,TXT_NULL,TXT_ENG_RETURN},
    TXT_ENG_STANDBY_TIME,0,0,0,MENU_STANDBY_TIME}, 
    {ID_ENG_GET_FLASH_INFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
    TXT_ENG_GET_FLASH_INFO ,0, 0, 0, MENU_NULL},
    {ID_ENG_UPDATE_IMEI, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
    TXT_ENG_UPDATE_IMEI ,0, 0, 0, MENU_NULL},
#ifdef DSP_USB_LOG
    {ID_ENG_DSPCARD_LOG_ENABLE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DSPCARD_LOG_ENABLE, 0, 0, 0, MENU_NULL},//xuefangjiang 20110729
#endif
#if 0
    {ID_ENG_MEM_PRESS_TEST, TIP_NULL, {TXT_COMMON_OK, TXT_NULL, STXT_RETURN},
     TXT_ENG_MEM_PRESS_INFO, 0, 0, 0, MENU_NULL},
#endif
};
#ifdef MMI_AUTOTEST_SUPPORT
const GUIMENU_ITEM_T menu_auto_test_set[] = 
{    
    /*,@CR247145 renwei add begin*/
    {ID_ENG_AT_ALL_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_AT_ALL_SET, 0, 0, 0, MENU_NULL},	 
    /*,@CR247145 renwei add end*/
	{ID_ENG_AT_IMAGE_ID, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AT_IMAGE_ID, 0, 0, 0, MENU_NULL},

	{ID_ENG_AT_TEXT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AT_TEXT, 0, 0, 0, MENU_NULL},
	 
	{ID_ENG_AT_WIN_MSG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AT_WIN_MSG, 0, 0, 0, MENU_NULL},

	{ID_ENG_AT_TP, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AT_TP, 0, 0, 0, MENU_NULL},
     
	{ID_ENG_AT_KEY, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AT_KEY, 0, 0, 0, MENU_NULL},

	{ID_ENG_AT_MSG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AT_MSG, 0, 0, 0, MENU_NULL},

	{ID_ENG_AT_SOFTKEY, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AT_SOFTKEY, 0, 0, 0, MENU_NULL},

	{ID_ENG_AT_TITLE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AT_TITLE, 0, 0, 0, MENU_NULL},

	{ID_ENG_AT_POINTER_STATE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AT_POINTER_STATE, 0, 0, 0, MENU_NULL},	 

	{ID_ENG_AT_BACKLIGHT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AT_BACKLIGHT, 0, 0, 0, MENU_NULL},	 
};
#endif
#ifdef WIFI_SUPPORT
const GUIMENU_ITEM_T menu_wlan_set[] = 
{    
    {ID_ENG_WLAN_PERFORMANCE_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_WLAN_PERFORMANCE_MODE, 0, 0, 0, MENU_NULL},

    {ID_ENG_WLAN_IPERF, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_WLAN_IPERF, 0, 0, 0, MENU_NULL},

    {ID_ENG_WLAN_RADIO_FREQUENCY, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_WLAN_RADIO_FREQUENCY, 0, 0, 0, MENU_NULL},
};
#endif

#ifdef SFR_SUPPORT_CUCC
const GUIMENU_ITEM_T menu_cuccdm_set[] = 
{    
    {ID_ENG_CUCC_DM_REG_PER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_CUCC_DM_SET_REG_PER, 0, 0, 0, MENU_NULL},

    {ID_ENG_CUCC_DM_REG_MODE,TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_CUCC_DM_SET_REG_MODE, 0, 0, 0, MENU_NULL},
};
#endif

const GUIMENU_ITEM_T menu_app_set[] =
{	
#if 0
	{ID_ENG_WAPDEBUG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_WAP_LOG, 0, 0, 0, MENU_WAP_LOG},
#endif
	{ID_ENG_CALLFORWARD_QUERY, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_CALLFORWARD_QUERY, 0, 0, 0, MENU_NULL},
#ifdef MMIENG_PING_SUPPORT
    {ID_ENG_PING_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_PING_MODE, 0, 0, 0, MENU_NULL},
#endif
#ifdef CARD_LOG	
	{ID_ENG_CARDLOG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_CARDLOG, 0, 0, 0, MENU_NULL},
#endif	 
    {ID_ENG_NPS_TIMER_CHANGE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_NPS_TIMER_CHANGE, 0, 0, 0, MENU_NULL},
#ifdef NANDBOOT_SUPPORT
	{ID_ENG_HIDDEN_PARTITION_VISIBLE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_HIDDEN_PARTITION_VISIBLE, 0, 0, 0, MENU_NULL},	 
#endif	 
	{ID_ENG_DV_FRAME_FRE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DV_FRAME_FRE, 0, 0, 0, MENU_NULL},
#ifdef  CAMERA_SUPPORT	 
	{ID_ENG_DC_PARAM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DC_PARAM, 0, 0, 0, MENU_DC_PARAM},
#endif	 
    {ID_ENG_AUTO_ANSWER_CALL_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AUTO_ANSWER_CALL, 0, 0, 0, MENU_NULL},
#ifdef PIM_SUPPORT
	{ID_ENG_PIM_DEBUG_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_PIM_DEBUG_SETTING, 0, 0, 0, MENU_NULL},
#endif //PIM_SUPPORT
#if (defined(DM_SUPPORT) || defined(DM_ONLY_SELFREG_SUPPORT))
    {ID_ENG_DM_PRAR_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_DM_SETTING, 0, 0, 0, MENU_NULL},
#endif
#ifdef DCD_SUPPORT
	{ID_ENG_DCD_SETTING, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DCD_SET, 0, 0, 0, MENU_DCD_SET},
#endif
#ifdef MMI_SMS_RETRY_SUPPORT
	 {ID_ENG_SMS_RETRY, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	  TXT_SMS_RETRY_SET, 0, 0, 0, MENU_NULL},
#endif
	 {ID_ENG_UA, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	  TXT_ENG_UA_SETTINGS, 0, 0, 0, MENU_UA},
    {ID_ENG_CALL_BARRING, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_CALL_BARRING, 0, 0, 0, MENU_NULL},
#ifdef MMI_RES_ORIENT_BOTH 
    {ID_ENG_SET_ANGLE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SET_ANGLE, 0, 0, 0, MENU_NULL},
#endif
#ifdef JAVA_SUPPORT_IA
	{ID_ENG_JAVA_AUTO_TCK_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_JAVA_AUTO_TCK_MODE, 0, 0, 0, MENU_NULL},
#endif
#ifdef BROWSER_SUPPORT
    {ID_ENG_BROWSER_LOG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_BROWSER_LOG, 0, 0, 0, MENU_NULL},

    {ID_ENG_BROWSER_Change_URL, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_BROWSER_CHANGE_URL, 0, 0, 0, MENU_NULL},
    {ID_ENG_BROWSER_DEFAULT_TYPE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_BM_SET_SELECT_BROWSER, 0, 0, 0, MENU_NULL},	 
    {ID_ENG_SPN_PNN_ORDER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_PNN_ORDER, 0, 0, 0, MENU_NULL},	 
#endif
    {ID_ENG_SCREEN_LOG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
    TXT_ENG_SCREEN_LOG, 0, 0, 0, MENU_NULL},
#ifdef PRINTSCREEN_SUPPORT
	{ID_ENG_PRINTSCREEN, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_PRINTSCREEN, 0, 0, 0, MENU_NULL},
#endif
#ifdef MMI_DUALMODE_ENABLE
    {ID_ENG_NETWORK_TYPE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},TXT_ENG_NETWORK_TYPE, 0, 0, 0, NULL},
#endif
    {ID_ENG_NETWORK_ATTACH_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},TXT_DATA_CONNECTION_SET, 0, 0, 0, NULL},
#ifdef MMISRV_AUDIO_TEST_SUPPORT
	{ID_ENG_AUDIO_SELF_TEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AUDIO_SELF_TEST, 0, 0, 0, MENU_NULL},
#endif

#ifdef TP_TEST_SUPPORT
    {ID_ENG_TP_TEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
    TXT_ENG_TP_SELF_TEST, 0, 0, 0, MENU_NULL},
#endif

    {ID_ENG_PB_DEBUG, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
    TXT_ENG_PB_DEBUG_MENU, 0, 0, 0, MENU_NULL},

#ifdef MP3_SUPPORT
    {ID_ENG_MP3_PLAY_TEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
    TXT_ENG_MP3_PLAY_TEST, 0, 0, 0, MENU_NULL},
#endif

    {ID_ENG_DTMF_SET_TIMER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_DTMF_SET_TIMER, 0, 0, 0, MENU_NULL},
#ifdef ENG_SECONDEDAC_SUPPORT
    {ID_ENG_SECONDEDAC_ENABLE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SECONDEDAC_ENABLE, 0, 0, 0, MENU_NULL},
#endif
   {ID_ENG_TEST_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_TEST_MODE, 0, 0, 0, MENU_NULL},
   {ID_ENG_FORBID_ALL_DATA, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_FORBID_ALL_DATA, 0, 0, 0, MENU_NULL}, 
   {ID_ENG_USB_TEST_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_USB_TEST_SET, 0, 0, 0, MENU_NULL},
   {ID_ENG_ESD_TEST_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_ESD_TEST_SET, 0, 0, 0, MENU_NULL},
   {ID_ENG_UPDATE_TEST_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_UPDATE_TEST_SET, 0, 0, 0, MENU_NULL},
   {ID_ENG_FOTA_SET_BEGIN_NV, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_FOTA_SET_BEGIN_NV, 0, 0, 0, MENU_NULL},
   {ID_ENG_IMS_NV_PARAM_ID, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_IMS_NV_PARAM_ID, 0, 0, 0, MENU_NULL},
   {ID_ENG_UPLMN_CHANGE_ID, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_UPLMN_CAHNGE_ID, 0, 0, 0, MENU_NULL},
   {ID_ENG_GCF_BANG41_ID, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_GCF_BAND41_SET, 0, 0, 0, MENU_NULL},
   {ID_ENG_VOLTE_SHOW_ID, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_VOLTE_SHOW_SET, 0, 0, 0, MENU_NULL},
};

const GUIMENU_ITEM_T menu_voice_param[] = 
{
	{ID_ENG_VOICEPARAM_HDSTTONE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_HDSTSDTONE, 0, 0, 0, MENU_NULL},
	{ID_ENG_VOICEPARAM_CLOSE_HDSTTONE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_C_HDSTSDTONE, 0, 0, 0, MENU_NULL},
	{ID_ENG_VOICEPARAM_EARPHTONE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_EARPHSDTONE, 0, 0, 0, MENU_NULL},
	{ID_ENG_VOICEPARAM_CLOSE_EARPHTONE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_C_EARPHSDTONE, 0, 0, 0, MENU_NULL},
	{ID_ENG_VOICEPARAM_HDSTDGT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_HDSTDGT, 0, 0, 0, MENU_NULL},
	{ID_ENG_VOICEPARAM_HDFREDGT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_HDFREDGT, 0, 0, 0, MENU_NULL},
	{ID_ENG_VOICEPARAM_EARPHDGT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_EARPHDGT, 0, 0, 0, MENU_NULL},
	{ID_ENG_VOICEPARAM_HDSTPGA, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_HDSTPGA, 0, 0, 0, MENU_NULL},
	{ID_ENG_VOICEPARAM_HDFREPGA, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_HDFREPGA, 0, 0, 0, MENU_NULL},
	{ID_ENG_VOICEPARAM_EARPHPGA, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_EARPHPGA, 0, 0, 0, MENU_NULL},
	{ID_ENG_VOICEPARAM_HDSTSCL, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_HDSTSCL, 0, 0, 0, MENU_NULL},
	{ID_ENG_VOICEPARAM_HDFRESCL, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_HDFRESCL, 0, 0, 0, MENU_NULL},
	{ID_ENG_VOICEPARAM_EARPHSCL, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_EARPHSCL, 0, 0, 0, MENU_NULL}
};

#ifdef SUBLCD_SIZE_NONE
const GUIMENU_ITEM_T menu_lcd_param[] = 
{
//	{ID_ENG_LCDPARAM_CON, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
// 	 TXT_ENG_CONTRAST, 0, 0, 0, NULL},
	{ID_ENG_LCDPARAM_BRT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_BRIGHTNESS, 0, 0, 0, NULL}
};
#else
const GUIMENU_ITEM_T menu_lcd_param[] = 
{
//	{ID_ENG_LCDPARAM_CON, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
//	 TXT_ENG_CONTRAST, 0, 0, 0, MENU_LCD_PARAM_CON},
	{ID_ENG_LCDPARAM_BRT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_BRIGHTNESS, 0, 0, 0, MENU_LCD_PARAM_BRT}
};
#endif

const GUIMENU_ITEM_T menu_lcd_param_con[] = 
{
	{ID_ENG_LCDPARAM_CON_MAIN, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_MAINLCD, 0, 0, 0, MENU_NULL},
	{ID_ENG_LCDPARAM_CON_SUB, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SUBLCD, 0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_lcd_param_brt[] = 
{
//	{ID_ENG_LCDPARAM_BRT_MAIN, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
//	 TXT_ENG_MAINLCD, 0, 0, 0, MENU_NULL},
	{ID_ENG_LCDPARAM_BRT_SUB, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SUBLCD, 0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_debug_param[] = 
{
	//{ID_ENG_DEBUGPARAM_SMSASSERT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	// TXT_ENG_SMSASSERT, 0, 0, 0, MENU_SMS_ASSERT},
	//{ID_ENG_DEBUGPARAM_BAND, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	// TXT_ENG_BAND, 0, 0, 0, MENU_NULL},
//	{ID_ENG_DEBUGPARAM_PORT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
//	 TXT_ENG_PORTSET, 0, 0, 0, MENU_NULL},
	{ID_ENG_DEBUGPARAM_ASSERTMODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_ASSERTMODE, 0, 0, 0, MENU_NULL},
	//{ID_ENG_DEBUGPARAM_ASSERTTARGET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	// TXT_ENG_ASSERTTARGET, 0, 0, 0, MENU_NULL},
    {ID_ENG_DEBUGPARAM_MANUALASSERT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_MANUALASSERT, 0, 0, 0, MENU_MANUAL_ASSERT},
	{ID_ENG_DEBUGPARAM_FORBID_PLMN, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_FORBIDPLMN, 0, 0, 0, MENU_NULL},
#ifdef PLATFORM_SC6800H
	{ID_ENG_DEBUGPARAM_PLMN_SELECT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_PLMN_SELECT, 0, 0, 0, MENU_PLMN_SELECT}	 
#endif	 
};

const GUIMENU_ITEM_T menu_plmn_select[] = 
{
    {ID_ENG_DEBUGPARAM_SIM1_PLMN_SELECT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_SIM_SEL_SIM1, 0, 0, 0, MENU_NULL},	 
#if  defined   MMI_MULTI_SIM_SYS_DUAL
    {ID_ENG_DEBUGPARAM_SIM2_PLMN_SELECT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_SIM_SEL_SIM2, 0, 0, 0, MENU_NULL},	                     
#elif defined MMI_MULTI_SIM_SYS_TRI
    {ID_ENG_DEBUGPARAM_SIM2_PLMN_SELECT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_SIM_SEL_SIM2, 0, 0, 0, MENU_NULL},  
    {ID_ENG_DEBUGPARAM_SIM3_PLMN_SELECT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_SIM_SEL_SIM3, 0, 0, 0, MENU_NULL},	              
#elif defined MMI_MULTI_SIM_SYS_QUAD
    {ID_ENG_DEBUGPARAM_SIM2_PLMN_SELECT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_SIM_SEL_SIM2, 0, 0, 0, MENU_NULL},  
    {ID_ENG_DEBUGPARAM_SIM3_PLMN_SELECT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_SIM_SEL_SIM3, 0, 0, 0, MENU_NULL},
    {ID_ENG_DEBUGPARAM_SIM4_PLMN_SELECT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_SIM_SEL_SIM4, 0, 0, 0, MENU_NULL},   
#endif
};

const GUIMENU_ITEM_T menu_sms_assert[] = 
{
	{ID_ENG_DEBUGPARAM_SMSASSERT_OPEN, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_OPEN_COMN, 0, 0, 0, MENU_NULL},
	{ID_ENG_DEBUGPARAM_SMSASSERT_CLOSE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_CLOSE, 0, 0, 0, MENU_NULL}
};




const GUIMENU_ITEM_T menu_manual_assert[] = 
{
	{ID_ENG_DEBUGPARAM_MANUALASSERT_RESTART, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_ASSERT_RESTART, 0, 0, 0, MENU_NULL},
	{ID_ENG_DEBUGPARAM_MANUALASSERT_INFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_ASSERT_INFO, 0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T menu_rf_param[] = 
{
	{ID_ENG_RFPARAM_SEND, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SEND_POWER, 0, 0, 0, MENU_NULL}
};


const GUIMENU_ITEM_T menu_hw_param[] = 
{
#ifndef ENGTD_SUPPORT
	{ID_ENG_HWPARAM_NETLOST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_NETLOST, 0, 0, 0, MENU_NULL},
#endif
	{ID_ENG_HWPARAM_TCV, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_TCV, 0, 0, 0, MENU_NULL},
#if 0
	{ID_ENG_HWPARAM_AFC, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AFC, 0, 0, 0, MENU_NULL},
	{ID_ENG_HWPARAM_PA, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_PA, 0, 0, 0, MENU_NULL},
	{ID_ENG_HWPARAM_AGC, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_AGC, 0, 0, 0, MENU_NULL},
#endif
	{ID_ENG_HWPARAM_RATE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_ERRRATE, 0, 0, 0, MENU_NULL}
};

//for SUPPORT_STANDBY_RECORD
const GUIMENU_ITEM_T menu_standby_time[] =
{    
    {ID_ENG_SHOW_STANDBY_TIME,TIP_NULL,{TXT_ENG_OK,TXT_NULL,TXT_ENG_RETURN},
        TXT_ENG_SHOW_STANDBY_TIME,0,0,0,MENU_NULL},
	{ID_ENG_STANDBY_SET,TIP_NULL,{TXT_ENG_OK,TXT_NULL,TXT_ENG_RETURN},
	TXT_ENG_STANDBY_TIME_SET,0,0,0,MENU_NULL}
};
//end for SUPPORT_STANDBY_RECORD

#ifdef CMMB_SUPPORT
const GUIMENU_ITEM_T menu_mtv_log[] = 
{
    {ID_ENG_MTV_LOG_SWITCH, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_MTV_LOG_SWITCH, 0, 0, 0, MENU_NULL},
    {ID_ENG_MTV_LOG_TO_BB_SWITCH, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_MTV_LOG_TO_BB_SWITCH, 0, 0, 0, MENU_NULL},
    {ID_ENG_MTV_LOG_STORAGE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_MTV_LOG_STORAGE_SELECT, 0, 0, 0, MENU_NULL}
};
#endif

const GUIMENU_ITEM_T menu_tcpip_debug[] = 
{
	{ID_ENG_CAP_OUTPUT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_CAP_OUTPUT, 0, 0, 0, MENU_NULL}
	
};          

const GUIMENU_ITEM_T menu_dcd_setting[] = 
{
	{ID_ENG_DCD_NET_SETTING, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_NET_SET, 0, 0, 0, MENU_NULL},
	{ID_ENG_DCD_UPDATE_NOTE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DCD_NOTE, 0, 0, 0, MENU_NULL}
};


const GUIMENU_ITEM_T menu_ua[] = 
{
       {ID_ENG_UA_AGENT_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_UA_AGENT, 0, 0, 0, MENU_NULL},
	{ID_ENG_UA_PROFILE_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_UA_PROFILE, 0, 0, 0, MENU_NULL},
#if 0
	{ID_ENG_USER_AGENT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_UA, 0, 0, 0, MENU_NULL},
	{ID_ENG_UA_PROFILE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_UA_PROFILE, 0, 0, 0, MENU_NULL},
	{ID_ENG_UA_DEFAULT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DEFAULT, 0, 0, 0, MENU_NULL},
	 #ifdef MMI_ENABLE_DCD
	 {ID_ENG_UA_DCD_DEFAULT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_DCD_DEFAULT, 0, 0, 0, MENU_NULL},
	 #endif
	{ID_ENG_WAPMMS_SAS_TEST_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SAS_TEST_MODE, 0, 0, 0, MENU_NULL},
#endif
};

const GUIMENU_ITEM_T menu_ua_sub[] = 
{
    {ID_ENG_UA_SET_ONOFF, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
    	 TXT_ENG_UA_ON_OR_OFF, 0, 0, 0, MENU_NULL},
    {ID_ENG_UA_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
    	 TXT_ENG_UA_SET, 0, 0, 0, MENU_NULL},
    {ID_ENG_UA_SET_SHOW, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
    	 TXT_ENG_UA_SHOW, 0, 0, 0, MENU_NULL},
};

const GUIMENU_ITEM_T menu_wap_log[] = 
{
	{ID_ENG_WAP_LOG_ON, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_ON, 0, 0, 0, MENU_NULL},
	{ID_ENG_WAP_LOG_OFF, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_OFF, 0, 0, 0, MENU_NULL},
};

const GUIMENU_ITEM_T	menu_chip_test[] =
{
    {ID_ENG_CHIP_TEST,		TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        TXT_ENG_START_CHIP_TEST,	0, 0, 0, MENU_NULL},
	{ID_ENG_CHIP_TEST_SETTING,		TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        STXT_MAIN_SETTING,	0, 0, 0, MENU_NULL},
};

//工厂测试、研发调试
const GUIMENU_ITEM_T	menu_cmmb_main[] =
{
    {ID_ENG_CMMB_FACTORY_TEST,   TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL}, TXT_ENG_CMMB_FACTORY_TEST,	0, 0, 0, MENU_NULL},
    {ID_ENG_CMMB_RD_TEST,        TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL}, TXT_ENG_CMMB_RD_TEST,	0, 0, 0, MENU_NULL},
};

//研发调试：IQ数据、Display
const GUIMENU_ITEM_T	menu_cmmb_rd_test[] =
{
    {ID_ENG_CMMB_DISPLAY,   TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL}, TXT_ENG_CMMB_DISPLAY, 0, 0, 0, MENU_NULL},
   #ifdef MBBMS_SUPPORT
    {ID_MBBMS_INTERFACE_TEST,   TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL}, TXT_ENG_MBBMS_INTERFACE_TEST,0, 0, 0, MENU_NULL},
    {ID_MBBMS_SMD_COUNTER,TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL}, TXT_ENG_MBBMS_SMD_COUNTER,0, 0, 0, MENU_NULL},
    {ID_MBBMS_AUDIO,      TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL}, TXT_ENG_MBBMS_AUDIO_SERVICE,0, 0, 0, MENU_NULL},
#ifdef DEMOD_HW_SIANO
    {ID_MBBMS_LOG_CONTROL,   TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL}, TXT_ENG_MBBMS_LOG,0, 0, 0, MENU_NULL},	
#endif
    #endif
};

//工厂测试：有信号测试、无信号测试
const GUIMENU_ITEM_T	menu_cmmb_factory_test[] =
{
    {ID_ENG_CMMB_FACTORY_HAVE_SIGNAL,   TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL}, TXT_ENG_CMMB_FACTORY_HAVE_SIGNAL,	0, 0, 0, MENU_NULL},
    {ID_ENG_CMMB_FACTORY_NO_SIGNAL,     TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL}, TXT_ENG_CMMB_FACTORY_NO_SIGNAL, 0, 0, 0, MENU_NULL},
    {ID_ENG_CMMB_SN,                    TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL}, TXT_ENG_CMMB_SN_NO, 0, 0, 0, MENU_NULL},
};

//有信号测试
const GUIMENU_ITEM_T	menu_cmmb_ok_signal[] =
{
    {ID_ENG_CMMB_PLAY,      TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL}, TXT_NET_PLAY,	0, 0, 0, MENU_NULL},
};

//无信号测试: RF测试、解码测试
const GUIMENU_ITEM_T	menu_cmmb_no_signal[] =
{
    {ID_ENG_CMMB_RF_TEST,       TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL}, TXT_ENG_CMMB_RF_TEST,	0, 0, 0, MENU_NULL},
};


const GUIMENU_ITEM_T menu_iq_mode[] = 
{
	{ID_ENG_IQ_DATA_ONOFF, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_IQ_MODE_ONOFF, 0, 0, 0, MENU_NULL},//
	{ID_ENG_IQ_DATA, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_IQ_DATA, 0, 0, 0, MENU_NULL}
};

const GUIMENU_ITEM_T	menu_iq_data_enable[] =
{
    {ID_ENG_IQ_DATA_ENABLE, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        TXT_ENG_IQ_DATA_ENABLE, 0, 0, 0, MENU_NULL},
    {ID_ENG_IQ_DATA_SETTINGS, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        STXT_MAIN_SETTING,	0, 0, 0, MENU_IQ_DATA_SETTINGS},
};

const GUIMENU_ITEM_T	menu_iq_data_disable[] =
{
    {ID_ENG_IQ_DATA_DISABLE, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        TXT_ENG_IQ_DATA_DISABLE, 0, 0, 0, MENU_NULL},
    {ID_ENG_IQ_DATA_SETTINGS, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        STXT_MAIN_SETTING,	0, 0, 0, MENU_IQ_DATA_SETTINGS},
};

const GUIMENU_ITEM_T	menu_iq_data_settings[] =
{
    {ID_ENG_IQ_DATA_MODES_SETTINGS, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        TXT_ENG_IQ_DATA_MODE_SETTINGS, 0, 0, 0, MENU_NULL},
    {ID_ENG_IQ_DATA_POWER_ON_START, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        TXT_ENG_IQ_DATA_POWER_ON_START,	0, 0, 0, MENU_NULL},
};

const GUIMENU_ITEM_T	menu_iq_data_mode_setting[] =
{
    {ID_ENG_IQ_DATA_MODE_SETTING_ENABLE, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        TXT_ENG_IQ_DATA_ENABLE, 0, 0, 0, MENU_NULL},
    {ID_ENG_IQ_DATA_MODE_SETTING, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        STXT_MAIN_SETTING, 0, 0, 0, MENU_IQ_DATA_MODE_SETTING_SET},
};

const GUIMENU_ITEM_T	menu_iq_data_mode_setting_set[] =
{
    {ID_ENG_IQ_DATA_MODE_SETTING_FORMAT, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        TXT_ENG_IQ_DATA_FORMAT_SETTING, 0, 0, 0, MENU_NULL},
    {ID_ENG_IQ_DATA_MODE_SETTING_CHANNEL, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        TXT_ENG_IQ_DATA_CHANNEL_SETTING, 0, 0, 0, MENU_NULL},
    {ID_ENG_IQ_DATA_MODE_SETTING_TIME_LIMIT, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        TXT_ENG_IQ_DATA_TIME_LIMIT, 0, 0, 0, MENU_NULL},
    {ID_ENG_IQ_DATA_MODE_SETTING_FRAME_LENGTH, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        TXT_ENG_IQ_DATA_FRAME_LENGTH, 0, 0, 0, MENU_NULL},
    {ID_ENG_IQ_DATA_MODE_SETTING_BLOCK_COUNT, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},
        TXT_ENG_IQ_DATA_BLOCK_COUNT, 0, 0, 0, MENU_NULL},
/*[START] Jerry Liang for IQ MODE 2008/07/31*/        
//    {ID_ENG_IQ_DATA_MODE_SETTING_ARFCN, TIP_NULL, {TXT_NULL, TXT_NULL, TXT_NULL},//modify by mary
 //       TXT_ENG_IQ_DATA_ARFCN, 0, 0, 0, MENU_NULL},        
/*[END] Jerry Liang for IQ MODE 2008/07/31*/        
};
#ifdef PCLINK_SUPPORT
const GUIMENU_ITEM_T	menu_pclink[] =
{
    {ID_ENG_PCLINK_ENABLE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_PCLINK_ENABLE, 0, 0, 0, MENU_NULL},
    {ID_ENG_PCLINK_IP, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_PCLINK_IP, 0, 0, 0, MENU_NULL},
    {ID_ENG_PCLINK_DNS, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_PCLINK_DNS, 0, 0, 0, MENU_NULL},
    {ID_ENG_PCLINK_GATEWAY, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_PCLINK_DEFGW, 0, 0, 0, MENU_NULL},
    {ID_ENG_PCLINK_SUBNET_MAS, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_PCLINK_SNMASK, 0, 0, 0, MENU_NULL},
    {ID_ENG_PCLINK_TEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_PCLINK_TEST, 0, 0, 0, MENU_PCLINK_TEST},
};

const GUIMENU_ITEM_T	menu_pclink_test[] =
{
    {ID_ENG_PCLINK_TEST_ADDRESS, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_PCLINK_TEST_ADDR, 0, 0, 0, MENU_NULL},
    {ID_ENG_PCLINK_TEST_PING, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_PCLINK_PING_TEST, 0, 0, 0, MENU_NULL},
};
#endif
#ifdef CAMERA_SUPPORT
const GUIMENU_ITEM_T	menu_dc_param[] =
{
    //{ID_ENG_DC_PARAM_SCREEN_SIZE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
    //    TXT_ENG_DC_PARAM_SCREEN_SIZE, 0, 0, 0, MENU_NULL},
#if (defined(MAINLCD_LOGIC_ANGLE_0) || defined(MAINLCD_LOGIC_ANGLE_180))
    {ID_ENG_DC_PARAM_SCREEN_SWITCH, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_DC_PARAM_SCREEN_SWITCH, 0, 0, 0, MENU_NULL},
#endif
	{ID_ENG_DC_PARAM_PREV_SET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_DC_PARAM_PREV_SET, 0, 0, 0, MENU_NULL},
	{ID_ENG_DC_PARAM_SENSOR_ANGLE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_DC_PARAM_SENSOR_ANGLE, 0, 0, 0, MENU_NULL}
};
#endif

const GUIMENU_ITEM_T	menu_audio_setting[] =
{

    {ID_ENG_AUDIO_HANDSET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_HANDSET, 0, 0, 0, MENU_AUDIO_HANDSET},
	{ID_ENG_AUDIO_HEADSET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_COMM_HEADSET, 0, 0, 0, MENU_AUDIO_HAEDSET},
        {ID_ENG_AUDIO_HANDSFREE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_HANDSFREE, 0, 0, 0, MENU_AUDIO_HAEDSFREE},
        {ID_ENG_AUDIO_MP4HFTP, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_MP4HFTP, 0, 0, 0, MENU_AUDIO_MP4HFTP},
        {ID_ENG_AUDIO_MP4HFTR, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_MP4HFTR, 0, 0, 0, MENU_AUDIO_MP4HFTR},
        {ID_ENG_AUDIO_MP4HEADSET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_MP4HEADSET, 0, 0, 0, MENU_AUDIO_MP4HANDSET},
        {ID_ENG_AUDIO_RECORD, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_RECORD, 0, 0, 0, MENU_AUDIO_RECORD},
        {ID_ENG_AUDIO_BT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_NET_UK_BT, 0, 0, 0, MENU_AUDIO_BT},
        {ID_ENG_AUDIO_MP3_LOUDSPK, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_MP3_LOUDSPK, 0, 0, 0, MENU_AUDIO_MP3_LOUDSPK},
        {ID_ENG_AUDIO_MP3_EARPHONE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_MP3_EARPHONE, 0, 0, 0, MENU_AUDIO_MP3_EARPHONE},
        {ID_ENG_AUDIO_MP3_HEADFREE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_MP3_HEADFREE, 0, 0, 0, MENU_AUDIO_MP3_HEADFREE},
        
};
const GUIMENU_ITEM_T	menu_audio_handset[] =
{

    {ID_ENG_AUDIO_HANDSET_SIDETONE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_SIDETONE_VOLUME, 0, 0, 0, MENU_NULL},
	{ID_ENG_AUDIO_HANDSET_RECEIVER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_RECEIVER_VOLUME, 0, 0, 0, MENU_NULL},
        {ID_ENG_AUDIO_HANDSET_MIC, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_MIC_VOLUME, 0, 0, 0, MENU_NULL},

        
};

const GUIMENU_ITEM_T	menu_audio_headset[] =
{

    {ID_ENG_AUDIO_HEADSET_EAR, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_EAR_VOLUME, 0, 0, 0, MENU_NULL},
	{ID_ENG_AUDIO_HEADSET_MIC, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_MIC_VOLUME, 0, 0, 0, MENU_NULL},    
};

const GUIMENU_ITEM_T	menu_audio_handsfree[] =
{

    {ID_ENG_AUDIO_HANDSFREE_SPEAKER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_SPEAKER_VOLUME, 0, 0, 0, MENU_NULL},
	{ID_ENG_AUDIO_HANDSFREE_MIC, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_MIC_VOLUME, 0, 0, 0, MENU_NULL},

};

const GUIMENU_ITEM_T	menu_audio_mp4hftp[] =
{

    {ID_ENG_AUDIO_MP4HFTP_SPEAKER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_SPEAKER_VOLUME, 0, 0, 0, MENU_NULL},  
};

const GUIMENU_ITEM_T	menu_audio_mp4hftr[] =
{

    {ID_ENG_AUDIO_MP4HFTR_MIC, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_MIC_VOLUME, 0, 0, 0, MENU_NULL},     
};

const GUIMENU_ITEM_T	menu_audio_mp4handset[] =
{

    {ID_ENG_AUDIO_MP4HEADSET_EAR, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_EAR_VOLUME, 0, 0, 0, MENU_NULL}, 
};

const GUIMENU_ITEM_T	menu_audio_record[] =
{

    {ID_ENG_AUDIO_RECORD_MIC, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_MIC_VOLUME, 0, 0, 0, MENU_NULL},
	
};

const GUIMENU_ITEM_T	menu_audio_BT[] =
{

    {ID_ENG_AUDIO_BT_EAR, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_EAR_VOLUME, 0, 0, 0, MENU_NULL},
	{ID_ENG_AUDIO_BT_MIC, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_MIC_VOLUME, 0, 0, 0, MENU_NULL},
};

const GUIMENU_ITEM_T	menu_audio_MP3_LoudSPK[] =
{

    {ID_ENG_AUDIO_MP3_LOUDSPK_SPEAKER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_SPEAKER_VOLUME, 0, 0, 0, MENU_NULL},       
};

const GUIMENU_ITEM_T	menu_audio_MP3_Earphone[] =
{

    {ID_ENG_AUDIO_MP3_EARPHONE_EAR, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_EAR_VOLUME, 0, 0, 0, MENU_NULL},      
};

const GUIMENU_ITEM_T	menu_audio_MP3_HeadFree[] =
{
    
    {ID_ENG_AUDIO_MP3_HEADFREE_SPEAKER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_AUDIO_SPEAKER_VOLUME, 0, 0, 0, MENU_NULL},       
};
	
#ifdef JAVA_SUPPORT_IA
const GUIMENU_ITEM_T menu_java_auto_tck_mode[] = 
{
	{ID_ENG_JAVA_AUTO_TCK_MODE_ON, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_ON, 0, 0, 0, MENU_NULL},
	{ID_ENG_JAVA_AUTO_TCK_MODE_OFF, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_COMM_OFF, 0, 0, 0, MENU_NULL}
};
#endif
const GUIMENU_ITEM_T	menu_phone_test[] =		//MS00193068
{

    {ID_ENG_TEST_FULLTEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_FULLTEST, 0, 0, 0, MENU_NULL},      
     {ID_ENG_TEST_VIEWRESULT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_VIEWRESULT, 0, 0, 0, MENU_NULL},   
        {ID_ENG_TEST_ITEMTEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_ITEMTEST, 0, 0, 0, MENU_PHONE_ITEM_TEST},   
     {ID_ENG_ADC_CALIBRATE_INFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_ADC_CALIBRATE_INFO, 0, 0, 0, MENU_NULL},    
    {ID_ENG_TEST_SW_VERSION, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_VERSION_INFO, 0, 0, 0, MENU_NULL}, 
     {ID_ENG_TEST_FACTORYRESET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_COMMON_RESTORE_FACTORY_SETTINGS, 0, 0, 0, MENU_NULL},
	{ID_ENG_TEST_PHONEINFO, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_PHONE_INFO, 0, 0, 0, MENU_NULL}, 
};

const GUIMENU_ITEM_T	menu_phone_test_zdt[] =		//MS00193068
{

    {ID_ENG_TEST_FULLTEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_FULLTEST, 0, 0, 0, MENU_NULL},      
        {ID_ENG_TEST_ITEMTEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_ITEMTEST, 0, 0, 0, MENU_PHONE_ITEM_TEST},   
};

const GUIMENU_ITEM_T	menu_phone_item_test[] =		
 { 

 {ID_ENG_TEST_VERSION, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
       TXT_ENG_VERSION_INFO, 0, 0, 0, MENU_NULL}, 
       
     {ID_ENG_TEST_SIM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
       TXT_ENG_TEST_SIM, 0, 0, 0, MENU_NULL}, 
  #ifdef MSDC_CARD_SUPPORT         
            {ID_ENG_TEST_SDCARD, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_SDCARD, 0, 0, 0, MENU_NULL},   
#endif
   {ID_ENG_TEST_MAINLCD, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_MAINLCD, 0, 0, 0, MENU_NULL},    
        
	{ID_ENG_TEST_MELODY, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_MELODY, 0, 0, 0, MENU_NULL},   
	    {ID_ENG_TEST_LOOPBACK, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_LOOPBACK, 0, 0, 0, MENU_NULL},  
        
     {ID_ENG_TEST_KEY, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_KEY, 0, 0, 0, MENU_NULL},        
     
        
        
           {ID_ENG_TEST_VIBRATER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_VIBRATER, 0, 0, 0, MENU_NULL},   
           {ID_ENG_TEST_BACKLIGHT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_BACKLIGHT, 0, 0, 0, MENU_NULL},   

        
#ifdef  CAMERA_SUPPORT   	
   {ID_ENG_TEST_CAMERA, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_CAMERA, 0, 0, 0, MENU_NULL}, 
#endif

#if 0
def MMI_TORCH_LED_SUPPORT
    {ID_ENG_TEST_TORCH_LED, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
     TXT_ENG_TEST_TORCH, 0, 0, 0, MENU_NULL},
#endif

#ifdef BLUETOOTH_SUPPORT
	//BT should before camer
	   {ID_ENG_TEST_BLUETOOTH, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_BLUETOOTH, 0, 0, 0, MENU_NULL},   
#endif

	//   {ID_ENG_TEST_HEADSET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
      ///  TXT_ENG_TEST_HEADSET, 0, 0, 0, MENU_NULL},   
	{ID_ENG_KEYPAD_LED, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_KEYPAD_LED_TEST, 0, 0, 0, MENU_NULL},


#ifdef APP_ENG_COMTEST_SUPPORT   
        {ID_ENG_TEST_COM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_COM, 0, 0, 0, MENU_NULL},   
#endif 

#ifdef FM_SUPPORT
    	   {ID_ENG_TEST_FM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_FM, 0, 0, 0, MENU_NULL},   
#endif

#ifdef GPS_SUPPORT
      {ID_ENG_TEST_GPS, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_GPS, 0, 0, 0, MENU_NULL},   
#endif

/* BEGIN: Added by George.Liu 01526, 2010/7/13   PN:WiFi_UITest */
#if 0
def WIFI_SUPPORT
      {ID_ENG_TEST_WIFI, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_WIFI, 0, 0, 0, MENU_NULL}, 
#endif
/* END:   Added by George.Liu 01526, 2010/7/13  */

#if 0
def MOTION_SENSOR_TYPE
          {ID_ENG_TEST_MOTION_SENSOR, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
            TXT_ENG_TEST_MOTIONSENSOR, 0, 0, 0, MENU_NULL}, 
#endif


#ifdef ATV_SUPPORT
      {ID_ENG_TEST_ATV, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_ATV, 0, 0, 0, MENU_NULL}, 
#endif

     {ID_ENG_TEST_CHARGING, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
       TXT_ENG_TEST_CHARGING, 0, 0, 0, MENU_NULL}, 
   {ID_ENG_TEST_RTC, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_TEST_RTC, 0, 0, 0, MENU_NULL},  
//bug 746951
//    {ID_ENG_EMCC_TEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
  //  TXT_ENG_TEST_EMCC, 0, 0, 0, MENU_NULL}, 
//bug 746951
};

#ifdef MMI_UNISOC_MANUALLY_CIT_SUPPORT
const GUIMENU_ITEM_T	menu_unisoc_test[] =
{
	
	{ID_UNISOC_TEST_FULLTEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_FULLTEST, 0, 0, 0, MENU_NULL},      
	//{ID_UNISOC_TEST_VIEWRESULT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	//TXT_ENG_VIEWRESULT, 0, 0, 0, MENU_NULL},   
	{ID_UNISOC_TEST_ITEMTEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_ITEMTEST, 0, 0, 0, MENU_UNISOC_ITEM_TEST},   
	
};

const GUIMENU_ITEM_T	menu_unisoc_item_test[] =		
{ 
	{ID_UNISOC_TEST_VERSION, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_VERSION_TEST, 0, 0, 0, MENU_NULL},
	{ID_UNISOC_TEST_SIM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_SIM_TEST, 0, 0, 0, MENU_NULL},
	{ID_UNISOC_TEST_TFLASH, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_TFLASH_TEST, 0, 0, 0, MENU_NULL},
	{ID_UNISOC_TEST_MAINLCD, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_LCD_TEST, 0, 0, 0, MENU_NULL},
	{ID_UNISOC_TEST_RECEIVER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_RECEIVER_TEST, 0, 0, 0, MENU_NULL},
	{ID_UNISOC_TEST_SPEAKER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_SPEAKER_TEST, 0, 0, 0, MENU_NULL},
	{ID_UNISOC_TEST_MIC_RECEIVER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_MIC_RECEIVER_TEST, 0, 0, 0, MENU_NULL},
	{ID_UNISOC_TEST_MIC_SPEAKER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_MIC_SPEAKER_TEST, 0, 0, 0, MENU_NULL},
	#ifdef  CAMERA_SUPPORT  
	{ID_UNISOC_TEST_CAMERA, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_CAMERA_TEST, 0, 0, 0, MENU_NULL},
	{ID_UNISOC_TEST_CAMERA_CAPTURE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_CAMERA_CAPTURE_TEST, 0, 0, 0, MENU_NULL},
	#endif
	#if 0
def MMI_TORCH_LED_SUPPORT
	{ID_UNISOC_TEST_TORCH, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_TORCHLED_TEST, 0, 0, 0, MENU_NULL},
	#endif
#ifdef ZDT_PRODUCT_VIBRATE
	{ID_UNISOC_TEST_VIBRATER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_VIBRATE_TEST, 0, 0, 0, MENU_NULL},
#endif
	#ifdef Z695_KEYLOCK_INT_SUPPORT
		{ID_UNISOC_TEST_KEYLOCK, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_KEYLOCK_TEST, 0, 0, 0, MENU_NULL},
	#endif
	{ID_UNISOC_TEST_KEYPAD_LED, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_KEYPAD_LED_TEST, 0, 0, 0, MENU_NULL},
	{ID_UNISOC_TEST_KEY, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_KEY_TEST, 0, 0, 0, MENU_NULL},
	#ifdef FM_SUPPORT
	{ID_UNISOC_TEST_FM, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_FM_TEST, 0, 0, 0, MENU_NULL},
	#endif
	//{ID_UNISOC_TEST_HEADSET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	//TXT_ENG_HEADSET_TEST, 0, 0, 0, MENU_NULL},
	//{ID_UNISOC_TEST_MIC_HEADSET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	//TXT_ENG_MIC_HEADSET_TEST, 0, 0, 0, MENU_NULL},
	#ifdef BLUETOOTH_SUPPORT
	{ID_UNISOC_TEST_BT, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_BT_TEST, 0, 0, 0, MENU_NULL},
	#endif
	{ID_UNISOC_TEST_CHARGING, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_CHARGING_TEST, 0, 0, 0, MENU_NULL},
	{ID_UNISOC_TEST_RTC, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_RTC_TEST, 0, 0, 0, MENU_NULL},
	{ID_UNISOC_TEST_RESET, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_COMMON_RESTORE_FACTORY_SETTINGS, 0, 0, 0, MENU_NULL},
	//bug 746951
   // {ID_ENG_EMCC_TEST, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
  //  TXT_ENG_TEST_EMCC, 0, 0, 0, MENU_NULL},
        //bug 746951
};

const GUIMENU_ITEM_T	menu_aging_test[] =		
{ 
	{ID_UNISOC_TEST_MAINLCD, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_LCD_TEST, 0, 0, 0, MENU_NULL},
	{ID_UNISOC_TEST_RECEIVER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_RECEIVER_TEST, 0, 0, 0, MENU_NULL},
	{ID_UNISOC_TEST_SPEAKER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_SPEAKER_TEST, 0, 0, 0, MENU_NULL},
	
#ifdef ZDT_PRODUCT_VIBRATE
	{ID_UNISOC_TEST_VIBRATER, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	TXT_ENG_VIBRATE_TEST, 0, 0, 0, MENU_NULL},
#endif
};
#endif/*MMI_UNISOC_MANUALLY_CIT_SUPPORT*/

const GUIMENU_ITEM_T menu_pscell_option[] =
{
    {ID_ENG_FROCE_CELL, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_FORCE_CELL, 0, 0, 0, MENU_NULL},
    {ID_ENG_CANCEL_FORCE_CELL, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
        TXT_ENG_CANCEL_FORCE_CELL, 0, 0, 0, MENU_NULL}
};
#if defined ENG_NETWORK_SET //zhouqin
const GUIMENU_ITEM_T menu_network_set[] =
{
	{ID_ENG_SET_LTE_SERVICE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SET_LTE_SERVICE, 0, 0, 0, MENU_NULL},
	 
	{ID_ENG_SET_LTE_OPERATION_MODE, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SET_LTE_OPERATION_MODE, 0, 0, 0, MENU_NULL},
};
#endif
#if defined ENG_BAND_FREQ_SUPPORT //zhouqin
const GUIMENU_ITEM_T menu_band_freq_set[] =
{
	{ID_ENG_SET_BAND, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SET_BAND, 0, 0, 0, SET_BAND_MENU_ENG},
	 
	{ID_ENG_SET_FREQ, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SET_FREQ, 0, 0, 0, SET_FREQ_MENU_ENG},
};
const GUIMENU_ITEM_T menu_set_band[] =
{
	{ID_ENG_SET_LTE_BAND, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SET_LTE_BAND, 0, 0, 0, MENU_NULL},
	 
	{ID_ENG_SET_GSM_BAND, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SET_GSM_BAND, 0, 0, 0, MENU_NULL},
};

const GUIMENU_ITEM_T menu_set_freq[] =
{
	{ID_ENG_SET_LTE_FREQ, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SET_LTE_FREQ, 0, 0, 0, MENU_NULL},
	 
	{ID_ENG_SET_GSM_FREQ, TIP_NULL, {TXT_ENG_OK, TXT_NULL, TXT_ENG_RETURN},
	 TXT_ENG_SET_GSM_FREQ, 0, 0, 0, MENU_NULL},
};
#endif
#define MENU_DEF(_TABLEID, _ITEMPTR, _STYLE, _TITLESTR, _TITLE_ICON, _TITLE_NUMICON, _TITLE_BACKGROUND, \
	_ITEMCOUNT) \
     _ITEMPTR, _STYLE, _TITLESTR, _TITLE_ICON, _TITLE_NUMICON, _TITLE_BACKGROUND, _ITEMCOUNT, 

const GUIMENU_GROUP_T mmieng_menu_table[] = 
{
    {NULL},
    #include "mmieng_menutable.def"
};

#undef MENU_DEF

/*****************************************************************************/
// 	Description : Register eng menu group
//	Global resource dependence : none
//  Author: songbin.zeng
//	Note:
/*****************************************************************************/
PUBLIC void MMIENG_RegMenuGroup(void)
{
    MMI_RegMenuGroup(MMI_MODULE_ENG, mmieng_menu_table);
}

#ifdef   __cplusplus
    }
#endif
/*-------------------------------------------------------------------------*/
#endif//ENG_SUPPORT
