#ifdef GAME_GOLDMINER_SUPPORT

/*
RES_ADD_IMG(IMAGE_GOLDMINER,"\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER.bmp", IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_GOLDMINER_CLIPPERS,"\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_CLIPPERS.bmp", IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMAGE_GOLDMINER_DIAMOND,"\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_GOLD_DIAMOND.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_GOLDMINER_BOMB,"\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_BOMB.png.bmp", IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_GOLDMINER_MINI_GOLD, "\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_MINI_GOLD.bmp", IMG_CMP_BMP_16_565_RLE, 0) 
RES_ADD_IMG(IMAGE_GOLDMINER_MINI_STONE, "\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_MINI_STONE.bmp", IMG_CMP_BMP_16_565_RLE, 0) 
RES_ADD_IMG(IMAGE_GOLDMINER_BIG_GOLD, "\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_BIG_GOLD.bmp", IMG_CMP_BMP_16_565_RLE, 0) 
RES_ADD_IMG(IMAGE_GOLDMINER_BIG_STONE, "\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_BIG_STONE.bmp", IMG_CMP_BMP_16_565_RLE, 0) 
*/

RES_ADD_IMG(IMAGE_GOLDMINER_1,"\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_1.png", IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GOLDMINER_2,"\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_2.png", IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GOLDMINER_CLIPPERS,"\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_CLIPPERS.png", IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GOLDMINER_CLIPPERS_CLOSE,"\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_CLIPPERS_CLOSE.png", IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_GOLDMINER_DIAMOND,"\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_GOLD_DIAMOND.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GOLDMINER_TOOL,"\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_GOLD_TOOL.png", IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GOLDMINER_BOMB,"\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_MINI_BOMB.png", IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GOLDMINER_ENERGY,"\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_GOLD_ENERGY.png", IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GOLDMINER_MINI_GOLD, "\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_MINI_GOLD.png", IMG_CMP_PNG_ARGB_RLE, 0) 
RES_ADD_IMG(IMAGE_GOLDMINER_MINI_STONE, "\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_MINI_STONE.png", IMG_CMP_PNG_ARGB_RLE, 0) 
RES_ADD_IMG(IMAGE_GOLDMINER_BIG_GOLD, "\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_BIG_GOLD.png", IMG_CMP_PNG_ARGB_RLE, 0) 
RES_ADD_IMG(IMAGE_GOLDMINER_BIG_STONE, "\\MMI_RES_##\\IMAG\\IMAGE_GOLDMINER_BIG_STONE.png", IMG_CMP_PNG_ARGB_RLE, 0) 

#ifndef MMIGAME_GOLDMINER_LOW_MEMORY
RES_ADD_IMG(IMAGE_GAME_GOLDMINER_BG,"\\MMI_RES_##\\IMAG\\IMAGE_GAME_GOLDMINER_BG.bmp", IMG_CMP_BMP_16_565_RLE,0)
#endif

//define string infomation
RES_ADD_STRING(TXT_GOLDMINER,"Gold Miner")
RES_ADD_STRING(TXT_GOLDMINER_SCORE,"Score")
RES_ADD_STRING(TXT_GOLDMINER_LEVEL,"Level")
RES_ADD_STRING(TXT_GOLDMINER_HELP,"Help")
RES_ADD_STRING(TXT_GOLDMINER_GAME_INFO,"S:Target Score C:Current Score T:Time L:Level.")
RES_ADD_STRING(TXT_GOLDMINER_NEW_GAME,"New Game")
RES_ADD_STRING(TXT_GOLDMINER_GAMEOVER,"Game over! Restart?")
//RES_ADD_STRING(TXT_GOLDMINER_HIGHSCORE,"High Score")
RES_ADD_STRING(TXT_GOLDMINER_HIGHRECORD,"High Record")
RES_ADD_STRING(TXT_GOLDMINER_HIGHLEVEL,"High Level")
RES_ADD_STRING(TXT_GOLDMINER_USETIME,"Time(s)")
RES_ADD_STRING(TXT_GOLDMINER_SET_LEVEL,"Please input:")
RES_ADD_STRING(TXT_GOLDMINER_VIEW_TARGETSCORE,"S:")
RES_ADD_STRING(TXT_GOLDMINER_VIEW_CURRENTSCORE,"C:")
RES_ADD_STRING(TXT_GOLDMINER_VIEW_TIME,"T:")
RES_ADD_STRING(TXT_GOLDMINER_VIEW_LEVEL,"L:")
RES_ADD_STRING(TXT_GOLDMINER_PAUSE,"Pause")
RES_ADD_STRING(TXT_GOLDMINER_RESET,"Reset")

RES_ADD_STRING(TXT_GOLDMINER_SETLEVEL_FAIL,"Please enter a valid value!")
RES_ADD_STRING(TXT_GOLDMINER_LEVEL_DONE,"Level Done! Continue?")
RES_ADD_STRING(TXT_GOLDMINER_GAME_OVER,"Game Over ! Retry? ")
RES_ADD_STRING(TXT_GOLDMINER_GAME_FINISH,"Congratulation! Game Done! Replay?")
RES_ADD_STRING(TXT_GOLDMINER_GAME_DUMMY_1,"Congratulation! Game Done! Replay?")
RES_ADD_STRING(TXT_GOLDMINER_GAME_DUMMY_2,"Congratulation! Game Done! Replay?")
#endif

