/***************************************************************************
** File Name:      mmigame_goldminer_position.h                            *
** Author:                                                                 *
** Date:           06/09/2012                                              *
** Copyright:      2012 Spreadtrum, Incoporated. All Rights Reserved.      *
** Description:    This file is used to describe the data struct of        *
**                 system, applicaiton, window and control                 *
****************************************************************************
**                         Important Edit History                          *
** ------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION                             *
** 06/09/2011     leon.wang        Create                                  * 
****************************************************************************/
#ifndef  _MMIGAME_GOLDMINER_POSITION_H_    
#define  _MMIGAME_GOLDMINER_POSITION_H_  

 /**--------------------------------------------------------------------------*
 **                         Include Files                                    *
 **--------------------------------------------------------------------------*/
#include "sci_types.h"
#ifdef GAME_GOLDMINER_SUPPORT
#include "os_api.h"
#include "mmk_type.h"
#include "mmi_module.h"
/**---------------------------------------------------------------------------*
 **                         Compiler Flag                                     *
 **---------------------------------------------------------------------------*/
#ifdef __cplusplus
   extern   "C"
   {
#endif
/*---------------------------------------------------------------------------*/
/*                          MACRO DEFINITION                                 */
/*---------------------------------------------------------------------------*/
//关于位置的宏定义
#if defined MAINLCD_SIZE_128X160 || defined MAINLCD_SIZE_176X220
#define MMIGAME_GOLDMINER_LOW_MEMORY  //用于决定是否禁用大背景图片等资源
#endif

#define MMI_GM_GOLDMINER_CELL_INFO_NULL 0xFF    //用于初始化grid cell用，因为后续需要设置group_id 为0的情况，
                                                                                          //故初始化grid cell时不要用"0" 初始化
//score
#define MMI_GM_GOLDMINER_MINI_GOLD_SCORE    100
#define MMI_GM_GOLDMINER_BIG_GOLD_SCORE     200
#define MMI_GM_GOLDMINER_MINI_STONE_SCORE   10
#define MMI_GM_GOLDMINER_BIG_STONE_SCORE    20
#define MMI_GM_GOLDMINER_DIAMOND_SCORE      500
//timer
#define MMI_SWING_TIME_INTERNAL       100//50      //绳子左右摇摆Timer间隔
#define MMI_STRETCH_TIME_INTERNAL   100//50    //绳子伸缩Timer 间隔
#define MMI_COUNTED_TIME_INTERNAL   500    //游戏倒计时Timer
#define MMI_MINER_TIME_INTERNAL     500

#define MMI_SWING_ANGLE_INTERNAL    5           //绳索每次摇摆角度间隔
#define MMI_SWING_ANGLE_BOUNDARY_LEFT   15      //绳索摇摆左边边界
#define MMI_SWING_ANGLE_BOUNDARY_RIGHT   165    //绳索摇摆右边边界

#ifdef MAINLCD_SIZE_320X480
//#elif defined MAINLCD_SIZE_320X480
 //320X480P
#define MMI_GM_GOLDMINER_GRID_INTERVAL 20   //每个cell 的边长
#define MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H 23   //屏幕横向网格数量
#define MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V 10   //屏幕纵向网格数量
#define MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP 120     //网格总布局rect 的top 值
#define MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT 10      //网格总布局rect的left值

#define MMI_GM_SHOOTER_LINE_LENGTH 40       //发射器绳子长度
#define MMI_GM_SHOOTER_DEFAULT_ANGLE    150     //发射器默认绳子的角度

#define MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_X 240    //发射器位置坐标X
#define MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y 80      //发射器位置坐标Y

#define MMI_GM_GOLDMINER_SPEED      10      //绳索延伸正常速度
#define MMI_GM_GOLDMINER_SPEED_HIGH      20 //绳索延伸道具使用加速
#define MMI_GM_GOLDMINER_SPEED_LOW      2   //绳索延伸减速速( 勾住大物体)
//边界值信息
//#define MMI_GM_GOLDMINER_RECT       {MMI_GM_GOLDMINER_GRID_INTERVAL/2, MMI_GM_GOLDMINER_SHOOTER_Y, (MMI_GM_GOLDMINER_GRID_INTERVAL/2+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_H+MMI_GM_GOLDMINER_GRID_TOP)}
//#define MMI_GM_GOLDMINER_HORIZONTAL_RECT       {MMI_GM_GOLDMINER_GRID_INTERVAL/2, MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y, (MMI_GM_GOLDMINER_GRID_INTERVAL/2+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V+MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP)}
#define MMI_GM_GOLDMINER_HORIZONTAL_RECT       {MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT, MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y, (MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V+MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP)}

#define MMI_GOLDMINER_TARGETSCORE_RECT  {20,10,70,70}
#define MMI_GOLDMINER_SCORE_RECT        {20,60,70,120}
#define MMI_GOLDMINER_TIME_RECT         {250,10,300,70}
#define MMI_GOLDMINER_LEVEL_RECT        {250,60,300,120}
#define MMI_GOLDMINER_BOMB_NUM_RECT     {100,100,120,120}
#define MMI_GOLDMINER_ENERGY_NUM_RECT   {200,100,220,120}
//提示区信息显示rect
#define MMI_GOLDMINER_TARGETSCORE_HORIZONTAL_RECT         {20,10,70,70}         //Target Score
#define MMI_GOLDMINER_SCORE_HORIZONTAL_RECT                      {20,60,70,120}       //current score
#define MMI_GOLDMINER_TIME_HORIZONTAL_RECT                          {410,10,460,70}     //count time
#define MMI_GOLDMINER_LEVEL_HORIZONTAL_RECT                       {410,60,460,120}    //level info
#define MMI_GOLDMINER_BOMB_NUM_HORIZONTAL_RECT               {180,60,200,80}     //Bomb num
#define MMI_GOLDMINER_ENERGY_NUM_HORIZONTAL_RECT            {280,60,300,80}     //Energy num

#define MMI_GOLDMINER_VIEW_LEVLE_RECT   {0,40,160,60}
#define MMI_GOLDMINER_VIEW_TIME_RECT     {0,60,160,80}
#define MMI_GOLDMINER_SETLEVEL_LABLE_RECT     {0,40,160,60} 
#define MMI_GOLDMINER_SETLEVEL_EDIT_RECT        {40,60,120,90}

#define MMI_GOLDMINER_TOOL_NUM_TOP_OFFSET   15
#define MMI_GOLDMINER_TOOL_NUM_RIGHT_OFFSET   5

#elif (defined MAINLCD_SIZE_240X320) || (defined MAINLCD_SIZE_240X400)

#define MMI_GM_GOLDMINER_GRID_INTERVAL 15   //每个cell 的边长
#ifdef MAINLCD_SIZE_240X320
#define MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H 20   //屏幕横向网格数量
#else   //MAINLCD_SIZE_240X400
#define MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H 24   //屏幕横向网格数量
#endif

#define MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V 10   //屏幕纵向网格数量
#define MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP 90     //网格总布局rect 的top 值

#ifdef MAINLCD_SIZE_240X320
#define MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT 10      //网格总布局rect的left值
#else
#define MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT 20      //网格总布局rect的left值
#endif

//#define MMI_GM_GOLDMINER_GRID_LEFT  10
#define MMI_GM_SHOOTER_LINE_LENGTH 20       //发射器绳子长度
#define MMI_GM_SHOOTER_DEFAULT_ANGLE    150     //发射器默认绳子的角度

#ifdef MAINLCD_SIZE_240X320
#define MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_X 160    //发射器位置坐标X
#else
#define MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_X 200    //发射器位置坐标X
#endif

#define MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y 70      //发射器位置坐标Y

#define MMI_GM_GOLDMINER_SPEED      10      //绳索延伸正常速度
#define MMI_GM_GOLDMINER_SPEED_HIGH      20 //绳索延伸道具使用加速
#define MMI_GM_GOLDMINER_SPEED_LOW      2   //绳索延伸减速速( 勾住大物体)
//边界值信息
//#define MMI_GM_GOLDMINER_RECT       {MMI_GM_GOLDMINER_GRID_INTERVAL/2, MMI_GM_GOLDMINER_SHOOTER_Y, (MMI_GM_GOLDMINER_GRID_INTERVAL/2+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_H+MMI_GM_GOLDMINER_GRID_TOP)}
//#define MMI_GM_GOLDMINER_HORIZONTAL_RECT       {MMI_GM_GOLDMINER_GRID_INTERVAL/2, MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y, (MMI_GM_GOLDMINER_GRID_INTERVAL/2+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V+MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP)}
#define MMI_GM_GOLDMINER_HORIZONTAL_RECT       {MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT, MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y, (MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V+MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP)}

//提示区信息显示rect
#define MMI_GOLDMINER_TARGETSCORE_HORIZONTAL_RECT         {20,10,70,70}         //Target Score
#define MMI_GOLDMINER_SCORE_HORIZONTAL_RECT                      {20,60,70,120}       //current score
#ifdef MAINLCD_SIZE_240X320
#define MMI_GOLDMINER_TIME_HORIZONTAL_RECT                          {270,10,319,70}     //count time
#define MMI_GOLDMINER_LEVEL_HORIZONTAL_RECT                       {270,60,319,120}    //level info
#define MMI_GOLDMINER_BOMB_NUM_HORIZONTAL_RECT               {100,40,120,60}     //Bomb num
#define MMI_GOLDMINER_ENERGY_NUM_HORIZONTAL_RECT            {200,40,220,60}     //Energy num
#else
#define MMI_GOLDMINER_TIME_HORIZONTAL_RECT                          {350,10,399,70}     //count time
#define MMI_GOLDMINER_LEVEL_HORIZONTAL_RECT                       {350,60,399,120}    //level info
#define MMI_GOLDMINER_BOMB_NUM_HORIZONTAL_RECT               {150,40,170,60}     //Bomb num
#define MMI_GOLDMINER_ENERGY_NUM_HORIZONTAL_RECT            {230,40,250,60}     //Energy num
#endif

#ifdef MAINLCD_SIZE_240X320
#ifdef MAINLCD_DEV_SIZE_320X240
#define MMI_GOLDMINER_VIEW_LEVLE_RECT   {0,100,320,120}
#define MMI_GOLDMINER_VIEW_TIME_RECT     {0,120,320,140}
#define MMI_GOLDMINER_SETLEVEL_LABLE_RECT     {0,100,320,120} 
#define MMI_GOLDMINER_SETLEVEL_EDIT_RECT        {115,120,210,150}
#else
#define MMI_GOLDMINER_VIEW_LEVLE_RECT   {0,130,240,150}
#define MMI_GOLDMINER_VIEW_TIME_RECT     {0,150,240,170}
#define MMI_GOLDMINER_SETLEVEL_LABLE_RECT     {0,130,240,150} 
#define MMI_GOLDMINER_SETLEVEL_EDIT_RECT        {60,150,180,180}
#endif
#else
#define MMI_GOLDMINER_VIEW_LEVLE_RECT   {0,130,240,150}
#define MMI_GOLDMINER_VIEW_TIME_RECT     {0,150,240,170}
#define MMI_GOLDMINER_SETLEVEL_LABLE_RECT     {0,130,240,150} 
#define MMI_GOLDMINER_SETLEVEL_EDIT_RECT        {60,150,180,180}
#endif

#define MMI_GOLDMINER_TOOL_NUM_TOP_OFFSET   15
#define MMI_GOLDMINER_TOOL_NUM_RIGHT_OFFSET   5

//176X220
#elif defined MAINLCD_DEV_SIZE_220X176

#define MMI_GM_GOLDMINER_GRID_INTERVAL 10   //每个cell 的边长
#define MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H 20   //屏幕横向网格数量
#define MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V 10   //屏幕纵向网格数量
#define MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP 76     //网格总布局rect 的top 值
#define MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT 10      //网格总布局rect的left值

#define MMI_GM_SHOOTER_LINE_LENGTH 20       //发射器绳子长度
#define MMI_GM_SHOOTER_DEFAULT_ANGLE    150     //发射器默认绳子的角度

#define MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_X 110    //发射器位置坐标X
#define MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y 40      //发射器位置坐标Y

#define MMI_GM_GOLDMINER_SPEED      10      //绳索延伸正常速度
#define MMI_GM_GOLDMINER_SPEED_HIGH      20 //绳索延伸道具使用加速
#define MMI_GM_GOLDMINER_SPEED_LOW      2   //绳索延伸减速速( 勾住大物体)
//边界值信息
//#define MMI_GM_GOLDMINER_RECT       {MMI_GM_GOLDMINER_GRID_INTERVAL/2, MMI_GM_GOLDMINER_SHOOTER_Y, (MMI_GM_GOLDMINER_GRID_INTERVAL/2+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_H+MMI_GM_GOLDMINER_GRID_TOP)}
//#define MMI_GM_GOLDMINER_HORIZONTAL_RECT       {MMI_GM_GOLDMINER_GRID_INTERVAL/2, MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y, (MMI_GM_GOLDMINER_GRID_INTERVAL/2+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_H
#define MMI_GM_GOLDMINER_HORIZONTAL_RECT       {MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT, MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y, (MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V+MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP)}

//提示区信息显示rect
#define MMI_GOLDMINER_TARGETSCORE_HORIZONTAL_RECT         {10,10,60,40}         //Target Score
#define MMI_GOLDMINER_SCORE_HORIZONTAL_RECT                      {10,40,60,70}       //current score
#define MMI_GOLDMINER_TIME_HORIZONTAL_RECT                          {160,10,210,40}     //count time
#define MMI_GOLDMINER_LEVEL_HORIZONTAL_RECT                       {160,40,210,70}    //level info
#define MMI_GOLDMINER_BOMB_NUM_HORIZONTAL_RECT               {70,30,80,40}     //Bomb num
#define MMI_GOLDMINER_ENERGY_NUM_HORIZONTAL_RECT            {140,30,150,40}     //Energy num

#define MMI_GOLDMINER_VIEW_LEVLE_RECT   {0,60,220,80}
#define MMI_GOLDMINER_VIEW_TIME_RECT     {0,80,220,100}
#define MMI_GOLDMINER_SETLEVEL_LABLE_RECT     {0,60,220,80} 
#define MMI_GOLDMINER_SETLEVEL_EDIT_RECT        {60,80,160,110}

#define MMI_GOLDMINER_TOOL_NUM_TOP_OFFSET   15
#define MMI_GOLDMINER_TOOL_NUM_RIGHT_OFFSET   5

#elif defined MAINLCD_SIZE_176X220

#define MMI_GM_GOLDMINER_GRID_INTERVAL 10   //每个cell 的边长
//以下关于一些横屏的定义，在mini screen项目竖屏上也有此命名
#define MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H 17   //屏幕横向网格数量
#define MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V 12   //屏幕纵向网格数量
#define MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP 100     //网格总布局rect 的top 值
#define MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT 3      //网格总布局rect的left值

#define MMI_GM_SHOOTER_LINE_LENGTH 20       //发射器绳子长度
#define MMI_GM_SHOOTER_DEFAULT_ANGLE    150     //发射器默认绳子的角度

#define MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_X 88    //发射器位置坐标X
#define MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y 60      //发射器位置坐标Y

#define MMI_GM_GOLDMINER_SPEED      10      //绳索延伸正常速度
#define MMI_GM_GOLDMINER_SPEED_HIGH      20 //绳索延伸道具使用加速
#define MMI_GM_GOLDMINER_SPEED_LOW      2   //绳索延伸减速速( 勾住大物体)
//边界值信息
//#define MMI_GM_GOLDMINER_RECT       {MMI_GM_GOLDMINER_GRID_INTERVAL/2, MMI_GM_GOLDMINER_SHOOTER_Y, (MMI_GM_GOLDMINER_GRID_INTERVAL/2+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_H+MMI_GM_GOLDMINER_GRID_TOP)}
//#define MMI_GM_GOLDMINER_HORIZONTAL_RECT       {MMI_GM_GOLDMINER_GRID_INTERVAL/2, MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y, (MMI_GM_GOLDMINER_GRID_INTERVAL/2+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V+MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP)}
#define MMI_GM_GOLDMINER_HORIZONTAL_RECT       {MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT, MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y, (MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V+MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP)}


//提示区信息显示rect
#define MMI_GOLDMINER_TARGETSCORE_HORIZONTAL_RECT         {5,10,60,50}         //Target Score
#define MMI_GOLDMINER_SCORE_HORIZONTAL_RECT                      {5,60,60,100}       //current score
#define MMI_GOLDMINER_TIME_HORIZONTAL_RECT                          {110,10,171,50}     //count time
#define MMI_GOLDMINER_LEVEL_HORIZONTAL_RECT                       {110,60,171,100}    //level info
#define MMI_GOLDMINER_BOMB_NUM_HORIZONTAL_RECT               {50,50,60,60}          //Bomb num
#define MMI_GOLDMINER_ENERGY_NUM_HORIZONTAL_RECT            {116,50,126,60}      //Energy num

#define MMI_GOLDMINER_VIEW_LEVLE_RECT   {0,80,160,100}
#define MMI_GOLDMINER_VIEW_TIME_RECT     {0,100,160,120}
#define MMI_GOLDMINER_SETLEVEL_LABLE_RECT     {0,80,160,100} 
#define MMI_GOLDMINER_SETLEVEL_EDIT_RECT        {30,100,130,130}

#define MMI_GOLDMINER_TOOL_NUM_TOP_OFFSET   15
#define MMI_GOLDMINER_TOOL_NUM_RIGHT_OFFSET   5

#elif defined MAINLCD_DEV_SIZE_160X128

#define MMI_GM_GOLDMINER_GRID_INTERVAL 10   //每个cell 的边长
//以下关于一些横屏的定义，在mini screen项目竖屏上也有此命名
#define MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H 15   //屏幕横向网格数量
#define MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V 7   //屏幕纵向网格数量
#define MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP 58     //网格总布局rect 的top 值
#define MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT 5      //网格总布局rect的left值

#define MMI_GM_SHOOTER_LINE_LENGTH 10       //发射器绳子长度
#define MMI_GM_SHOOTER_DEFAULT_ANGLE    150     //发射器默认绳子的角度

#define MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_X 80    //发射器位置坐标X
#define MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y 38      //发射器位置坐标Y

#define MMI_GM_GOLDMINER_SPEED      10      //绳索延伸正常速度
#define MMI_GM_GOLDMINER_SPEED_HIGH      20 //绳索延伸道具使用加速
#define MMI_GM_GOLDMINER_SPEED_LOW      2   //绳索延伸减速速( 勾住大物体)
//边界值信息
//#define MMI_GM_GOLDMINER_RECT       {MMI_GM_GOLDMINER_GRID_INTERVAL/2, MMI_GM_GOLDMINER_SHOOTER_Y, (MMI_GM_GOLDMINER_GRID_INTERVAL/2+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_H+MMI_GM_GOLDMINER_GRID_TOP)}
//#define MMI_GM_GOLDMINER_HORIZONTAL_RECT       {MMI_GM_GOLDMINER_GRID_INTERVAL/2, MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y, (MMI_GM_GOLDMINER_GRID_INTERVAL/2+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V+MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP)}
#define MMI_GM_GOLDMINER_HORIZONTAL_RECT       {MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT, MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y, (MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V+MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP)}

//提示区信息显示rect
#define MMI_GOLDMINER_TARGETSCORE_HORIZONTAL_RECT         {0,0,40,25}         //Target Score
#define MMI_GOLDMINER_SCORE_HORIZONTAL_RECT                      {0,25,40,50}       //current score
#define MMI_GOLDMINER_TIME_HORIZONTAL_RECT                          {119,0,159,25}     //count time
#define MMI_GOLDMINER_LEVEL_HORIZONTAL_RECT                       {119,25,159,50}    //level info
#define MMI_GOLDMINER_BOMB_NUM_HORIZONTAL_RECT               {50,25,60,35}          //Bomb num
#define MMI_GOLDMINER_ENERGY_NUM_HORIZONTAL_RECT            {100,25,110,35}      //Energy num

#define MMI_GOLDMINER_VIEW_LEVLE_RECT   {0,40,160,60}
#define MMI_GOLDMINER_VIEW_TIME_RECT     {0,60,160,80}
#define MMI_GOLDMINER_SETLEVEL_LABLE_RECT     {0,40,160,60} 
#define MMI_GOLDMINER_SETLEVEL_EDIT_RECT        {40,60,120,90}

#define MMI_GOLDMINER_TOOL_NUM_TOP_OFFSET   15
#define MMI_GOLDMINER_TOOL_NUM_RIGHT_OFFSET   5
#else// MAINLCD_SIZE_128X160

#define MMI_GM_GOLDMINER_GRID_INTERVAL 10   //每个cell 的边长
//以下关于一些横屏的定义，在mini screen项目竖屏上也有此命名
#define MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H 12   //屏幕横向网格数量
#define MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V 10   //屏幕纵向网格数量
#define MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP 60     //网格总布局rect 的top 值
#define MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT 4      //网格总布局rect的left值

#define MMI_GM_SHOOTER_LINE_LENGTH 10       //发射器绳子长度
#define MMI_GM_SHOOTER_DEFAULT_ANGLE    150     //发射器默认绳子的角度

#define MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_X 64    //发射器位置坐标X
#define MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y 40      //发射器位置坐标Y

#define MMI_GM_GOLDMINER_SPEED      10      //绳索延伸正常速度
#define MMI_GM_GOLDMINER_SPEED_HIGH      20 //绳索延伸道具使用加速
#define MMI_GM_GOLDMINER_SPEED_LOW      2   //绳索延伸减速速( 勾住大物体)
//边界值信息
//#define MMI_GM_GOLDMINER_RECT       {MMI_GM_GOLDMINER_GRID_INTERVAL/2, MMI_GM_GOLDMINER_SHOOTER_Y, (MMI_GM_GOLDMINER_GRID_INTERVAL/2+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_H+MMI_GM_GOLDMINER_GRID_TOP)}
//#define MMI_GM_GOLDMINER_HORIZONTAL_RECT       {MMI_GM_GOLDMINER_GRID_INTERVAL/2, MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y, (MMI_GM_GOLDMINER_GRID_INTERVAL/2+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V+MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP)}
#define MMI_GM_GOLDMINER_HORIZONTAL_RECT       {MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT, MMI_GM_GOLDMINER_SHOOTER_HORIZONTAL_Y, (MMI_GM_GOLDMINER_GRID_HORIZONTAL_LEFT+MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_H), (MMI_GM_GOLDMINER_GRID_INTERVAL*MMI_GM_GOLDMINER_GRID_NUM_HORIZONTAL_V+MMI_GM_GOLDMINER_GRID_HORIZONTAL_TOP)}

//提示区信息显示rect
#define MMI_GOLDMINER_TARGETSCORE_HORIZONTAL_RECT         {0,0,40,30}         //Target Score
#define MMI_GOLDMINER_SCORE_HORIZONTAL_RECT                      {0,30,40,60}       //current score
#define MMI_GOLDMINER_TIME_HORIZONTAL_RECT                          {87,0,127,30}     //count time
#define MMI_GOLDMINER_LEVEL_HORIZONTAL_RECT                       {87,30,127,60}    //level info
#define MMI_GOLDMINER_BOMB_NUM_HORIZONTAL_RECT               {35,25,45,35}          //Bomb num
#define MMI_GOLDMINER_ENERGY_NUM_HORIZONTAL_RECT            {85,25,95,35}      //Energy num

#define MMI_GOLDMINER_VIEW_LEVLE_RECT   {0,60,127,80}
#define MMI_GOLDMINER_VIEW_TIME_RECT     {0,80,127,100}
#define MMI_GOLDMINER_SETLEVEL_LABLE_RECT     {0,50,127,70} 
#define MMI_GOLDMINER_SETLEVEL_EDIT_RECT        {28,70,105,100}

#define MMI_GOLDMINER_TOOL_NUM_TOP_OFFSET   15
#define MMI_GOLDMINER_TOOL_NUM_RIGHT_OFFSET   5
#endif

//#else   //  其他分辨率可按需求添加,此处仅用于保证编译通过

//#endif


#ifdef   __cplusplus
   }
#endif
#endif
#endif// _MMIGAME_GOLDMINER_POSITION_H_

