//[[define image infomation
//]]define image infomation


//[[define anim infomation
//]]define anim infomation


//[[define string infomation
RES_ADD_STRING(TXT_ENG_OK,"OK")
RES_ADD_STRING(TXT_ENG_RETURN,"Return")
RES_ADD_STRING(TXT_ENG_PASS, "Pass")			//MS00193068
RES_ADD_STRING(TXT_ENG_FAIL, "Fail")			//MS00193068
RES_ADD_STRING(TXT_ENG_PHONETEST,"Phone test")			//MS00193068
RES_ADD_STRING(TXT_ENG_VERSION_INFO,"Version info")

RES_ADD_STRING(TXT_ENG_UITEST_TITLE,"MMI UI-TEST")
//RES_ADD_STRING(TXT_ENG_UIREADY,"Any key continue")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_ENG_SHOWVERSION_TITLE,"VERSION")      //case3£ºdefined but not used
RES_ADD_STRING(TXT_ENG_UIRTC_TITLE,"RTC")
RES_ADD_STRING(TXT_ENG_UIVIBRATE_TITLE,"Vibrate")
RES_ADD_STRING(TXT_ENG_UIBACKLIGHT_TITLE,"Backlight")
//RES_ADD_STRING(TXT_ENG_UICAMERA_TITLE,"Camera")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_ENG_UIHEADSET_TITLE,"Headset")  //replaced by common ID  TXT_COMM_HEADSET
RES_ADD_STRING(TXT_ENG_UILOOPBACK_TITLE,"Loopback")
RES_ADD_STRING(TXT_ENG_UIMELODY_TITLE,"Melody")
RES_ADD_STRING(TXT_ENG_UISD_TITLE,"SD Card")
RES_ADD_STRING(TXT_ENG_PRODUCT,"Product")

//RES_ADD_STRING(TXT_ENG_EDIT,"Edit")
RES_ADD_STRING(TXT_ENG_CLEAR,"Clear")
RES_ADD_STRING(TXT_ENG_LANGUAGE_SET_SUCC,"Language set Success")
//RES_ADD_STRING(TXT_ENG_CANCEL,"Cancel")       //case3£ºdefined but not used
//RES_ADD_STRING(TXT_ENG_SELECT,"Select")       //case3£ºdefined but not used
#ifdef ENG_SUPPORT
RES_ADD_STRING(TXT_ENG_HELP_INFO,"Help Info")
RES_ADD_STRING(TXT_ENG_MEM_PRESS_INFO,"MEM Press Test")
RES_ADD_STRING(TXT_ENG_UDISK_PRESS_INFO,"UDISK Press Test")
RES_ADD_STRING(TXT_ENG_SD_PRESS_INFO,"SD Press Test")
RES_ADD_STRING(TXT_ENG_SIM_PRESS_RUN,"Run")
RES_ADD_STRING(TXT_ENG_SIM_PRESS_STOP,"Stop")

#ifdef WRE_SUPPORT
RES_ADD_STRING(TXT_ENG_WRE_VERSION_INFO,"WRE Version Info")
#endif
RES_ADD_STRING(TXT_ENG_NET_INFO,"Net info")
RES_ADD_STRING(TXT_ENG_PSCELL_INFO,"acfcn,  relvx   ,S/Ncell")
//net info start 
RES_ADD_STRING(TXT_ENG_NW_CAP,"NW cap")
RES_ADD_STRING(TXT_ENG_SERVING_CELL,"Serving cell")
RES_ADD_STRING(TXT_ENG_THE_ADJACENT_CELL ,"The Adjacent Cell")
RES_ADD_STRING(TXT_ENG_BETWEEN_ADJACENT_CELL_2G,"Between Adjacent cell(2G)")
RES_ADD_STRING(TXT_ENG_OUTFIELD_NETWORK_INFORMATION,"Outfield Network Information")
RES_ADD_STRING(TXT_ENG_NETINFO_STATISTICS,"Netinfo statistics")
RES_ADD_STRING(TXT_ENG_NETINFO_RESELECT,"RESELECT")
RES_ADD_STRING(TXT_ENG_NETINFO_HANDOVER ,"HANDOVER")
RES_ADD_STRING(TXT_ENG_NETINFO_ATTACHTIME,"ATTACHTIME")
RES_ADD_STRING(TXT_ENG_NETINFO_DROPTIMES,"DROPTIMES")
//net info end
RES_ADD_STRING(TXT_ENG_PHONE_INFO,"Phone info")
RES_ADD_STRING(TXT_ENG_RESTORE_ENG,"Restore English language")
RES_ADD_STRING(TXT_ENG_PARA_SET,"Para set")
RES_ADD_STRING(TXT_ENG_POWER_KEY,"Power key")
#ifdef DSP_USB_LOG
RES_ADD_STRING(TXT_ENG_DSPCARD_LOG_ENABLE,"dsp card log enable")//xuefangjiang 20110729
#endif
RES_ADD_STRING(TXT_ENG_VOICE_PARAM,"Voice Param")
RES_ADD_STRING(TXT_ENG_LCD_PARAM,"LCD param")
RES_ADD_STRING(TXT_ENG_DEBUG_PARAM,"Debug Param")
RES_ADD_STRING(TXT_ENG_RF_PARAM,"RF param")
RES_ADD_STRING(TXT_ENG_HW_PARAM,"HW param")
RES_ADD_STRING(TXT_ENG_ARM_LOG,"AP log")
RES_ADD_STRING(TXT_ENG_SLEEP_MODE,"Sleep mode")
RES_ADD_STRING(TXT_ENG_AUTO_POWERON,"Auto power on")
RES_ADD_STRING(TXT_ENG_STANDBY_TIME,"Standby time")
RES_ADD_STRING(TXT_ENG_SHOW_STANDBY_TIME,"Show standby time")
RES_ADD_STRING(TXT_ENG_STANDBY_TIME_SET,"Set standby time")    
RES_ADD_STRING(TXT_ENG_GET_FLASH_INFO,"Get FLASH ID")
RES_ADD_STRING(TXT_ENG_UPDATE_IMEI,"Update IMEI Number")
RES_ADD_STRING(TXT_ENG_DSP_LOG,"CP log")
//RES_ADD_STRING(TXT_ENG_GPRS,"GPRS") //replaced by common ID TXT_GPRS
RES_ADD_STRING(TXT_ENG_YES,"Yes")
RES_ADD_STRING(TXT_ENG_NO,"No")
//RES_ADD_STRING(TXT_ENG_OPEN,"Open")  //replaced by common ID TXT_OPEN_COMN
//RES_ADD_STRING(TXT_ENG_CLOSE,"Close")  //replaced by common ID TXT_COMM_CLOSE
//RES_ADD_STRING(TXT_ENG_ON,"On")  //replaced by common ID TXT_COMM_ON
//RES_ADD_STRING(TXT_ENG_OFF,"Off") //replaced by common ID TXT_COMM_OFF
RES_ADD_STRING(TXT_ENG_HDSTSDTONE,"Hdst Sidetone")
RES_ADD_STRING(TXT_ENG_C_HDSTSDTONE,"Close Hdst Sidetone")
RES_ADD_STRING(TXT_ENG_EARPHSDTONE,"Earphn Sidetone")
RES_ADD_STRING(TXT_ENG_C_EARPHSDTONE,"Close Earphn Sidetone")
RES_ADD_STRING(TXT_ENG_HDSTDGT,"Handset Dgt")
RES_ADD_STRING(TXT_ENG_HDFREDGT,"Handfree Dgt")
RES_ADD_STRING(TXT_ENG_EARPHDGT,"Earphone Dgt")
RES_ADD_STRING(TXT_ENG_HDSTPGA,"Handset PGA")
RES_ADD_STRING(TXT_ENG_HDFREPGA,"Handfree PGA")
RES_ADD_STRING(TXT_ENG_EARPHPGA,"Earphone PGA")
RES_ADD_STRING(TXT_ENG_HDSTSCL,"Handset Scl")
RES_ADD_STRING(TXT_ENG_HDFRESCL,"Handfree Scl")
RES_ADD_STRING(TXT_ENG_EARPHSCL,"Earphone Scl")
RES_ADD_STRING(TXT_ENG_BRIGHTNESS,"Brightness Test")
RES_ADD_STRING(TXT_ENG_MAINLCD,"Main LCD")
RES_ADD_STRING(TXT_ENG_SUBLCD,"Sub LCD")
RES_ADD_STRING(TXT_ENG_BAND,"Band select")
//RES_ADD_STRING(TXT_ENG_PORTSET,"Port set")
RES_ADD_STRING(TXT_ENG_ASSERTMODE,"Assert Mode")
RES_ADD_STRING(TXT_ENG_ASSERTTARGET,"Assert Target")
RES_ADD_STRING(TXT_ENG_MANUALASSERT,"Manual assert")
RES_ADD_STRING(TXT_ENG_FORBIDPLMN,"Forbid PLMN")
RES_ADD_STRING(TXT_ENG_NO_PLMN,"PLMN not found")
RES_ADD_STRING(TXT_ENG_PLMN_SELECT,"PLMN Select")


RES_ADD_STRING(TXT_ENG_ASSERT_RESTART,"Assert restart")
RES_ADD_STRING(TXT_ENG_ASSERT_INFO,"Assert info")
RES_ADD_STRING(TXT_ENG_BAND_PCS,"PCS band")
RES_ADD_STRING(TXT_ENG_BAND_GSM,"GSM band")
RES_ADD_STRING(TXT_ENG_BAND_DCS,"DCS band")
RES_ADD_STRING(TXT_ENG_BAND_DUL,"Dual band")
//RES_ADD_STRING(TXT_ENG_PORT_DATA,"Data mode")
//RES_ADD_STRING(TXT_ENG_PORT_AT,"AT mode")
//RES_ADD_STRING(TXT_ENG_PORT_MIXED,"Mixed mode")
//RES_ADD_STRING(TXT_ENG_DEBUGMODE,"Debug mode") ////replaced by common ID TXT_COMM_DEBUG_MODE
RES_ADD_STRING(TXT_ENG_RELEASEMODE,"Release mode")
RES_ADD_STRING(TXT_ENG_SEND_POWER,"Send power")
RES_ADD_STRING(TXT_ENG_NETLOST,"Net lost")
RES_ADD_STRING(TXT_ENG_TCV,"TCV")
//RES_ADD_STRING(TXT_ENG_AFC,"AFC")
//RES_ADD_STRING(TXT_ENG_PA,"PA")
//RES_ADD_STRING(TXT_ENG_AGC,"AGC")
RES_ADD_STRING(TXT_ENG_ERRRATE,"ERR rate")
RES_ADD_STRING(TXT_ENG_TITLE,"ENG MODE")
RES_ADD_STRING(TXT_ENG_RESULT,"Result")
RES_ADD_STRING(TXT_ENG_LAYER1_MONITOR,"Layer1 monitor")
RES_ADD_STRING(TXT_ENG_SENSOR_MODE,"Sensor Mode")
RES_ADD_STRING(TXT_ENG_DEFAULT,"Default")
//RES_ADD_STRING(TXT_ENG_DCD_DEFAULT,"DCD Default")
RES_ADD_STRING(TXT_ENG_DCD_NOTE,"DCD Update Log")
RES_ADD_STRING(TXT_ENG_NET_SET, "Net Setting")
RES_ADD_STRING(TXT_ENG_RGB,"RGB")
RES_ADD_STRING(TXT_ENG_YUV,"YUV")
//RES_ADD_STRING(TXT_ENG_UIKEYBOARD_TITLE,"Keyboard")       //case3£ºdefined but not used
RES_ADD_STRING(TXT_ENG_DV_FRAME_FRE,"DV frame fre")
//RES_ADD_STRING(TXT_ENG_WAP_SETTINGS,"Wap settings")         //case3£ºdefined but not used
RES_ADD_STRING(TXT_ENG_UA_AGENT,"User agent")
RES_ADD_STRING(TXT_ENG_UA_PROFILE,"UA profile")
RES_ADD_STRING(TXT_ENG_WAP_LOG,"Wap log")
//RES_ADD_STRING(TXT_ENG_SAS_TEST_MODE,"SAS Test Mode")
RES_ADD_STRING(TXT_ENG_HIDDEN_PARTITION_VISIBLE,"Hidden partition visible")
RES_ADD_STRING(TXT_ENG_CALLFORWARD_QUERY,"Start Call forward query when power on")
RES_ADD_STRING(TXT_ENG_BT_INFO,"Bluetooth info")
RES_ADD_STRING(TXT_EMG_BT_ADDR_INFO,"Address info")
RES_ADD_STRING(TXT_ENG_ENTER_BT_EUT,"Enter EUT mode")
RES_ADD_STRING(TXT_ENG_LEAVE_BT_EUT,"Leave EUT mode")
RES_ADD_STRING(TXT_ENG_BT_SSP_DEBUG,"SSP debug mode")
RES_ADD_STRING(TXT_ENG_BT_BQB_MODE,"Bqb mode")
//RES_ADD_STRING(TXT_ENG_BAND_TRIPLE,"Triple band")      //case3£ºdefined but not used
RES_ADD_STRING(TXT_ENG_BAND_QUAD,"Quadruple Band")
//RES_ADD_STRING(TXT_ENG_CHIP_TEST_SETTING,"Setting")      //replaced by common ID STXT_MAIN_SETTING
RES_ADD_STRING(TXT_ENG_POWERON_RUN,"Run when power on")
//RES_ADD_STRING(TXT_ENG_POWERON_NOT_RUN,"Not run when power on")   //case3£ºdefined but not used
RES_ADD_STRING(TXT_ENG_CHIP_TEST,"Chip Test")
//RES_ADD_STRING(TXT_ENG_TIP_MPEG4,"Can't find test.mp4")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_ENG_TIP_MP3,"Can't find test.mp3")    //case3£ºdefined but not used
//RES_ADD_STRING(STXT_ENG_GPS_TEST,"Test")    //case3£ºdefined but not used
RES_ADD_STRING(TXT_ENG_CARDLOG,"Card Log")
RES_ADD_STRING(TXT_ENG_NPS_TIMER_CHANGE,"NPS timer change")//[MS]
RES_ADD_STRING(TXT_ENG_NPS_TIMER_CHANGE1,"Please input timer:")//[MS]
RES_ADD_STRING(TXT_ENG_NPS_TIMER_ONE_HOUR,"one hour(1-60*60(s)")//[MS]
RES_ADD_STRING(TXT_ENG_NPS_TIMER_HOUR_ACCOUNT,"hour account(1-24*14)")//[MS]
RES_ADD_STRING(TXT_ENG_NPS_TIMER_CHANGE_VALUE,"The time value is one hour multiply hour account")//[MS]
RES_ADD_STRING(TXT_ENG_AUTO_ANSWER_CALL,"Auto Answer Call")
//RES_ADD_STRING(TXT_ENG_GPRS_ATTACH,"GPRS ATTACH")        //case3£ºdefined but not used
RES_ADD_STRING(TXT_ENG_IQ_MODE,"IQ Mode")
//RES_ADD_STRING(TXT_ENG_POWERSWEEP_INFO,"Powersweep Info")
RES_ADD_STRING(TXT_ENG_IQ_DATA,"IQ Data")
//RES_ADD_STRING(TXT_ENG_IQ_DATA_SETTINGS,"Settings")       //replaced by common ID STXT_MAIN_SETTING
RES_ADD_STRING(TXT_ENG_IQ_DATA_MODE_SETTINGS,"Mode Settings")
RES_ADD_STRING(TXT_ENG_IQ_DATA_POWER_ON_START,"Power On Start")
//RES_ADD_STRING(TXT_ENG_IQ_DATA_MODE_D_SETTINGS,"Traffic IQ")     //case3£ºdefined but not used
//RES_ADD_STRING(TXT_ENG_IQ_DATA_MODE_CUSTOMIZE_SETTINGS,"Mode customized")  //replaced by common ID TXT_EXPORT_LOC_CUSTOM
RES_ADD_STRING(TXT_ENG_IQ_DATA_FORMAT_SETTING,"Format Setting")
RES_ADD_STRING(TXT_ENG_IQ_DATA_CHANNEL_SETTING,"Channel Setting")
RES_ADD_STRING(TXT_ENG_IQ_DATA_TIME_LIMIT,"Time Limit")
RES_ADD_STRING(TXT_ENG_IQ_DATA_FRAME_LENGTH,"Frame Length")
RES_ADD_STRING(TXT_ENG_IQ_DATA_BLOCK_COUNT,"Block Count")
RES_ADD_STRING(TXT_ENG_IQ_DATA_ARFCN,"arfcn")
//RES_ADD_STRING(TXT_ENG_USB_LOG,"USB LOG") //replaced by local ID TXT_COMM_USB_LOG
//RES_ADD_STRING(TXT_ENG_MMS_RESPONCE,"MMS Responce")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_ENG_MMS_MAX_SIZE,"MMS Max Size")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_ENG_MMS_300,"300")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_ENG_MMS_100,"100")      //case3£ºdefined but not used

RES_ADD_STRING(TXT_ENG_START_CHIP_TEST,"Start Chip Test")
RES_ADD_STRING(TXT_ENG_SMSASSERT,"SMS ASSERT")
RES_ADD_STRING(TXT_ENG_IQ_MODE_WARNING,"Cannot Operate Record In IQ Mode")
RES_ADD_STRING(TXT_ENG_IQ_DATA_RECORD_AGAIN,"Format Memory, Record Again?")
RES_ADD_STRING(TXT_ENG_IQ_DATA_STOP_IQ_DATA_WARNING,"Please stop IQ data")
RES_ADD_STRING(TXT_ENG_IQ_DATA_MODE_A_SETTINGS,"CCCH IQ")
RES_ADD_STRING(TXT_ENG_IQ_DATA_MODE_B_SETTINGS,"Voice Data")
RES_ADD_STRING(TXT_ENG_IQ_DATA_MODE_C_SETTINGS,"Search IQ")
RES_ADD_STRING(TXT_ENG_IQ_DATA_ENABLE,"Enable")
RES_ADD_STRING(TXT_ENG_IQ_DATA_DISABLE,"Disable")
RES_ADD_STRING(TXT_ENG_IQ_DATA_CHANNEL_FILE,"File Output")
RES_ADD_STRING(TXT_ENG_IQ_DATA_CHANNEL_ARM_LOG,"ARM Log Output")
RES_ADD_STRING(TXT_ENG_GPS_TEST,"GPS test")
RES_ADD_STRING(TXT_ENG_FULLTEST,"Full phone test")			//MS00193068
RES_ADD_STRING(TXT_ENG_FORCE_CELL,"Froce cell")
RES_ADD_STRING(TXT_ENG_DV_FRAME_FRE_15,"15HZ")
RES_ADD_STRING(TXT_ENG_DV_FRAME_FRE_20,"20HZ")
RES_ADD_STRING(TXT_ENG_DV_FRAME_FRE_25,"25HZ")
RES_ADD_STRING(TXT_ENG_DV_FRAME_FRE_30,"30HZ")
RES_ADD_STRING(TXT_ENG_DV_FRAME_FRE_10,"10HZ")
RES_ADD_STRING(TXT_ENG_DCD_SET, "DCD Setting")
RES_ADD_STRING(TXT_ENG_CONTRAST,"Contrast Set")
RES_ADD_STRING(TXT_ENG_CMMB_RD_TEST, "CMMB R&D test")
RES_ADD_STRING(TXT_ENG_CMMB_DISPLAY,"Display")
RES_ADD_STRING(TXT_ENG_CMCC_TEST_SERVER, "CMCC test server")
//RES_ADD_STRING(TXT_ENG_CARDLOG_OPEN_ERROR, "Card log open fail!")// @cr239352 renwei add
RES_ADD_STRING(TXT_ENG_CARDLOG_OPEN_ERROR_UDISK, "Card log open fail! U Disk is in use!")// @cr239352 renwei add
RES_ADD_STRING(TXT_ENG_CARDLOG_OPEN_ERROR_USBLOG, "Card log open fail! USB log is on!")// @cr239352 renwei add
RES_ADD_STRING(TXT_ENG_CARDLOG_OPEN_ERROR_SDUSBLOG, "Card log open fail! SD USB log is on!")// @cr239352 renwei add

RES_ADD_STRING(TXT_ENG_CARDLOG_FORMAT_CONTINUE,"Card Log Format Continue")
RES_ADD_STRING(TXT_ENG_3RDPARTY_VERSION_INFO,"Third party version info")
RES_ADD_STRING(TXT_ENG_AUDIO_SPEAKER_VOLUME,"Speaker Volume")
RES_ADD_STRING(TXT_ENG_AUDIO_SIDETONE_VOLUME,"Sidetone Volume")
RES_ADD_STRING(TXT_ENG_AUDIO_RECORD,"Record")
RES_ADD_STRING(TXT_ENG_AUDIO_RECEIVER_VOLUME,"Receiver Volume")
RES_ADD_STRING(TXT_ENG_AUDIO_MP4HFTR,"MP4HFTR")
RES_ADD_STRING(TXT_ENG_AUDIO_MP4HFTP,"MP4HFTP")
RES_ADD_STRING(TXT_ENG_AUDIO_MP4HEADSET,"MP4Headset")
RES_ADD_STRING(TXT_ENG_AUDIO_MP3_LOUDSPK,"MP3_LoudSPK")
RES_ADD_STRING(TXT_ENG_AUDIO_MP3_EARPHONE,"MP3_EarPhone")
RES_ADD_STRING(TXT_ENG_AUDIO_MP3_HEADFREE,"MP3_HeadFree")
RES_ADD_STRING(TXT_ENG_AUDIO_MIC_VOLUME,"MIC Volume")
RES_ADD_STRING(TXT_ENG_AUDIO_HANDSFREE,"Handsfree")
RES_ADD_STRING(TXT_ENG_AUDIO_HANDSET,"Handset")
RES_ADD_STRING(TXT_ENG_AUDIO_EAR_VOLUME,"Ear Volume")
RES_ADD_STRING(TXT_ENG_CANCEL_FORCE_CELL,"Cancel forced cell")
RES_ADD_STRING(TXT_ENG_ADC_CALIBRATE_INFO,"Adc Calibrate Info")
RES_ADD_STRING(TXT_ENG_CMMB_TEST,"CMMB TV Test")
RES_ADD_STRING(TXT_ENG_CMMB_INI_FILE_ERROR, "CMMB configuration file error or not exist")
RES_ADD_STRING(TXT_ENG_CMMB_FACTORY_TEST, "CMMB factory test")
RES_ADD_STRING(TXT_ENG_CMMB_SN_NO, "CMMB SN")
RES_ADD_STRING(TXT_ENG_CMMB_FACTORY_HAVE_SIGNAL, "CMMB has signal test")
RES_ADD_STRING(TXT_ENG_CMMB_FACTORY_NO_SIGNAL, "CMMB no signal test")
RES_ADD_STRING(TXT_ENG_CMMB_RF_TEST, "CMMB RF test")
RES_ADD_STRING(TXT_ENG_ITEMTEST,"Item test")	
//RES_ADD_STRING(TXT_ENG_INVALID_ADDRESS,"Invalid address")     //case3£ºdefined but not used

#ifdef PCLINK_SUPPORT
RES_ADD_STRING(TXT_ENG_SUCCESS_NEED_RESET,"Success,you need to reset")
RES_ADD_STRING(TXT_ENG_PCLINK,"PC Link Set")
RES_ADD_STRING(TXT_ENG_PCLINK_ENABLE,"PC Link enable")
RES_ADD_STRING(TXT_ENG_PCLINK_IP,"PC Link IP")
RES_ADD_STRING(TXT_ENG_PCLINK_SNMASK,"PC Link subnet mask")
RES_ADD_STRING(TXT_ENG_PCLINK_DEFGW,"PC Link gateway")
RES_ADD_STRING(TXT_ENG_PCLINK_DNS,"PC Link DNS")
RES_ADD_STRING(TXT_ENG_PCLINK_PING_TEST_START,"Ping test start ...")
RES_ADD_STRING(TXT_ENG_PCLINK_PING_TEST_OK,"Ping test OK")
RES_ADD_STRING(TXT_ENG_PCLINK_PING_TEST_TIMEOUT,"Ping test time-out")
RES_ADD_STRING(TXT_ENG_PCLINK_PING_TEST_CANCELED,"Ping test canceled")
RES_ADD_STRING(TXT_ENG_PCLINK_PING_TEST_ERROR,"Ping test error")
RES_ADD_STRING(TXT_ENG_PCLINK_TEST,"PC Link test")
RES_ADD_STRING(TXT_ENG_PCLINK_TEST_ADDR,"Test Address")
RES_ADD_STRING(TXT_ENG_PCLINK_PING_TEST,"Ping Test")
#endif

RES_ADD_STRING(TXT_ENG_APP_SET,"App Set")
RES_ADD_STRING(TXT_ENG_DC_PARAM,"DC param")
RES_ADD_STRING(TXT_ENG_DC_PARAM_SCREEN_SIZE,"Screen Size")
RES_ADD_STRING(TXT_ENG_DC_PARAM_SCREEN_SWITCH,"Screen Switch")
RES_ADD_STRING(TXT_ENG_UA_SETTINGS,"UA SETTING")
RES_ADD_STRING(TXT_ENG_DC_PARAM_PREV_SET,"Prev Set")
RES_ADD_STRING(TXT_ENG_DC_PARAM_SENSOR_ANGLE,"Sensor Angle")
#ifdef  CAMERA_SUPPORT
RES_ADD_STRING(TXT_ENG_DC_176_220,"176*220")
RES_ADD_STRING(TXT_ENG_DC_240_320,"240*320")
RES_ADD_STRING(TXT_ENG_DC_220_400,"220*400")
RES_ADD_STRING(TXT_ENG_DC_ACROSS_SCREEN,"Across Screen")
RES_ADD_STRING(TXT_ENG_DC_UPRIGHT_SCREEN,"Upright Screen")
RES_ADD_STRING(TXT_ENG_DC_FULL_SCREEN,"Full Screen")
RES_ADD_STRING(TXT_ENG_DC_FULL_VIEW,"Full View")
#endif
RES_ADD_STRING(TXT_ENG_IQ_MODE_ONOFF,"On/Off")
//RES_ADD_STRING(TXT_ENG_LANGUAGE_SET_SUCC,"Language set Success")
//RES_ADD_STRING(TXT_ENG_LANGUAGE_NOT_EXIST,"Not Exist") //replaced by common ID TXT_COMMON_NOT_EXIST
//RES_ADD_STRING(TXT_ENG_CMMB_IQ_DATA,"IQ data")       //case3£ºdefined but not used
//RES_ADD_STRING(TXT_ENG_CMMB_PLAY,"Play")  //replaced by common ID  TXT_NET_PLAY
//RES_ADD_STRING(TXT_ENG_CMMB_SET,"Setting")        //case3£ºdefined but not used

RES_ADD_STRING(TXT_ENG_AUDIO_SETTING,"Audio set")
//RES_ADD_STRING(TXT_ENG_AUDIO_HEADSET,"Headset") //replaced by common ID TXT_COMM_HEADSET
//RES_ADD_STRING(TXT_ENG_AUDIO_BT,"BT")  //replaced by common ID TXT_NET_UK_BT
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME1,"Vol 1")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME2,"Vol 2")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME3,"Vol 3")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME4,"Vol 4")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME5,"Vol 5")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME6,"Vol 6")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME7,"Vol 7")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME8,"Vol 8")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME9,"Vol 9")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME10,"Vol 10")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME11,"Vol 11")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME12,"Vol 12")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME13,"Vol 13")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME14,"Vol 14")
RES_ADD_STRING(TXT_ENG_AUDIO_VOLUME15,"Vol 15")

//RES_ADD_STRING(TXT_ENG_PIM_DEBUG_SET,"PIM Debug set")//wangxiaolin 2009.07.07
//RES_ADD_STRING(TXT_ENG_MTV_INPUT_FREQ, "Input FREQ")   //case3£ºdefined but not used
//RES_ADD_STRING(TXT_ENG_CMMB_PLAY_RECORD, "Play record")    //case3£ºdefined but not used

//RES_ADD_STRING(TXT_ENG_MBBMS_GBA,"GBA Test")     //case3£ºdefined but not used
#ifdef DEMOD_HW_SIANO
RES_ADD_STRING(TXT_ENG_MBBMS_LOG,"LOG Control")
RES_ADD_STRING(TXT_ENG_MBBMS_MSK,"MSK Test")
#endif
//RES_ADD_STRING(TXT_ENG_MBBMS_GBA_AND_MSK_TEST,"GBA&&MSK Test")      //case3£ºdefined but not used
#ifdef MBBMS_SUPPORT
RES_ADD_STRING(TXT_ENG_MBBMS_INTERFACE_TEST,"Interface testing")
RES_ADD_STRING(TXT_ENG_MBBMS_SMD_COUNTER,"SMD Counter")
#endif
#ifdef CMMB_SUPPORT
RES_ADD_STRING(TXT_ENG_MTV_LOG,"MTV LOG")
RES_ADD_STRING(TXT_ENG_MTV_LOG_SWITCH,"Switch")
RES_ADD_STRING(TXT_ENG_MTV_LOG_TO_BB_SWITCH,"Log to BB Switch")
RES_ADD_STRING(TXT_ENG_MTV_LOG_STORAGE_SELECT,"Storage Select")
RES_ADD_STRING(TXT_ENG_MTV_LOG_STORAGE_U,"U Disk")
RES_ADD_STRING(TXT_ENG_MTV_LOG_STORAGE_SD,"SD Card")

RES_ADD_STRING(TXT_ENG_MBBMS_AUDIO_SERVICE,"MBBMS audio service")
#endif
//RES_ADD_STRING(TXT_ENG_CMMB_DECODE_TEST, "CMMB Decode test")      //case3£ºdefined but not used
RES_ADD_STRING(TXT_ENG_TCPIP_DEBUG, "Tcpip Debug")

RES_ADD_STRING(TXT_CAP_OUTPUT, "Cap Output")
//#endif  //ENG_SUPPORT
#ifdef MMI_SMS_RETRY_SUPPORT
RES_ADD_STRING(TXT_SMS_RETRY_SET, "SMS Retry set")
#endif

RES_ADD_STRING(TXT_ENG_UA_ON_OR_OFF,"on/off")
RES_ADD_STRING(TXT_ENG_UA_SET,"Set")
RES_ADD_STRING(TXT_ENG_UA_SHOW,"Show")

RES_ADD_STRING(TXT_ENG_PROFILE_SONYERICSSON,"SONYERICSSON")
RES_ADD_STRING(TXT_ENG_PROFILE_NOKIA,"NOKIA")
RES_ADD_STRING(TXT_ENG_ANGLE_0,"0")
RES_ADD_STRING(TXT_ENG_ANGLE_90,"90")
RES_ADD_STRING(TXT_ENG_ANGLE_180,"180")
RES_ADD_STRING(TXT_ENG_ANGLE_270,"270")
RES_ADD_STRING(TXT_ENG_UA_EDIT,"Edit")
RES_ADD_STRING(TXT_ENG_UA_LIST,"List")

RES_ADD_STRING(TXT_ENG_UA_NONE,"None")
RES_ADD_STRING(TXT_ENG_UA_DORADO,"DORADO")
RES_ADD_STRING(TXT_ENG_UA_MTK,"MTK")
RES_ADD_STRING(TXT_ENG_UA_09A,"09A")
RES_ADD_STRING(TXT_ENG_UA_NOKIA,"NOKIA")
RES_ADD_STRING(TXT_ENG_UA_NF,"NF")



RES_ADD_STRING(TXT_ENG_CALL_BARRING,"Call Barring")//MS00186848
RES_ADD_STRING(TXT_ENG_SET_ANGLE,"Set logic Angle")
#ifdef ENG_BAND_FREQ_SUPPORT //zhouqin 
RES_ADD_STRING(TXT_ENG_BAND_FREQ_SET,"Lock Band & Frequency")
RES_ADD_STRING(TXT_ENG_SET_BAND,"Lock Band")
RES_ADD_STRING(TXT_ENG_SET_FREQ,"Lock Frequency")
RES_ADD_STRING(TXT_ENG_SET_LTE_FREQ,"Lock LTE Frequency")
RES_ADD_STRING(TXT_ENG_SET_GSM_FREQ,"Lock GSM Frequency")

RES_ADD_STRING(TXT_ENG_SET_LTE_BAND,"LTE Band")
RES_ADD_STRING(TXT_ENG_SET_GSM_BAND,"GSM Band")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_1,"1")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_2,"2")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_3,"3")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_4,"4")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_5,"5")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_7,"7")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_8,"8")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_12,"12")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_13,"13")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_17,"17")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_20,"20")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_28,"28")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_38,"38")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_39,"39")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_40,"40")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_41,"41")
RES_ADD_STRING(TXT_ENG_SET_LTE_BAND_66,"66")
RES_ADD_STRING(TXT_ENG_SET_GSM_BAND_1800,"1800")
RES_ADD_STRING(TXT_ENG_SET_GSM_BAND_1900,"1900")
RES_ADD_STRING(TXT_ENG_SET_GSM_BAND_850,"850")
RES_ADD_STRING(TXT_ENG_SET_GSM_BAND_900,"900")
RES_ADD_STRING(TXT_ENG_INVALID_FREQ,"Invalid Frequency")

#endif

#ifdef ENG_NETWORK_SET
RES_ADD_STRING(TXT_ENG_NOT_SUPPORT_LTE,"Please open 4G mode")
RES_ADD_STRING(TXT_ENG_LTE_NETWORK_SET,"Set LTE Network")
RES_ADD_STRING(TXT_ENG_SET_LTE_SERVICE,"LTE Service Priority")
RES_ADD_STRING(TXT_ENG_SET_LTE_CS_VOICE_ONLY,"CS Voice only")
RES_ADD_STRING(TXT_ENG_SET_LTE_CS_VOICE_PREFER,"CS Voice preferred")
RES_ADD_STRING(TXT_ENG_SET_LTE_PS_VOICE_PREFER,"IMS PS Voice preferred")
RES_ADD_STRING(TXT_ENG_SET_LTE_PS_VOICE_ONLY,"IMS PS Voice only")
RES_ADD_STRING(TXT_ENG_SET_LTE_OPERATION_MODE,"LTE operation Mode")
RES_ADD_STRING(TXT_ENG_SET_LTE_PS_2,"PS mode 2 ")
RES_ADD_STRING(TXT_ENG_SET_LTE_CS_PS_1,"CS/PS mode 1")
RES_ADD_STRING(TXT_ENG_SET_LTE_CS_PS_2,"CS/PS mode 2")
RES_ADD_STRING(TXT_ENG_SET_LTE_PS_1,"PS mode 1")


#endif  

//ENG_TEST_MODE
#ifndef  ENG_TEST_MODE_FLAG
RES_ADD_STRING(TXT_ENG_FORBID_ALL_DATA,"Forbid all gprs data")
RES_ADD_STRING(TXT_ENG_TEST_MODE,"Test Mode")
RES_ADD_STRING(TXT_ENG_USB_TEST_SET,"USB Test Set")
RES_ADD_STRING(TXT_ENG_USB_CHOOSE_EVERYTIME,"Choose Everytime")
RES_ADD_STRING(TXT_ENG_ESD_TEST_SET,"ESD Test Set")
RES_ADD_STRING(TXT_ENG_UPDATE_TEST_SET,"Fota Update Set")
RES_ADD_STRING(TXT_ENG_FOTA_SET_BEGIN_NV,"Fota Set Begin NV")
RES_ADD_STRING(TXT_ENG_UPDATE_TEST_NEVER,"Never")
RES_ADD_STRING(TXT_ENG_UPDATE_TEST_ONE_DAY,"Per Day")
RES_ADD_STRING(TXT_ENG_UPDATE_TEST_ONE_WEEK,"Per Week")
RES_ADD_STRING(TXT_ENG_UPDATE_TEST_ONE_MONTH,"Per Month")
RES_ADD_STRING(TXT_ENG_GCF_BAND41_SET,"Band41")
RES_ADD_STRING(TXT_ENG_VOLTE_SHOW_SET,"Volte Set")
#endif


#endif  //ENG_SUPPORT

#ifdef JAVA_SUPPORT_IA
RES_ADD_STRING(TXT_ENG_JAVA_AUTO_TCK_MODE, "JAVA AUTO TCK MODE")
#endif



#ifdef MEDIA_DEMO_SUPPORT
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO,"Media demo")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_DEMO,"Audio demo")
RES_ADD_STRING(TXT_ENG_MEDIA_VIDEO_DEMO,"Video demo")


RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_AAC_STREAM_DEMO,"Aac stream")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_AMR_STREAM_DEMO,"Amr stream")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_AMR_RECORD_DEMO,"Amr record")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_MP3_STREAM_DEMO,"Mp3 stream")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_WAV_STREAM_DEMO,"Wav stream")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_EXPRESS_DEMO,   "Audio expression")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_CAT_MVOICE_DEMO,"Cat Mvoice")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_MIC_SAMPLE_DEMO,"Mic Sample")


RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_STREAM_LEFT_TRACK,"LTrack")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_STREAM_RIGHT_TRACK,"RTrack")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_STREAM_LEFT_AND_RIGHT,"LRTrack")

RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_RECORD, "Record")
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_PLAY,   "Play")
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_STOP,   "Stop")
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_PAUSE,  "Pause")
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_RESUME, "Resume")
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_START,  "Start ")
RES_ADD_STRING(TXT_ENG_MEDIA_DEMO_NEXT,   "NEXT ")

RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_MVCOIE,  "Mvoice ")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_VCOIE,   "Voice ")

RES_ADD_STRING(TXT_ENG_MEDIA_VIDEO_CHAT_DEMO, "Video Chat")
RES_ADD_STRING(TXT_ENG_MEDIA_VIDEO_YUV_DEMO,"YUV Show ") 
RES_ADD_STRING(TXT_ENG_MEDIA_VIDEO_YUV422_2P,"422_2P")
RES_ADD_STRING(TXT_ENG_MEDIA_VIDEO_YUV420_2P,"420_2P")
RES_ADD_STRING(TXT_ENG_MEDIA_VIDEO_YUV420_3P,"420_3P")

RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_EXPRESSION_CARD,"No card or No Demo source LRTrack1.mp3, please check and try again!")
RES_ADD_STRING(TXT_ENG_MEDIA_AUDIO_CAT_MVOICE_CARD,"No card,please check and try again!")
#endif
#ifdef ENG_SUPPORT
//MS00216980 cheney begin
RES_ADD_STRING(TXT_ENG_CMCC_TEST_CONFIG, "CMCC test config")
RES_ADD_STRING(TXT_ENG_CMCC_BUSINESS_SERVER, "CMCC business server")
//MS00216980 cheney end

RES_ADD_STRING(TXT_ENG_VIEWRESULT,"View phone test result")	//MS00193068
//RES_ADD_STRING(TXT_ENG_TEST_BATTERY , "Battery test")    //case3£ºdefined but not used
RES_ADD_STRING(TXT_ENG_TEST_KEY , "Key test"  )
RES_ADD_STRING(TXT_ENG_TEST_MAINLCD, "Main lcd test")

RES_ADD_STRING(TXT_ENG_TEST_SIM, "SIM test")
RES_ADD_STRING(TXT_ENG_TEST_SIM_RESULT, "Test result:")

RES_ADD_STRING(TXT_ENG_TEST_SIM1, "Test SIM1 reslut:")
RES_ADD_STRING(TXT_ENG_TEST_SIM2, "Test SIM2 reslut:")

RES_ADD_STRING(TXT_ENG_TEST_SIM_RESULT1, "Success!")
RES_ADD_STRING(TXT_ENG_TEST_SIM_RESULT2, "Failed!")

RES_ADD_STRING(TXT_ENG_TEST_RTC , "RTC test")
RES_ADD_STRING(TXT_ENG_TEST_VIBRATER, "Vibrater test" )
RES_ADD_STRING(TXT_ENG_TEST_BACKLIGHT, "Backlight test" )
RES_ADD_STRING(TXT_ENG_TEST_LOOPBACK, "Loopback test" )
RES_ADD_STRING(TXT_ENG_TEST_CAMERA , "Camera test" )
RES_ADD_STRING(TXT_ENG_TEST_TORCH , "Torch LED test" )
RES_ADD_STRING(TXT_ENG_TEST_BLUETOOTH , "BlueTooth test" )
RES_ADD_STRING(TXT_ENG_TEST_HEADSET , "Headset test" )
RES_ADD_STRING(TXT_ENG_TEST_MELODY , "Melody test")
#ifdef MSDC_CARD_SUPPORT
RES_ADD_STRING(TXT_ENG_TEST_SDCARD , "SDcard test" )
#endif
#endif
#ifdef APP_ENG_COMTEST_SUPPORT
RES_ADD_STRING(TXT_ENG_TEST_COM , "COM test")
#endif
#ifdef FM_SUPPORT
RES_ADD_STRING(TXT_ENG_TEST_FM , "FM test" )
#endif
#ifdef GPS_SUPPORT
RES_ADD_STRING(TXT_ENG_TEST_GPS  , "GPS test" )
#endif
//RES_ADD_STRING(TXT_ENG_TEST_TVOUT  , "TVOUT test" )    //case3£ºdefined but not used


#ifdef ATV_SUPPORT
RES_ADD_STRING(TXT_ENG_TEST_ATV,  "ATV test" )
RES_ADD_STRING(TXT_ATV_CHANNEL,  "ATV Channel" )
RES_ADD_STRING(TXT_ATV_SIGNAL,  "ATV Signal" )
RES_ADD_STRING(TXT_ATV_CHANNEL_EDIT,  "ATV Channel Edit" )
#endif
RES_ADD_STRING(TXT_ENG_TEST_CHARGING,  "Charging Test" )
RES_ADD_STRING(TXT_ENG_TEST_EMCC,  "Emcc Test" )
#ifdef ENG_SUPPORT
RES_ADD_STRING(TXT_ENG_NVCOUNT,"Running NV Counting")		//195273
RES_ADD_STRING(TXT_ENG_BROWSER_LOG,"Browser Log")		//195273
RES_ADD_STRING(TXT_ENG_BROWSER_CHANGE_URL,"Browser Change URL")		//195273
RES_ADD_STRING(TXT_ENG_SCREEN_LOG,"Screen Log")
RES_ADD_STRING(TXT_ENG_UART, "UART")
RES_ADD_STRING(TXT_ENG_USB, "USB")
#endif

#ifdef MMI_AUTOTEST_SUPPORT
RES_ADD_STRING(TXT_ENG_AUTO_TEST_SET,"Auto test set")	
RES_ADD_STRING(TXT_ENG_AT_IMAGE_ID,"image id set")
RES_ADD_STRING(TXT_ENG_AT_TEXT,"text string set")
RES_ADD_STRING(TXT_ENG_AT_WIN_MSG,"window message set")
RES_ADD_STRING(TXT_ENG_AT_TP,"Tp set")
RES_ADD_STRING(TXT_ENG_AT_KEY,"key set")
RES_ADD_STRING(TXT_ENG_AT_MSG,"message set")
RES_ADD_STRING(TXT_ENG_AT_SOFTKEY,"softkey set")
RES_ADD_STRING(TXT_ENG_AT_TITLE,"title set")
RES_ADD_STRING(TXT_ENG_AT_POINTER_STATE,"pointer state set")
RES_ADD_STRING(TXT_ENG_AT_BACKLIGHT,"back light set")
#endif



//MS00202867 rick
#ifdef NANDBOOT_SUPPORT
RES_ADD_STRING(TXT_ENG_XSR_DEBUG, "Xsr Debug")
#endif
//MS00202867 rick


//RES_ADD_STRING(TXT_ENG_DEBUG_PORT_FAIL, "Debug port fail!")    //case3£ºdefined but not used
#ifdef NORMAL_TO_DEBUG_MODE
RES_ADD_STRING(TXT_ENG_USBLOG_ON, "Usb log on!")      //case3£ºdefined but not used /*Ankur*/
RES_ADD_STRING(TXT_ENG_USBLOG_OFF, "Usb log off!")
#endif
#ifdef PRINTSCREEN_SUPPORT
RES_ADD_STRING(TXT_ENG_PRINTSCREEN, "PrintScreen")
RES_ADD_STRING(TXT_ENG_PRINTSCREEN_OFF, "Off")
//renwei cr00114478 modify
#ifdef KEYPAD_TYPE_FOUR_KEY_UNIVERSE
RES_ADD_STRING(TXT_ENG_PRINTSCREEN_PRESS_CAMREA_ONLYLCD_MODE, "Press Camrea(Only lcd)")
RES_ADD_STRING(TXT_ENG_PRINTSCREEN_PRESS_CAMREA_LCDANDLAYER_MODE, "Press Camrea(Lcd and layer)")
#else
RES_ADD_STRING(TXT_ENG_PRINTSCREEN_PRESS_ONLYLCD_MODE, "Press Call(Only lcd)")
RES_ADD_STRING(TXT_ENG_PRINTSCREEN_PRESS_LCDANDLAYER_MODE, "Press Call(Lcd and layer)")
#endif
//renwei cr00114478 modify
RES_ADD_STRING(TXT_ENG_PRINTSCREEN_AUTO_MODE, "Auto")
#endif

#ifdef MMISRV_AUDIO_TEST_SUPPORT
RES_ADD_STRING(TXT_ENG_AUDIO_SELF_TEST, "Audio Self Test")
RES_ADD_STRING(TXT_ENG_AUDIO_PLAY, "Audio Play")
#ifdef PRINTSCREEN_SUPPORT
RES_ADD_STRING(TXT_ENG_AUDIO_DISPLAY_INFO, "Display Audio Info")
#endif
#endif
// WLAN
#ifdef WIFI_SUPPORT
RES_ADD_STRING(TXT_ENG_WLAN_SET, "WLAN")
RES_ADD_STRING(TXT_ENG_WLAN_POWER_SAVE, "power save")
RES_ADD_STRING(TXT_ENG_WLAN_ROAMING, "roaming")
RES_ADD_STRING(TXT_ENG_WLAN_PERFORMANCE_MODE, "performance mode")
RES_ADD_STRING(TXT_ENG_WLAN_RADIO_FREQUENCY, "Radio Frequency")
RES_ADD_STRING(TXT_ENG_WLAN_IPERF, "iperf")
RES_ADD_STRING(TXT_ENG_TEST_WIFI,  "WIFI test" )
#endif
//RES_ADD_STRING(TXT_ENG_AT_ALL_SET, "All settings") // @CR247145 renwei add

#ifdef TF_LOAD_SUPPORT
RES_ADD_STRING(TXT_ENG_TF_UPDATE,"TF update")
RES_ADD_STRING(TXT_ENG_TF_UPDATE_NOTIFICATION,"TF update notification")
RES_ADD_STRING(TXT_EN_TF_UPDATE_WARNING_1, "Low Battery")
RES_ADD_STRING(TXT_EN_TF_UPDATE_WARNING_2, "Not Allow Upgrading")
RES_ADD_STRING(TXT_EN_TF_UPDATE_WARNING_3, "No SD Card")
RES_ADD_STRING(TXT_EN_TF_UPDATE_WARNING_4, "No find update file")
RES_ADD_STRING(TXT_EN_TF_UPDATE_WARNING_5, "PAC not match")
RES_ADD_STRING(TXT_EN_TF_UPDATE_WARNING_6, "tfboot.bin not match")
RES_ADD_STRING(TXT_EN_TF_UPDATE_WARNING_7, "Failed to find tfboot.bin")
RES_ADD_STRING(TXT_DIAL_CHARGE_PHONE_UPD, "This update requires battery over 21%, need to charge your phone at first.")
#endif

#ifdef MMI_DUALMODE_ENABLE
RES_ADD_STRING(TXT_ENG_NETWORK_TYPE,"Network type")
#endif

#ifdef MOTION_SENSOR_TYPE
RES_ADD_STRING(TXT_ENG_NOT_SUPPORT_MOTIONSENSOR,"Can't Support Motion Sensor!")
RES_ADD_STRING(TXT_ENG_TEST_MOTIONSENSOR,"Motion sensor test" )
RES_ADD_STRING(TXT_ENG_MOTIONSENSOR_TITLE,"Motion Sensor")
#endif
RES_ADD_STRING(TXT_ENG_MONKEY_TEST_SET,"Monkey test set collection")
RES_ADD_STRING(TXT_ENG_SLIENT_ENVIRONMENT, "Silent mode")
RES_ADD_STRING(TXT_ENG_PB_FULL, "Phone book full filled")
RES_ADD_STRING(TXT_ENG_SMS_FULL, "SMS full filled, not implemented yet")
RES_ADD_STRING(TXT_ENG_KEY_LOCK_OFF, "Key lock off")
RES_ADD_STRING(TXT_ENG_DISABLE_FLYMODE_SETTINGS, "Disable flymode settings")
RES_ADD_STRING(TXT_ENG_TORCH_LED_TEST,"Torch led test")
RES_ADD_STRING(TXT_ENG_PVLCD_TEST,"LCD PV test")
RES_ADD_STRING(TXT_ENG_PVVIB_TEST,"Vibrator PV test")

RES_ADD_STRING(TXT_DTMF_SET_TIMER, "DTMF  TimerSet")

#ifdef ENG_SECONDEDAC_SUPPORT
RES_ADD_STRING(TXT_ENG_SECONDEDAC_ENABLE,"Second DAC")
#endif

#ifdef MMI_UNISOC_MANUALLY_CIT_SUPPORT
RES_ADD_STRING(TXT_ENG_RETEST,"Retest")
RES_ADD_STRING(TXT_ENG_VERSION_TEST,"Version test")
RES_ADD_STRING(TXT_ENG_LCD_TEST,"Lcd test")
RES_ADD_STRING(TXT_ENG_VIBRATE_TEST,"Vibrate test")
RES_ADD_STRING(TXT_ENG_RTC_TEST, "Rtc test")
RES_ADD_STRING(TXT_ENG_SPEAKER_TEST,"Speaker test")
RES_ADD_STRING(TXT_ENG_RECEIVER_TEST,"Receiver test")
RES_ADD_STRING(TXT_ENG_KEYPAD_LED_TEST,"Keypad led test")
RES_ADD_STRING(TXT_ENG_MIC_RECEIVER_TEST,"Mic-Receiver test")
RES_ADD_STRING(TXT_ENG_MIC_SPEAKER_TEST,"Mic-Speaker test")
RES_ADD_STRING(TXT_ENG_HEADSET_TEST,"Headset test")
RES_ADD_STRING(TXT_ENG_KEY_TEST,"Key test")
RES_ADD_STRING(TXT_ENG_MIC_HEADSET_TEST,"Mic-Headset test")
RES_ADD_STRING(TXT_ENG_TFLASH_TEST,"T-Flash test")
RES_ADD_STRING(TXT_ENG_SIM_TEST,"SIM test")
RES_ADD_STRING(TXT_ENG_CHARGING_TEST,"Charging test")
RES_ADD_STRING(TXT_ENG_CAMERA_TEST,"Camera test")
RES_ADD_STRING(TXT_ENG_CAMERA_CAPTURE_TEST,"Camera capture test")
RES_ADD_STRING(TXT_ENG_TORCHLED_TEST,"Torch-led test")
RES_ADD_STRING(TXT_ENG_BT_TEST,"BT test")
RES_ADD_STRING(TXT_ENG_FM_TEST,"FM test")
//RES_ADD_STRING(TXT_ENG_CAMERA_CAPTURE,"Capture")
RES_ADD_STRING(TXT_ENG_CAMERA_CAPTURE,"Take")
RES_ADD_STRING(TXT_ENG_SLPASS_SRFAIL,"Please press left key when pass.\nPress right key when failed.")
RES_ADD_STRING(TXT_ENG_TORCHNOTE,"up --- open torch led.\ndown --- close torch led.")
RES_ADD_STRING(TXT_ENG_SPKPLUGOUTHEADSET,"Please plug out headset!")
RES_ADD_STRING(TXT_PASS,"Pass")
RES_ADD_STRING(TXT_ENG_HEADSETIN,"Headset in")
RES_ADD_STRING(TXT_ENG_HEADSETOUT,"Headset out")
RES_ADD_STRING(TXT_ENG_SDIN,"Have SD Card")
RES_ADD_STRING(TXT_ENG_SDOUT,"No SD Card")
RES_ADD_STRING(TXT_ENG_SIMIN,"Have SIM Card")
RES_ADD_STRING(TXT_ENG_SIMOUT,"No SIM Card")
RES_ADD_STRING(TXT_ENG_PLUGIN,"Charging plug in")
RES_ADD_STRING(TXT_ENG_PLUGOUT,"Charging plug out")
RES_ADD_STRING(TXT_ENG_BTFLYMODE,"Fly Mode On, Fail key to next step!")
RES_ADD_STRING(TXT_ENG_BT_HAS_OPEN,"Bluetooth has open!")
RES_ADD_STRING(TXT_ENG_BTSEARCH,"Bluetooth search ...")
RES_ADD_STRING(TXT_ENG_BTSEARCH_FAIL,"Bluetooth search fail")
RES_ADD_STRING(TXT_ENG_BTOPEN_WAIT,"Open bluetooth, waiting ...")
RES_ADD_STRING(TXT_ENG_BTOPEN_FAIL,"Open bluetooth fail")
RES_ADD_STRING(TXT_ENG_BT_OPEN_FAIL,"Bluetooth open fail")
RES_ADD_STRING(TXT_ENG_BTSEARCH_TIMEOUT,"Bluetooth search timeout")
RES_ADD_STRING(TXT_ENG_FM_FLYMODEON,"Fly Mode On !")
RES_ADD_STRING(TXT_ENG_FM_HEADSETIN,"Headset is in")
RES_ADD_STRING(TXT_ENG_FM_INSERT_HEADSET,"Insert Headset!")
RES_ADD_STRING(TXT_ENG_BT_IS_OPEN,"Bluetooth is open!")
RES_ADD_STRING(TXT_ENG_PASS_FAIL_RETEST,"Pass to next,fail to exit,or retest!")
RES_ADD_STRING(TXT_ENG_BTFAIL,"Bluetooth is open!")
RES_ADD_STRING(TXT_ENG_RESET,"Restore factory settings and delete all user data and settings...")
RES_ADD_STRING(TXT_ENG_MENU_RESET,"Reset factory settings")
#endif
#ifdef Z695_KEYLOCK_INT_SUPPORT
RES_ADD_STRING(TXT_ENG_KEYLOCK_TEST, "Keylock")
#endif
RES_ADD_STRING(TXT_ENG_PB_DEBUG_MENU, "PB debug menu")

RES_ADD_STRING(TXT_ENG_SIM_PRESS_INFO,"SIM Press Test")
RES_ADD_STRING(TXT_ENG_IMS_NV_PARAM_ID,"IMS NV PARAM ID")//[MS]
RES_ADD_STRING(TXT_ENG_IMS_NV_PARAM_MES,"Update Or Read")//[MS]
RES_ADD_STRING(TXT_ENG_IMS_NV_ID,"Please input ID:")//[MS]
RES_ADD_STRING(TXT_ENG_IMS_NV_VALUE,"Please input Value:")//[MS]
RES_ADD_STRING(TXT_ENG_UPLMN_CAHNGE_ID,"UPLMN")//[MS]

RES_ADD_STRING(TXT_ENG_FATHER,"father")
RES_ADD_STRING(TXT_ENG_MOTHER,"mother")
RES_ADD_STRING(TXT_ENG_GRANDPA,"grandpa")
RES_ADD_STRING(TXT_ENG_GRANDMA,"gradma")
RES_ADD_STRING(TXT_ENG_TEACHER,"teacher")
RES_ADD_STRING(TXT_ENG_CLASSMATE,"classmate")

RES_ADD_STRING(TXT_ENG_IMAGE1,"image1")
RES_ADD_STRING(TXT_ENG_IMAGE2,"image2")
RES_ADD_STRING(TXT_ENG_IMAGE3,"image3")
RES_ADD_STRING(TXT_ENG_IMAGE4,"image4")
RES_ADD_STRING(TXT_ENG_IMAGE5,"image5")
RES_ADD_STRING(TXT_ENG_IMAGE6,"image6")


RES_ADD_STRING(TXT_ENG_ADD_CONTACT,"Add Contact")
RES_ADD_STRING(TXT_ENG_CONTACT_EXIST,"Name exist")

RES_ADD_STRING(TXT_ENG_MP3_PLAY_TEST,"MP3 PLAY Test")

RES_ADD_STRING(TXT_ENG_AGINGTEST,"Aging")//[MS]
RES_ADD_STRING(TXT_ENG_SIM_NETWORK_TEST,"network test")
RES_ADD_STRING(TXT_ENG_SIM_NETWORK_INSERT_SIM,"network insert sim")

//]]define string infomation


//[[define data infomation
//]]define data infomation
