/*****************************************************************************
** File Name:      mmidisplay_data.h                                         *
** Author:                                                                   *
** Date:           23/06/2004                                                *
** Copyright:      2003 Spreadtrum, Incoporated. All Rights Reserved.        *
** Description:    This file is used to describe gui common data struct      *
******************************************************************************
**                         Important Edit History                            *
** --------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION                               *
** 06/2004        Edison.rao          Create                                 *
******************************************************************************/

#ifndef _MMIDISPLAY_DATA_H_
#define _MMIDISPLAY_DATA_H_

/**--------------------------------------------------------------------------*
 **                         Include Files                                    *
 **--------------------------------------------------------------------------*/
#include "guicommon.h"
#include "mmi_position.h"
#include "mmi_custom_define.h"
/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef __cplusplus
    extern   "C"
    {
#endif


/**--------------------------------------------------------------------------*
 **                         MACRO DEFINITION                                 *
 **--------------------------------------------------------------------------*/
#ifdef SUB_LCD_96_64
    #define MMI_SUBSCREEN_WIDTH             96
    #define MMI_SUBSCREEN_HEIGHT            64
#else
    #define MMI_SUBSCREEN_WIDTH             96
    #define MMI_SUBSCREEN_HEIGHT            96
#endif

// MAINLCD_SIZE_128X160
#if defined MAINLCD_SIZE_128X160
#ifdef GUIF_TITLE_PDASTYLE
#define MMI_TITLE_TEXT_MARGIN_PDA           5
#define MMI_TITLE_TEXT_FONT_PDA             SONG_FONT_12 //Title上文字的字体
#define MMI_TITLE_THEME_HEIGHT_PDA          25
#define MMI_TITLE_THEME_HEIGHT_H_PDA        25
#define MMI_TITLE_THEME_HEIGHT_ISTYLE_PDA          45
#define MMI_TITLE_THEME_HEIGHT_H_ISTYLE_PDA        45
#endif

#define MMI_STATUS_FONT_TYPE                SONG_FONT_18   
#define MMI_DCD_IDLE_TEXT_FONT              SONG_FONT_12
#define MMI_SET_TIME_FONT                   SONG_FONT_34
#define MMI_SET_DATE_FONT                   SONG_FONT_22

#define MMI_TAB_ITEM_TEXT_BOTTOM_SPACE      3

#define MMI_TAB_CARD_DEFAULT_WIDTH          24

#ifdef GUITAB_PDASTYLE_SUPPORT
#define MMI_TAB_DISP_MAX_ITEM_NUM           4
#define MMI_TAB_DISP_MAX_ITEM_NUM_H         4
#define MMI_TAB_DISP_MAX_ITEM_NUM_ISTYLE           5
#define MMI_TAB_ITEM_DEFAULT_HEIGHT         64
#define MMI_TAB_ITEM_DEFAULT_WIDTH          44
#define MMI_TAB_ITEM_DEFAULT_WIDTH_H        55
#define MMI_TAB_ITEM_DEFAULT_WIDTH_ISTYLE          35
#define MMI_TAB_PRG_HEIGHT				    4
#else
#define MMI_TAB_DISP_MAX_ITEM_NUM           4
#define MMI_TAB_DISP_MAX_ITEM_NUM_H         4
#define MMI_TAB_ITEM_DEFAULT_HEIGHT         22
#define MMI_TAB_ITEM_DEFAULT_WIDTH          32
#define MMI_TAB_ITEM_DEFAULT_WIDTH_H        43
#define MMI_TAB_PRG_HEIGHT				    4
#endif
        
#define MMI_DEFAULT_TEXT_FONT               MMI_DEFAULT_NORMAL_FONT
#define MMI_FULLSCREEN_SOFTKEY_TEXT_FONT    MMI_DEFAULT_NORMAL_FONT //全屏下SOFTKEY上文字的字体
#define MMI_FULLSCREEN_SOFTKEY_TEXT_SMALL_FONT  MMI_DEFAULT_NORMAL_FONT //SOFTKEY外文时的字体

#if defined  MMI_KEY_LOCK_EFFECT_TYPE2_SUPPORT || defined TOUCHPANEL_TYPE
#define MMI_FULLSCREEN_SCROLLKEY_TEXT_FONT  SONG_FONT_24
#endif
#ifdef GUIF_TITLE_PDASTYLE
#define MMI_TITLE_TEXT_FONT                 MMI_TITLE_TEXT_FONT_PDA //Title上文字的字体
#else
#define MMI_TITLE_TEXT_FONT                 MMI_DEFAULT_BIG_FONT //Title上文字的字体
#endif

//  soft key 文字距离水平和垂直方向的距离
#define MMI_SOFTKEY_TEXT_HOR_SPACE  2

#define MMI_NUMBER_EDIT_TOP_MARGIN    1
#define MMI_NUMBER_EDIT_HEIGHT    25
//password
#define MMI_PASSWORD_EDIT_LEFT      20
#define MMI_PASSWORD_EDIT_TOP       48
#define MMI_PASSWORD_EDIT_RIGHT     (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMI_PASSWORD_EDIT_LEFT)
#define MMI_PASSWORD_EDIT_BOTTOM    (MMI_PASSWORD_EDIT_TOP + 30)
#define MMI_PASSWORD_IMAGE_LEFT         MMI_TIME_IMAGE_LEFT
#define MMI_PASSWORD_IMAGE_TOP          MMI_TIME_IMAGE_TOP
#define MMI_PASSWORD_EDIT_TOP_MARGIN    8
#define MMI_PASSWORD_EDIT_TOP_MARGIN_H    1     //横屏时，输入法虚拟键盘打开edit调整后，高度不够，引起assert
#define MMI_PASSWORD_EDIT_HEIGHT    25

//time/date
#define MMI_TIME_EDIT_LEFT          5
#define MMI_TIME_EDIT_TOP           48
#define MMI_TIME_EDIT_RIGHT         (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMI_TIME_EDIT_LEFT)
#define MMI_TIME_EDIT_BOTTOM        (MMI_TIME_EDIT_TOP + 40)
#define MMI_TIME_IMAGE_LEFT         48
#define MMI_TIME_IMAGE_TOP          90
#define MMI_DATE_EDIT_LEFT          MMI_TIME_EDIT_LEFT//176*220的DATE控件需要调整坐标
#define MMI_DATE_EDIT_TOP           MMI_TIME_EDIT_TOP
#define MMI_DATE_EDIT_RIGHT         MMI_TIME_EDIT_RIGHT
#define MMI_DATE_EDIT_BOTTOM        MMI_TIME_EDIT_BOTTOM

//fixed by hongjun.jia for bugzilla 2461-2464
#define MMI_TITLE_TEXT_L_MARGIN	            10//35

//title
#define MMI_TITLE_ARROW_MARGIN	        3
#define MMI_TITLE_ARROW_RECT_WIDTH      20 
#define MMI_TITLE_ISTYLE_MENU_ICON_MARGIN	 3

#define MMI_TITLE_LEFT_ARROW_WIDTH      20
#define MMI_TITLE_LEFT_ARROW_HEIGHT     18
#define MMI_TITLE_RIGHT_ARROW_WIDTH     20
#define MMI_TITLE_RIGHT_ARROW_HEIGHT    18

#define MMI_TITLE_LEFT_ARROW_LEFT       3
#define MMI_TITLE_LEFT_ARROW_TOP        1
#define MMI_TITLE_LEFT_ARROW_RIGHT          ( MMI_TITLE_LEFT_ARROW_LEFT + MMI_TITLE_LEFT_ARROW_WIDTH - 1)
#define MMI_TITLE_LEFT_ARROW_BOTTOM      (MMI_TITLE_LEFT_ARROW_TOP+MMI_TITLE_LEFT_ARROW_HEIGHT-1)

#define MMI_TITLE_RIGHT_ARROW_LEFT		(MMI_MAINSCREEN_WIDTH - MMI_TITLE_LEFT_ARROW_LEFT -MMI_TITLE_RIGHT_ARROW_WIDTH)
#define MMI_TITLE_RIGHT_ARROW_TOP       MMI_TITLE_LEFT_ARROW_TOP
#define MMI_TITLE_RIGHT_ARROW_RIGHT          ( MMI_TITLE_RIGHT_ARROW_LEFT + MMI_TITLE_RIGHT_ARROW_WIDTH - 1)
#define MMI_TITLE_RIGHT_ARROW_BOTTOM      (MMI_TITLE_RIGHT_ARROW_TOP+MMI_TITLE_RIGHT_ARROW_HEIGHT-1)

// tips position info
#define MMITIPS_RECT_MIN_HEIGHT                22   // 默认高度
#define MMITIPS_RECT_MAX_WIDTH                 155  // 默认宽度

//pubwin font info
#define MMI_PUBWIN_EXTRA_BIG_FONT          SONG_FONT_24//boda
#define MMI_PUBWIN_BIG_FONT          SONG_FONT_14
#define MMI_PUBWIN_NORMAL_FONT       SONG_FONT_12
#define MMI_PUBWIN_SMALL_FONT        SONG_FONT_11
#ifdef MMI_RES_ORIENT_PORTRAIT
#define MMI_COMMOM_IDLE_STK_TEXT_Y   121
#else
#define MMI_COMMOM_IDLE_STK_TEXT_Y   96
#endif
//////////////////////////////////////////////////////////////////////////
// MAINLCD_SIZE_176X220
#elif defined MAINLCD_SIZE_176X220
#ifdef GUIF_TITLE_PDASTYLE
#define MMI_TITLE_TEXT_MARGIN_PDA           5
#define MMI_TITLE_TEXT_FONT_PDA             SONG_FONT_16 //Title上文字的字体
#define MMI_TITLE_THEME_HEIGHT_PDA          25
#define MMI_TITLE_THEME_HEIGHT_H_PDA        25
#define MMI_TITLE_THEME_HEIGHT_ISTYLE_PDA          45
#define MMI_TITLE_THEME_HEIGHT_H_ISTYLE_PDA        45
#endif

#define MMI_STATUS_FONT_TYPE                SONG_FONT_18   
#define MMI_DCD_IDLE_TEXT_FONT              SONG_FONT_12
#define MMI_SET_TIME_FONT                   SONG_FONT_34
#define MMI_SET_DATE_FONT                   SONG_FONT_22

#define MMI_TAB_ITEM_TEXT_BOTTOM_SPACE      3

#define MMI_TAB_CARD_DEFAULT_WIDTH          24

#ifdef GUITAB_PDASTYLE_SUPPORT
#define MMI_TAB_DISP_MAX_ITEM_NUM           4
#define MMI_TAB_DISP_MAX_ITEM_NUM_H         4
#define MMI_TAB_DISP_MAX_ITEM_NUM_ISTYLE           5
#define MMI_TAB_ITEM_DEFAULT_HEIGHT         64
#define MMI_TAB_ITEM_DEFAULT_WIDTH          44
#define MMI_TAB_ITEM_DEFAULT_WIDTH_H        55
#define MMI_TAB_ITEM_DEFAULT_WIDTH_ISTYLE          35
#define MMI_TAB_PRG_HEIGHT				    4
#else
#define MMI_TAB_DISP_MAX_ITEM_NUM           4
#define MMI_TAB_DISP_MAX_ITEM_NUM_H         4
#define MMI_TAB_ITEM_DEFAULT_HEIGHT         30//22
#define MMI_TAB_ITEM_DEFAULT_WIDTH          32
#define MMI_TAB_ITEM_DEFAULT_WIDTH_H        43
#define MMI_TAB_PRG_HEIGHT				    4
#endif
        
#define MMI_DEFAULT_TEXT_FONT               MMI_DEFAULT_NORMAL_FONT
#define MMI_FULLSCREEN_SOFTKEY_TEXT_FONT    MMI_DEFAULT_BIG_FONT //全屏下SOFTKEY上文字的字体
#define MMI_FULLSCREEN_SOFTKEY_TEXT_SMALL_FONT  MMI_DEFAULT_NORMAL_FONT //SOFTKEY外文时的字体

#if defined(MMI_KEY_LOCK_EFFECT_TYPE2_SUPPORT) ||defined(GUIF_SCROLLKEY)
#define MMI_FULLSCREEN_SCROLLKEY_TEXT_FONT  SONG_FONT_24
#endif
#ifdef GUIF_TITLE_PDASTYLE
#define MMI_TITLE_TEXT_FONT                 MMI_TITLE_TEXT_FONT_PDA //Title上文字的字体
#else
#define MMI_TITLE_TEXT_FONT                 MMI_DEFAULT_BIG_FONT //Title上文字的字体
#endif

//  soft key 文字距离水平和垂直方向的距离
#define MMI_SOFTKEY_TEXT_HOR_SPACE  2

#define MMI_NUMBER_EDIT_TOP_MARGIN    4
#define MMI_NUMBER_EDIT_HEIGHT    25
//password
#define MMI_PASSWORD_EDIT_LEFT      20
#define MMI_PASSWORD_EDIT_TOP       48
#define MMI_PASSWORD_EDIT_RIGHT     (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMI_PASSWORD_EDIT_LEFT)
#define MMI_PASSWORD_EDIT_BOTTOM    (MMI_PASSWORD_EDIT_TOP + 30)
#define MMI_PASSWORD_IMAGE_LEFT         MMI_TIME_IMAGE_LEFT
#define MMI_PASSWORD_IMAGE_TOP          MMI_TIME_IMAGE_TOP
#define MMI_PASSWORD_EDIT_TOP_MARGIN    8
#define MMI_PASSWORD_EDIT_TOP_MARGIN_H    1     //横屏时，输入法虚拟键盘打开edit调整后，高度不够，引起assert
#define MMI_PASSWORD_EDIT_HEIGHT    25

//time/date
#define MMI_TIME_EDIT_LEFT          5
#define MMI_TIME_EDIT_TOP           48
#define MMI_TIME_EDIT_RIGHT         (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMI_TIME_EDIT_LEFT)
#define MMI_TIME_EDIT_BOTTOM        (MMI_TIME_EDIT_TOP + 40)
#define MMI_TIME_IMAGE_LEFT         48
#define MMI_TIME_IMAGE_TOP          90
#define MMI_DATE_EDIT_LEFT          MMI_TIME_EDIT_LEFT//176*220的DATE控件需要调整坐标
#define MMI_DATE_EDIT_TOP           MMI_TIME_EDIT_TOP
#define MMI_DATE_EDIT_RIGHT         MMI_TIME_EDIT_RIGHT
#define MMI_DATE_EDIT_BOTTOM        MMI_TIME_EDIT_BOTTOM

#define MMI_TITLE_TEXT_L_MARGIN	            10//35

//title
#define MMI_TITLE_ARROW_MARGIN	        3
#define MMI_TITLE_ARROW_RECT_WIDTH      20 
#define MMI_TITLE_ISTYLE_MENU_ICON_MARGIN	 3

#define MMI_TITLE_LEFT_ARROW_WIDTH      20
#define MMI_TITLE_LEFT_ARROW_HEIGHT     18
#define MMI_TITLE_RIGHT_ARROW_WIDTH     20
#define MMI_TITLE_RIGHT_ARROW_HEIGHT    18

#define MMI_TITLE_LEFT_ARROW_LEFT       3
#define MMI_TITLE_LEFT_ARROW_TOP        1
#define MMI_TITLE_LEFT_ARROW_RIGHT          ( MMI_TITLE_LEFT_ARROW_LEFT + MMI_TITLE_LEFT_ARROW_WIDTH - 1)
#define MMI_TITLE_LEFT_ARROW_BOTTOM      (MMI_TITLE_LEFT_ARROW_TOP+MMI_TITLE_LEFT_ARROW_HEIGHT-1)

#define MMI_TITLE_RIGHT_ARROW_LEFT		(MMI_MAINSCREEN_WIDTH - MMI_TITLE_LEFT_ARROW_LEFT -MMI_TITLE_RIGHT_ARROW_WIDTH)
#define MMI_TITLE_RIGHT_ARROW_TOP       MMI_TITLE_LEFT_ARROW_TOP
#define MMI_TITLE_RIGHT_ARROW_RIGHT          ( MMI_TITLE_RIGHT_ARROW_LEFT + MMI_TITLE_RIGHT_ARROW_WIDTH - 1)
#define MMI_TITLE_RIGHT_ARROW_BOTTOM      (MMI_TITLE_RIGHT_ARROW_TOP+MMI_TITLE_RIGHT_ARROW_HEIGHT-1)

// tips position info
#define MMITIPS_RECT_MIN_HEIGHT                22   // 默认高度
#define MMITIPS_RECT_MAX_WIDTH                 155  // 默认宽度

//pubwin font info
#define MMI_PUBWIN_BIG_FONT          SONG_FONT_16
#define MMI_PUBWIN_NORMAL_FONT       SONG_FONT_12
#define MMI_PUBWIN_SMALL_FONT        SONG_FONT_10
#ifdef MMI_RES_ORIENT_PORTRAIT
#define MMI_COMMOM_IDLE_STK_TEXT_Y   175
#else
#define MMI_COMMOM_IDLE_STK_TEXT_Y   145
#endif
#elif defined MAINLCD_SIZE_240X320
#ifdef GUIF_TITLE_PDASTYLE
#define MMI_TITLE_TEXT_MARGIN_PDA           5
#define MMI_TITLE_TEXT_FONT_PDA             SONG_FONT_16 //Title上文字的字体
#define MMI_TITLE_THEME_HEIGHT_PDA          32//20
#define MMI_TITLE_THEME_HEIGHT_H_PDA        32//20
#define MMI_TITLE_THEME_HEIGHT_ISTYLE_PDA          34
#define MMI_TITLE_THEME_HEIGHT_H_ISTYLE_PDA        34
#endif

#define MMI_STATUS_FONT_TYPE                SONG_FONT_12
#define MMI_DCD_IDLE_TEXT_FONT              SONG_FONT_14
#define MMI_SET_TIME_FONT                   SONG_FONT_50
#define MMI_SET_DATE_FONT                   SONG_FONT_36
        
#define MMI_TAB_ITEM_TEXT_BOTTOM_SPACE      7

#define MMI_TAB_CARD_DEFAULT_WIDTH          40

#ifdef GUITAB_PDASTYLE_SUPPORT
#define MMI_TAB_DISP_MAX_ITEM_NUM           4
#define MMI_TAB_DISP_MAX_ITEM_NUM_H         5
#define MMI_TAB_DISP_MAX_ITEM_NUM_ISTYLE           5
#define MMI_TAB_ITEM_DEFAULT_HEIGHT         44
#define MMI_TAB_ITEM_DEFAULT_WIDTH          60
#define MMI_TAB_ITEM_DEFAULT_WIDTH_H        64
#define MMI_TAB_ITEM_DEFAULT_WIDTH_ISTYLE          48
#define MMI_TAB_PRG_HEIGHT				    3
#else
#define MMI_TAB_DISP_MAX_ITEM_NUM           4
#define MMI_TAB_DISP_MAX_ITEM_NUM_H         5
#define MMI_TAB_ITEM_DEFAULT_HEIGHT         33
#define MMI_TAB_ITEM_DEFAULT_WIDTH          40
#define MMI_TAB_ITEM_DEFAULT_WIDTH_H        48
#define MMI_TAB_PRG_HEIGHT				    4
#endif

#define MMI_DEFAULT_TEXT_FONT               MMI_DEFAULT_BIG_FONT

#define MMI_FULLSCREEN_SOFTKEY_TEXT_FONT    MMI_DEFAULT_BIG_FONT //全屏下SOFTKEY上文字的字体
#define MMI_FULLSCREEN_SOFTKEY_TEXT_SMALL_FONT  MMI_DEFAULT_NORMAL_FONT //SOFTKEY外文时的字体

#if defined(MMI_KEY_LOCK_EFFECT_TYPE2_SUPPORT) ||defined(GUIF_SCROLLKEY)
#define MMI_FULLSCREEN_SCROLLKEY_TEXT_FONT  SONG_FONT_24
#endif
#ifdef GUIF_TITLE_PDASTYLE
#define MMI_TITLE_TEXT_FONT                 MMI_TITLE_TEXT_FONT_PDA //Title上文字的字体
#else
#define MMI_TITLE_TEXT_FONT                 MMI_DEFAULT_BIG_FONT //Title上文字的字体
#endif

//  soft key 文字距离水平和垂直方向的距离
#define MMI_SOFTKEY_TEXT_HOR_SPACE  2

#define MMI_NUMBER_EDIT_TOP_MARGIN    20
#define MMI_NUMBER_EDIT_HEIGHT    30
//password
#define MMI_PASSWORD_EDIT_LEFT      30
#define MMI_PASSWORD_EDIT_TOP       68
#define MMI_PASSWORD_EDIT_RIGHT     (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMI_PASSWORD_EDIT_LEFT)
#define MMI_PASSWORD_EDIT_BOTTOM    (MMI_PASSWORD_EDIT_TOP + 30)
#define MMI_PASSWORD_IMAGE_LEFT         MMI_TIME_IMAGE_LEFT
#define MMI_PASSWORD_IMAGE_TOP          MMI_TIME_IMAGE_TOP
#define MMI_PASSWORD_EDIT_TOP_MARGIN    20
#define MMI_PASSWORD_EDIT_TOP_MARGIN_H    20     
#define MMI_PASSWORD_EDIT_HEIGHT    30
#define MMI_EDITPWCTRL 62

//time/date
#define MMI_TIME_EDIT_LEFT          10
#define MMI_TIME_EDIT_TOP           68
#define MMI_TIME_EDIT_RIGHT         (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMI_TIME_EDIT_LEFT)
#define MMI_TIME_EDIT_BOTTOM        (MMI_TIME_EDIT_TOP + 55)
#define MMI_TIME_IMAGE_LEFT         73
#define MMI_TIME_IMAGE_TOP          160
#define MMI_DATE_EDIT_LEFT          MMI_TIME_EDIT_LEFT
#define MMI_DATE_EDIT_TOP           MMI_TIME_EDIT_TOP
#define MMI_DATE_EDIT_RIGHT         MMI_TIME_EDIT_RIGHT
#define MMI_DATE_EDIT_BOTTOM        MMI_TIME_EDIT_BOTTOM
//title左侧margin调整为10，配合居左显示以保证所有title都可完整显示，也比较美观
#define MMI_TITLE_TEXT_L_MARGIN	            6//45
//title
#define MMI_TITLE_ARROW_MARGIN	        3
#define MMI_TITLE_ARROW_RECT_WIDTH      24 
#define MMI_TITLE_ISTYLE_MENU_ICON_MARGIN	 3

#define MMI_TITLE_LEFT_ARROW_WIDTH      24 
#define MMI_TITLE_LEFT_ARROW_HEIGHT     22
#define MMI_TITLE_RIGHT_ARROW_WIDTH     24
#define MMI_TITLE_RIGHT_ARROW_HEIGHT    22

#define MMI_TITLE_LEFT_ARROW_LEFT       3
#define MMI_TITLE_LEFT_ARROW_TOP        3
#define MMI_TITLE_LEFT_ARROW_RIGHT      ( MMI_TITLE_LEFT_ARROW_LEFT + MMI_TITLE_LEFT_ARROW_WIDTH - 1)
#define MMI_TITLE_LEFT_ARROW_BOTTOM     (MMI_TITLE_LEFT_ARROW_TOP+MMI_TITLE_LEFT_ARROW_HEIGHT-1)

#define MMI_TITLE_RIGHT_ARROW_LEFT		(MMI_MAINSCREEN_WIDTH - MMI_TITLE_LEFT_ARROW_LEFT -MMI_TITLE_RIGHT_ARROW_WIDTH)
#define MMI_TITLE_RIGHT_ARROW_TOP       MMI_TITLE_LEFT_ARROW_TOP
#define MMI_TITLE_RIGHT_ARROW_RIGHT     ( MMI_TITLE_RIGHT_ARROW_LEFT + MMI_TITLE_RIGHT_ARROW_WIDTH - 1)
#define MMI_TITLE_RIGHT_ARROW_BOTTOM    (MMI_TITLE_RIGHT_ARROW_TOP+MMI_TITLE_RIGHT_ARROW_HEIGHT-1)

// tips position info
#define MMITIPS_RECT_MIN_HEIGHT                22   // 默认高度
#define MMITIPS_RECT_MAX_WIDTH                 218  // 默认宽度

//pubwin font info
#define MMI_PUBWIN_EXTRA_BIG_FONT          SONG_FONT_24
#define MMI_PUBWIN_BIG_FONT          SONG_FONT_20
#define MMI_PUBWIN_NORMAL_FONT       SONG_FONT_16
#define MMI_PUBWIN_SMALL_FONT        SONG_FONT_14
#elif defined MAINLCD_SIZE_128X64
#ifdef GUIF_TITLE_PDASTYLE
#define MMI_TITLE_TEXT_MARGIN_PDA           5
#define MMI_TITLE_TEXT_FONT_PDA             SONG_FONT_16 //Title上文字的字体
#define MMI_TITLE_THEME_HEIGHT_PDA          25
#define MMI_TITLE_THEME_HEIGHT_H_PDA        25
#define MMI_TITLE_THEME_HEIGHT_ISTYLE_PDA          45
#define MMI_TITLE_THEME_HEIGHT_H_ISTYLE_PDA        45
#endif

#define MMI_STATUS_FONT_TYPE                SONG_FONT_14   
#define MMI_DCD_IDLE_TEXT_FONT              SONG_FONT_14
#define MMI_SET_TIME_FONT                   SONG_FONT_14
#define MMI_SET_DATE_FONT                   SONG_FONT_14

//add for fix compile error: MS00215025        
#define MMI_TAB_ITEM_TEXT_BOTTOM_SPACE      7

#define MMI_TAB_CARD_DEFAULT_WIDTH          12

#ifdef GUITAB_PDASTYLE_SUPPORT
#define MMI_TAB_DISP_MAX_ITEM_NUM           4
#define MMI_TAB_DISP_MAX_ITEM_NUM_H         4
#define MMI_TAB_DISP_MAX_ITEM_NUM_ISTYLE           5
#define MMI_TAB_ITEM_DEFAULT_HEIGHT         64
#define MMI_TAB_ITEM_DEFAULT_WIDTH          80
#define MMI_TAB_ITEM_DEFAULT_WIDTH_H        30
#define MMI_TAB_ITEM_DEFAULT_WIDTH_ISTYLE          25
#define MMI_TAB_PRG_HEIGHT				    4
#else
#define MMI_TAB_DISP_MAX_ITEM_NUM           4
#define MMI_TAB_DISP_MAX_ITEM_NUM_H         4
#define MMI_TAB_ITEM_DEFAULT_HEIGHT         16
#define MMI_TAB_ITEM_DEFAULT_WIDTH          30
#define MMI_TAB_ITEM_DEFAULT_WIDTH_H        30
#define MMI_TAB_PRG_HEIGHT				    4
#endif

#define MMI_DEFAULT_TEXT_FONT               MMI_DEFAULT_BIG_FONT
#define MMI_FULLSCREEN_SOFTKEY_TEXT_FONT    MMI_DEFAULT_BIG_FONT //全屏下SOFTKEY上文字的字体
#define MMI_FULLSCREEN_SOFTKEY_TEXT_SMALL_FONT  MMI_DEFAULT_NORMAL_FONT //SOFTKEY外文时的字体

#if defined(MMI_KEY_LOCK_EFFECT_TYPE2_SUPPORT) ||defined(GUIF_SCROLLKEY)
#define MMI_FULLSCREEN_SCROLLKEY_TEXT_FONT  SONG_FONT_24
#endif
#ifdef GUIF_TITLE_PDASTYLE
#define MMI_TITLE_TEXT_FONT                 MMI_TITLE_TEXT_FONT_PDA //Title上文字的字体
#else
#define MMI_TITLE_TEXT_FONT                 MMI_DEFAULT_BIG_FONT //Title上文字的字体
#endif

//  soft key 文字距离水平和垂直方向的距离
#define MMI_SOFTKEY_TEXT_HOR_SPACE  2

//number
#define MMI_NUMBER_EDIT_LEFT          0
#define MMI_NUMBER_EDIT_TOP           0
#define MMI_NUMBER_EDIT_RIGHT         (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMI_NUMBER_EDIT_LEFT)
#define MMI_NUMBER_EDIT_BOTTOM        (MMI_NUMBER_EDIT_LEFT + 47)

#define MMI_NUMBER_IMAGE_LEFT         MMI_TIME_IMAGE_LEFT
#define MMI_NUMBER_IMAGE_TOP          MMI_TIME_IMAGE_TOP
#define MMI_NUMBER_EDIT_TOP_MARGIN    20
#define MMI_NUMBER_EDIT_HEIGHT    30

#define MMI_PASSWORD_EDIT_LEFT     0
#define MMI_PASSWORD_EDIT_TOP       0
#define MMI_PASSWORD_EDIT_RIGHT     (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMI_PASSWORD_EDIT_LEFT)
#define MMI_PASSWORD_EDIT_BOTTOM    (MMI_PASSWORD_EDIT_TOP + 47)


//password
#define MMI_PASSWORD_IMAGE_LEFT         MMI_TIME_IMAGE_LEFT
#define MMI_PASSWORD_IMAGE_TOP          MMI_TIME_IMAGE_TOP
#define MMI_PASSWORD_EDIT_TOP_MARGIN    20
#define MMI_PASSWORD_EDIT_TOP_MARGIN_H    20     
#define MMI_PASSWORD_EDIT_HEIGHT    30

//time/date
#define MMI_TIME_EDIT_LEFT           0
#define MMI_TIME_EDIT_TOP             0
#define MMI_TIME_EDIT_RIGHT         (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMI_TIME_EDIT_LEFT)
#define MMI_TIME_EDIT_BOTTOM        (MMI_TIME_EDIT_TOP+ 47)
#define MMI_TIME_IMAGE_LEFT         0
#define MMI_TIME_IMAGE_TOP          0
#define MMI_DATE_EDIT_LEFT          0
#define MMI_DATE_EDIT_TOP           0
#define MMI_DATE_EDIT_RIGHT         MMI_TIME_EDIT_RIGHT
#define MMI_DATE_EDIT_BOTTOM        MMI_TIME_EDIT_BOTTOM

//由45改为35是为了扩大Title文本显示区域。
#define MMI_TITLE_TEXT_L_MARGIN	             35//20//45
//title
#define MMI_TITLE_ARROW_MARGIN	        3
#define MMI_TITLE_ARROW_RECT_WIDTH      24 
#define MMI_TITLE_ISTYLE_MENU_ICON_MARGIN	 3

#define MMI_TITLE_LEFT_ARROW_WIDTH      24 
#define MMI_TITLE_LEFT_ARROW_HEIGHT     22
#define MMI_TITLE_RIGHT_ARROW_WIDTH     24
#define MMI_TITLE_RIGHT_ARROW_HEIGHT    22

#define MMI_TITLE_LEFT_ARROW_LEFT       3
#define MMI_TITLE_LEFT_ARROW_TOP        3
#define MMI_TITLE_LEFT_ARROW_RIGHT      ( MMI_TITLE_LEFT_ARROW_LEFT + MMI_TITLE_LEFT_ARROW_WIDTH - 1)
#define MMI_TITLE_LEFT_ARROW_BOTTOM     (MMI_TITLE_LEFT_ARROW_TOP+MMI_TITLE_LEFT_ARROW_HEIGHT-1)

#define MMI_TITLE_RIGHT_ARROW_LEFT		(MMI_MAINSCREEN_WIDTH - MMI_TITLE_LEFT_ARROW_LEFT -MMI_TITLE_RIGHT_ARROW_WIDTH)
#define MMI_TITLE_RIGHT_ARROW_TOP       MMI_TITLE_LEFT_ARROW_TOP
#define MMI_TITLE_RIGHT_ARROW_RIGHT     ( MMI_TITLE_RIGHT_ARROW_LEFT + MMI_TITLE_RIGHT_ARROW_WIDTH - 1)
#define MMI_TITLE_RIGHT_ARROW_BOTTOM    (MMI_TITLE_RIGHT_ARROW_TOP+MMI_TITLE_RIGHT_ARROW_HEIGHT-1)

// tips position info
// tips position info
#define MMITIPS_RECT_MIN_HEIGHT                16   // 默认高度
#define MMITIPS_RECT_MAX_WIDTH                 127  // 默认宽度

//pubwin font info
#define MMI_PUBWIN_BIG_FONT          SONG_FONT_12
#define MMI_PUBWIN_NORMAL_FONT       SONG_FONT_10
#define MMI_PUBWIN_SMALL_FONT        SONG_FONT_10
#define MMI_CLIENT_RECT                     {0, MMI_TITLE_HEIGHT, MMI_MAINSCREEN_RIGHT_MAX_PIXEL,\
                                                MMI_MAINSCREEN_BOTTOM_MAX_PIXEL - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT}

#elif  defined MAINLCD_SIZE_240X400
#ifdef GUIF_TITLE_PDASTYLE
#define MMI_TITLE_TEXT_MARGIN_PDA           5
#define MMI_TITLE_TEXT_FONT_PDA             SONG_FONT_16 //Title上文字的字体
#define MMI_TITLE_THEME_HEIGHT_PDA          32//20
#define MMI_TITLE_THEME_HEIGHT_H_PDA        32//20
#define MMI_TITLE_THEME_HEIGHT_ISTYLE_PDA          45
#define MMI_TITLE_THEME_HEIGHT_H_ISTYLE_PDA        45
#endif

#define MMI_STATUS_FONT_TYPE                SONG_FONT_16
#define MMI_DCD_IDLE_TEXT_FONT              SONG_FONT_14
#define MMI_SET_TIME_FONT                   SONG_FONT_50
#define MMI_SET_DATE_FONT                   SONG_FONT_36

#define MMI_TAB_ITEM_TEXT_BOTTOM_SPACE      8

#define MMI_TAB_CARD_DEFAULT_WIDTH          12

#ifdef GUITAB_PDASTYLE_SUPPORT
#define MMI_TAB_DISP_MAX_ITEM_NUM           4
#define MMI_TAB_DISP_MAX_ITEM_NUM_H         5
#define MMI_TAB_DISP_MAX_ITEM_NUM_ISTYLE           5
#define MMI_TAB_ITEM_DEFAULT_HEIGHT         44
#define MMI_TAB_ITEM_DEFAULT_WIDTH          60
#define MMI_TAB_ITEM_DEFAULT_WIDTH_H        64
#define MMI_TAB_ITEM_DEFAULT_WIDTH_ISTYLE          48
#define MMI_TAB_PRG_HEIGHT				    3
#else
#define MMI_TAB_DISP_MAX_ITEM_NUM           4
#define MMI_TAB_DISP_MAX_ITEM_NUM_H         5
#define MMI_TAB_ITEM_DEFAULT_HEIGHT         33
#define MMI_TAB_ITEM_DEFAULT_WIDTH          40
#define MMI_TAB_ITEM_DEFAULT_WIDTH_H        64
#define MMI_TAB_PRG_HEIGHT				    4
#endif
   
#define MMI_DEFAULT_TEXT_FONT               MMI_DEFAULT_BIG_FONT
#define MMI_FULLSCREEN_SOFTKEY_TEXT_FONT    MMI_DEFAULT_BIG_FONT //全屏下SOFTKEY上文字的字体
#define MMI_FULLSCREEN_SOFTKEY_TEXT_SMALL_FONT  MMI_DEFAULT_NORMAL_FONT //SOFTKEY外文时的字体

#if defined(MMI_KEY_LOCK_EFFECT_TYPE2_SUPPORT) ||defined(GUIF_SCROLLKEY)
#define MMI_FULLSCREEN_SCROLLKEY_TEXT_FONT  SONG_FONT_24
#endif
#ifdef GUIF_TITLE_PDASTYLE
#define MMI_TITLE_TEXT_FONT                 MMI_TITLE_TEXT_FONT_PDA //Title上文字的字体
#else
#define MMI_TITLE_TEXT_FONT                 MMI_DEFAULT_BIG_FONT //Title上文字的字体
#endif

//  soft key 文字距离水平和垂直方向的距离
#define MMI_SOFTKEY_TEXT_HOR_SPACE  2

#define MMI_NUMBER_EDIT_TOP_MARGIN    20
#define MMI_NUMBER_EDIT_HEIGHT    30
//password
#define MMI_PASSWORD_EDIT_LEFT      30
#define MMI_PASSWORD_EDIT_TOP       88
#define MMI_PASSWORD_EDIT_RIGHT     (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMI_PASSWORD_EDIT_LEFT)
#define MMI_PASSWORD_EDIT_BOTTOM    (MMI_PASSWORD_EDIT_TOP + 30)
#define MMI_PASSWORD_IMAGE_LEFT         MMI_TIME_IMAGE_LEFT
#define MMI_PASSWORD_IMAGE_TOP          MMI_TIME_IMAGE_TOP
#define MMI_PASSWORD_EDIT_TOP_MARGIN    20
#define MMI_PASSWORD_EDIT_TOP_MARGIN_H    20     
#define MMI_PASSWORD_EDIT_HEIGHT    30

//time/date
#define MMI_TIME_EDIT_LEFT          10
#define MMI_TIME_EDIT_TOP           68
#define MMI_TIME_EDIT_RIGHT         (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMI_TIME_EDIT_LEFT)
#define MMI_TIME_EDIT_BOTTOM        (MMI_TIME_EDIT_TOP + 55)
#define MMI_TIME_IMAGE_LEFT         73
#define MMI_TIME_IMAGE_TOP          160
#define MMI_DATE_EDIT_LEFT          MMI_TIME_EDIT_LEFT
#define MMI_DATE_EDIT_TOP           MMI_TIME_EDIT_TOP
#define MMI_DATE_EDIT_RIGHT         MMI_TIME_EDIT_RIGHT
#define MMI_DATE_EDIT_BOTTOM        MMI_TIME_EDIT_BOTTOM

#define MMI_TITLE_TEXT_L_MARGIN	            45 

//title
#define MMI_TITLE_ARROW_MARGIN	        3
#define MMI_TITLE_ARROW_RECT_WIDTH      24 
#define MMI_TITLE_ISTYLE_MENU_ICON_MARGIN	  3

#define MMI_TITLE_LEFT_ARROW_WIDTH      24
#define MMI_TITLE_LEFT_ARROW_HEIGHT     22
#define MMI_TITLE_RIGHT_ARROW_WIDTH     24
#define MMI_TITLE_RIGHT_ARROW_HEIGHT    22

#define MMI_TITLE_LEFT_ARROW_LEFT       3
#define MMI_TITLE_LEFT_ARROW_TOP        3
#define MMI_TITLE_LEFT_ARROW_RIGHT      ( MMI_TITLE_LEFT_ARROW_LEFT + MMI_TITLE_LEFT_ARROW_WIDTH - 1)
#define MMI_TITLE_LEFT_ARROW_BOTTOM     (MMI_TITLE_LEFT_ARROW_TOP+MMI_TITLE_LEFT_ARROW_HEIGHT-1)

#define MMI_TITLE_RIGHT_ARROW_LEFT		(MMI_MAINSCREEN_WIDTH - MMI_TITLE_LEFT_ARROW_LEFT -MMI_TITLE_RIGHT_ARROW_WIDTH)
#define MMI_TITLE_RIGHT_ARROW_TOP       MMI_TITLE_LEFT_ARROW_TOP
#define MMI_TITLE_RIGHT_ARROW_RIGHT     ( MMI_TITLE_RIGHT_ARROW_LEFT + MMI_TITLE_RIGHT_ARROW_WIDTH - 1)
#define MMI_TITLE_RIGHT_ARROW_BOTTOM    (MMI_TITLE_RIGHT_ARROW_TOP+MMI_TITLE_RIGHT_ARROW_HEIGHT-1)

// tips position info
#define MMITIPS_RECT_MIN_HEIGHT                22   // 默认高度
#define MMITIPS_RECT_MAX_WIDTH                 218  // 默认宽度 

//pubwin font info
#define MMI_PUBWIN_BIG_FONT          SONG_FONT_20
#define MMI_PUBWIN_NORMAL_FONT       SONG_FONT_18
#define MMI_PUBWIN_SMALL_FONT        SONG_FONT_16
#elif  defined MAINLCD_SIZE_320X480
#ifdef GUIF_TITLE_PDASTYLE
#define MMI_TITLE_TEXT_MARGIN_PDA           5
#define MMI_TITLE_TEXT_FONT_PDA             SONG_FONT_16 //Title上文字的字体
#define MMI_TITLE_THEME_HEIGHT_PDA          40//32//25
#define MMI_TITLE_THEME_HEIGHT_H_PDA        40//32//25
#define MMI_TITLE_THEME_HEIGHT_ISTYLE_PDA          45
#define MMI_TITLE_THEME_HEIGHT_H_ISTYLE_PDA        45
#endif

#define MMI_STATUS_FONT_TYPE                SONG_FONT_16
#define MMI_DCD_IDLE_TEXT_FONT              SONG_FONT_14
#define MMI_SET_TIME_FONT                   SONG_FONT_50
#define MMI_SET_DATE_FONT                   SONG_FONT_36

#define MMI_TAB_ITEM_TEXT_BOTTOM_SPACE      7
#define MMI_TAB_CARD_DEFAULT_WIDTH          40

#ifdef GUITAB_PDASTYLE_SUPPORT
#define MMI_TAB_DISP_MAX_ITEM_NUM           4
#define MMI_TAB_DISP_MAX_ITEM_NUM_H         6
#define MMI_TAB_DISP_MAX_ITEM_NUM_ISTYLE           5
#define MMI_TAB_ITEM_DEFAULT_HEIGHT         64
#define MMI_TAB_ITEM_DEFAULT_WIDTH          64
#define MMI_TAB_ITEM_DEFAULT_WIDTH_H        80
#define MMI_TAB_ITEM_DEFAULT_WIDTH_ISTYLE   64
#define MMI_TAB_PRG_HEIGHT				    4
#else
#define MMI_TAB_DISP_MAX_ITEM_NUM           4
#define MMI_TAB_DISP_MAX_ITEM_NUM_H         5
#define MMI_TAB_ITEM_DEFAULT_HEIGHT         30
#define MMI_TAB_ITEM_DEFAULT_WIDTH          60
#define MMI_TAB_ITEM_DEFAULT_WIDTH_H        80
#define MMI_TAB_PRG_HEIGHT				    4
#endif
        
#define MMI_DEFAULT_TEXT_FONT               MMI_DEFAULT_BIG_FONT
#define MMI_FULLSCREEN_SOFTKEY_TEXT_FONT    MMI_DEFAULT_BIG_FONT //全屏下SOFTKEY上文字的字体
#define MMI_FULLSCREEN_SOFTKEY_TEXT_SMALL_FONT  MMI_DEFAULT_NORMAL_FONT //SOFTKEY外文时的字体

#if defined(MMI_KEY_LOCK_EFFECT_TYPE2_SUPPORT) ||defined(GUIF_SCROLLKEY)
#define MMI_FULLSCREEN_SCROLLKEY_TEXT_FONT  SONG_FONT_24
#endif
#ifdef GUIF_TITLE_PDASTYLE
#define MMI_TITLE_TEXT_FONT                 MMI_TITLE_TEXT_FONT_PDA //Title上文字的字体
#else
#define MMI_TITLE_TEXT_FONT                 MMI_DEFAULT_BIG_FONT //Title上文字的字体
#endif

//  soft key 文字距离水平和垂直方向的距离
#define MMI_SOFTKEY_TEXT_HOR_SPACE  10

#define MMI_NUMBER_EDIT_TOP_MARGIN    20
#define MMI_NUMBER_EDIT_HEIGHT    30
//password
#define MMI_PASSWORD_EDIT_LEFT      35
#define MMI_PASSWORD_EDIT_TOP       290
#define MMI_PASSWORD_EDIT_RIGHT     (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMI_PASSWORD_EDIT_LEFT)
#define MMI_PASSWORD_EDIT_BOTTOM    (MMI_PASSWORD_EDIT_TOP + 30)
#define MMI_PASSWORD_IMAGE_LEFT         122
#define MMI_PASSWORD_IMAGE_TOP          126
#define MMI_PASSWORD_EDIT_TOP_MARGIN    20
#define MMI_PASSWORD_EDIT_TOP_MARGIN_H    20     
#define MMI_PASSWORD_EDIT_HEIGHT    30

//time/date
#define MMI_TIME_EDIT_LEFT          10
#define MMI_TIME_EDIT_TOP           68
#define MMI_TIME_EDIT_RIGHT         (MMI_MAINSCREEN_RIGHT_MAX_PIXEL - MMI_TIME_EDIT_LEFT)
#define MMI_TIME_EDIT_BOTTOM        (MMI_TIME_EDIT_TOP + 60)
#define MMI_TIME_IMAGE_LEFT         112
#define MMI_TIME_IMAGE_TOP          160
#define MMI_DATE_EDIT_LEFT          MMI_TIME_EDIT_LEFT
#define MMI_DATE_EDIT_TOP           MMI_TIME_EDIT_TOP
#define MMI_DATE_EDIT_RIGHT         MMI_TIME_EDIT_RIGHT
#define MMI_DATE_EDIT_BOTTOM        MMI_TIME_EDIT_BOTTOM

#define MMI_TITLE_TEXT_L_MARGIN	            45 

//title
#define MMI_TITLE_ARROW_MARGIN	        10
#define MMI_TITLE_ARROW_RECT_WIDTH      24 
#define MMI_TITLE_ISTYLE_MENU_ICON_MARGIN	  10

#define MMI_TITLE_LEFT_ARROW_WIDTH      24
#define MMI_TITLE_LEFT_ARROW_HEIGHT     22
#define MMI_TITLE_RIGHT_ARROW_WIDTH     24
#define MMI_TITLE_RIGHT_ARROW_HEIGHT    22

#define MMI_TITLE_LEFT_ARROW_LEFT       3
#define MMI_TITLE_LEFT_ARROW_TOP        3
#define MMI_TITLE_LEFT_ARROW_RIGHT      ( MMI_TITLE_LEFT_ARROW_LEFT + MMI_TITLE_LEFT_ARROW_WIDTH - 1)
#define MMI_TITLE_LEFT_ARROW_BOTTOM     (MMI_TITLE_LEFT_ARROW_TOP+MMI_TITLE_LEFT_ARROW_HEIGHT-1)

#define MMI_TITLE_RIGHT_ARROW_LEFT		(MMI_MAINSCREEN_WIDTH - MMI_TITLE_LEFT_ARROW_LEFT -MMI_TITLE_RIGHT_ARROW_WIDTH)
#define MMI_TITLE_RIGHT_ARROW_TOP       MMI_TITLE_LEFT_ARROW_TOP
#define MMI_TITLE_RIGHT_ARROW_RIGHT     ( MMI_TITLE_RIGHT_ARROW_LEFT + MMI_TITLE_RIGHT_ARROW_WIDTH - 1)
#define MMI_TITLE_RIGHT_ARROW_BOTTOM    (MMI_TITLE_RIGHT_ARROW_TOP+MMI_TITLE_RIGHT_ARROW_HEIGHT-1)

// tips position info
#define MMITIPS_RECT_MIN_HEIGHT                26   // 默认高度
#define MMITIPS_RECT_MAX_WIDTH                 468  // 默认宽度 

//pubwin font info
#define MMI_PUBWIN_BIG_FONT          SONG_FONT_24
#define MMI_PUBWIN_NORMAL_FONT       SONG_FONT_20
#define MMI_PUBWIN_SMALL_FONT        SONG_FONT_18
#else
#error
#endif // MAINLCD_SIZE_240X400

#ifdef MENU_CRYSTALCUBE_SUPPORT

    #define MENUICON_CRYSTALCUBE_SELECTICON_WIDTH      56
    #define MENUICON_CRYSTALCUBE_SELECTICON_HEIGHT     56
#if defined MAINLCD_SIZE_320X480
    #define MMI_CRYSTALCUBE_REGION_WIDTH           240//192
    #define MMI_CRYSTALCUBE_REGION_HEIGHT          280//224
#elif defined (MAINLCD_SIZE_176X220) 
    #define MMI_CRYSTALCUBE_REGION_WIDTH           120//192
    #define MMI_CRYSTALCUBE_REGION_HEIGHT          140//224
#elif  defined (MAINLCD_SIZE_128X160)
    #define MMI_CRYSTALCUBE_REGION_WIDTH           120//192
    #define MMI_CRYSTALCUBE_REGION_HEIGHT          140//224
#else
    #define MMI_CRYSTALCUBE_REGION_WIDTH           180//192
    #define MMI_CRYSTALCUBE_REGION_HEIGHT          220//224
#endif
#if defined MAINLCD_SIZE_240X320
    #define MMI_CUBEPAGE_PAGE_RECT          {24, 61, 24+MMI_CRYSTALCUBE_REGION_WIDTH-1, 61+MMI_CRYSTALCUBE_REGION_HEIGHT-1}//jinx
#elif defined MAINLCD_SIZE_240X400
    #define MMI_CUBEPAGE_PAGE_RECT          {24, 111, 24+MMI_CRYSTALCUBE_REGION_WIDTH-1, 111+MMI_CRYSTALCUBE_REGION_HEIGHT-1}//jinx
#elif defined MAINLCD_SIZE_320X480
    #define MMI_CUBEPAGE_PAGE_RECT          {30, 121, 30+MMI_CRYSTALCUBE_REGION_WIDTH-1, 121+MMI_CRYSTALCUBE_REGION_HEIGHT-1}//jinx    
#elif defined (MAINLCD_SIZE_176X220) 
    #define MMI_CUBEPAGE_PAGE_RECT          {15, 50, 15+MMI_CRYSTALCUBE_REGION_WIDTH-1, 50+MMI_CRYSTALCUBE_REGION_HEIGHT-1}//jinx    
#elif defined (MAINLCD_SIZE_128X160) 
    #define MMI_CUBEPAGE_PAGE_RECT          {15, 50, 15+MMI_CRYSTALCUBE_REGION_WIDTH-1, 50+MMI_CRYSTALCUBE_REGION_HEIGHT-1}//jinx    
#endif
#endif

#define MMI_MAINSCREEN_RIGHT_MAX_PIXEL      (MMI_MAINSCREEN_WIDTH-1)
#define MMI_MAINSCREEN_BOTTOM_MAX_PIXEL	    (MMI_MAINSCREEN_HEIGHT-1)

#define MMI_LEFT_ARROW_RECT                 {MMI_TITLE_LEFT_ARROW_LEFT, MMI_TITLE_LEFT_ARROW_TOP, MMI_TITLE_LEFT_ARROW_RIGHT, MMI_TITLE_LEFT_ARROW_BOTTOM}
#define MMI_RIGHT_ARROW_RECT                {MMI_TITLE_RIGHT_ARROW_LEFT, MMI_TITLE_RIGHT_ARROW_TOP, MMI_TITLE_RIGHT_ARROW_RIGHT, MMI_TITLE_RIGHT_ARROW_BOTTOM}                                              MMI_MAINSCREEN_BOTTOM_MAX_PIXEL - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT}

#define MMI_CLIENT_RECT_TOP                 MMI_TITLE_HEIGHT
#define MMI_CLIENT_RECT_BOTTOM              (MMI_MAINSCREEN_BOTTOM_MAX_PIXEL - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT)

//default info
#define MMI_DEFAULT_SUBLCD_BLOCK	0

#define MMI_MAINSCREEN_MP3_LEFT     10
#define MMI_MAINSCREEN_MP3_WIDTH    (MMI_MAINSCREEN_WIDTH-MMI_MAINSCREEN_MP3_LEFT-MMI_MAINSCREEN_MP3_LEFT)

#define MMI_MAINSCREEN_IDLE_STK_LEFT     10
#define MMI_MAINSCREEN_IDLE_STK_WIDTH    (MMI_MAINSCREEN_WIDTH - 2*MMI_MAINSCREEN_IDLE_STK_LEFT)
#define MMI_MAINSCREEN_IDLE_STK_HEIGHT   20

#define MMI_DNLIST_TEXT_LEFT_SPACE              5 // for dropdownlist control

//add for prompt window and msgbox default
#define MMI_PROMPT_BK_PIC_WINDTH	132               //the width of pub win background picture
#define MMI_PROMPT_BK_PIC_HEIGHT	140				//the height of pub win background picture
#define MMI_PROMPT_IMAGE_WIDTH		56                //the width of pub win image
#define MMI_PROMPT_IMAGE_HEIGHT		59                //the height of pub win image
#define MMI_PROMPT_SK_HEIGHT		25                //the height of pub win soft key
#define MMI_PROMPT_TEXT_HEIGHT		20                //the height of pun win text rectangle
		
#define MMI_PROMPT_WIN_LEFT			(MMI_MAINSCREEN_WIDTH - MMI_PROMPT_BK_PIC_WINDTH )/2//14
#define MMI_PROMPT_WIN_TOP			(MMI_MAINSCREEN_HEIGHT - MMI_PROMPT_BK_PIC_HEIGHT)/2//37//20
#define MMI_PROMPT_WIN_RIGHT		(MMI_MAINSCREEN_WIDTH - MMI_PROMPT_WIN_LEFT -1)//113//115
#define MMI_PROMPT_WIN_BOTTOM		(MMI_MAINSCREEN_HEIGHT - MMI_PROMPT_WIN_TOP)//130//121//122


#define MMI_PROMPT_WIN_RECT			{MMI_PROMPT_WIN_LEFT, MMI_PROMPT_WIN_TOP, MMI_PROMPT_WIN_RIGHT, MMI_PROMPT_WIN_BOTTOM}//{14, 20, 114, 121}//{14, 20, 115, 122}
#define MMI_PROMPT_IMAGE_LEFT       (MMI_MAINSCREEN_WIDTH - MMI_PROMPT_IMAGE_WIDTH)/2//14
#define MMI_PROMPT_IMAGE_TOP        MMI_PROMPT_WIN_TOP//37
#define MMI_PROMPT_IMAGE_RIGHT      (MMI_MAINSCREEN_WIDTH - MMI_PROMPT_IMAGE_LEFT)//114
#define MMI_PROMPT_IMAGE_BOTTOM     (MMI_PROMPT_IMAGE_TOP + MMI_PROMPT_IMAGE_HEIGHT)//90//67
#define MMI_PROMPT_IMAGE_RECT		{MMI_PROMPT_IMAGE_LEFT, MMI_PROMPT_IMAGE_TOP, MMI_PROMPT_IMAGE_RIGHT, MMI_PROMPT_IMAGE_BOTTOM}
#define MMI_PROMPT_TEXT_RECT		{MMI_PROMPT_WIN_LEFT,(MMI_PROMPT_IMAGE_BOTTOM + MMI_PROMPT_TEXT_HEIGHT),MMI_PROMPT_WIN_RIGHT,(MMI_PROMPT_IMAGE_BOTTOM + MMI_PROMPT_TEXT_HEIGHT *2)}//{14,90,114,105}//{14,77,114,93}//{14,77,115,93}
#define MMI_PROMPT_WAIT_IMAGE_RECT  {MMI_PROMPT_WIN_LEFT,MMI_PROMPT_WIN_TOP,(MMI_PROMPT_WIN_LEFT + MMI_PROMPT_BK_PIC_WINDTH),(MMI_PROMPT_WIN_TOP + MMI_PROMPT_IMAGE_HEIGHT)}
#define MMI_PROMPT_WAIT_TEXT_RECT   {MMI_PROMPT_WIN_LEFT,(MMI_PROMPT_WIN_TOP + MMI_PROMPT_IMAGE_HEIGHT),MMI_PROMPT_WIN_RIGHT,(MMI_PROMPT_WIN_BOTTOM - MMI_PROMPT_SK_HEIGHT)}
#define MMI_PROMPT_SK_RECT			{MMI_PROMPT_WIN_LEFT, (MMI_PROMPT_WIN_BOTTOM - MMI_PROMPT_SK_HEIGHT),MMI_PROMPT_WIN_RIGHT,MMI_PROMPT_WIN_BOTTOM}//{14, 112, 114, 130}//{15, 100, 113, 119}

/* list box item style*/
#ifdef MAINLCD_SIZE_128X64
#define MMI_LIST_BIG_ITEM_FONT		 (SONG_FONT_20)

#define MMI_LIST_NORMAL_ITEM_FONT    (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_DEFAULT_ITEM_FONT   (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_EXPAND_ITEM_FONT    (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_EXPAND_ITEM_HEIGHT  (MMI_LIST_ITEM_HEIGHT)
#define MMI_LIST_ITEM_SMALL_FONT     (MMI_LIST_DEFAULT_ITEM_FONT)

#elif defined MAINLCD_SIZE_128X160
#define MMI_LIST_BIG_ITEM_FONT		 (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_NORMAL_ITEM_FONT    (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_DEFAULT_ITEM_FONT   (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_EXPAND_ITEM_FONT    (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_EXPAND_ITEM_HEIGHT  (MMI_LIST_ITEM_HEIGHT)
#define MMI_LIST_ITEM_SMALL_FONT     (MMI_DEFAULT_SMALL_FONT)

#elif defined MAINLCD_SIZE_176X220
#define MMI_LIST_BIG_ITEM_FONT		 (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_NORMAL_ITEM_FONT    (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_DEFAULT_ITEM_FONT   (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_EXPAND_ITEM_FONT    (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_EXPAND_ITEM_HEIGHT  (MMI_LIST_ITEM_HEIGHT)
#define MMI_LIST_ITEM_SMALL_FONT     (MMI_LIST_DEFAULT_ITEM_FONT)

#elif defined MAINLCD_SIZE_240X320
#define MMI_LIST_BIG_ITEM_FONT		 (SONG_FONT_26)

#if GUIF_LIST_PDASTYLE
#define MMI_LIST_DEFAULT_ITEM_FONT   (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_NORMAL_ITEM_FONT    (SONG_FONT_18)
#define MMI_LIST_EXPAND_ITEM_FONT    (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_EXPAND_ITEM_HEIGHT  (MMI_LIST_ITEM_HEIGHT)
#define MMI_LIST_ITEM_SMALL_FONT     (SONG_FONT_14)
#else
#define MMI_LIST_DEFAULT_ITEM_FONT   (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_NORMAL_ITEM_FONT    (MMI_DEFAULT_TEXT_FONT)
//#define MMI_LIST_EXPAND_ITEM_FONT    ((MMI_DEFAULT_TEXT_FONT)*14/10)
#define MMI_LIST_EXPAND_ITEM_FONT    (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_EXPAND_ITEM_HEIGHT  ((MMI_LIST_ITEM_HEIGHT)*14/10)
#define MMI_LIST_ITEM_SMALL_FONT     (MMI_DEFAULT_SMALL_FONT)
#endif

#elif defined MAINLCD_SIZE_240X400
#define MMI_LIST_BIG_ITEM_FONT		 (SONG_FONT_26)

#ifdef GUIF_LIST_PDASTYLE
#define MMI_LIST_DEFAULT_ITEM_FONT   (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_NORMAL_ITEM_FONT    (SONG_FONT_18)
#define MMI_LIST_EXPAND_ITEM_FONT    (MMI_DEFAULT_TEXT_FONT)

#define MMI_LIST_EXPAND_ITEM_HEIGHT  (MMI_LIST_ITEM_HEIGHT)
#define MMI_LIST_ITEM_SMALL_FONT     (SONG_FONT_14)
#else
#define MMI_LIST_DEFAULT_ITEM_FONT   (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_NORMAL_ITEM_FONT    (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_EXPAND_ITEM_FONT    ((MMI_DEFAULT_TEXT_FONT)*14/10)
#define MMI_LIST_EXPAND_ITEM_HEIGHT  ((MMI_LIST_ITEM_HEIGHT)*14/10)
#define MMI_LIST_ITEM_SMALL_FONT     (MMI_DEFAULT_SMALL_FONT)
#endif
#elif defined MAINLCD_SIZE_320X480
#define MMI_LIST_BIG_ITEM_FONT		 (SONG_FONT_26)
#ifdef GUIF_LIST_PDASTYLE
#define MMI_LIST_DEFAULT_ITEM_FONT   (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_NORMAL_ITEM_FONT    (SONG_FONT_18)
#define MMI_LIST_EXPAND_ITEM_FONT    (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_EXPAND_ITEM_HEIGHT  (MMI_LIST_ITEM_HEIGHT)
#define MMI_LIST_ITEM_SMALL_FONT     (SONG_FONT_16)
#else
#define MMI_LIST_DEFAULT_ITEM_FONT   (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_NORMAL_ITEM_FONT    (MMI_DEFAULT_TEXT_FONT)
#define MMI_LIST_EXPAND_ITEM_FONT    ((MMI_DEFAULT_TEXT_FONT)*14/10)
#define MMI_LIST_EXPAND_ITEM_HEIGHT  ((MMI_LIST_ITEM_HEIGHT)*14/10)
#define MMI_LIST_ITEM_SMALL_FONT     (MMI_LIST_DEFAULT_ITEM_FONT)
#endif

#endif


//整个颜色
#define MMI_WHITE_COLOR		        0xffff
#define MMI_BLACK_COLOR		        0x0000
#define MMI_GRAY_WHITE_COLOR        0xef9d
#ifdef MAINLCD_SIZE_128X64 //@CR226145 2011.01.24
#define MMI_DEFAULT_TEXT_COLOR      MMI_BLACK_COLOR     //内屏幕中所有的字体颜色,黑色
#define MMI_TRANSPARENCE_COLOR      0x0001              //所有界面中透明色定义为0x0001 
#define MMI_WINDOW_BACKGROUND_COLOR	MMI_WHITE_COLOR              //窗口的背景色@phoebe
#define MMI_BACKGROUND_COLOR        MMI_WHITE_COLOR              //应用通用的背景色，接近黑色
#define WAIT_TEXT_BACKGROUND_COLOR  MMI_BLACK_COLOR  //特殊界面中文本背景的颜色
#else 
#define MMI_DEFAULT_TEXT_COLOR      MMI_BLACK_COLOR //MMI_GRAY_WHITE_COLOR     //内屏幕中所有的字体颜色,黑色
#define MMI_TRANSPARENCE_COLOR      MMI_WHITE_COLOR     //所有界面中透明色定义为0x0 
#ifdef MMI_PDA_SUPPORT
#define MMI_WINDOW_BACKGROUND_COLOR	MMI_WHITE_COLOR              //窗口的背景色@phoebe
#else
#define MMI_WINDOW_BACKGROUND_COLOR	MMI_WHITE_COLOR //MMI_BLACK_COLOR              //窗口的背景色@phoebe
#endif
#define MMI_BACKGROUND_COLOR        MMI_WHITE_COLOR //MMI_BLACK_COLOR              //应用通用的背景色，接近黑色
#define WAIT_TEXT_BACKGROUND_COLOR      0x955d  //特殊界面中文本背景的颜色
#endif
#define MMI_DARK_BLUE_COLOR             0x001f
#define MMI_BLUE_COLOR                  0x07ff
#define MMI_DARK_GREEN_COLOR            0x03e0
#define MMI_DARK_CYAN_COLOR             0xf81f
#define MMI_GREEN_COLOR                 0x07e0
#define MMI_CYAN_COLOR                  0xfb81	      
#define MMI_DARK_RED_COLOR              0xf800
#define MMI_DARK_MAGENTA_COLOR          0x0081
#define MMI_DARK_YELLOW_COLOR           0x0090
#define MMI_DARK_GRAY_COLOR             0x8410
#define MMI_GRAY_COLOR                  0xCD7C
#define MMI_RED_COLOR                   0x8000
#define MMI_MAGENTA_COLOR               0x00e3
#define MMI_YELLOW_COLOR                0xfff0
#define MMI_PURPLE_COLOR                0x81fb
#define MMI_WEAK_DARK_COLOR             0x0800
#define MMI_EDITBOX_COLOR               0x1258
#define MMI_TEXTBOX_RECT_COLOR          0x1258
#define MMI_PROMPT_SK_BG_COLOR          0xa63f
#define MMI_IS_SELECTED_COLOR           0x6E7E
#define MMI_OSD_TRANSPARENT_COLOR       0Xf81f
#define MMI_OSD_DEFAULT_ALPHA           0x00ff              //覆盖下层图片
#define MMI_DARK_WHITE_COLOR            0xb5b6
#define MMI_DIAL_GRAY_COLOR             0xcccc
#define MMI_DEFAULT_TITLE_BG_COLOR      0x1258              //default title color
#define	MMI_SPELL_BACK_COLOR            0x9e7f
#define	MMI_T9_FONT_COLOR               0x193
#define MMI_TAB_DEFAULT_FOCUS_COLOR     0x397
#define MMI_LIGHT_BLUE_COLOR            0x7e3d
#define MMI_HIGH_LIGHT_COLOR            0xff0f
#define MMI_BLACK_GRAY_COLOR            0x0841

#define MMI_OPACITY60_WHITE_COLOR   0x9cd3

#define MMI_MASK_ALPHA              204                 //蒙层的透明度，80%透明;

// 列表控件Item的薄雾效果颜色
#define MMI_LIST_ITEM_MIST_COLOR    0x6e7e    //被提示的图片的alpha blending颜色

// list number font type
#define MMI_LISTNUM_FONT                        SONG_FONT_10        // 显示在右上角的ListNumber信息的字体

typedef enum
{
	MMI_MAIN_BACKGROUND_PIC,		//MAIN LCD背景图片
	MMI_MAIN_SOFTKEY_BAR,           //MAIN LCD SOFTKEY BAR

	MMI_MAIN_IDLE_SIGNAL_ICON,      //MAIN LCD信号量提示 
#ifdef MMI_MULTI_SIM_SYS_DUAL
	MMI_MAIN_IDLE_SIGNAL_ICON_2,    //MAIN LCD信号量2提示 
#endif
	MMI_MAIN_IDLE_GPRS_ICON,	//MAIN LCD gprs状态标志显示，@zhaohui add for gprs icon
    MMI_MAIN_IDLE_MESSAGE_ICON,     //MAIN LCD短信提示
	MMI_MAIN_IDLE_EARPHONE_ICON,    //MAIN LCD 耳机提示
    MMI_MAIN_IDLE_ALARM_ICON,		//MAIN LCD闹钟提示
	MMI_MAIN_IDLE_ENVSET_ICON,		//MAIN LCD情景模式：静音，铃声，振动提示
	MMI_MAIN_IDLE_CALL_FORWARD,		//MAIN LCD呼叫转移
	MMI_MAIN_IDLE_BLUE_TOOTH,		//MAIN LCD蓝牙
	MMI_MAIN_IDLE_BATTERY_ICON,     //MAIN LCD电池提示
	MMI_MAIN_IS_CHARGING_ANIM,      //MAIN LCD关机下 充电动画
	MMI_MAIN_IS_ALARM_ANIM,			//MAIN LCD闹钟闹铃动画
    MMI_MAIN_IDLE_LINE_INFO_ICON,	//MAIN LCD通话线路状态
    MMI_MAIN_IDLE_SD_ICON,          //MAIN LCD SD卡提示
    TOTAL_IDLE_ICONANIM_NUMBER
} MMI_IDLE_ICON_INDEX_E;

typedef enum
{
	IDLE_ALIGN_LEFT,			//左对齐
	IDLE_ALIGN_RIGHT,			//右对齐
	IDLE_ALIGN_X_CENTER,		//居屏幕中间
	IDLE_ALIGN_CUSTOM,			//自定义
	IDLE_ALIGN_MAX		
}MMI_IDLE_DISPLAY_ALIGN_E;

//IDLE界面显示的文字的坐标，颜色，大小
typedef struct
{
	uint16						text_frame_x;		//文本显示区域的其实X坐标
    uint16						text_frame_top;		//文本显示区域的起始Y坐标
	MMI_IDLE_DISPLAY_ALIGN_E	text_align;			//文本显示对齐方式
    GUI_FONT_T					text_font;			//文本显示字体大小
}MMI_IDLE_DISPLAY_T;	

//定义待机界面下需要显示的枚举
typedef enum
{
    MMI_MAIN_LCD_NONE,
    MMI_MAIN_LCD_PLMN,				//待机MAIN LCD运营商文字
#ifndef MMI_MULTI_SIM_SYS_SINGLE
    MMI_MAIN_LCD_PLMN2,				//待机MAIN LCD运营商文字
#if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
    MMI_MAIN_LCD_PLMN3,				//待机MAIN LCD运营商文字
#endif
#if defined(MMI_MULTI_SIM_SYS_QUAD)
    MMI_MAIN_LCD_PLMN4,				//待机MAIN LCD运营商文字
#endif
#endif
//    MMI_MAIN_LCD_SPN,               //待机MAIN LCD Service Providor name
    
	//MMI_MAIN_LCD_COMMEMORATE_DAY,	//待机MAIN LCD纪念日
	MMI_MAIN_LCD_CUSTOM_WORD,		//待机MAIN LCD自定义词语
	MMI_MAIN_LCD_COUNTEDTIME,		//待机MAIN LCD 倒记时显示,@zhaohui,counted time
	MMI_MAIN_LCD_CALENDAR,			//待机MAIN LCD 日历显示
#ifdef MMI_SMSCB_CELL_INFO_SUPPORT
    MMI_MAIN_LCD_CELL_INFO,
#endif

	//MMI_MAIN_LCD_ALARM,				//待机MIAN LCD闹钟到了的时间文本显示
	
    MMI_MAIN_LCD_MP3,				//待机MAIN LCD MP3背景播放mp3 name
    MMI_MAIN_LCD_FM,                //待机MAIN LCD FM背景播放FM name
	MMI_MAIN_LCD_TIME,				//待机MAIN LCD时间
	MMI_MAIN_LCD_DATE,				//待机MAIN LCD日期
	MMI_MAIN_LCD_WEEK,				//待机MAIN LCD星期
    
	MMI_SUB_LCD_TIME,				//待机SUB LCD时间
	MMI_SUB_LCD_DATE,				//待机SUB LCD日期
	MMI_SUB_LCD_WEEK,				//待机SUB LCD星期	
	MMI_SUB_LCD_ALARM,				//SUB LCD闹钟到了的时间文本显示
	MMI_SUB_LCD_COUNTEDTIME,        //SUB LCD倒记时显示,
	MMI_MAIN_LCD_STK_IDLE_MODE,     //STK  在set up idle mode text需要显示的文本

    MMI_MAIN_LCD_LEFT_SOFTKEY,      //左软键
    MMI_MAIN_LCD_RIGHT_SOFTKEY,     //右软键

	TOTAL_IDLE_DISPLAY_NUMBER
} MMI_IDLE_DISPLAY_INDEX_E;

/**--------------------------------------------------------------------------*
 **                         EXTERNAL DECLARE                                 *
 **--------------------------------------------------------------------------*/  
/*****************************************************************************/
// 	Description : get idle display style
//	Global resource dependence : 
//  Author: bruce.chi
//	Note:
/*****************************************************************************/
MMI_IDLE_DISPLAY_T  MMITHEME_GetIdleDispStyle(MMI_IDLE_DISPLAY_INDEX_E e_idle_disp_index);

/*****************************************************************************/
// 	Description : get idle icon display position
//	Global resource dependence : 
//  Author: bruce.chi
//	Note:
/*****************************************************************************/
PUBLIC GUI_POINT_T MMITHEME_GetIdleIconPos(MMI_IDLE_ICON_INDEX_E e_icon);
  
  
/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef   __cplusplus
    }
#endif

#endif  
