
 //[[define image infomation
 //contrast

#ifndef MMI_GUI_STYLE_MINISCREEN
#ifdef MMI_LOW_MEMORY_RESOURCE
RES_ADD_IMG(IMAGE_SET_CONTRAST_BAR_BG,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_BAR_BG.png",IMG_CMP_PNG_SABM_RLE | SABM_HOR_STRETCH,0)
#else
RES_ADD_IMG(IMAGE_SET_CONTRAST_BAR_BG,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_BAR_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_SET_CONTRAST_BAR_FG,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_BAR_FG.png",IMG_CMP_PNG_ARGB_RLE,0)
#else
//michael wang
RES_ADD_IMG(IMAGE_SET_CONTRAST_BAR_FG_NEW,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_BAR_FG_NEW.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAGE_SET_CONTRAST_BAR_BG_NEW,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_BAR_BG_NEW.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
#ifndef TOUCH_PANEL_SUPPORT  //Touch情况下不需要三角提示
RES_ADD_IMG(IMAGE_SET_CONTRAST_TRIANGLE_LEFT,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_TRIANGLE_LEFT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_CONTRAST_TRIANGLE_RIGHT,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_TRIANGLE_RIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
//RES_ADD_IMG(IMAGE_SET_CONTRAST_DOWN_PRESSED,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_DOWN_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined DPHONE_SUPPORT
RES_ADD_IMG(IMAGE_SET_CONTRAST_DOWN_RELEASED,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_DOWN_RELEASED.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SET_CONTRAST_DOWN_RELEASED_DEC_GREY,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_DOWN_RELEASED_DEC_GREY.png",IMG_CMP_PNG_ARGB_RLE,0)

#endif
//RES_ADD_IMG(IMAGE_SET_CONTRAST_UP_PRESSED,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_UP_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined DPHONE_SUPPORT
RES_ADD_IMG(IMAGE_SET_CONTRAST_UP_RELEASED,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_UP_RELEASED.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SET_CONTRAST_UP_RELEASED_DEC_GREY,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_UP_RELEASED_DEC_GREY.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
//RES_ADD_IMG(IMAGE_SET_CONTRAST_LEVEL_0,"\\MMI_RES_##\\IMAG\\Contrast_setting\\IMAGE_SET_CONTRAST_LEVEL_0.bmp",IMG_CMP_BMP_16_565_RLE,0)
//#if defined MMI_GUI_STYLE_TYPICAL
 #ifndef MMI_RES_LOW_COST
//dong.chunguang remove useless img
RES_ADD_IMG(IMAGE_SET_DATE_ICON,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_DATE_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//#endif
RES_ADD_IMG(IMAGE_SET_TIME_ICON,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_TIME_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_SET_DIRKEY_LEFT,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_DIRKEY_LEFT.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SET_DIRKEY_RIGHT,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_DIRKEY_RIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SET_SL,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_SL.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SET_SR,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_SR.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SET_DIRKEY_UP,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_DIRKEY_UP.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SET_DIRKEY_DOWN,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_DIRKEY_DOWN.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef DPHONE_SUPPORT //@CR230547 2011.03.04
RES_ADD_IMG(IMAGE_SET_ALLOWABLE_2G,"\\MMI_RES_##\\IMAG\\Call_setting\\IMAGE_SET_ALLOWABLE_2G.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_SET_ALLOWABLE_3G,"\\MMI_RES_##\\IMAG\\Call_setting\\IMAGE_SET_ALLOWABLE_3G.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_SET_FORBIDDEN_2G,"\\MMI_RES_##\\IMAG\\Call_setting\\IMAGE_SET_FORBIDDEN_2G.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_SET_FORBIDDEN_3G,"\\MMI_RES_##\\IMAG\\Call_setting\\IMAGE_SET_FORBIDDEN_3G.bmp",IMG_CMP_BMP_16_565_RLE,0)
#else
RES_ADD_IMG(IMAGE_SET_ALLOWABLE_2G,"\\MMI_RES_##\\IMAG\\Call_setting\\IMAGE_SET_ALLOWABLE_2G.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SET_ALLOWABLE_3G,"\\MMI_RES_##\\IMAG\\Call_setting\\IMAGE_SET_ALLOWABLE_3G.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_2G_4G_SUPPORT
RES_ADD_IMG(IMAGE_SET_ALLOWABLE_4G,"\\MMI_RES_##\\IMAG\\Call_setting\\IMAGE_SET_ALLOWABLE_4G.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_FORBIDDEN_4G,"\\MMI_RES_##\\IMAG\\Call_setting\\IMAGE_SET_FORBIDDEN_4G.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_ALLOWABLE_LTE,"\\MMI_RES_##\\IMAG\\Call_setting\\IMAGE_SET_ALLOWABLE_LTE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_FORBIDDEN_LTE,"\\MMI_RES_##\\IMAG\\Call_setting\\IMAGE_SET_FORBIDDEN_LTE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_SET_FORBIDDEN_2G,"\\MMI_RES_##\\IMAG\\Call_setting\\IMAGE_SET_FORBIDDEN_2G.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SET_FORBIDDEN_3G,"\\MMI_RES_##\\IMAG\\Call_setting\\IMAGE_SET_FORBIDDEN_3G.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAGE_ADJUST_VOL_PLUG,"\\MMI_RES_##\\IMAG\\IMAGE_ADJUST_VOL_PLUG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_ADJUST_VOL_MINUS,"\\MMI_RES_##\\IMAG\\IMAGE_ADJUST_VOL_MINUS.png",IMG_CMP_PNG_ARGB_RLE,0)
//dong.chunguang remove useless img
RES_ADD_IMG(IMAGE_SET_IDLE_SHORTCUT1,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_IDLE_SHORTCUT1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IDLE_SHORTCUT2,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_IDLE_SHORTCUT2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IDLE_SHORTCUT3,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_IDLE_SHORTCUT3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IDLE_SHORTCUT4,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_IDLE_SHORTCUT4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IDLE_SHORTCUT5,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_IDLE_SHORTCUT5.png",IMG_CMP_PNG_ARGB_RLE,0)

//#if !defined MMI_PDA_SUPPORT && defined MULTI_THEME_SUPPORT
//RES_ADD_IMG(IMAGE_SET_THEME1,"\\MMI_RES_##\\IMAG\\IMAGE_SET_THEME1.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_SET_THEME2,"\\MMI_RES_##\\IMAG\\IMAGE_SET_THEME2.bmp",IMG_CMP_BMP_16_565_RLE,0)
//#endif

#if defined(MMI_BLACKLIST_SUPPORT)
//RES_ADD_IMG(IMAGE_SET_BLACKLIST,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_BLACKLIST.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#if defined(MMI_WHITELIST_SUPPORT)
//RES_ADD_IMG(IMAGE_SET_WHITELIST,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_SET_WHITELIST.png",IMG_CMP_PNG_ARGB_RLE,0) 
#endif
#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG(IMAGE_ENVSET_FLYOFF,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_ENVSET_FLYOFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_ENVSET_FLYON,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_ENVSET_FLYON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_ENVSET_SILENTOFF,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_ENVSET_SILENTOFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_ENVSET_SILENTON,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_ENVSET_SILENTON.png",IMG_CMP_PNG_ARGB_RLE,0)
//#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG(IMAGE_POWEROFF,"\\MMI_RES_##\\IMAG\\Phone_setting\\IMAGE_POWEROFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifndef MMI_SETTING_CUTDOWN_MAINMENU
// 主菜单的类型图片
// 宫格类型
RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_ICON,           "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_ICON.png",         IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_ICON,            "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_ICON.png",          IMG_CMP_PNG_ARGB_RLE,0)
#ifdef PDA_UI_SUPPORT_MANIMENU_GO
RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_GO,            "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_GO.png",          IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_GO,            "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_GO.png",          IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef MENU_SWEETS_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_SWEET,            "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_SWEET.png",          IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_SWEET,            "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_SWEET.png",          IMG_CMP_PNG_ARGB_RLE,0)
#endif
// 宫格类型，带Title
// RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_ICON_TITLE,     "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_ICON_TITLE.png",   IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_ICON_TITLE,      "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_ICON_TITLE.png",    IMG_CMP_PNG_ARGB_RLE,0)
// 左右滑动菜单
#ifdef SLIDE_MAIN_MENU_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_SLIDE_PAGE,     "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_SLIDE_PAGE.png",   IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_SLIDE_PAGE,      "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_SLIDE_PAGE.png",    IMG_CMP_PNG_ARGB_RLE,0)
#endif
// 立方体
// RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_CUBE,           "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_CUBE.png",         IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_CUBE,            "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_CUBE.png",          IMG_CMP_PNG_ARGB_RLE,0)
// 梯形滑动，即左右滑动时有梯形变换
#ifdef TRAPEZOID_MAIN_MENU_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_TRAPEZOID,      "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_TRAPEZOID.png",    IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_TRAPEZOID,       "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_TRAPEZOID.png",     IMG_CMP_PNG_ARGB_RLE,0)
#endif
// 水晶立方
#ifdef MENU_CRYSTALCUBE_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_CRYSTAL_CUBE,   "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_CRYSTAL_CUBE.png", IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_CRYSTAL_CUBE,    "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_CRYSTAL_CUBE.png",  IMG_CMP_PNG_ARGB_RLE,0)
#endif
// 龙卷风
#ifdef MENU_CYCLONE_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_CYCLONE,        "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_CYCLONE.png",      IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_CYCLONE,         "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_CYCLONE.png",       IMG_CMP_PNG_ARGB_RLE,0)
#endif
// 球体
#ifdef SPHERE_MAIN_MENU_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_SPHERE,        "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_SPHERE.png",      IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_SPHERE,         "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_SPHERE.png",       IMG_CMP_PNG_ARGB_RLE,0)
#endif

// 圆柱体
#ifdef CYLINDER_MAIN_MENU_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_CYLINDER,       "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_CYLINDER.png",      IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_CYLINDER,        "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_CYLINDER.png",       IMG_CMP_PNG_ARGB_RLE,0)
#endif

// 双子星
#ifdef BINARY_STAR_MAIN_MENU_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_BINARY_STAR,    "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_BINARY_STAR.png",  IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_BINARY_STAR,     "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_BINARY_STAR.png",   IMG_CMP_PNG_ARGB_RLE,0)
#endif
// 百叶窗
#ifdef SHUTTER_MAIN_MENU_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_SHUTTER,        "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_SHUTTER.png",      IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_SHUTTER,         "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_SHUTTER.png",       IMG_CMP_PNG_ARGB_RLE,0)
#endif
// 滚咕噜咕噜滚
#ifdef CHARIOT_MAIN_MENU_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_MAINMENU_CHARIOT,        "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_ICON_MAINMENU_CHARIOT.png",      IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SET_IMG_MAINMENU_CHARIOT,         "\\MMI_RES_##\\IMAG\\mainmenu_style\\IMAGE_SET_IMG_MAINMENU_CHARIOT.png",       IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
//#ifndef MMI_SETTING_LOW_MEMORY

//#endif
#if 1
// 屏锁类型——————————————————————————————————————————————————————————————————————————
#ifdef MMI_KEY_LOCK_EFFECT_TYPE0_SUPPORT
#ifndef MMI_KEYLOCK_MINI_SUPPORT
//RES_ADD_IMG(IMAGE_SET_ICON_SCREEN_LOCK_0,   "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_ICON_SCREEN_LOCK_0.png",   IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_SET_IMG_SCREEN_LOCK_0,    "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_IMG_SCREEN_LOCK_0.png",    IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
//
#ifdef MMI_KEY_LOCK_EFFECT_TYPE1_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_SCREEN_LOCK_1,   "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_ICON_SCREEN_LOCK_1.png",   IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_SET_IMG_SCREEN_LOCK_1,    "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_IMG_SCREEN_LOCK_1.png",    IMG_CMP_PNG_ARGB_RLE,0)
#endif
//
#ifdef MMI_KEY_LOCK_EFFECT_TYPE2_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_SCREEN_LOCK_2,   "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_ICON_SCREEN_LOCK_2.png",   IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_SET_IMG_SCREEN_LOCK_2,    "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_IMG_SCREEN_LOCK_2.png",    IMG_CMP_PNG_ARGB_RLE,0)
#endif
//
#ifdef MMI_KEY_LOCK_EFFECT_TYPE3_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_SCREEN_LOCK_3,   "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_ICON_SCREEN_LOCK_3.png",   IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_SET_IMG_SCREEN_LOCK_3,    "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_IMG_SCREEN_LOCK_3.png",    IMG_CMP_PNG_ARGB_RLE,0)
#endif
//
#ifdef MMI_KEY_LOCK_EFFECT_TYPE4_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_SCREEN_LOCK_4,   "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_ICON_SCREEN_LOCK_4.png",   IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_SET_IMG_SCREEN_LOCK_4,    "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_IMG_SCREEN_LOCK_4.png",    IMG_CMP_PNG_ARGB_RLE,0)
#endif
//
#ifdef MMI_KEY_LOCK_EFFECT_TYPE5_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_SCREEN_LOCK_5,   "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_ICON_SCREEN_LOCK_5.png",   IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_SET_IMG_SCREEN_LOCK_5,    "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_IMG_SCREEN_LOCK_5.png",    IMG_CMP_PNG_ARGB_RLE,0)
#endif
//
#ifdef MMI_KEY_LOCK_EFFECT_TYPE6_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_SCREEN_LOCK_6,   "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_ICON_SCREEN_LOCK_6.png",   IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_SET_IMG_SCREEN_LOCK_6,    "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_IMG_SCREEN_LOCK_6.png",    IMG_CMP_PNG_ARGB_RLE,0)
#endif
//
#ifdef MMI_KEY_LOCK_EFFECT_TYPE7_SUPPORT
//RES_ADD_IMG(IMAGE_SET_ICON_SCREEN_LOCK_7,   "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_ICON_SCREEN_LOCK_7.png",   IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_SET_IMG_SCREEN_LOCK_7,    "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_IMG_SCREEN_LOCK_7.png",    IMG_CMP_PNG_ARGB_RLE,0)
#endif

//
//#ifdef MMI_KEY_LOCK_EFFECT_TYPE8_SUPPORT
//RES_ADD_IMG(IMAGE_SET_ICON_SCREEN_LOCK_8,   "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_ICON_SCREEN_LOCK_8.png",   IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_SET_IMG_SCREEN_LOCK_8,    "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_IMG_SCREEN_LOCK_8.png",    IMG_CMP_PNG_ARGB_RLE,0)
//#endif

#ifdef MMI_KEY_LOCK_FRUIT_SPLIT_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_SCREEN_LOCK_FRUIT,   "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_ICON_SCREEN_LOCK_FRUIT.png",   IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_SET_IMG_SCREEN_LOCK_FRUIT,    "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_IMG_SCREEN_LOCK_FRUIT.png",    IMG_CMP_PNG_ARGB_RLE,0)
#endif
//michael wang kl
#ifdef MMI_KEY_LOCK_DOUBLE_CIRCLE_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_SCREEN_LOCK_CIRCLE,   "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_ICON_SCREEN_LOCK_CIRCLE.png",   IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_SET_IMG_SCREEN_LOCK_FRUIT,    "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_IMG_SCREEN_LOCK_FRUIT.png",    IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef MMI_KEY_LOCK_SPEC_DOUBLE_CIRCLE_SUPPORT
RES_ADD_IMG(IMAGE_SET_ICON_SCREEN_LOCK_SPECCIRCLE,   "\\MMI_RES_##\\IMAG\\screenlock_style\\IMAGE_SET_ICON_SCREEN_LOCK_SPECCIRCLE.png",   IMG_CMP_PNG_ARGB_RLE,0)
#endif
//michael wang
#endif
RES_ADD_IMG(IMAGE_SETTING_SYSTEM_ICON,"\\MMI_RES_##\\IMAG\\System_setting\\IMAGE_SETTINGS_SYSTEM_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)


//]]define image infomation





//[[define anim infomation

//]]define anim infomation





//[[define string infomation
#if 1
//RES_ADD_STRING(TXT_SET_RING_SELECT,"Select ring")        //case3：defined but not used

//RES_ADD_STRING(TXT_SET_RING_FIXED,"Fixed rings")            //replaced by common ID TXT_RING_FIXED

//RES_ADD_STRING(TXT_SET_RING_VOLUME,"Adjust volume")    //replaced by common ID TXT_RING_VOLUME

RES_ADD_STRING(TXT_SET_RING_CALL_TYPE,"Call alert")

RES_ADD_STRING(TXT_SET_RING_MSG_TYPE,"Message alert")

RES_ADD_STRING(TXT_SET_RING_KEY_TONE,"Keypad tones")
#ifdef FLIP_PHONE_SUPPORT
RES_ADD_STRING(TXT_SET_RING_FLIP_RING,"Flip alert")
RES_ADD_STRING(TXT_SET_RING_FLIP_DOWN_RING,"Flip down alert")
#endif
RES_ADD_STRING(TXT_SET_DOWNLOAD_NOTIFY,"Download alert")

RES_ADD_STRING(TXT_SET_RING_VOLTAGE_WARNING,"Battery low alert")

RES_ADD_STRING(TXT_SET_RING_SELECT_CALL,"Incoming ringtone")

//RES_ADD_STRING(TXT_SET_RING_SELECT_ALARM,"Alarm ringtone")         //case3：defined but not used

RES_ADD_STRING(TXT_SET_RING_SELECT_MSG,"Message ringtone")

RES_ADD_STRING(TXT_SET_RING_VOLUME_COMM,"Earpiece volume")

//RES_ADD_STRING(TXT_SET_RING_VOLUME_POWER,"Power on/off tone")      //replaced by local ID TXT_ENVSET_POWER_RING_TYPE
#ifdef MMI_READMENU_ENABLE
RES_ADD_STRING(TXT_SET_RING_VOLUME_MENUREAD,"Menu read volume")
#endif
RES_ADD_STRING(TXT_SET_RING_RING,"Ring")

//RES_ADD_STRING(TXT_SET_RING_VIBRA,"Vibrate")    //replaced by common ID  TXT_RING_VIBRA

//RES_ADD_STRING(TXT_SET_RING_SILENT,"Silent")  //replaced by common ID TXT_RING_SILENT

RES_ADD_STRING(TXT_SET_RING_VIBRA_BEFORE_RING,"Vibrate then ring")

RES_ADD_STRING(TXT_SET_RING_VIBRA_AND_RING,"Ring and vibrate")

//RES_ADD_STRING(TXT_SET_RING_RING1,"Ringtone1")        //replaced by common ID TXT_COMMON_RING_RING1

//RES_ADD_STRING(TXT_SET_RING_RING2,"Ringtone2")        //replaced by common ID TXT_COMMON_RING_RING2

RES_ADD_STRING(TXT_ENVSET_STANDARD,"Normal mode")

RES_ADD_STRING(TXT_ENVSET_SILENT,"Silent mode")

RES_ADD_STRING(TXT_ENVSET_MEETING,"Meeting mode")

RES_ADD_STRING(TXT_ENVSET_INSIDE,"Inside mode")

RES_ADD_STRING(TXT_ENVSET_NOISY,"Outside mode")
#if !defined DPHONE_SUPPORT && defined MMIENVSET_EARPHONE_BLUETOOTH_SUPPORT
RES_ADD_STRING(TXT_ENVSET_EARPHONE,"Headset")

RES_ADD_STRING(TXT_ENVSET_BLUETOOTH,"Bluetooth")
#endif

//RES_ADD_STRING(TXT_ENVSET_FLY,"Fly")       //case3：defined but not used

//RES_ADD_STRING(TXT_ENVSET_ACTIVATE,"Active")  //replaced by common ID TXT_ACTIVE_OPERATIVE

#if !defined DPHONE_SUPPORT && defined MMIENVSET_EARPHONE_BLUETOOTH_SUPPORT
RES_ADD_STRING(TXT_SET_PROFILES_EARPHONE_PLUG_IN,"Earphone plugged in")

RES_ADD_STRING(TXT_SET_PROFILES_EARPHONE_PLUG_OUT,"Earphone plugged out")
#endif

//RES_ADD_STRING(TXT_ENVSET_SETTING_OPT,"Settings")  //replaced by common ID TXT_EXPORT_LOC_CUSTOM

//RES_ADD_STRING(TXT_ENVSET_CHANGE_NAME,"Rename")  //replaced by common ID TXT_COMMON_RENAME

RES_ADD_STRING(TXT_ENVSET_EMPTY_NAME,"Empty name")

RES_ADD_STRING(TXT_ENVSET_ALARM_RING_TYPE,"Alarm remind")

RES_ADD_STRING(TXT_ENVSET_POWER_RING_TYPE,"Power ring")

RES_ADD_STRING(TXT_SET_TIME_DATE,"Time and date")

RES_ADD_STRING(TXT_SET_TIME,"Set time")

RES_ADD_STRING(TXT_SET_DATE,"Set date")

//RES_ADD_STRING(TXT_SET_LANGUAGE,"Language")      //case3：defined but not used

RES_ADD_STRING(TXT_SET_LANGUAGE_SETTINGS,"Language")

RES_ADD_STRING(TXT_SET_SHOW_LANGUAGE,"Show language")

//RES_ADD_STRING(TXT_SET_INPUT_LANGUAGE,"Input language")    //replaced by common ID TXT_INPUT_LANGUAGE

//RES_ADD_STRING(TXT_SET_ENGLISH,"English")        //case3：defined but not used

//RES_ADD_STRING(TXT_SET_S_CHINESE,"Chinese simple")       //case3：defined but not used

//RES_ADD_STRING(TXT_SET_T_CHINESE,"Chinese traditional")     //case3：defined but not used

//RES_ADD_STRING(TXT_SET_ARABIC,"Arabic")      //case3：defined but not used

//RES_ADD_STRING(STXT_SET_HINDI,"Hindi")        //case3：defined but not used

//RES_ADD_STRING(STXT_SET_THAI,"Thai")        //case3：defined but not used

RES_ADD_STRING(TXT_SET_KEY_BOARD_LIGHT,"Keypad light")

RES_ADD_STRING(TXT_SET_AUTO_BOADRKEY,"Auto key")

//RES_ADD_STRING(TXT_SET_DISPLAY,"Display settings")    //replaced by common ID TXT_DISPLAY_SET

//RES_ADD_STRING(TXT_SET_WALLPAPER,"Wallpaper settings")         //replaced by common ID TXT_COMMON_SET_WALLPAPER

#if defined ( DPHONE_SUPPORT ) ||!defined MMI_KEY_LOCK_BACKLIGHT_IN_1_SUPPORT
RES_ADD_STRING(TXT_SET_BACK_LIGHT,"Backlight")
#endif

RES_ADD_STRING(TXT_SET_CONTRAST,"Contrast")

//RES_ADD_STRING(TXT_SET_CALL,"Call settings")    //replaced by common ID  TXT_SETTINGS_CALL

RES_ADD_STRING(TXT_SET_IP_NUMBER,"IP number")

RES_ADD_STRING(TXT_SET_FLIP_ANSWER,"Open to answer")

RES_ADD_STRING(TXT_SET_CALL_DIVERTS,"Call divert")
//RES_ADD_STRING(STXT_CALL_DIVERT,"Call forwarding")
RES_ADD_STRING(STXT_HEADER_CALL_DIVERT,"Call forwarding")
// RES_ADD_STRING(STR_LIST_BLOCKED_NUMBER_EXT01,"Blocked number")
RES_ADD_STRING(STR_COST_CONTROL_MENU,"Cost settings")
RES_ADD_STRING(STR_HDR_COST_SETT_EXT01,"Cost settings")
RES_ADD_STRING(STR_PHONEBOOTH_HDR,"Call trackers")
RES_ADD_STRING(STR_SET_MOBILE_PHONEBOOTH,"Call trackers")
RES_ADD_STRING(STXT_TIME_50_SECONDS_EXT01,"50 s")
RES_ADD_STRING(STXT_TIME_55_SECONDS_EXT01,"55 s")
RES_ADD_STRING(STXT_TIME_60_SECONDS_EXT01,"60 s")
RES_ADD_STRING(STR_SETT_LIST_CUSTOMISED_EXT01,"Customised")
RES_ADD_STRING(STR_PROMPT_INPUT_TIME_EXT01,"Input time (1-60 s)")

RES_ADD_STRING(TXT_SET_CALL_WAITING,"Call waiting")
RES_ADD_STRING(TXT_SET_CALL_BAR,"Call barring")

RES_ADD_STRING(STXT_HEADER_CALL_WAITING,"Call waiting")
RES_ADD_STRING(STR_LIST_SIM_EXT01,"SIM")
RES_ADD_STRING(STR_CALL_WAITING_ACTIVATED_EXT01,"Call waiting on")
RES_ADD_STRING(STR_CALL_WAITING_OFF_EXT01,"Call waiting off")



//RES_ADD_STRING(TXT_SET_NETWORK,"Network settings") //网络选择    //replaced by common ID TXT_NETWORK_SELECT

#ifdef MMI_PREFER_PLMN_SUPPORT
//RES_ADD_STRING(TXT_SET_NETWORK_SETTING,"Network setting") // 网络设置    //replaced by common ID TXT_NETWORK_SETTING

RES_ADD_STRING(TXT_SET_PREFER_NETWORK,"Preferences") //偏好网络

RES_ADD_STRING(TXT_SET_PREFER_NETWORK_ADD,"Add from list") // 从列表添加

RES_ADD_STRING(TXT_SET_PREFER_NETWORK_PRIORITY,"Change priority") // 更改优先级

RES_ADD_STRING(TXT_SET_PREFER_NETWORK_ADD_ERROR,"Create Failed") //无法添加网络

RES_ADD_STRING(TXT_SET_NETWORK_PLMN_LIST,"PLMN list") // PLMN 列表

//RES_ADD_STRING(TXT_SET_NETWORK_PLMN_PRIORITY,"Priority") //优先权  //replaced by common ID TXT_COMMON_PRIORITY
#endif

//RES_ADD_STRING(TXT_SET_BAND,"Band select")         //case3：defined but not used

//RES_ADD_STRING(TXT_SET_SECURITY,"Security settings")  //replaced by common ID TXT_COMM_SECURITY_SETTING

RES_ADD_STRING(TXT_SET_PIN1,"PIN")

RES_ADD_STRING(TXT_SET_PIN2,"PIN2")

//RES_ADD_STRING(TXT_SET_RESET_FACTORY,"Restore factory settings")   //replaced by common ID TXT_COMMON_RESTORE_FACTORY_SETTINGS

RES_ADD_STRING(TXT_SET_DIVERTS_ALL_CALLS,"Unconditional")
RES_ADD_STRING(STXT_DIVERT_ALL,"All voice calls")

RES_ADD_STRING(STXT_CANCEL_ALL_DIVERTS,"no call forwarding")

RES_ADD_STRING(TXT_SET_DIVERTS_WHEN_BUSY,"If busy")

RES_ADD_STRING(TXT_SET_DIVERTS_NO_ANSWER,"If no answered")

RES_ADD_STRING(STXT_DIVERT_NOT_AVAIL,"If out of reach")


RES_ADD_STRING(TXT_SET_DIVERTS_NOT_REACHABLE,"If out of reach")

RES_ADD_STRING(TXT_SET_DIVERTS_CANCEL_ALL,"Cancel all diverts")

RES_ADD_STRING(TXT_SET_BAR_ALL_MO_CALLS,"All outgoing calls")

RES_ADD_STRING(TXT_SET_BAR_ALL_MT_CALLS,"All incoming calls")

RES_ADD_STRING(TXT_SET_BAR_MT_CALLS_ROAM,"Incoming when roam")

RES_ADD_STRING(TXT_SET_BAR_MO_CALLS_INTL,"All intl outgoing")

RES_ADD_STRING(TXT_SET_BAR_MO_CALLS_INTL_ROAM,"Outgoing intl roam")

RES_ADD_STRING(TXT_SET_BAR_CANCEL_ALL,"Cancel all barring")

RES_ADD_STRING(TXT_SET_BAR_CHANGE_PW,"Change password")

RES_ADD_STRING(TXT_SET_QUERY_STATUS,"Check status")

RES_ADD_STRING(TXT_SET_DIVERT_VOICE,"Divert to voicemail")

RES_ADD_STRING(TXT_SET_DIVERT_NUMBER,"Divert to number")

//RES_ADD_STRING(TXT_SET_NO_ANSWER_TIME,"No answer time")    //replaced by common ID TXT_NO_REPLY_TIME

RES_ADD_STRING(TXT_SET_TIME_OPEN_FOREVER,"Always on")

RES_ADD_STRING(TXT_SET_TIME_30S,"30s")

RES_ADD_STRING(TXT_SET_TIME_25S,"25s")

RES_ADD_STRING(TXT_SET_TIME_20S,"20s")

RES_ADD_STRING(TXT_SET_TIME_15S,"15s")

RES_ADD_STRING(TXT_SET_TIME_10S,"10s")//replaced by common ID TXT_COMM_10SECOND

RES_ADD_STRING(TXT_SET_TIME_5S,"5s")

RES_ADD_STRING(TXT_SET_TIME_40S,"40s")

RES_ADD_STRING(TXT_SET_TIME_COMM_60S,"60s")

RES_ADD_STRING(TXT_SET_TIME_120S,"120s")

//RES_ADD_STRING(TXT_SET_TIME_CLOSE,"Deactivate")         //replaced by common ID TXT_CLOSE

//RES_ADD_STRING(TXT_SET_NETWORK_CONNECT,"Network connect")    //replaced by common ID  TXT_NETWORK_CONNECT

//RES_ADD_STRING(TXT_SET_AUTO_SEL,"Auto select")  //replaced by common ID TXT_COMMON_AUTO_SELECT

RES_ADD_STRING(TXT_SET_MANUAL_SEL,"Manual select")

RES_ADD_STRING(TXT_SET_PCS_BAND,"PCS band")

RES_ADD_STRING(TXT_SET_DUAL_BAND,"Dual band")

//RES_ADD_STRING(TXT_SET_ANIMATION_WALLPAPER,"Anim wallpaper")

//RES_ADD_STRING(TXT_SET_POWER_ON_OFF_ANIMATION,"On/off animation")

#ifdef MMI_SETTING_POWERON_ANIM
RES_ADD_STRING(TXT_SET_POWER_ON_ANIMATION,"Power on animation")       //replaced by common ID TXT_COMMON_POWER_ON_ANIMATION

RES_ADD_STRING(TXT_SET_POWER_OFF_ANIMATION,"Power off animation")     //replaced by common ID TXT_COMMON_POWER_OFF_ANIMATION

RES_ADD_STRING(TXT_SET_ANIMATION_1,"Animation one")

RES_ADD_STRING(TXT_SET_ANIMATION_2,"Animation two")

RES_ADD_STRING(TXT_SET_ANIMATION_3,"Animation three")
#endif

//RES_ADD_STRING(TXT_SET_DISPLAY_TYPE,"Display type")      //case3：defined but not used

RES_ADD_STRING(TXT_SET_TIME_DISPLAY_TYPE,"Time display type")

//RES_ADD_STRING(TXT_SET_TIME_12_HOUR,"12 hours") //replaced by common ID TXT_COMM_12_HOURS

//RES_ADD_STRING(TXT_SET_TIME_24_HOUR,"24 hours")  //replaced by common ID TXT_COMM_24_HOURS

//RES_ADD_STRING(TXT_SET_MINUTE_ALERT,"50 secs warning")        //case3：defined but not used
//#ifdef MAINLCD_SIZE_128X64
//RES_ADD_STRING(TXT_SET_SPEED_DIAL_TIME_1S,"1 Second")  //replaced by common ID TXT_COMM_1_SECOND
//RES_ADD_STRING(TXT_SET_SPEED_DIAL_TIME_2S,"2 Second")  //replaced by common ID TXT_COMM_2_SECONDS
//RES_ADD_STRING(TXT_SET_SPEED_DIAL_TIME_3S,"3 Second")  //replaced by common ID TXT_COMM_3_SECONDS
RES_ADD_STRING(TXT_SET_SPEED_DIAL_TIME_4S,"4 Second")
//RES_ADD_STRING(TXT_SET_SPEED_DIAL_TIME_5S,"5 Second")  //replaced by common ID TXT_COMM_5_SECONDS
//RES_ADD_STRING(TXT_SET_SPEED_DIAL_TIME_6S,"6 Second")  //replaced by common ID TXT_COMM_6_SECONDS
RES_ADD_STRING(TXT_SET_SPEED_DIAL_TIME_7S,"7 Second")
RES_ADD_STRING(TXT_SET_SPEED_DIAL_TIME_8S,"8 Second")
//#endif
RES_ADD_STRING(TXT_SPEED_DIAL,"Speed dial")
RES_ADD_STRING(TXT_SET_CALL_TIME_REMINDER,"call time minute reminder")

RES_ADD_STRING(TXT_SET_TIME_50S,"50S")

RES_ADD_STRING(TXT_SET_TIME_55S,"55S")

RES_ADD_STRING(TXT_SET_TIME_60S,"60S")

//RES_ADD_STRING(TXT_SET_MINUTE_REMINDER_SET,"set time")  //replaced by common ID TXT_EXPORT_LOC_CUSTOM

RES_ADD_STRING(TXT_SET_MINUTE_REMINDER_TIME,"Time:(0-60s)")

//RES_ADD_STRING(TXT_SET_OUT_OF_RANGE,"Out of range")       //case3：defined but not used


RES_ADD_STRING(STXT_CALL_REPEAT,"Automatic redial")

RES_ADD_STRING(TXT_SET_AUTO_REDAIL,"Auto redial")

#ifdef MMI_AUTO_RECORD_SUPPORT
RES_ADD_STRING(TXT_SET_AUTO_RECORD,"Auto Record")
#endif
#ifdef ZDT_PRODUCT_Q98
RES_ADD_STRING(TXT_SET_AUTO_HANDFREE,"Auto Handfree")
#endif

//RES_ADD_STRING(TXT_SET_MAIN_LCD,"Main display")

//RES_ADD_STRING(TXT_SET_SUB_LCD,"Sub display")

//RES_ADD_STRING(TXT_SET_DIRECTIONKEY_MAIN,"Direction key")

RES_ADD_STRING(TXT_SET_DIRECTIONKEY_UP,"Set up direction key")

RES_ADD_STRING(TXT_SET_DIRECTIONKEY_DOWN,"Set down direction key")

RES_ADD_STRING(TXT_SET_DIRECTIONKEY_LEFT,"Set left direction key")

RES_ADD_STRING(TXT_SET_DIRECTIONKEY_RIGHT,"Set right direction key")

//RES_ADD_STRING(TXT_SET_PIC_WALLPAPER,"Picture wallpaper")

//RES_ADD_STRING(TXT_SET_MENU_ANIMATION,"Main menu animation")

RES_ADD_STRING(TXT_SET_IDLE_DISPLAY,"Set idle display")
#ifdef SCREENSAVER_SUPPORT
RES_ADD_STRING(TXT_SET_SCREENSAVER,"Set screensavers")

//RES_ADD_STRING(TXT_SET_SCREENSAVER_CLOSE,"Deactivate")      //replaced by common ID TXT_CLOSE

//RES_ADD_STRING(TXT_SET_SCREENSAVER_1,"Screensavers one")         //case3：defined but not used

//RES_ADD_STRING(TXT_SET_SCREENSAVER_2,"Screensavers two")         //case3：defined but not used
#endif
RES_ADD_STRING(TXT_SET_TIME_AND_DATE,"Time & date")

RES_ADD_STRING(TXT_SET_NETWORK_NAME,"Network name")

RES_ADD_STRING(TXT_SET_CUSTOM_WORD,"Custom word")

//RES_ADD_STRING(TXT_SET_EDIT_CUSTOM_WORD,"Edit")        //case3：defined but not used

//RES_ADD_STRING(TXT_SET_TV_OUT,"TV out mode")           //case3：defined but not used

//RES_ADD_STRING(TXT_SET_TIME_AUTO,"Auto")    //replaced by common ID TXT_NIGHT_MODE

//RES_ADD_STRING(TXT_SET_MORE_RING,"More ring")           //replaced by common ID TXT_COMMON_MORE_RING

RES_ADD_STRING(TXT_SET_SET_PRIVACY_PROTECT,"Privacy protect")

//RES_ADD_STRING(TXT_SET_MODIFY_CODE,"Password change")

//RES_ADD_STRING(TXT_SET_EBOOK,"Ebook")  //replaced by common ID TXT_COMM_EBOOK

RES_ADD_STRING(TXT_SET_CONNECT_PROMPT,"Connect prompt")

#if defined ( MMI_GUI_STYLE_TYPICAL ) ||defined( MMI_REJECT_CALL_BY_SMS_SUPPORT )||defined( DPHONE_SUPPORT )
RES_ADD_STRING(TXT_SET_ANYKEY_REJECT_MODE,"Anykey/Reject mode")
#endif

RES_ADD_STRING(TXT_SET_HIDE_ID,"Hide ID")
//RES_ADD_STRING(TXT_SEND_CALLER_ID,"send caller ID")
RES_ADD_STRING(STXT_CLIR,"send caller ID")

RES_ADD_STRING(TXT_SET_CLIP_ID,"Show number of caller")

RES_ADD_STRING(TXT_SET_COLP_ID,"Show number of anwsering")

RES_ADD_STRING(TXT_SET_COLR_ID,"Hide my caller ID on anwsering")

RES_ADD_STRING(TXT_SET_CNAP_SUCC_ID,"Successful CNAP interrogation")

#if defined(MMI_REJECT_CALL_BY_SMS_SUPPORT)
RES_ADD_STRING(TXT_SET_SMS_REPLY,"SmsReply after reject")
#endif

RES_ADD_STRING(TXT_SET_ANYKEY_ANSWER,"Anykey answer")

RES_ADD_STRING(TXT_SET_DISPLAY_ID,"Display ID")

RES_ADD_STRING(TXT_SET_HIDEID,"Hide ID")

RES_ADD_STRING(TXT_SET_DISPLAY_ID_BY_NETWORK,"Display ID by  network")

//RES_ADD_STRING(TXT_SET_INPUT_PRIVACY_PWD,"Input privacy protect pwd(1-8)")        //case3：defined but not used

//RES_ADD_STRING(TXT_SET_INPUT_NEW_PRIVACY_PWD,"Input new pwd (1-8)")    //replaced by common ID TXT_INPUT_NEW_PWD

//RES_ADD_STRING(TXT_SET_INPUT_NEW_PRIVACY_PWD_CNF,"Input pwd cnf (1-8)")     //replaced by common ID TXT_INPUT_NEW_PWD_CNF

//RES_ADD_STRING(TXT_SET_MMS_INBOX,"Inbox")        //case3：defined but not used

//RES_ADD_STRING(TXT_SET_MISSED_CALLS,"Missed calls")        //case3：defined but not used

//RES_ADD_STRING(TXT_SET_RECEIVED_CALLS,"Received calls")      //case3：defined but not used

//RES_ADD_STRING(TXT_SET_REFUSED_CALLS,"Rejected")             //case3：defined but not used

//RES_ADD_STRING(TXT_SET_WRITE_MESSAGE,"Write messages")  //replaced by common ID TXT_COMMON_WRITE_MESSAGE

//RES_ADD_STRING(TXT_SET_VIDEO,"Handycam")          //case3：defined but not used

//RES_ADD_STRING(TXT_SET_ALARM_CLOCK,"Alarm")      //case3：defined but not used

//RES_ADD_STRING(TXT_SET_MP3,"MP3 player")        //case3：defined but not used

//RES_ADD_STRING(TXT_SET_GAME,"Games")           //case3：defined but not used

//RES_ADD_STRING(TXT_SET_SEARCH,"Phonebook search")      //case3：defined but not used

//RES_ADD_STRING(TXT_SET_PB_VIEW,"Phonebook view")      //case3：defined but not used

//RES_ADD_STRING(TXT_SET_MPEG4,"MediaPlayer")       //case3：defined but not used

RES_ADD_STRING(TXT_SET_PAL_LINE_BY_LINE,"PAL line by line")
#ifdef MMISET_TVOUT_INTERLEAVING_MODE
RES_ADD_STRING(TXT_SET_PAL_INTERLEAVING_LINE,"PAL interleaving line")
#endif
RES_ADD_STRING(TXT_SET_NTSC_LINE_BY_LINE,"NTSC line by lie")
#ifdef MMISET_TVOUT_INTERLEAVING_MODE
RES_ADD_STRING(TXT_SET_NTSC_INTERLEAVING_LINE,"NTSC interleaving line")
#endif
//RES_ADD_STRING(TXT_SET_FM_RADIO,"FM")    //replaced by common ID TXT_FM

//RES_ADD_STRING(TXT_SET_BLUETOOTH,"Blue tooth")       //case3：defined but not used

//RES_ADD_STRING(TXT_SET_MESSAGES,"Messages")         //case3：defined but not used

RES_ADD_STRING(TXT_SET_CLEAN_USER_DATA,"Restore factory settings and delete all user data and settings?")

//RES_ADD_STRING(TXT_SET_LINE_SELECT_LINE1,"Line 1")

//RES_ADD_STRING(TXT_SET_LINE_SELECT_LINE2,"Line 2")

#ifdef MMI_CSP_SUPPORT
RES_ADD_STRING(TXT_SET_DIVERTS_ALL_CONDITIONAL,"Call foward conditional")

RES_ADD_STRING(TXT_SET_LINE_LOCKED,"Line is locked")
#endif

//RES_ADD_STRING(TXT_SET_LINE1_NUMBER,"Line 1 number")    //replaced by common ID TXT_LINE1_NUMBER

//RES_ADD_STRING(TXT_SET_LINE2_NUMBER,"Line 2 number")    //replaced by common ID TXT_LINE2_NUMBER

//RES_ADD_STRING(TXT_SET_FAX_NUMBER,"Fax number")  //replaced by common ID TXT_COMM_FAX_NUMBER

RES_ADD_STRING(TXT_SET_DATA_NUMBER,"Date number")

//RES_ADD_STRING(TXT_SET_LINE_SELECT,"Line select")

//RES_ADD_STRING(TXT_SET_PROFILES,"Profiles")      //replaced by common ID TXT_SETTINGS_ENVIONMENT

RES_ADD_STRING(TXT_SET_PROFILES_ACTIVATED,"Activated:")

//RES_ADD_STRING(TXT_SET_PROFILES_MODE,"Mode")           //case3：defined but not used

RES_ADD_STRING(TXT_SET_RING_SET,"Ring set")

RES_ADD_STRING(TXT_SET_DATE_DISPLAY_TYPE,"Date display type")

//RES_ADD_STRING(TXT_SET_FUNCTION_SHORTCUT,"Set idle function shortcut")      //case3：defined but not used

#if defined TOUCH_PANEL_SUPPORT && !defined TOUCHPANEL_TYPE_MULTITP
RES_ADD_STRING(TXT_SET_COORDINATE,"Set coordinate")
#endif

//RES_ADD_STRING(TXT_SET_MEMORY_MANAGEMENT,"Memory management")      //case3：defined but not used

RES_ADD_STRING(TXT_SET_DATE_YMD,"Year-month-day")

RES_ADD_STRING(TXT_SET_DATE_DMY,"Day-month-year")

//RES_ADD_STRING(TXT_SET_SHORTCUT_DIAL,"Dial")  //replaced by common ID TXT_COMM_DIALPAD

//RES_ADD_STRING(TXT_SET_SHORTCUT_PB,"Phone book")    //replaced by common ID  STXT_MAIN_PB

//RES_ADD_STRING(TXT_SET_SHORTCUT_MESSAGE,"Message")          //case3：defined but not used

//RES_ADD_STRING(TXT_SET_SHORTCUT_WRITE_SMS,"Write sms")  //replaced by common ID TXT_COMMON_WRITE_SMS

RES_ADD_STRING(TXT_SET_SHORTCUT_MP3,"Audio player")

//RES_ADD_STRING(TXT_SET_SHORTCUT_VIDEO,"Video player")  //replaced by common ID TXT_COMMON_VIDEOPLAYER

//RES_ADD_STRING(TXT_SET_SHORTCUT_CAMERA,"Camera")    //replaced by common ID TXT_ENTERTAIMENT_CAMERA

//RES_ADD_STRING(TXT_SET_SHORTCUT_DIGITAL_VIDEO,"Digital video")          //case3：defined but not used

//RES_ADD_STRING(TXT_SET_SHORTCUT_RING,"Choose ring")

//RES_ADD_STRING(TXT_SET_SHORTCUT_PROFILES,"Profiles")     //replaced by common ID TXT_SETTINGS_ENVIONMENT

//RES_ADD_STRING(TXT_SET_SHORTCUT_ALARM,"Alarm ")      //replaced by common ID TXT_ALARM_CLOCK

//RES_ADD_STRING(TXT_SET_SHORTCUT_GAME,"Game")    //replaced by common ID TXT_ENTERTAIMENT_GAME

//RES_ADD_STRING(TXT_SET_SHORTCUT_DOCUMENT,"Document")          //case3：defined but not used

//RES_ADD_STRING(TXT_SET_SHORTCUT_BT,"Bluetooth")      //replaced by common ID TXT_BLUETOOTH

//RES_ADD_STRING(TXT_SET_SHORTCUT_CALENDAR,"Calendar")    //replaced by common ID TXT_IDLE_CALENDAR

//RES_ADD_STRING(TXT_SET_SHORTCUT_CALCULATOR,"Calculator")      //replaced by common ID TXT_COMMON_CALCULATOR

//RES_ADD_STRING(TXT_SET_SHORTCUT_WEB,"Web")           //replaced by common ID STR_ILIST_INTERNET_EXT01

//RES_ADD_STRING(TXT_SET_SHORTCUT_EBOOK,"Ebook")  //replaced by common ID TXT_COMM_EBOOK

//RES_ADD_STRING(TXT_SET_SHORTCUT_SMS_INBOX,"inbox")    //replaced by common ID TXT_INBOX

//RES_ADD_STRING(TXT_SET_SHORTCUT_JAVA,"JAVA")   //replaced by common ID TXT_JAVA

//RES_ADD_STRING(TXT_SET_SHORTCUT_MAINMENU,"Main Menu")  //replaced by common ID TXT_COMMON_MAINMENU

//RES_ADD_STRING(TXT_SET_SHORTCUT,"Set shortcut")       //replaced by common ID TXT_COMMON_SPEEDKEY_SET

//RES_ADD_STRING(TXT_SET_FUNCKEY,"Set function key")        //case3：defined but not used
#ifdef SCREENSAVER_SUPPORT
RES_ADD_STRING(TXT_SET_SCREENSAVER_MORE,"More screen saver")
#endif
//RES_ADD_STRING(TXT_SET_POWER_ON_OFF_ANIM_CLOSE,"Close")           //case3：defined but not used

//RES_ADD_STRING(TXT_SET_POWER_ON_OFF_ANIM_DEFAULT,"Default")       //replaced by common ID TXT_EXPORT_LOC_DEFAULT

RES_ADD_STRING(TXT_SET_POWER_ON_OFF_ANIM_MORE,"More animation")

RES_ADD_STRING(TXT_SET_WALLPAPER_1,"Wallpaper1")

RES_ADD_STRING(TXT_SET_WALLPAPER_2,"Wallpaper2")
#ifndef MMI_SETTING_CUTDOWN_WALLPAPER
RES_ADD_STRING(TXT_SET_WALLPAPER_3,"Wallpaper3")
RES_ADD_STRING(TXT_SET_WALLPAPER_4,"Wallpaper4")
#endif
///RES_ADD_STRING(TXT_SET_FLY_MODE,"Fly mode")

//RES_ADD_STRING(TXT_SET_DUALMODE_SWITCH,"Dualmode switch")       //case3：defined but not used

//RES_ADD_STRING(TXT_SET_DUALMODE_GSM,"GSM")        //case3：defined but not used

//RES_ADD_STRING(TXT_SET_DUALMODE_TDSCDMA,"TD-SCDMA")        //case3：defined but not used

//RES_ADD_STRING(TXT_SET_NETWORK_TYPE,"Network type")    //replaced by common ID  TXT_NETEWORK_TYPE

RES_ADD_STRING(TXT_SET_NETWORK_METHOD,"Network method")

//RES_ADD_STRING(TXT_SET_AUTO,"Auto")  //replaced by common ID TXT_AUTO


//RES_ADD_STRING(TXT_SET_HAND,"Manual")    //replaced by common ID TXT_MANUAL
#ifdef MMI_DUALMODE_ENABLE
RES_ADD_STRING(TXT_SET_GSM,"GSM")
RES_ADD_STRING(TXT_SET_TDSCDMA,"TD-SCDMA")
#ifdef PLATFORM_SC7702
RES_ADD_STRING(TXT_SET_WCDMA,"W-CDMA")
#endif
#endif
//RES_ADD_STRING(TXT_SET_DM,"dual mode")

//RES_ADD_STRING(TXT_SET_GSM_PREFER,"GSM preferred") //replaced by common ID TXT_COMM_GSM_PREFER
#ifdef MMI_DUALMODE_ENABLE
RES_ADD_STRING(TXT_SET_TD_PREFER,"TD preferred")
#ifdef PLATFORM_SC7702
RES_ADD_STRING(TXT_SET_W_PREFER,"W preferred")
#endif
#endif
#if defined ( TOUCH_PANEL_SUPPORT )
RES_ADD_STRING(TXT_SET_DIAL_PANEL_TOUCH_VIBRATE,"Dial panel touch vibrate setting")
RES_ADD_STRING(TXT_SET_TP_KEY_LOCK_RING,"key lock ring")
#endif
#if defined(MMI_DIALPANEL_DTMF_SUPPORT)
RES_ADD_STRING(TXT_SET_DIAL_TONE,"Dial Tone")
#endif

#ifdef MMI_READMENU_ENABLE
RES_ADD_STRING(TXT_SET_MENU_READ,"Menu Read")
#endif

//RES_ADD_STRING(TXT_SET_AUDIOCALL,"Audio call")    //replaced by common ID TXT_CALL_AUDIO

RES_ADD_STRING(TXT_SET_VIDEOCALL,"Video call")

RES_ADD_STRING(TXT_SET_AUDIOANDVIDEO_CALL,"Audio&Video call")

//RES_ADD_STRING(TXT_SET_DIVERTS_QUERY_ALL_CALLS,"Check all status")       //case3：defined but not used

RES_ADD_STRING(TXT_SET_FDN,"Fixed dialing")
RES_ADD_STRING(TXT_FDN_MODE,"Fixed dialing Mode")
RES_ADD_STRING(TXT_FDN_NUM,"Fixed dialing number")

//RES_ADD_STRING(TXT_SET_STATE,"State")  //replaced by common ID TXT_COMMON_STATE

//RES_ADD_STRING(TXT_SET_ACTIVE_TYPE,"Set active type")     //case3：defined but not used

RES_ADD_STRING(TXT_SET_SELECT_ON_POWER,"Select when power on")

//RES_ADD_STRING(TXT_SET_FLYMODE_SELECT_ON_POWER,"Flight mode select when power on")         //case3：defined but not used

//RES_ADD_STRING(TXT_SET_SIM1_ENABLE,"SIM1 enable")         //case3：defined but not used

//RES_ADD_STRING(TXT_SET_SIM2_ENABLE,"SIM2 enable")        //case3：defined but not used

//RES_ADD_STRING(TXT_SET_SIM_SELECT,"Select sim")        //case3：defined but not used

//RES_ADD_STRING(TXT_PLS_INPUT_PWD,"Input PWD, please!")      //case3：defined but not used

RES_ADD_STRING(TXT_SET_RING_SIM1_SELECT_CALL,"SIM1 call ring")

RES_ADD_STRING(TXT_SET_RING_SIM2_SELECT_CALL,"SIM2 call ring")

RES_ADD_STRING(TXT_SET_RING_SIM3_SELECT_CALL,"SIM3 call ring")
RES_ADD_STRING(TXT_SET_RING_SIM4_SELECT_CALL,"SIM4 call ring")   //dayo

RES_ADD_STRING(TXT_SET_RING_SIM1_SELECT_MSG,"SIM1 MSG ring")

RES_ADD_STRING(TXT_SET_RING_SIM2_SELECT_MSG,"SIM2 MSG ring")

RES_ADD_STRING(TXT_SET_RING_SIM3_SELECT_MSG,"SIM3 MSG ring")
RES_ADD_STRING(TXT_SET_RING_SIM4_SELECT_MSG,"SIM4 MSG ring")   //dayo

RES_ADD_STRING(TXT_SET_DUAL_SIM_SETTING,"Dual sim setting")
#if !defined ( MMI_MULTI_SIM_SYS_DUAL) ||! defined (MMI_MULTI_SIM_SYS_SINGLE)
RES_ADD_STRING(TXT_SET_MULTI_SIM_SETTING,"Multi sim setting")
#endif


//RES_ADD_STRING(TXT_SET_CARD_SLOT1,"Card slot 1")       //case3：defined but not used

//RES_ADD_STRING(TXT_SET_CARD_SLOT2,"Card slot 2")       //case3：defined but not used

//RES_ADD_STRING(TXT_SET_CALL_SIM_SEL,"Call")  //replaced by common ID TXT_COMM_CALL

RES_ADD_STRING(TXT_SET_SMS_SIM_SEL,"Send SMS")

//RES_ADD_STRING(TXT_SET_MMS_SIM_SEL,"Send MMS") //replaced by common ID TXT_MMS

//RES_ADD_STRING(TXT_SET_BROWSER_SIM_SEL,"Browser")      //replaced by common ID STR_ILIST_INTERNET_EXT01

//RES_ADD_STRING(TXT_SET_SPEED_DIAL,"Prompt dial")       //replaced by common ID TXT_COMMON_SPEEDDIAL

RES_ADD_STRING(TXT_SET_PROMPT_TO_SEL,"Prompt to select")

//RES_ADD_STRING(TXT_SET_DELETE_BLACKLIST,"Delete redial blacklist")

RES_ADD_STRING(TXT_SET_REPLY_BY_ORIGINAL_SIM,"Use original Sim reply")

//RES_ADD_STRING(TXT_SET_WINDOW_MOVE_STYLE,"Window slide style")      //case3：defined but not used

RES_ADD_STRING(TXT_SET_HORIZONTAL_MOVE_STYLE,"Horizontal slide")

RES_ADD_STRING(TXT_SET_VERTICAL_MOVE_STYLE,"Vertical slide")

RES_ADD_STRING(TXT_SET_FORBIDDEN_MOVE,"No slide")

//RES_ADD_STRING(TXT_SET_INSERT_SIM,"No sim card")         //case3：defined but not used

//RES_ADD_STRING(TXT_SET_HELP,"Help")  //replaced by common ID TXT_HELP

//RES_ADD_STRING(TXT_SET_NEXT_STEP,"Next step")    //replaced by common ID TXT_NEXT_STEP

//RES_ADD_STRING(TXT_SET_DUALSIM_WIZARD_QUERY,"Dual sim setting?")      //case3：defined but not used

//RES_ADD_STRING(TXT_SET_MULTISIM_WIZARD_QUERY,"Multi sim setting?")     //case3：defined but not used

//RES_ADD_STRING(TXT_SET_SETTING,"Setting")       //replaced by common ID STXT_MAIN_SETTING

//RES_ADD_STRING(TXT_SET_FINISHED,"Finished")    //replaced by common ID  STXT_FINISH
#if defined(MMIPB_SIMDN_SUPPORT) && defined(MMI_DUALSIM_CALL_DIVERT_SUPPORT)
RES_ADD_STRING(TXT_SET_DUAL_HELP, "1. When Dual SIM Call Divert Set success, SIM2 incoming call will divert to SIM1 if SIM1 is IN Call.  2. The condition of setting success is that, both SIM support Call Divert unreachable, and Own number of each SIM is set correctly")
#endif
//RES_ADD_STRING(TXT_SET_INSERT_ANOTHER_SIM,"Need another sim card")         //case3：defined but not used

RES_ADD_STRING(TXT_SET_MAINMENU_STYLE,"Main menu style")
#ifdef PDA_UI_SUPPORT_U_IDLE
RES_ADD_STRING(TXT_SET_UIDLE_STYLE,"UIdle Effect")
#endif
//RES_ADD_STRING(TXT_SET_MAINMENU_OP,"Option page menu")      //case3：defined but not used
RES_ADD_STRING(TXT_SET_MAINMENU_ICON,"Block menu")
//RES_ADD_STRING(TXT_SET_SND_MAINMENU_ICON,"Matrix menu")
#if defined ( SLIDE_MAIN_MENU_SUPPORT ) ||defined( GO_FLASH_MAIN_MENU_SUPPORT)||((defined MMI_SMART_IDLE_SUPPORT_LARGE_ICON || defined MMI_SMART_IDLE_SUPPORT_SMALL_ICON)&& defined(MMI_COMMON_IDLE_SUPPORT))
RES_ADD_STRING(TXT_SET_MAINMENU_SLIDE,"Slide menu")
#endif
//RES_ADD_STRING(TXT_SET_MAINMENU_CUBE,"Cube menu")
#ifdef MENU_CRYSTALCUBE_SUPPORT
RES_ADD_STRING(TXT_SET_MAINMENU_CRYSTALCUBE,"Crystal Cube")
#endif
#ifdef MENU_CYCLONE_SUPPORT
RES_ADD_STRING(TXT_SET_MAINMENU_CYCLONE,"Cyclone")
#endif
//RES_ADD_STRING(TXT_SET_MAINMENU_TRAPEZOID,"Trapezoid menu")    //replaced by common ID TXT_ZOOM
#ifdef BINARY_STAR_MAIN_MENU_SUPPORT
//RES_ADD_STRING(TXT_SET_MAINMENU_BINARY_STAR,"Binary star")
#endif
#ifdef SHUTTER_MAIN_MENU_SUPPORT
//RES_ADD_STRING(TXT_SET_MAINMENU_SHUTTER,"Shutter")
#endif
#ifdef CHARIOT_MAIN_MENU_SUPPORT
//RES_ADD_STRING(TXT_SET_MAINMENU_CHARIOT,"Chariot")
#endif
#ifdef SPHERE_MAIN_MENU_SUPPORT
//RES_ADD_STRING(TXT_SET_MAINMENU_SPHERE,"Sphere menu")
#endif
#ifdef CYLINDER_MAIN_MENU_SUPPORT
RES_ADD_STRING(TXT_SET_MAINMENU_CYLINDER,"Cylinder menu")
#endif

#if defined(PDA_UI_MAINMENU_SUPPORT_SELECT_ANIM)
RES_ADD_STRING(TXT_SET_MAINMENU_SELECT_STYLE,"Mainmenu select style")
RES_ADD_STRING(TXT_SET_MAINMENU_SELECT_STATIC,"Static")
RES_ADD_STRING(TXT_SET_MAINMENU_SELECT_ROUNDLIGHT,"Roundlight")
RES_ADD_STRING(TXT_SET_MAINMENU_SELECT_FIRE,"Fire")
RES_ADD_STRING(TXT_SET_MAINMENU_SELECT_LIGHTING,"Lighting")
RES_ADD_STRING(TXT_SET_MAINMENU_SELECT_WATER,"Water")
RES_ADD_STRING(TXT_SET_MAINMENU_SELECT_SNOW,"SNOW")
#endif
#if defined(PDA_UI_SUPPORT_MANIMENU_GO)
RES_ADD_STRING(TXT_SET_MAINMENU_GO,"GO menu")
#ifdef GO_BINARY_STAR_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_BINARY_STAR,"Binary star")
#endif
#ifdef GO_SHUTTER_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_SHUTTER,"Shutter")
#endif
#ifdef GO_SPHERE_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_SPHERE,"Sphere")
#endif
#ifdef GO_CYLINDER_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_CYLINDER,"Cylinder")
#endif
#ifdef GO_SLOPE_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_SLOPE,"Slope")
#endif
#ifdef GO_WHEEL_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_WHEEL,"Wheel")
#endif
#ifdef GO_OCEANWAVE_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_OCEANWAVE,"Oceanwave")
#endif
#ifdef GO_PEGTOP_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_PEGTOP,"Pegtop")
#endif
#ifdef GO_TURNTABLE_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_TURNTABLE,"Turntable")
#endif
#ifdef GO_BOXROT_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_BOXROT,"Boxrot")
#endif
#ifdef GO_ICONBOXROT_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_ICONBOXROT,"Iconboxrot")
#endif
#ifdef GO_BOOKPAGE_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_BOOKPAGE,"Bookpage")
#endif
#ifdef GO_MIDROTATE_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_MIDROTATE,"Midrotate")
#endif
#ifdef GO_SMALLITEMS_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_SMALLITEMS,"Smallitems")
#endif
//#ifdef GO_CLASSIC_MAIN_MENU_SUPPORT
//    RES_ADD_STRING(TXT_SET_MAINMENU_CLASSIC,"Classic")         //replaced by common ID TXT_COMMON_CLASSIC
//#endif
    RES_ADD_STRING(TXT_SET_MAINMENU_SELECT_RANDOM,"Random")
#ifdef GO_CONSTICK_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_CONSTICK,"Constick")
#endif
#ifdef GO_SYMMETRY_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_SYMMETRY,"Symmetry")
#endif
#ifdef GO_BENZITEM_MAIN_MENU_SUPPORT
    RES_ADD_STRING(TXT_SET_MAINMENU_BENZITEM,"Benzitem")
#endif
#endif
//RES_ADD_STRING(TXT_SET_MAINMENU_TITLE_ICON,"Title block menu")
//RES_ADD_STRING(TXT_SET_IDLE_STYLE,"Switching system")    //replaced by common ID TXT_IDLE_SWITH

#ifndef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_SET_IDLE_COMMON,"Common style")
RES_ADD_STRING(TXT_SET_IDLE_SMART,"Smart style")
RES_ADD_STRING(TXT_SET_IDLE_WIDGET,"Widget style")
#endif

//RES_ADD_STRING(TXT_SET_IDLE_GRID,"GRID style")  //replaced by local ID TXT_SET_IDLE_WIDGET

RES_ADD_STRING(TXT_SET_WALLPAPER_MORE,"More wallpaper")

#ifdef MMI_VIDEOWALLPAPER_SUPPORT
RES_ADD_STRING(TXT_SET_WALLPAPER_VIDEO,"Video wallpaper")
RES_ADD_STRING(TXT_SET_WALLPAPER_VIDEO_SWITCH,"Open video wallpaper")
RES_ADD_STRING(TXT_SET_WALLPAPER_VIDEO_LIST,"Customized list(limited to 10)")
RES_ADD_STRING(TXT_SET_WALLPAPER_VIDEO_LIST_FULL,"Customized list is full, not all files are added")
RES_ADD_STRING(TXT_SET_SETAS_WALLPAPER_VIDEO_LIST_FULL,"Video wallpaper list is full")
#endif

#ifdef SLIDESHOW_WALLPAPER_SUPPORT
RES_ADD_STRING(TXT_SET_SLIDESHOW_NO_FILE,"Photos Dir No Valid File")
RES_ADD_STRING(TXT_SET_WALLPAPER_SLIDESHOW,"Slideshow wallpaper")
RES_ADD_STRING(TXT_SET_SLIDESHOW_TIME_INTERVAL,"Time Interval")
#endif
//RES_ADD_STRING(TXT_SET_WAITING,"Wait for setting")      //case3：defined but not used

RES_ADD_STRING(TXT_SET_RING_TKEY_TONE,"Touch tones")

RES_ADD_STRING(TXT_SET_NETWORK_REGISTERING,"Network registering")
#ifdef SCREENSAVER_SUPPORT
RES_ADD_STRING(TXT_SET_SCREENSAVER_STAR,"Star")

RES_ADD_STRING(TXT_SET_SCREENSAVER_SNAKE,"Snake")

RES_ADD_STRING(TXT_SET_SCREENSAVER_SEED,"Seed")
#endif

RES_ADD_STRING(TXT_SET_POWER_MANAGEMENT,"Power management")

#ifdef MMI_POWER_SAVING_MODE_SUPPORT
RES_ADD_STRING(TXT_SET_POWER_SAVING_MODE,"Power Saving Mode")    //replaced by common ID TXT_ENERGY_SAVING

//RES_ADD_STRING(TXT_POWER_SAVING_LEFT,"power saving schedule setting")         //case3：defined but not used

RES_ADD_STRING(TXT_POWER_SAVING_LEFT_TWE,"20% battery left")

RES_ADD_STRING(TXT_POWER_SAVING_LEFT_FOURTY,"40% battery left")

RES_ADD_STRING(TXT_POWER_SAVING_LEFT_SIXTY,"60% battery left")

RES_ADD_STRING(TXT_SET_POWER_SAVING,"Power Saving")

RES_ADD_STRING(TXT_POWER_SAVING_MODE_SCHEDULE,"Power saving mode schedule")

RES_ADD_STRING(TXT_POWER_SAVING_MODE_FORBIDDEN_BG_DATA,"Forbidden Bg Data")
RES_ADD_STRING(TXT_POWER_SAVING_MODE_FORBIDDEN_BG_DATA_EX,"close BG APP")

RES_ADD_STRING(TXT_POWER_SAVING_MODE_FORBIDDEN_WLAN,"Forbidden WLAN")
RES_ADD_STRING(TXT_POWER_SAVING_MODE_FORBIDDEN_WLAN_EX,"close WIFI when not used")

RES_ADD_STRING(TXT_POWER_SAVING_MODE_FORBIDDEN_BLUETOOTH,"Forbidden BLUETOOTH")
RES_ADD_STRING(TXT_POWER_SAVING_MODE_FORBIDDEN_BLUETOOTH_EX,"close BT when not used")

RES_ADD_STRING(TXT_POWER_SAVING_MODE_FORBIDDEN_ANIM,"Forbidden ANIM")
RES_ADD_STRING(TXT_POWER_SAVING_MODE_FORBIDDEN_ANIM_EX,"close animation")

RES_ADD_STRING(TXT_POWER_SAVING_MODE_FORBIDDEN_SCREEN_SAVER,"SCREEN SAVER")
RES_ADD_STRING(TXT_POWER_SAVING_MODE_FORBIDDEN_SCREEN_SAVER_EX,"close screen saver")

RES_ADD_STRING(TXT_POWER_SAVING_MODE_KEYPAD_SETTING,"Keypad Light")
RES_ADD_STRING(TXT_POWER_SAVING_MODE_KEYPAD_SETTING_EX,"close keypad light")

//RES_ADD_STRING(TXT_POWER_SAVING_MODE_WALLPAPER_SETTING,"wallpaper anim")       //replaced by common ID TXT_COMMON_SET_WALLPAPER
RES_ADD_STRING(TXT_POWER_SAVING_MODE_WALLPAPER_SETTING_EX,"close anim wallpaper")

//RES_ADD_STRING(TXT_POWER_SAVING_MODE_ALERT_SETTING,"Alert Ring")    //replaced by common ID TXT_TONE
RES_ADD_STRING(TXT_POWER_SAVING_MODE_ALERT_SETTING_EX,"close alert ring")

RES_ADD_STRING(TXT_ENVSET_QUERY,"Power saving mode is open,change the mode will conflict,sure to change the mode?")

//RES_ADD_STRING(TXT_OPEN_POWER_SAVING_QUERY,"Open power saving mode will close the data transfer,sure to open it?")       //case3：defined but not used

//RES_ADD_STRING(TXT_CHR_OPEN_POWER_SAVING_QUERY1,"The Capacity remains: ") //replaced by common ID TXT_BTRY_CAP_LABEL_TEXT

RES_ADD_STRING(TXT_CHR_OPEN_POWER_SAVING_QUERY2,",sure to open the power saving mode?")

RES_ADD_STRING(TXT_SET_POWER,"Capacity")

RES_ADD_STRING(TXT_SET_START_POWER_SAVING_AS_SETTING,"start power saving mode")

RES_ADD_STRING(TXT_SET_POWER_SAVING_SEETING,"power saving setting")
RES_ADD_STRING(TXT_SET_POWER_SAVING_IS_STARTED,"Power saving is started")
RES_ADD_STRING(TXT_SET_POWER_SAVING_IS_CLOSED,"Power saving is closed")
#endif
//RES_ADD_STRING(TXT_MMISET_3D_STYLE_MAINMENU_NONE,"Normal")       //replaced by common ID TXT_COMMON_COMMON_NORMAL

RES_ADD_STRING(TXT_MMISET_3D_STYLE_MAINMENU_WRAPBAND,"Wrapband")

RES_ADD_STRING(TXT_MMISET_3D_STYLE_MAINMENU_ROTATE3D,"Rotate 3D")

RES_ADD_STRING(TXT_MMISET_3D_STYLE_MAINMENU_DISTORTMOVE,"Distort move")

RES_ADD_STRING(TXT_MMISET_3D_STYLE_MAINMENU_SLIDEMOVE,"Slide move")

RES_ADD_STRING(TXT_MMISET_3D_STYLE_MAINMENU_ROTATEMOVE,"Rotate move")

RES_ADD_STRING(TXT_MMISET_3D_STYLE_MAINMENU_LUCKYBOARD,"Lucky board")

RES_ADD_STRING(TXT_MMISET_3D_STYLE_MAINMENU_MAGICMOVE,"Magic move")

//RES_ADD_STRING(TXT_MMISET_3D_STYLE_G_SENSOR_NONE,"Close")      //replaced by common ID TXT_CLOSE

//RES_ADD_STRING(TXT_MMISET_3D_STYLE_G_SENSOR_DEFAULT,"Default")   //replaced by common ID TXT_SET_3D_STYLE_SCREEN_DEFAULT

//RES_ADD_STRING(TXT_MMISET_3D_STYLE_G_SENSOR_ROTATE3D,"Fade")  //replaced by common ID TXT_COMM_FADE_INOUT

//RES_ADD_STRING(TXT_SET_3D_STYLE,"3D style")

RES_ADD_STRING(TXT_SET_3D_STYLE_MAINMENU,"3D style mainmenu")

#ifdef SET_3D_STYLE_SUPPORT
RES_ADD_STRING(TXT_SET_3D_STYLE_SCREEN,"3D style screen")
#endif
//RES_ADD_STRING(TXT_SET_3D_STYLE_SCREEN_CLOSE,"Close") // 关闭     //replaced by common ID TXT_COMMON_COMMON_NORMAL
RES_ADD_STRING(TXT_SET_3D_STYLE_SCREEN_DEFAULT,"Default") // 缺省
//RES_ADD_STRING(TXT_SET_3D_STYLE_SCREEN_AUTO,"Auto") // 自动  //replaced by common ID TXT_AUTO
RES_ADD_STRING(TXT_SET_3D_STYLE_SCREEN_SLIDE_MOVE,"Slide screen") // 滑入滑入滑出

RES_ADD_STRING(TXT_SET_3D_STYLE_SCREEN_SLIDE,"Push screen") // 水平推送
RES_ADD_STRING(TXT_SET_3D_STYLE_SCREEN_ZOOM,"Zoom inout")  // 层出迭见
//RES_ADD_STRING(TXT_SET_3D_STYLE_SCREEN_FADE,"Fade screen") // 淡入淡出  //replaced by common ID TXT_COMM_FADE_INOUT
RES_ADD_STRING(TXT_SET_3D_STYLE_SCREEN_ROLL,"Roll screen") // 3D翻转

#ifdef SET_3D_STYLE_SUPPORT
RES_ADD_STRING(TXT_SET_3D_STYLE_SCREEN_FADE_INOUT,"Fade InOut") // 渐隐渐现  //replaced by common ID TXT_COMM_FADE_INOUT
RES_ADD_STRING(TXT_SET_3D_STYLE_SCREEN_VERT_INOUT,"Vert InOut") // 自由落体
#endif

//RES_ADD_STRING(TXT_SET_3D_OTHER,"3D other")       //replaced by common ID TXT_TOOLS_OTHERS

RES_ADD_STRING(TXT_MMISET_3D_STYLE_LIST_ROLL,"3D style list roll")

//RES_ADD_STRING(TXT_MMISET_3D_STYLE_IDLE_ROLL,"3D style idle roll")      //case3：defined but not used
#ifdef MMI_RES_ORIENT_BOTH // 说明支持横竖屏切换
RES_ADD_STRING(TXT_MMISET_3D_STYLE_GSENSOR_ROLL,"G-Sensor switch")
#endif
//RES_ADD_STRING(TXT_MMISET_3D_STYLE_SCREEN_ROLL,"3D style screen roll")      //case3：defined but not used
#ifdef SCREENSAVER_SUPPORT
RES_ADD_STRING(TXT_SET_SCREENSAVER_MATCH,"Match")
RES_ADD_STRING(TXT_SET_SCREENSAVER_SEA,"Sea")
#endif
RES_ADD_STRING(TXT_SET_INVALID_CUSTOM_WORD,"Invalid custom word")

RES_ADD_STRING(TXT_SET_ORIGIN_REPLY_CALL,"Reply call")
#ifdef MMIMMS_SMS_IN_1_SUPPORT
RES_ADD_STRING(TXT_SET_ORIGIN_REPLY_MESSAGE,"Reply Message")
#endif
RES_ADD_STRING(TXT_SET_ORIGIN_REPLY_SMS,"Reply SMS")

RES_ADD_STRING(TXT_SET_ORIGIN_REPLY_MMS,"Reply MMS")

//RES_ADD_STRING(TXT_SET_ORIGIN_REPLY_WAP,"Reply WAP")
//#if defined ( MULTI_THEME_SUPPORT )|| defined ( MMI_VCALENDAR_SUPPORT )
//RES_ADD_STRING(TXT_SET_THEME,"Theme")
//#endif
#if defined ( MULTI_THEME_SUPPORT )
RES_ADD_STRING(TXT_SET_THEME_1,"Theme 1")
RES_ADD_STRING(TXT_SET_THEME_2,"Theme 2")
#endif
RES_ADD_STRING(TXT_SET_SETTING_ACTIVATED,"Setting activated")

RES_ADD_STRING(TXT_SET_SETTING_CANCELED,"Setting canceled")

RES_ADD_STRING(TXT_SET_SETTING_FAIL,"Setting failed")    //replaced by common ID TXT_COMMON_SETTING_FAIL

RES_ADD_STRING(TXT_SET_SETTING_CANCEL_FAIL,"Setting cancel failed")

//RES_ADD_STRING(TXT_SET_NETWORK_CONNECT_FAIL,"Network connect fail")  //replaced by common ID TXT_COMMON_NETWORK_CONNECT_FAIL

RES_ADD_STRING(TXT_SET_DATE_MDY,"Month-day-year")

RES_ADD_STRING(TXT_SET_TODAY_SCHEDULE,"Today schedule")

RES_ADD_STRING(TXT_SET_FUNCKEY_SL,"Set left function key")

RES_ADD_STRING(TXT_SET_FUNCKEY_RIGHT,"Set right function key")
#if defined(MMI_PDA_SUPPORT)
RES_ADD_STRING(TXT_SET_IDLE_SHORTCUT,"Idle shortcut")
#endif
RES_ADD_STRING(TXT_SET_IDLE_SHORTCUT1,"Shortcut 1")
RES_ADD_STRING(TXT_SET_IDLE_SHORTCUT2,"Shortcut 2")
RES_ADD_STRING(TXT_SET_IDLE_SHORTCUT3,"Shortcut 3")
RES_ADD_STRING(TXT_SET_IDLE_SHORTCUT4,"shortcut 4")
RES_ADD_STRING(TXT_SET_IDLE_SHORTCUT5,"shortcut 5")

//RES_ADD_STRING(TXT_SET_TIME_1M,"1 min")  //replaced by common ID TXT_COMM_1_MINUTE

//RES_ADD_STRING(TXT_SET_TIME_5M,"5 min")  //replaced by common ID TXT_COMM_5_MINUTES
RES_ADD_STRING(TXT_SET_ANIMATION,"Animation")
RES_ADD_STRING(TXT_SET_RED_KEYLOCK,"Red Key Locks Keyboard")
//RES_ADD_STRING(TXT_DISC_PC_LINK,"Please disconnect PC link")         //case3：defined but not used
#ifdef MMI_MULTISIM_COLOR_SUPPORT
RES_ADD_STRING(TXT_SET_SIM_COLOR,"TXT_SET_SIM_COLOR")
#endif
RES_ADD_STRING(TXT_SET_STREAMING,"Streaming")
#if defined(MMIPB_SIMDN_SUPPORT) && defined(MMI_DUALSIM_CALL_DIVERT_SUPPORT)
//RES_ADD_STRING(TXT_SET_DUALSIM_DIVERT,"Set Dual SIM Call Divert")
RES_ADD_STRING(TXT_SET_DUALSIM_DIVERT_FAIL_PROMPT,"set failed, Please check ")
#endif
#ifdef VT_SUPPORT
RES_ADD_STRING(TXT_SET_VIDEOPHONE,"Videophone setting")
RES_ADD_STRING(TXT_SET_VT_FALLBACK_HANDLE,"Fallback handle mode") //已有
RES_ADD_STRING(TXT_SET_SPCIFY_SAVE_PATH,"Specify save path") //“指定保存文件位置”
RES_ADD_STRING(TXT_SET_VT_REPLACE_IMAGE,"Specify replace pic") //“指定替代画面”
RES_ADD_STRING(TXT_SET_VT_LOCAL_VIDEO,"Local video setting") //“本地视频设置”
RES_ADD_STRING(TXT_OPTION_FALLBACK_QUERY,"always user query") //已有
RES_ADD_STRING(TXT_OPTION_FALLBACK_QUIT,"auto quit")  //已有
RES_ADD_STRING(TXT_OPTION_FALLBACK_AUTO,"auto fallback") //已有

RES_ADD_STRING(TXT_OPTION_SPECIFY,"Specify") //“指定”
RES_ADD_STRING(TXT_SET_VT_REPLACE_LOCAL_IMAGE,"Local replace pic") //“本端替代图片”
RES_ADD_STRING(TXT_SET_VT_REPLACE_REMOTE_IMAGE,"Remote replace pic") //“远端替代图片”
RES_ADD_STRING(TXT_SET_VT_REPLACE_DEFAULT,"Default resource") //“默认资源”
RES_ADD_STRING(TXT_SET_VT_ONE_TIME_RING,"Accept voice, play one time ring") //“语音接听一次振铃”
//RES_ADD_STRING(TXT_SET_VT_REMOTE_SHUTDOWN_CAMERA,"Remote shutdown camera") //“对方关闭摄像头”  //replaced by common ID TXT_COMM_REMOTE_CAMERA_OFF
RES_ADD_STRING(TXT_SET_VT_DISPLAY_REMOTE_REPLACE_IMAGE,"Display remote replace image") //“显示远端替代图像”
RES_ADD_STRING(TXT_SET_VT_DISPLAY_REMOTE_SENDING_IMAGE,"Display remote send image") //“显示对方传输图像”

#endif
#if defined FONT_TYPE_SUPPORT_VECTOR && defined FILE_FONT_SUPPORT
RES_ADD_STRING(TXT_SET_FONT,"Font settings")
RES_ADD_STRING(TXT_SET_DEFAULT_FONT,"Default font")
RES_ADD_STRING(TXT_SET_FONT_MORE,"More font")
RES_ADD_STRING(TXT_SET_FONT_SUCCEED,"Set font succeed!")
RES_ADD_STRING(TXT_SET_FONT_FAILED,"Set font failed!")
#endif
#ifdef LCD_SLIDE_SUPPORT
RES_ADD_STRING(TXT_SET_SLIDE_TONE_ENABLE,"Slide on")
RES_ADD_STRING(TXT_SET_SLIDE_TONE_DISABLE,"Slide off")
RES_ADD_STRING(TXT_SET_RING_SLIDE_TONE,"Slide tone")
RES_ADD_STRING(TXT_SET_SLIDE_OPERATION,"Slide operation")
RES_ADD_STRING(TXT_SET_SLIDE_OPEN,"Slide open")
RES_ADD_STRING(TXT_SET_SLIDE_CLOSE,"Slide close")
RES_ADD_STRING(TXT_SET_KEYLOCK_SWITCH,"Keylock switch")
RES_ADD_STRING(TXT_SET_RECEIVE_PHONE,"Receive phone")
RES_ADD_STRING(TXT_SET_REJECT_PHONE,"Reject phone")
RES_ADD_STRING(TXT_SET_STOP_OPERATION,"Stop operation")
RES_ADD_STRING(TXT_SET_CONTINUE_OPERATION,"Continue operation")
RES_ADD_STRING(TXT_SET_KEYLOCK_SWITCH_ON,"Switch on keylock")
RES_ADD_STRING(TXT_SET_KEYLOCK_SWITCH_OFF,"Switch off keylock")
#endif

RES_ADD_STRING(TXT_SET_ENHANCE_RING,"Enhance ring")

#ifdef MOTION_SENSOR_TYPE
RES_ADD_STRING(TXT_SET_SENSOR_RESPONDENT,"Direction sensor")
RES_ADD_STRING(TXT_SET_SENSOR_LANDSCAPE,"Screen roll display")
RES_ADD_STRING(TXT_SET_SENSOR_CALL_SILENCE,"Tone switch")
RES_ADD_STRING(TXT_SET_SENSOR_REPLACE_WALLPAPER,"Wallpaper switch")
RES_ADD_STRING(TXT_SET_SENSOR_NEXT_SONG,"Song switch")
RES_ADD_STRING(TXT_SET_SENSOR_VIDEO_FULLSCREEN,"Video screen switch")
#endif
//RES_ADD_STRING(TXT_MMISET_OPEN,"Open")    //replaced by common ID TXT_COMMON_ENABLE_ON
//RES_ADD_STRING(TXT_MMISET_CLOSE,"Close")       //replaced by common ID TXT_CLOSE
//RES_ADD_STRING(TXT_SET_UPLMN_SETTING,"UPLMN") //MS00216980 cheney //replaced by common ID TXT_COMM_UPLMN_SETTING

RES_ADD_STRING(TXT_SET_RING_TYPE,"Ring type")
RES_ADD_STRING(TXT_SET_RING_OTHER,"Other ring set")

//RES_ADD_STRING(TXT_RING1,"Ring1")        //replaced by common ID TXT_COMMON_RING_RING1
//RES_ADD_STRING(TXT_RING2,"Ring2")        //replaced by common ID TXT_COMMON_RING_RING2
#ifndef MMI_LOW_MEMORY_RING
RES_ADD_STRING(TXT_RING3,"Ring3")
RES_ADD_STRING(TXT_RING4,"Ring4")
RES_ADD_STRING(TXT_RING5,"Ring5")
RES_ADD_STRING(TXT_RING6,"Ring6")
RES_ADD_STRING(TXT_RING7,"Ring7")
RES_ADD_STRING(TXT_RING8,"Ring8")
#endif
RES_ADD_STRING(TXT_SET_SIM1_RING_CALL_TYPE,"SIM1 Call alert")
RES_ADD_STRING(TXT_SET_SIM2_RING_CALL_TYPE,"SIM2 Call alert")
#if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_SET_SIM3_RING_CALL_TYPE,"SIM3 Call alert")
#if defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_SET_SIM4_RING_CALL_TYPE,"SIM4 Call alert")
#endif
#endif

RES_ADD_STRING(TXT_SET_SIM1_RING_MSG_TYPE,"SIM1 Message alert")
RES_ADD_STRING(TXT_SET_SIM2_RING_MSG_TYPE,"SIM2 Message alert")
#if defined(MMI_MULTI_SIM_SYS_TRI) || defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_SET_SIM3_RING_MSG_TYPE,"SIM3 Message alert")
#if defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_SET_SIM4_RING_MSG_TYPE,"SIM4 Message alert")
#endif
#endif


//RES_ADD_STRING(TXT_MMISET_CALL_MORE,"More")          //case3：defined but not used
//RES_ADD_STRING(TXT_CALL_USER_DEFINED,"Customized")  //replaced by common ID TXT_EXPORT_LOC_CUSTOM

RES_ADD_STRING(TXT_SERCURITY_MODIFY_PIN2,"Modify PIN2")
RES_ADD_STRING(TXT_SERCURITY_PHONE_LOC,"Lock Phone")
RES_ADD_STRING(TXT_SERCURITY_MODIFY_PHONE_PASSWORD,"Modify Phone Password")
RES_ADD_STRING(TXT_SERCURITY_MODIFY_PIN,"Modify PIN")

//RES_ADD_STRING(TXT_SETING_MAGICVOICE,"Magic Voice")       //case3：defined but not used
#ifdef SCREENSAVER_SUPPORT
RES_ADD_STRING(TXT_SET_SCREENSAVER_PICTURE,"Customized picture")
RES_ADD_STRING(TXT_SET_SCREENSAVER_ANIMATION,"Customized animation")
#endif
#if defined(MMI_UPDATE_TIME_SUPPORT)
RES_ADD_STRING(TXT_SET_UPDATE_TIME_SET,"Update time setting")
RES_ADD_STRING(TXT_SET_AUTO_UPDATE_TIME,"Auto update time")
//nhl modify the auto time
RES_ADD_STRING(TXT_OPEN_AUTO_UPDATE_TIME_QUERY,"Confirm open auto update time?")
RES_ADD_STRING(TXT_OPEN_AUTO_UPDATE_TIME_PROMPT,"Auto update time when attaching GPRS/connecting internet")
//RES_ADD_STRING(TXT_SET_UPDATE_TIME_WHEN_PHONE_STARTUP,"Auto update time when phone startup")       //case3：defined but not used
RES_ADD_STRING(TXT_SET_DTAE_AND_TIME_UPDATED,"Date and time updated")
RES_ADD_STRING(TXT_SET_UPDATE_SYSTEM_TIME,"Manual update  time")
RES_ADD_STRING(TXT_SET_UPDATE_TIME_HELP,"Update time help")
RES_ADD_STRING(TXT_SET_UPDATE_TIME_HELP_STR,"Help:  (1) update time information is depended on the operator's signals, \
some maybe have no time information;for details,please consult the local operator.                    (2) It will Auto update time when  \
attaching GPRS after turn on its switch.                                        (3) Manual update time means you get the network time manually.")
//RES_ADD_STRING(TXT_GET_NETTIME_FAIL,"Get server time fail")         //case3：defined but not used
//RES_ADD_STRING(TXT_GPRS_ACTIVE_FAIL,"Get Gprs active fail")        //case3：defined but not used
RES_ADD_STRING(TXT_CONNECT_SERVER_FAIL,"Connect server fail")
//RES_ADD_STRING(TXT_GET_NETTIME_TIMEOUT,"Get net time time-out")        //case3：defined but not used
//RES_ADD_STRING(TXT_CONNECT_NET_GET_TIME,"Connect internet update system time?")         //case3：defined but not used
//RES_ADD_STRING(TXT_UPDATE_FAIL_CONNECT_NET_GET_TIME,"Update fail.Do you connect internet update time?")       //case3：defined but not used
//RES_ADD_STRING(TXT_SET_HOME_CITY,"Set home city")         //case3：defined but not used
#endif

#if defined(MMI_BLACKLIST_SUPPORT)
//RES_ADD_STRING(TXT_SET_BLACKLIST,"Blacklist")
// RES_ADD_STRING(TXT_SET_BLACKLIST_LIST,"Blacklist list")
RES_ADD_STRING(TXT_SET_BLACKLIST_SETTING,"Blacklist setting")
RES_ADD_STRING(TXT_SET_BLACKLIST_TYPE_AUDIOCALL,"Block audio call")
RES_ADD_STRING(TXT_SET_BLACKLIST_TYPE_VEDIOCALL,"Block video call")
RES_ADD_STRING(TXT_SET_BLACKLIST_TYPE_MESSAGE,"Block Message")
RES_ADD_STRING(TXT_SET_NEW_BLACKLIST,"New blacklist")
RES_ADD_STRING(TXT_SET_BLACKLIST_FULL,"Blacklist full")
RES_ADD_STRING(TXT_SET_BLACKLIST_INPUT_NUM,"Please input number")
RES_ADD_STRING(TXT_SET_EDIT_BLACKLIST,"Edit blacklist")
//RES_ADD_STRING(TXT_SET_BLACKLIST_IF_DEL,"Delete?")    //replaced by common ID TXT_DELETE_QUERY
//RES_ADD_STRING(TXT_SET_BLACKLIST_IF_DELALL,"Delete all?")    //replaced by common ID TXT_DELETE_ALL_QUERY
RES_ADD_STRING(TXT_SET_BLACKLIST_BEYOND_MAX_NUM,"Beyond blacklist max num")
#if defined(MMI_WHITELIST_SUPPORT)
RES_ADD_STRING(TXT_SET_WHITELIST_LIST,"Whitelist numbers")
RES_ADD_STRING(TXT_SET_WHITELIST_SETTING,"Whitelist settings")
RES_ADD_STRING(TXT_SET_WHITELIST_TYPE_AUDIOCALL,"Allow audio call")
RES_ADD_STRING(TXT_SET_WHITELIST_TYPE_VEDIOCALL,"Allow video call")
RES_ADD_STRING(TXT_SET_WHITELIST_TYPE_MESSAGE,"Allow Message")
RES_ADD_STRING(TXT_SET_NEW_WHITELIST,"New whitelist")
RES_ADD_STRING(TXT_SET_WHITELIST_FULL,"Whitelist full")
RES_ADD_STRING(TXT_SET_WHITELIST_INPUT_NUM,"Please input number")
RES_ADD_STRING(TXT_SET_EDIT_WHITELIST,"Edit whitelist")
//RES_ADD_STRING(TXT_SET_BLACKLIST_IF_DEL,"Delete?")    //replaced by common ID TXT_DELETE_QUERY
//RES_ADD_STRING(TXT_SET_BLACKLIST_IF_DELALL,"Delete all?")    //replaced by common ID TXT_DELETE_ALL_QUERY
RES_ADD_STRING(TXT_SET_WHITELIST_BEYOND_MAX_NUM,"Beyond whitelist max num")
RES_ADD_STRING(TXT_SET_WHITELIST_NUM_EXIST,"Number exist")
RES_ADD_STRING(TXT_ENTER_WHITELIST_NUM_FIRST, "Please enter a whitelist number first")
#endif
RES_ADD_STRING(TXT_SET_BLACKLIST_NUM_EXIST,"Number exist")
#endif
//RES_ADD_STRING(TXT_SET_BLACKLIST_NEW,"New")    //replaced by common ID TXT_NEW
#if defined ( MMI_SIM_LOCK_SUPPORT ) ||defined( MMI_BLACKLIST_SUPPORT )
RES_ADD_STRING(TXT_SET_BLACKLIST_CONTACT,"Import contacts")
#endif

#ifdef MMI_INDIAN_SOS_SUPPORT
RES_ADD_STRING(TXT_SET_FROM_CONTACT,"Import contacts")
#endif

#ifdef MOTION_SENSOR_TYPE
RES_ADD_STRING(TXT_SET_SENSOR_90,"90")
RES_ADD_STRING(TXT_SET_SENSOR_180,"180")
RES_ADD_STRING(TXT_SET_SENSOR_270,"270")//maryxiao cr227614
#endif
#ifdef MMI_KEY_LOCK_EFFECT_SUPPORT
RES_ADD_STRING(TXT_SET_KEY_LOCK_EFFECT_TITLE, "Screen lock style")
RES_ADD_STRING(TXT_SET_KEY_LOCK_EFFECT_PREFIX, "Screen lock style")
//RES_ADD_STRING(TXT_SET_KEY_LOCK_LONG_TP, "Long TpDown Unlock")  //replaced by common ID TXT_KEYLOCK_UNLOCK_TIP
RES_ADD_STRING(TXT_SET_KEYLOCK_TYPE_SELECT,"Select KeyLock Type")
#ifdef MMI_KEY_LOCK_EFFECT_TYPE1_SUPPORT
    RES_ADD_STRING(TXT_SET_KEY_LOCK_SLIDEDOWN, "Slide Down Unlock")
#endif
#ifdef MMI_KEY_LOCK_EFFECT_TYPE2_SUPPORT
    RES_ADD_STRING(TXT_SET_KEY_LOCK_SLIDE_SCROLLKEY, "Slide ScrollKey Unlock")
#endif
#ifdef MMI_KEY_LOCK_EFFECT_TYPE3_SUPPORT
    RES_ADD_STRING(TXT_SET_KEY_LOCK_SMART_SLIDEDOWN, "Smart Slide Down Unlock")
#endif
#ifdef MMI_KEY_LOCK_EFFECT_TYPE4_SUPPORT
    RES_ADD_STRING(TXT_SET_KEY_LOCK_SLIDE_IPHONE, "Iphone Style Slide Unlock")
#endif
#ifdef MMI_KEY_LOCK_EFFECT_TYPE5_SUPPORT
    RES_ADD_STRING(TXT_SET_KEY_LOCK_GRAPHIC, "Draw Graphic Unlock")
RES_ADD_STRING(TXT_SET_USE_PATTERN_UNLOCK,"Use Pattern unlock")
RES_ADD_STRING(TXT_SET_CHANGE_PATTERN_UNLOCK,"Change screen lock")
RES_ADD_STRING(TXT_SET_VISIABLE_PATTERN_UNLOCK,"Visible pattern lock")
#endif
#ifdef MMI_KEY_LOCK_EFFECT_TYPE6_SUPPORT
    RES_ADD_STRING(TXT_SET_KEY_LOCK_ICON_RING, "Drag Icon Or Ring Unlock")
#endif

#ifdef  MMI_KEY_LOCK_FRUIT_SPLIT_SUPPORT
RES_ADD_STRING(TXT_SET_KEY_LOCK_FRUIT_SPLIT, "Split Fruit Unlock")
#endif
//michael wang kl
#ifdef MMI_KEY_LOCK_DOUBLE_CIRCLE_SUPPORT
RES_ADD_STRING(TXT_SET_KEY_LOCK_DOUBLE_CIRCLE, "Double Circle Unlock")
#endif
//spec
#ifdef  MMI_KEY_LOCK_SPEC_DOUBLE_CIRCLE_SUPPORT
RES_ADD_STRING(TXT_SET_KEY_LOCK_DOUBLE_CIRCLE_SPEC, "SPEC Double Circle Unlock")
#endif
//michael wang

#ifdef MMI_KEY_LOCK_EFFECT_PSW_SUPPORT
RES_ADD_STRING(TXT_SET_KL_PSW_LOCK,"Password lock")
//RES_ADD_STRING(TXT_SET_KL_PSW_SET,"Set password")          //case3：defined but not used
RES_ADD_STRING(TXT_SET_KL_PSW_INPUT,"Enter a password")
RES_ADD_STRING(TXT_SET_KL_PSW_TURN_OFF,"Turn password off")
//RES_ADD_STRING(TXT_SET_KL_PSW_TURN_ON,"Turn password on")       //case3：defined but not used
RES_ADD_STRING(TXT_SET_KL_PSW_CHANGE,"Change password")
RES_ADD_STRING(TXT_SET_KL_PSW_WAITING_TIME,"Require password")
RES_ADD_STRING(TXT_SET_KL_PSW_ERASE_DATA,"Earse data")

#endif
#endif
//]]define string infomation

RES_ADD_STRING(TXT_INPUT_PHONE_PASSWORD,"please input phone password(4-8)")
//RES_ADD_STRING(TXT_INPUT_ORIGIN_PASSWORD,"please input old password")         //case3：defined but not used

//RES_ADD_STRING(TXT_ADD_NEW,"Add")    //replaced by common ID TXT_ADDNEW
#ifdef MMI_SIM_LOCK_SUPPORT
RES_ADD_STRING(TXT_SET_SIM_LOCK,"SIM Lock")
RES_ADD_STRING(TXT_SET_SIM_LOCK_INFO,"SIM Lock Info")
RES_ADD_STRING(TXT_SET_SIM_LOCK_SWITCH,"SIM Lock Switch")
RES_ADD_STRING(TXT_SET_SIM_LOCK_NETWORK,"Network Lock")
RES_ADD_STRING(TXT_SET_SIM_LOCK_NETWORK_SUBSET,"Network Subset Lock")
RES_ADD_STRING(TXT_SET_SIM_LOCK_SP,"SP Lock")
RES_ADD_STRING(TXT_SET_SIM_LOCK_CORPORATE,"Corporate Lock")
RES_ADD_STRING(TXT_SET_SIM_LOCK_USER,"User Lock")
#elif defined(MMI_SIM_LOCK_TYPE2_SUPPORT) && defined(MMI_SIM_LOCK_TYPE2_UNLOCK_SUPPORT)
RES_ADD_STRING(TXT_SET_SIM_LOCK,"SIM Lock")
RES_ADD_STRING(TXT_SET_SIM_LOCK_INFO,"SIM Lock Info")
RES_ADD_STRING(TXT_SET_SIM_LOCK_UNLOCK,"UnLock SIM Lock")
RES_ADD_STRING(TXT_SET_SIM_LOCK_UNLOCKING,"UnLock SIM Lock?")
RES_ADD_STRING(TXT_SET_SIM_LOCK_UNLOCKIED,"SIM Lock is already unlocked!")
RES_ADD_STRING(TXT_SET_SIM_LOCK_NETWORK,"Network Lock")
#endif
#if defined ( MMI_PDA_SUPPORT ) ||defined( MMI_BLACKLIST_SUPPORT )
RES_ADD_STRING(TXT_LONGPOWER_OPTIONS,"Phone Option")
//RES_ADD_STRING(TXT_LONGPOWER_POWEROFF,"Power off")         //replaced by common ID TXT_POWER_OFF
#endif
#ifdef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_ENVSET_SILENTON,"Open slient mode")
RES_ADD_STRING(TXT_ENVSET_SILENTOFF,"Close slient mode")
RES_ADD_STRING(TXT_SET_FLY_MODEON,"Open flight mode")
RES_ADD_STRING(TXT_SET_FLY_MODEOFF,"Close flight mode")
#endif
#if defined ( MMI_PDA_SUPPORT ) ||defined( TOUCH_PANEL_SUPPORT )
RES_ADD_STRING(TXT_SET_AUTO_LOCK_SCREEN,"Auto screen lock")
#endif
RES_ADD_STRING(TXT_STATIC_WALLPAPER,"static wallpaper")
#ifdef LIVE_WALLPAPER_FRAMEWORK_SUPPORT
RES_ADD_STRING(TXT_DYNAMIC_WALLPAPER,"dynamic wallpaper")
#endif
//RES_ADD_STRING(TXT_MORE_WALLPAPER,"more picture")         //replaced by local ID TXT_MORE_PICTURE
//RES_ADD_STRING(TXT_MORE_VIDEO_WALLPAPER,"more video")      //case3：defined but not used
RES_ADD_STRING(TXT_MORE_PICTURE,"More pictures")
#ifdef MMI_BATTERY_PERCENT_IN_STATUSBAR
RES_ADD_STRING(TXT_SET_BATTERY_PERCENTAGE,"Battery Percentage")
#endif
#ifdef  PDA_UI_SUPPORT_LIGHT_SHADOW_RENDER
RES_ADD_STRING(TXT_SET_LIGHT_SHADOW_RENDER_ANIMATION,"Light Shadow Render")
RES_ADD_STRING(TXT_SET_GO_MENU_ANIMATION,"Go menu")
#endif
#endif
#ifdef MMI_VIDEOWALLPAPER_SUPPORT
RES_ADD_STRING(TXT_SET_QUERY_CLOSE_VIDEO_WALLPAPER,"Need to Close Video Wallpaper firstly, agree?")
#endif
#ifdef PDA_UI_SUPPORT_U_IDLE
RES_ADD_STRING(TXT_SET_QUERY_CLOSE_UIDLE_EFFECT,"Need to Close UIdle effect firstly, agree?")
#endif

#ifdef MENU_SWEETS_SUPPORT
RES_ADD_STRING(TXT_SET_MAINMENU_SWEETS,"Sweets")
#endif

//dong.chunguang@byd.com  add for system settings
RES_ADD_IMG(IMAGE_SETTING_CONNECTIVITY_ICON,"\\MMI_RES_##\\IMAG\\Connectivity_setting\\IMAGE_SETTINGS_CONNECTIVITY_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SETTING_PERSONALISATION_ICON,"\\MMI_RES_##\\IMAG\\Personalisation_setting\\IMAGE_SETTINGS_PERSONALIZATION_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SETTING_MS_ACCOUNT_ICON,"\\MMI_RES_##\\IMAG\\MS_account_setting\\IMAGE_SETTINGS_MICROSOFT_ACCOUNT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SETTING_TIME_LANGUAGE_ICON,"\\MMI_RES_##\\IMAG\\Time_language_setting\\IMAGE_SETTINGS_TIME_LANGUAGE_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SETTING_SECURITY_ICON,"\\MMI_RES_##\\IMAG\\Security_setting\\IMAGE_SETTINGS_SECURITY_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SETTING_STORAGE_ICON,"\\MMI_RES_##\\IMAG\\Storage_setting\\IMAGE_SETTINGS_STORAGE_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SETTING_OPERATOR_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SETTINGS_OPERATOR_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_SETTING_MYAPP_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SETTINGS_MYAPP_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_SUPPORT_CONTROLPANEL//Queen project no need
RES_ADD_IMG(IMAGE_SETTING_QUICK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SETTINGS_QUICK_SETTINGS_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_STRING(STR_SETT_LIST_SYSTEM_EXT01,"System")
RES_ADD_STRING(STR_ILIST_CONNECTIVITY_MENU,"Connectivity")
RES_ADD_STRING(STXT_CALL_SETTINGS,"Call settings")
RES_ADD_STRING(STXT_HEADER_CALL_SETTINGS,"Call settings")
RES_ADD_STRING(STR_OPT_NFS_NOTIFICATION_HDR,"Notifications")
RES_ADD_STRING(STR_OPT_NFS_NOTIFICATION,"Notifications")
RES_ADD_STRING(STXT_SIMATK_NOTES_ACTIVATION,"Conf. service actions")
RES_ADD_STRING(STR_ILIST_CALL_EXT01,"Calls")
RES_ADD_STRING(STR_ILIST_ALARM_CLOCK,"Alarms")
RES_ADD_STRING(STR_ILIST_CALENDAR_EXT01,"Calendar")
RES_ADD_STRING(STR_NOTIF_VOICEMAIL_EXT02,"Voice Mail")
RES_ADD_STRING(STR_LIST_OUTLOOK_EXT01,"Outlook")
RES_ADD_STRING(STXT_CELL_BROADCAST_TOPIC,"Operator")
RES_ADD_STRING(STR_MAINMENU_RADIO,"FM radio")
RES_ADD_STRING(STR_MAINMENU_MUSIC,"Music")

RES_ADD_STRING(STR_SETT_LIST_ABOUT_EXT01,"About")
RES_ADD_STRING(STR_SETT_HDR_ABOUT_EXT01,"About")
RES_ADD_STRING(STR_SETT_LIST_PRODUCT_EXT01,"Product info")
RES_ADD_STRING(STR_SETT_LIST_CHECK_UPDATE_EXT01,"Check for updates")
RES_ADD_STRING(STR_SETT_LIST_RESET_SETTINGS_EXT01,"Reset to factory settings")
RES_ADD_STRING(STR_NPS_ILIST_FEEDBACK_JT,"Send feedback")
RES_ADD_STRING(STR_SETT_LIST_PERSONALISATION_EXT01,"Personalisation")
RES_ADD_STRING(STR_SETT_HDR_PRODUCT_EXT01,"Product info")
RES_ADD_STRING(STR_DETAILS_MODEL_EXT01,"Model:")
RES_ADD_STRING(STR_DETAILS_CARRIER_EXT01,"Carrier:")
RES_ADD_STRING(STR_DETAILS_SOFTWARE_EXT01,"Software:")
RES_ADD_STRING(STR_DETAILS_OS_VERSION_EXT01,"OS verstion:")
RES_ADD_STRING(STR_PROMPT_FIRMWARE_NUM_EXT01,"Firmware number:")
RES_ADD_STRING(STR_DETAILS_YYYY_MS_EXT01,"%U HMD Global Oy")
RES_ADD_STRING(STR_MSA_LIST_SERVICE_TERMS,"Service Terms")
//RES_ADD_STRING(STR_READ_ABOUT_PRIVACY_EXT02,"Privacy Policy")
//RES_ADD_STRING(STR_READ_ABOUT_PRIVACY_DH,"Privacy Statement")

RES_ADD_STRING(STXT_USER_PRG_WAKEUP_MSG,"Welcome note")
RES_ADD_STRING(STR_SETT_LIST_SOUNDS_EXT01,"Sounds")
RES_ADD_STRING(STR_SETT_LIST_LOCK_BKGD_EXT01,"Lock screen background")
RES_ADD_STRING(STR_SETT_LIST_KEYPAD_EXT01,"Keypad settings")
RES_ADD_STRING(STXT_VIBRA_OPTIONS,"Vibration")
RES_ADD_STRING(STR_SETT_LIST_NOTIF_ALERT_EXT01,"Notification alert")
RES_ADD_STRING(STXT_WARNING_TONES,"Warning tones")
RES_ADD_STRING(STR_WP_LIST_WALLPAPER_EXT01,"Wallpapers")
RES_ADD_STRING(STR_SETT_LIST_CHOOSE_GALLERY_EXT01,"Choose from gallery")

RES_ADD_STRING(STR_SETT_LIST_KEYPAD_STCT_EXT01,"Keypad shortcuts")
RES_ADD_STRING(STR_SETT_LIST_SPEED_DIAL_EXT01,"Speed dial")
RES_ADD_STRING(STR_SETT_LIST_LOCK_STCT_EXT01,"Lock screen shortcuts")
RES_ADD_STRING(STR_SETT_RIGHT_SOFTKEY_EXT01,"Right softkey")
RES_ADD_STRING(STR_SETT_LEFT_SOFTKEY_EXT01,"Left softkey")
RES_ADD_STRING(STR_SETT_LIST_AUTO_POWER_EXT01,"Auto power")
RES_ADD_STRING(STR_SETT_LIST_BATTERY_STATUS_EXT01,"Battery status")
RES_ADD_STRING(STR_SETT_LIST_BATTERY_USAGE_EXT01,"Battery usage")
RES_ADD_STRING(STR_SETT_LIST_BATTERY_TIME_EXT01,"Estimated battery time")
RES_ADD_STRING(STR_SETT_LAST_FULL_CHARGE_EXT01,"Last full charge")

RES_ADD_STRING(STR_SETT_WELCOME_UPDATED_EXT01, "Welcome note updated")
RES_ADD_STRING(STR_SETT_HDR_LOCK_BKGD_EXT01, "Background")

RES_ADD_STRING(STR_LIST_NAVI_KEY_UP_EXT01,"Up")
RES_ADD_STRING(STR_LIST_NAVI_KEY_DOWN_EXT01,"Down")
RES_ADD_STRING(STR_LIST_NAVI_KEY_RIGHT_EXT01,"Right")
RES_ADD_STRING(STR_LIST_NAVI_KEY_LEFT_EXT01,"Left")
RES_ADD_STRING(STR_SETT_ILIST_NONE_EXT01, "None")
RES_ADD_STRING(STR_SETT_ILIST_MSA_ACCOUNT,"Microsoft account")
RES_ADD_STRING(STR_SETT_LIST_SECURITY_EXT01,"Security")
RES_ADD_STRING(STR_SETT_HDR_POWER_MANAGE_EXT01,"Power management")
RES_ADD_STRING(STR_DISPLAY_SETTINGS_HDR,"Display")
RES_ADD_STRING(STR_HDR_INSTALLED_APPS_EXT01,"Installed apps")

RES_ADD_STRING(STR_NPS_FEEDBACK_SENT_EXT01,"Feedback sent")
RES_ADD_STRING(STR_NPS_GIVE_SCORE_EXT02,"Give a score:")
RES_ADD_STRING(STR_NPS_HDR_FEEDBACK_EXT02,"Feedback")
RES_ADD_STRING(STR_NPS_QUERY_FEEDBACK_EXT02,"How likely are you to recommend this phone to a friend or colleague?")
RES_ADD_STRING(STR_NPS_LIST_0_EXT02,"0: Not at all likely")
RES_ADD_STRING(STR_NPS_LIST_10_EXT02,"10: Extremely likely")
RES_ADD_STRING(STR_NPS_LIST_SEND_EXT01,"Send")
RES_ADD_STRING(STR_MESSAGE_ALERT_EXT01,"Message Alert")
RES_ADD_STRING(STR_DETAILS_HARDWARE_EXT01,"Hardware number:")
RES_ADD_STRING(TXT_SET_RINGTONE_SELECTION,"Ringtone selection")
RES_ADD_STRING(STR_NOTIF_TYPE_EXT01,"Notification type")
RES_ADD_STRING(STR_NOTIF_REGULAR_EXT01,"Show full details")
RES_ADD_STRING(STR_NOTIF_ICON_EXT01,"Show icons only")
RES_ADD_STRING(STR_ILIST_OTHER_APPS_EXT01,"Other apps")
RES_ADD_STRING(TXT_SET_IMEI_SV,"IMEI SV :")
RES_ADD_STRING(STR_HDR_LEFT_SOFTKEY_EXT01,"Left key")
RES_ADD_STRING(STR_HDR_RIGHT_SOFTKEY_EXT01,"Right key")
RES_ADD_STRING(STR_ILIST_CALL_LOG_EXT01,"Call log")
RES_ADD_STRING(STR_ILIST_MESSAGING_EXT01,"Messaging")
RES_ADD_STRING(STR_ILIST_VIDEOS_EXT01,"Videos")
RES_ADD_STRING(STR_ILIST_CAMERA_EXT01,"Camera")
RES_ADD_STRING(STR_ILIST_SETTINGS_EXT01,"Settings")
RES_ADD_STRING(STR_ILIST_FILES_EXT01,"Files")
RES_ADD_STRING(STR_ILIST_PHOTOS_EXT01,"Photos")
RES_ADD_STRING(STR_ILIST_CALCULATOR_EXT01,"Calculator")
RES_ADD_STRING(STR_ILIST_VOICE_RECORDER_EXT01,"Voice Recorder")
RES_ADD_STRING(STR_ILIST_EXTRAS_EXT01,"Extras")
RES_ADD_STRING(STR_ILIST_COUNTERS_EXT01,"Counters")
RES_ADD_STRING(STR_ILIST_ONENOTE_EXT01,"OneNote")
RES_ADD_STRING(STR_ILIST_GROUPME_EXT01,"GroupMe")
RES_ADD_STRING(STR_LIST_FACEBOOK_EXT01,"Facebook")
RES_ADD_STRING(STR_ILIST_OPERA_STORE_EXT01,"Opera Store")
RES_ADD_STRING(STR_HDR_BING,"Bing")
//RES_ADD_STRING(STR_SERVICES_AGREEMENT,"Microsoft Services Agreement")
RES_ADD_STRING(STR_ILIST_GALLERY_EXT01,"Gallery")
//end
//2015-7-9 tangting add display strings
RES_ADD_STRING(STR_SETT_LIST_TIME_LANGUAGE_EXT01,"Time & language")
RES_ADD_STRING(STR_SETTINGS_BACKLIGHT,"Backlight")
RES_ADD_STRING(STR_SETTINGS_BACKLIGHT_HEADER,"Backlight")
RES_ADD_STRING(STR_SMSSE_SETT_FONT_SIZE,"Font size")
RES_ADD_STRING(TXT_SET_COMMON_LOCK_SCREEN,"Lock screen")
RES_ADD_STRING(STR_BACKLIGHT_TIMEOUT,"Time-out")
RES_ADD_STRING(STR_ILIST_CONTACTS_EXT01,"Contacts")
RES_ADD_STRING(STR_LIST_MENU_MENU,"Menu")
RES_ADD_STRING(STR_LIST_MENU_MESSAGES,"Messaging")
RES_ADD_STRING(STR_ILIST_NORMAL_FONT_SETT,"Normal font")
RES_ADD_STRING(STR_ILIST_SMSSE_BIG_FONT,"Large font")
RES_ADD_STRING(TXT_FONT_SIZE,"Size")
RES_ADD_STRING(STR_HDR_TIMEANDDATE_SETTINGS,"Date & time")
RES_ADD_STRING(STXT_HEADER_LANGUAGE,"Language")
RES_ADD_STRING(STXT_LANGUAGE_SELECT,"Language")
RES_ADD_STRING(STXT_LANGUAGE_AUTOMATIC,"Automatic")
RES_ADD_STRING(STXT_BACKLIGHT_TIME_T10,"10s")//replaced by common ID TXT_COMM_10SECOND
RES_ADD_STRING(STXT_BACKLIGHT_TIME_T20,"20s")
RES_ADD_STRING(STXT_BACKLIGHT_TIME_T40,"40s")
RES_ADD_STRING(STXT_BACKLIGHT_TIME_T60,"60s")
RES_ADD_STRING(STXT_BACKLIGHT_TIME_T120,"120s")

//nhl add security setting
RES_ADD_STRING(STR_CERTMAN_PW_MISMATCH,"Two passwords do not match")
RES_ADD_STRING(STR_PASSWORD_CHARACTERS_EXT01,"The password needed 4~8 characters")
RES_ADD_STRING(STR_SETT_INPUT_NEW_SECUR_CODE_EXT01,"New security code")
RES_ADD_STRING(STR_SETT_INPUT_CHECK_SECUR_CODE_EXT01,"Check new security code")
RES_ADD_STRING(STR_SETT_INPUT_CURRENT_SECUR_CODE_EXT01,"Current security code")
RES_ADD_STRING(STXT_SECURITY_CODE_CHANGED,"Security code changed.")
RES_ADD_STRING(STXT_SECURITY_CODE_SET_EXT01,"Security code set.")
RES_ADD_STRING(STR_SETT_LIST_CHANGE_SECUR_CODE_EXT01,"Change code")
RES_ADD_STRING(STR_SETT_HDR_KEYGUARD_EXT01,"Keyguard")
RES_ADD_STRING(STR_SETT_LIST_KEYGUARD_EXT01,"Keyguard")
RES_ADD_STRING(STXT_CALL_BARRING,"Call barring")
RES_ADD_STRING(STXT_KEYGUARD_AUTO_ACT,"Automatic Keyguard")
RES_ADD_STRING(STR_SECURITY_CODE_EXT01,"Security Code")
RES_ADD_STRING(STXT_KEYGUARD_AUTO_ON_EXT01,"On")
RES_ADD_STRING(STXT_KEYGUARD_AUTO_OFF_EXT01,"Off")
RES_ADD_STRING(STR_CLK_HDR_TIME_ZONE,"Time zone")
RES_ADD_STRING(STR_ILIST_24_H_EXT01,"24 hours clock")
RES_ADD_STRING(TXT_SET_AUTOMATICALLY,"Set automatically")
RES_ADD_STRING(STR_SETT_PROMPT_TIME_EXT01,"Time")
RES_ADD_STRING(STR_SETT_PROMPT_DATE_EXT01,"Date")
RES_ADD_STRING(STR_SETT_HDR_TIME_LANGUAGE_EXT01,"Time & language")
RES_ADD_STRING(STR_ILIST_TIMEDATE_SETTINGS,"Date & time")
RES_ADD_STRING(STR_SETT_HDR_SECURITY_EXT01,"Security")
//RES_ADD_STRING(STR_SETT_HDR_KEYGUARD_EXT01,"Keyguard")
RES_ADD_STRING(STR_KEYG_HDR_AUTOMATIC,"Automatic keyguard")
RES_ADD_STRING(STR_PRMPT_TIME_ZONE,"Time zone")	
RES_ADD_STRING(STR_SETT_TIME_SUCCESS,"Time set successful") 
RES_ADD_STRING(STR_SETT_DATE_SUCCESS,"Date set successful") 
RES_ADD_STRING(STXT_NITZ_UPDATE_DONE,"Date and time updated")




//end

//ljg add security setting
RES_ADD_STRING(STXT_HEADER_CALL_BARRING,"Call barring")
RES_ADD_STRING(STXT_NO_OUTGOING,"All outgoing")
RES_ADD_STRING(STXT_NO_INCOMING,"All incoming")
RES_ADD_STRING(STXT_NO_INCOMING_IF_ROAM_EXT01,"Incoming when roaming")
RES_ADD_STRING(STXT_NO_ISD_CALL_EXT01,"ISD calling")
RES_ADD_STRING(STXT_NO_INTERNATIONAL_CALL_EXT01,"Dial when Int. roaming")
RES_ADD_STRING(STR_LIST_CANCEL_BARRING_EXT01,"Cancell all barring")
RES_ADD_STRING(STR_CL_CHANGE_PASSWORD,"Change password")

RES_ADD_STRING(STXT_HEADER_OUTGOING_EXT01,"All outgoing")
RES_ADD_STRING(STXT_HEADER_INCOMING_EXT01,"All incoming")
RES_ADD_STRING(STXT_HEADER_INCOMING_IF_ROAM_EXT01,"Incoming roaming")
RES_ADD_STRING(STXT_HEADER_ISD_CALL_EXT01,"ISD calling")
RES_ADD_STRING(STXT_HEADER_INTERNATIONAL_CALL_EXT01,"Dial when Int.")
RES_ADD_STRING(STXT_BARRING_CANCELED_EXT01,"All barring cancelled.")
RES_ADD_STRING(STR_INPUT_SIM_PIN_EXT01,"Enter SIM pin code")
RES_ADD_STRING(STR_CALL_BARRING_PASSWORD,"Enter barring password")
RES_ADD_STRING(STR_SETT_NOT_ACTIVATED_EX01,"Setting not activated.")
RES_ADD_STRING(STR_SETT_UNABLE_TO_CHANGE_EXT01,"Unable to change setting.")
RES_ADD_STRING(STXT_VOICE_MBX_NBR,"Voic mail")
RES_ADD_STRING(STR_LIST_BOTH_SIM_EXT01,"From both SIMs")
RES_ADD_STRING(STR_LIST_FROM_SIM1_EXT01,"From SIM1")
RES_ADD_STRING(STR_LIST_FROM_SIM2_EXT01,"From SIM2")


RES_ADD_STRING(TXT_SET_CALLBARRING_LIST_ITEM_VALUE,"Searching network...")
RES_ADD_STRING(STR_FWD_CONDITION_EXT01,"Call options")
RES_ADD_STRING(STR_FWD_SIM_SELECTION_EXT01,"SIM options")
RES_ADD_STRING(STR_HDR_FWD_CONDITION_EXT01,"Forward calls")

RES_ADD_STRING(STR_SETT_LIST_ACTIVATE_EXT01,"Activate")
RES_ADD_STRING(STR_SETT_LIST_OFF_EXT01,"Off")
RES_ADD_STRING(STXT_CHECK_STATUS,"Check status")
RES_ADD_STRING(STR_SETT_STATUS_EXT01,"Status")

RES_ADD_STRING(STR_STATUS_PROVIDED_EXT01,"Provided")
RES_ADD_STRING(STR_STATUS_NOT_PROVIDED_EXT01,"Not Provided")
RES_ADD_STRING(STR_STATUS_ACTIVATED_EXT01,"Activated")
RES_ADD_STRING(STR_STATUS_NOT_ACTIVATED_EXT01,"Not activated")
RES_ADD_STRING(STR_SETT_ACTIVATED_EX01,"Setting activated.")
RES_ADD_STRING(STR_SETT_CANCELLED_EX01,"Setting cancel.")
RES_ADD_STRING(STR_CALL_BARRING_ACTIVATED_EXT01,"Call barring on")
RES_ADD_STRING(STR_CALL_BARRING_OFF_EXT01,"Call barring off")
RES_ADD_STRING(STR_CALL_FORWARDING_ON,"Call forwarding on")
RES_ADD_STRING(STR_CALL_FORWARDING_OFF,"Call forwading off")
RES_ADD_STRING(STR_CALL_WAITING_FAIL,"Call waiting settings failed")
RES_ADD_STRING(STR_CALL_WAITING_CANCEL_FAIL,"Cancel call waiting settings failed")
RES_ADD_STRING(STR_CALL_FORWARDING_FAIL,"Call forwarding settings failed")
RES_ADD_STRING(STR_CALL_FORWARDING_CANCEL_FAIL,"Cancel call forwaring settings failed")
RES_ADD_STRING(STR_CALL_BARRING_FAIL,"Call barring settings failed")
RES_ADD_STRING(STR_CALL_BARRING_CANCEL_FAIL,"Cancel call barring settings failed")

RES_ADD_STRING(STR_SIM1_CALL_FORWARDING_CANCEL_FAIL,"Your SIM1 call forwarding settings couldn't be changed.")
RES_ADD_STRING(STR_SIM1_CALL_FORWARDING_FAIL,"Your SIM1 call forwarding settings couldn't be changed.")
RES_ADD_STRING(STR_SIM1_CALL_FORWARDING_OFF,"SIM1 Call forwarding off")
RES_ADD_STRING(STR_SIM1_CALL_FORWARDING_ON,"SIM1 Call forwarding on")
RES_ADD_STRING(STR_SIM2_CALL_FORWARDING_CANCEL_FAIL,"Your SIM2 call forwarding settings couldn't be changed.")
RES_ADD_STRING(STR_SIM2_CALL_FORWARDING_FAIL,"Your SIM2 call forwarding settings couldn't be changed.")	
RES_ADD_STRING(STR_SIM2_CALL_FORWARDING_OFF,"SIM2 Call forwarding off")
RES_ADD_STRING(STR_SIM2_CALL_FORWARDING_ON,"STR_SIM2_CALL_FORWARDING_ON")

RES_ADD_STRING(TXT_SET_FORWARDING_LIST_SIMCARD_BOTHSIMS,"Both SIMs")
RES_ADD_STRING(STR_INPUT_PHONE_NUM_EXT01,"Input phone number")
RES_ADD_STRING(STR_SIM_HDR_SELECTION_EXT01,"SIM selection")
RES_ADD_STRING(STR_OLD_BARRING_CODE,"Current barring code:")
RES_ADD_STRING(STR_NEW_BARRING_CODE,"New barring code:")
RES_ADD_STRING(STR_VERIFY_BARRING_CODE,"Verify new barring code:")

RES_ADD_STRING(STR_CALLER_ID_SENT,"My caller ID is sent")
RES_ADD_STRING(STR_CALLER_ID_HIDE,"My caller ID is hide")
RES_ADD_STRING(STR_FWD_IF_NO_REPLY,"Forwarding if not answered is enabled to %0U after %1N seconds")
RES_ADD_STRING(STR_FWD_IF_OUT_OF_REACH,"Forwarding if out of reach is enabled to %U")
RES_ADD_STRING(STR_FWD_IF_BUSY,"Forwarding if busy is enabled to %U")
RES_ADD_STRING(STR_FWD_ALL_CALLS,"Forwarding is enabled to %U")
//end

//[[define data infomation
//]]define data infomation
//RES_ADD_STRING(STR_MSA_HDR_ACCOUNT,"Microsoft account")

RES_ADD_STRING(STR_MSA_LIST_REMOVE_ACCOUNT,"Remove account")
RES_ADD_STRING(STR_MSA_LIST_EDIT_ACCOUNT,"Edit account")
RES_ADD_STRING(STR_ONEDRIVE_LIST_PHOTOS_EXT01,"OneDrive photo")
RES_ADD_STRING(STR_MSA_ILIST_CONTA_SYNC_EXT01,"Contacts sync")
RES_ADD_STRING(STR_MSA_NOTE_REMOVE_ACCOUNT , "This will also remove your sync settings, remove account?")
RES_ADD_STRING(STR_MSA_ILIST_ADD_ACCOUNT_EXT01 , "Add an account")
RES_ADD_STRING(STR_MSA_CONNECTED_EXT01 , "Connected")
RES_ADD_STRING(STR_MSA_NOT_CONNECTED_EXT01 , "Not connected")

#ifdef UNISOC_TEST_ENTRY_FOR_TESTER
RES_ADD_STRING(STR_SETT_ILIST_PRIVACY_MODE_EX01 , "Privacy mode")
RES_ADD_STRING(STR_SETT_ILIST_SECURITY_CODE_EXT01 , "Security code")
//RES_ADD_STRING(STR_SETT_HDR_SECURITY_EXT01 , "Security")
RES_ADD_STRING(STR_SETT_INPUT_NEW_SECUR_EX01 , "New security code")
#endif
RES_ADD_STRING(TXT_SET_MSA_VALIDATE , "Validation failed")
//lulifei add for reset UI begin
RES_ADD_STRING(STR_QUERY_RESET_SETTINGS_EXT01 , "Restore factory settings and delete all user data and settings?")
//lulifei add for reset UI end
//[block list in call setting]
RES_ADD_STRING(STR_LIST_ADD_BLOCK_NUM_EXT01, "Add number")
RES_ADD_STRING(STR_LIST_REMOVE_BLOCK_NUM_EXT01, "Remove number")
RES_ADD_STRING(STXT_PHONE_NUMBER, "Phone number")
RES_ADD_STRING(STR_QUERY_REMOVE_NUM_EXT01, "Remove number from list? %U")
//RES_ADD_STRING(STR_CL_NUMBER_BLOCKED_EXT01, "Number blocked.")
RES_ADD_STRING(STR_MSG_NOTE_SCR_NUM_DEL_EXT02, "Number removed.")
RES_ADD_STRING(STR_BLOCK_EMPTY_EXT01,"When you block numbers, they will show up here.")
//RES_ADD_STRING(STR_CL_BLOCK_LIST_FULL,"The maximum amount of blocked numbers is 30.")
//[end]

#ifdef MMI_VOLTE_SUPPORT
RES_ADD_STRING(STR_LIST_SETT_VOLTE,"VoLTE")
RES_ADD_STRING(STR_VOLTE_SIM_ONE,"SIM1")
RES_ADD_STRING(STR_VOLTE_SIM_TWO,"SIM2")
#endif
#if defined(MMI_2G_4G_SUPPORT)
RES_ADD_STRING(TXT_SET_MODELOCK,"Select Mode")
RES_ADD_STRING(TXT_SET_2G_ONLY,"2G Only")
RES_ADD_STRING(TXT_SET_4G_ONLY,"4G Only")
RES_ADD_STRING(STR_OPT_NET_TYPE_AUTO,"4G/2G Auto")
RES_ADD_STRING(STR_OPT_NET_TYPE_4PLUS_ENABLE,"Enable 4.5G")
RES_ADD_STRING(STR_OPT_NET_TYPE_4PLUS_DISABLE,"Disable 4.5G")
RES_ADD_STRING(TXT_EFFECT_REBOOT,"Setting will take effect after reboot")
RES_ADD_STRING(TXT_SET_RECOMMEND,"4G/2G recommended")
RES_ADD_STRING(TXT_SET_4G,"4G")
RES_ADD_STRING(TXT_SET_2G,"2G")
RES_ADD_STRING(TXT_SET_LTE_AUTO,"LTE/2G Auto")
RES_ADD_STRING(TXT_SET_LTE_ONLY,"LTE Only")
RES_ADD_STRING(TXT_SET_LTE_RECOMMEND,"LTE/2G recommended")
RES_ADD_STRING(TXT_SET_LTE,"LTE")
#endif

#ifdef MMI_INDIAN_SOS_SUPPORT
RES_ADD_STRING(TXT_SET_SOS_TITLE,"SOS Activated")
RES_ADD_STRING(TXT_SET_SOS_NUMBER_LIST,"SOS number list")
RES_ADD_STRING(TXT_SET_SOS_MESSAGE_SETTINGS,"SOS message settings")
RES_ADD_STRING(TXT_SET_SOS_MESSAGE_SENDING,"SOS message sending")
RES_ADD_STRING(TXT_SET_SOS_SETTINGS,"SOS settings")
#ifdef MMIDC_F_FLASH
RES_ADD_STRING(TXT_SET_SOS_LED_ALERT_SETTINGS,"SOS LED Alert")
#endif
RES_ADD_STRING(TXT_SET_SOS_RING_ALERT_SETTINGS,"SOS Ring Alert")
RES_ADD_STRING(TXT_SET_SOS_MSG_DEFAULT,"Please help me! I am in an emergency")
RES_ADD_STRING(TXT_SET_SOS_HELP_NUMBER_LIST,"SOS number list: Add 5 contact numbers for seeking help in case of an emergency.")
RES_ADD_STRING(TXT_SET_SOS_HELP_MESSAGE_SETTINGS,"SOS message settings: Edit your personal text for emergency messages.")
RES_ADD_STRING(TXT_SET_SOS_HELP_TYPE_SETTINGS,"SOS settings: Config the switch of SOS and its sub-function like message sending, led alert, etc.")
#endif

RES_ADD_STRING(STR_LIST_SW_UPD_OFFINE,"Offline software update")
RES_ADD_STRING(STR_NOTE_SCAN_SD,"Scan SD card for software update")
RES_ADD_STRING(STR_TOAST_NO_UPD_AVAIL, "No software update available in SD card.")
RES_ADD_STRING(STR_DIAL_ILLEGAL_FILE, "Illegal file.")
RES_ADD_STRING(STR_TITLE_SOFTWARE_UPT, "Software update")
RES_ADD_STRING(STR_UPDATE_REBOOT_NOTE, "The upgrade will continue about 3 minutes,blue screen will be shown during update process,please do not power off or remove battery. ")
RES_ADD_STRING(STR_DIAL_ERASE_USER_DATA, "This update could be upgrade or downgrade depends on the selected file. User data will be earsed caused by update purpose.")
RES_ADD_STRING(STR_DIAL_CHARGE_PHONE_UPD, "This update requires battery over N%, need to charge your phone at first.")
RES_ADD_STRING(TXT_UPDATE_CANCELLED, "Update cancelled.")

