/* Copyright 2004-2009 Myriad Group AG. All Rights Reserved. */
/* THIS FILE IS AUTOMATICALLY GENERATED */

#ifndef _JBED_JBEDUPCALLS_H_
#define _JBED_JBEDUPCALLS_H_

#if defined(__cplusplus)
extern "C" {
#endif
extern void JBNI_IMPORT Jbed_sendComplexEvent(jint, jint, jint, struct INSTANCE_java_lang_Object_s * );
extern jint JBNI_IMPORT Jbni_intern_addHeapBlock(jint, jint, jint);
extern jint JBNI_IMPORT Jbni_intern_getClassNameUtf8(struct INSTANCE_java_lang_Class_s * , jint, jint);
extern jint JBNI_IMPORT Jbni_intern_getStringAscii(STRING_INSTANCE, jint, jint);
extern jint JBNI_IMPORT Jbni_intern_getStringCharsAscii(STRING_INSTANCE, jint, jint, jint, jint);
extern jint JBNI_IMPORT Jbni_intern_getStringCharsUtf8(STRING_INSTANCE, jint, jint, jint, jint);
extern jint JBNI_IMPORT Jbni_intern_getStringUtf8(STRING_INSTANCE, jint, jint);
extern jint JBNI_IMPORT Jbni_intern_moveHeapBlock(jint, jint, jint, jint);
extern STRING_INSTANCE JBNI_IMPORT Jbni_intern_newEmptyStringLen(jint);
extern STRING_INSTANCE JBNI_IMPORT Jbni_intern_newEmptyStringLenExc(jint);
extern STRING_INSTANCE JBNI_IMPORT Jbni_intern_newString(jint);
extern STRING_INSTANCE JBNI_IMPORT Jbni_intern_newStringExc(jint);
extern STRING_INSTANCE JBNI_IMPORT Jbni_intern_newStringLen(jint, jint);
extern STRING_INSTANCE JBNI_IMPORT Jbni_intern_newStringLenExc(jint, jint);
extern STRING_INSTANCE JBNI_IMPORT Jbni_intern_newStringUcs2(jint, jint);
extern STRING_INSTANCE JBNI_IMPORT Jbni_intern_newStringUcs2Exc(jint, jint);
extern void JBNI_IMPORT Jbni_intern_raiseCommonException(jint);
extern void JBNI_IMPORT Jbni_intern_raiseException(jint);
extern void JBNI_IMPORT Jbni_intern_raiseExceptionCString(jint, jint);
extern void JBNI_IMPORT Jbni_intern_raiseExceptionString(jint, STRING_INSTANCE);
extern jint JBNI_IMPORT Jbni_intern_releaseHeapBlock(jint);
extern BOOLEANARRAY JBNI_IMPORT Jbni_newBooleanArray(jint);
extern BYTEARRAY JBNI_IMPORT Jbni_newByteArray(jint);
extern CHARARRAY JBNI_IMPORT Jbni_newCharArray(jint);
extern struct INSTANCE_java_lang_Object_s *  JBNI_IMPORT Jbni_newInstance(struct INSTANCE_java_lang_Class_s * );
extern INTARRAY JBNI_IMPORT Jbni_newIntArray(jint);
extern LONGARRAY JBNI_IMPORT Jbni_newLongArray(jint);
extern REFARRAY JBNI_IMPORT Jbni_newObjectArray(jint);
extern SHORTARRAY JBNI_IMPORT Jbni_newShortArray(jint);
extern STRINGARRAY JBNI_IMPORT Jbni_newStringArray(jint);
extern void JBNI_IMPORT Jbni_runGc(jint);
extern void JBNI_IMPORT Jbni_throwException(struct INSTANCE_java_lang_Throwable_s * );
extern jint JBNI_IMPORT Jbed_intern_initialize(jint, jint);
extern void JBNI_IMPORT Jbed_shutdown(void);
extern struct INSTANCE_com_jbed_runtime_Signal_s *  JBNI_IMPORT Jbed_getCurrentSignal(void);
extern jint JBNI_IMPORT Jbed_iterate(jint);
extern void JBNI_IMPORT Jbed_timerEntry(void);
extern void JBNI_IMPORT Jbed_signal(struct INSTANCE_com_jbed_runtime_Signal_s * );
extern void JBNI_IMPORT Jbed_signalArg(struct INSTANCE_com_jbed_runtime_Signal_s * , jint);
extern void JBNI_IMPORT Jbed_signalArgFast(struct INSTANCE_com_jbed_runtime_Signal_s * , jint);
extern void JBNI_IMPORT Jbed_signalFast(struct INSTANCE_com_jbed_runtime_Signal_s * );
extern void JBNI_IMPORT Jbed_signalObjectArg(struct INSTANCE_com_jbed_runtime_Signal_s * , struct INSTANCE_java_lang_Object_s * );
extern void JBNI_IMPORT Jbed_signalObjectArgFast(struct INSTANCE_com_jbed_runtime_Signal_s * , struct INSTANCE_java_lang_Object_s * );
extern jint JBNI_IMPORT Jbed_getExitCode(void);
extern void JBNI_IMPORT Jbed_addEventAsync(jint, jint);
extern void JBNI_IMPORT Jbed_doAudioEvent(struct INSTANCE_com_jbed_runtime_SignalQueue_s * , jint, jint, jint);
extern void JBNI_IMPORT Jbed_doKeyDown(struct INSTANCE_com_jbed_runtime_SignalQueue_s * , jint);
extern void JBNI_IMPORT Jbed_doKeyUp(struct INSTANCE_com_jbed_runtime_SignalQueue_s * , jint);
extern void JBNI_IMPORT Jbed_doOtherEvent(struct INSTANCE_com_jbed_runtime_SignalQueue_s * , jint);
extern void JBNI_IMPORT Jbed_doPointerButtonDown(struct INSTANCE_com_jbed_runtime_SignalQueue_s * , jint, jint, jint);
extern void JBNI_IMPORT Jbed_doPointerButtonUp(struct INSTANCE_com_jbed_runtime_SignalQueue_s * , jint, jint, jint);
extern void JBNI_IMPORT Jbed_doPointerMove(struct INSTANCE_com_jbed_runtime_SignalQueue_s * , jint, jint);
extern void JBNI_IMPORT Jbed_doRawEvent(struct INSTANCE_com_jbed_runtime_SignalQueue_s * , jint);
extern void JBNI_IMPORT Jbed_doUserEvent(struct INSTANCE_com_jbed_runtime_SignalQueue_s * , jint, jint);
#if defined(__cplusplus)
}
#endif
#endif /* _JBED_JBEDUPCALLS_H_ */
