#include "sci_types.h"
#include "mmi_image.h"
#include "guimenu.h"
#include "mmi_common.h"
#include "mmi_nv.h"
#include "mmi_menutable.h"
#include "smartdualsim_text.h"
#include "smartdualsim_image.h"
#include "smartdualsim_menutable.h"

const GUIMENU_ITEM_T menu_forward_type_table[] =
{
    {MMI_SMARTDUALSIM_FORWARD_SIM_BOTH, TIP_NULL,{TXT_NULL,STXT_SOFTKEY_SELECT_MK,STXT_RETURN},STR_FWD_LIST_BTW_SIM_EXT02, 0, 0, 0, 0},
    {MMI_SMARTDUALSIM_FORWARD_SIM_1_TO_2, TIP_NULL,{TXT_NULL,STXT_SOFTKEY_SELECT_MK,STXT_RETURN},STR_FWD_LIST_TO_SIM1_EXT02, 0, 0, 0, 0},
    {MMI_SMARTDUALSIM_FORWARD_SIM_2_TO_1, TIP_NULL,{TXT_NULL,STXT_SOFTKEY_SELECT_MK,STXT_RETURN},STR_FWD_LIST_TO_SIM2_EXT02, 0, 0, 0, 0},
};

const GUIMENU_ITEM_T menu_main_menu_table[] =
{
//    {MMI_SMARTDUALSIM_CALL_FORWARDING, TIP_NULL,{TXT_NULL,STXT_SELECT,STXT_RETURN},STXT_CALL_DIVERT, 0, 0, 0, 0},
    {MMI_SMARTDUALSIM_FORWARD_TYPE, TIP_NULL,{TXT_NULL,STXT_SOFTKEY_SELECT_MK,STXT_RETURN},STR_FWD_LIST_FORWARD_EXT02, 0, 0, 0, 0},
    {MMI_SMARTDUALSIM_SIM_NUMBERS, TIP_NULL,{TXT_NULL,STXT_SOFTKEY_SELECT_MK,STXT_RETURN},STR_FWD_LIST_NUM_EXT02, 0, 0, 0, 0},
    {MMI_SMARTDUALSIM_SIM_SETTINGS, TIP_NULL,{TXT_NULL,STXT_SOFTKEY_SELECT_MK,STXT_RETURN},STR_SIM_LIST_SETT_EXT02, 0, 0, 0, 0},
    {MMI_SMARTDUALSIM_DATA_CONNECTION, TIP_NULL,{TXT_NULL,STXT_SOFTKEY_SELECT_MK,STXT_RETURN},STR_WMLS_SETT_CONN_BEHAVIOR, 0, 0, 0, 0},
};

const GUIMENU_ITEM_T menu_sim_settings_table[] =
{
    {MMI_SMARTDUALSIM_SIM_SETTINGS_SIM1, TIP_NULL,{TXT_NULL,STXT_SOFTKEY_SELECT_MK,STXT_RETURN},STR_ILIST_SIM_ONE, 0, 0, 0, 0},
    {MMI_SMARTDUALSIM_SIM_SETTINGS_SIM2, TIP_NULL,{TXT_NULL,STXT_SOFTKEY_SELECT_MK,STXT_RETURN},STR_ILIST_SIM_TWO, 0, 0, 0, 0},
};

#define MENU_DEF(_TABLEID, _ITEMPTR, _STYLE, _TITLESTR, _TITLE_ICON, _TITLE_NUMICON, _TITLE_BACKGROUND, \
    _ITEMCOUNT) \
     _ITEMPTR, _STYLE, _TITLESTR, _TITLE_ICON, _TITLE_NUMICON, _TITLE_BACKGROUND, _ITEMCOUNT, 

const GUIMENU_GROUP_T smartdualsim_menu_tables[] =
{
    {0},
    #include "smartdualsim_menutable.def"
};

PUBLIC void MMISmartDS_RegMenuGroup(void)
{
    MMI_RegMenuGroup(MMI_MODULE_SMARTDUALSIM, smartdualsim_menu_tables);
}

#undef MENU_DEF

