/* Copyright 2004-2009 Myriad Group AG. All Rights Reserved. */
/* THIS FILE IS AUTOMATICALLY GENERATED */

#ifndef _JBED_com_jbed_event_EventCode_H_
#define _JBED_com_jbed_event_EventCode_H_

#if defined(__cplusplus)
extern "C" {
#endif
#define STATIC_com_jbed_event_EventCode_MAX_PLAYER_ID (16)
#define STATIC_com_jbed_event_EventCode_EVT_BG_VOLUME_DOWN (19)
#define STATIC_com_jbed_event_EventCode_EVT_BG_VOLUME_UP (18)
#define STATIC_com_jbed_event_EventCode_EVT_VOLUME_CHANGE (17)
#define STATIC_com_jbed_event_EventCode_EVT_VOLUME_DOWN (15)
#define STATIC_com_jbed_event_EventCode_EVT_VOLUME_UP (14)
#define STATIC_com_jbed_event_EventCode_VM_ACTIVE (1)
#define STATIC_com_jbed_event_EventCode_VM_INACTIVE (0)
#define STATIC_com_jbed_event_EventCode_EVT_KILL_CURRENT_MIDLET (169)
#define STATIC_com_jbed_event_EventCode_EVT_NET_OFF (4249)
#define STATIC_com_jbed_event_EventCode_EVT_NET_ON (153)
#define STATIC_com_jbed_event_EventCode_EVT_OTHER_NET (153)
#define STATIC_com_jbed_event_EventCode_EVT_OTHER_COMMAND (137)
#define STATIC_com_jbed_event_EventCode_EVT_OTHER_DOREPAINT (89)
#define STATIC_com_jbed_event_EventCode_EVT_OTHER_UPCALL (73)
#define STATIC_com_jbed_event_EventCode_EVT_OTHER_CALL_END (8249)
#define STATIC_com_jbed_event_EventCode_EVT_OTHER_CALL_START (4153)
#define STATIC_com_jbed_event_EventCode_EVT_OTHER_CALL_INCOMING (57)
#define STATIC_com_jbed_event_EventCode_EVT_OTHER_CALL (57)
#define STATIC_com_jbed_event_EventCode_EVT_OTHER_NATIVE_AMS_EVENT (41)
#define STATIC_com_jbed_event_EventCode_EVT_NONE (15)
#define STATIC_com_jbed_event_EventCode_EVT_FIFTHUSER (14)
#define STATIC_com_jbed_event_EventCode_EVT_FOURTHUSER (13)
#define STATIC_com_jbed_event_EventCode_EVT_KEYTYPED (12)
#define STATIC_com_jbed_event_EventCode_EVT_ACTIVATE (11)
#define STATIC_com_jbed_event_EventCode_EVT_FIRSTUSER (10)
#define STATIC_com_jbed_event_EventCode_EVT_OTHER (9)
#define STATIC_com_jbed_event_EventCode_EVT_MEDIA (8)
#define STATIC_com_jbed_event_EventCode_EVT_USER (7)
#define STATIC_com_jbed_event_EventCode_EVT_QUIT (6)
#define STATIC_com_jbed_event_EventCode_EVT_KEYUP (4)
#define STATIC_com_jbed_event_EventCode_EVT_KEYDOWN (3)
#define STATIC_com_jbed_event_EventCode_EVT_BTNUP (2)
#define STATIC_com_jbed_event_EventCode_EVT_BTNDOWN (1)
#define STATIC_com_jbed_event_EventCode_EVT_PTRMOVE (0)
#if defined(__cplusplus)
}
#endif
#endif /* _JBED_com_jbed_event_EventCode_H_ */
