/* Copyright 2004-2009 Myriad Group AG. All Rights Reserved. */
/* THIS FILE IS AUTOMATICALLY GENERATED */

#ifndef _JBED_JBEDEXPUPCALLS_H_
#define _JBED_JBEDEXPUPCALLS_H_

#if defined(__cplusplus)
extern "C" {
#endif
extern struct ASYNC_INSTANCE_Signal_s * JBNI_IMPORT JbedExp_getCurrentSignal(void);
extern void JBNI_IMPORT JbedKNI_FatalError(jint);
extern jint JBNI_IMPORT JbedKNI_GetFieldAddress(void*, jint, jint, jint);
extern void JBNI_IMPORT JbedKNI_GetStringRange(void*, jint, jint, jint);
extern void* JBNI_IMPORT JbedKNI_LookupClass(jint);
extern void JBNI_IMPORT JbedKNI_Move(jint, jint, jint);
extern void* JBNI_IMPORT JbedKNI_NewCharString(jint, jint);
extern void* JBNI_IMPORT JbedKNI_NewUtfString(jint, jboolean);
extern jint JBNI_IMPORT JbedKNI_ThrowNew(jint, void*);
extern jint JBNI_IMPORT JbedKNI_VerifyArray(void*, jint, jint, void*);
extern void JBNI_IMPORT JbedKNI_VerifyArrayCopy(void*, jint, jint, jint, jboolean);
extern void JBNI_IMPORT JbedKNI_VerifyArraySetObj(void*, jint, jint, void*);
extern jint JBNI_IMPORT JbedKNI_VerifyField(void*, jint, jint, void*);
extern void JBNI_IMPORT JbedKNI_VerifyFieldSetObj(void*, jint, jint, void*);
extern void* JBNI_IMPORT JbedKNI_VerifyObject(void*, jint);
extern jboolean JBNI_IMPORT JbedKNI_IsAssignableFrom(void*, void*);
extern jboolean JBNI_IMPORT JbedKNI_IsInstance(void*, void*);
#if defined(__cplusplus)
}
#endif
#endif /* _JBED_JBEDEXPUPCALLS_H_ */
