#ifdef PIC_EDITOR_SUPPORT

//[[define image infomation
RES_ADD_IMG(IMAGE_PIC_ANGEL,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_ANGEL.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_ANIMAL_CAT,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_ANIMAL_CAT.bmp",IMG_CMP_BMP_16_565_RLE,0)
#ifndef MMI_LOW_MEMORY_RESOURCE
RES_ADD_IMG(IMAGE_PIC_ANIMAL_CATS,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_ANIMAL_CATS.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_ANIMAL_CHICK,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_ANIMAL_CHICK.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif
#ifdef MMI_COMPILE_E//8910uix
RES_ADD_IMG(IMAGE_PIC_ANIMAL_DOG,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_ANIMAL_DOG.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif
#ifndef MMI_LOW_MEMORY_RESOURCE
RES_ADD_IMG(IMAGE_PIC_ANIMAL_DOG1,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_ANIMAL_DOG1.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif
RES_ADD_IMG(IMAGE_PIC_ANIMAL_FISH,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_ANIMAL_FISH.bmp",IMG_CMP_BMP_16_565_RLE,0)
#ifndef MMI_LOW_MEMORY_RESOURCE
RES_ADD_IMG(IMAGE_PIC_BEAR,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_BEAR.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_BOWKNOT,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_BOWKNOT.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif
#ifdef MMI_PIC_PASTE_IMAGE_FULL
RES_ADD_IMG(IMAGE_PIC_CLOUD_CRY,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_CLOUD_CRY.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_CLOUD_SMILE,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_CLOUD_SMILE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_EYE_LEFT,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_EYE_LEFT.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_EYE_RIGHT,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_EYE_RIGHT.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_FAIRY,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_FAIRY.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_GHOST,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_GHOST.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_GIFT_BLUE,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_GIFT_BLUE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_GIFT_RED,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_GIFT_RED.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_HIT_SMILE,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_HIT_SMILE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_LOVE,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_LOVE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_OLLY,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_OLLY.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_SHIT1,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_SHIT1.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_SKULL,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_SKULL.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_SNOWFLAKE,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_SNOWFLAKE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_SOCK,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_SOCK.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_STAR,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_STAR.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_STRAWBERRY,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_STRAWBERRY.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_WING_LEFT,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_WING_LEFT.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_WING_RIGHT,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_WING_RIGHT.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_X_CANDLE,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_X_CANDLE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_ZZ,"\\MMI_RES_##\\IMAG\\clip\\IMAGE_PIC_ZZ.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

#ifdef PIC_EDIT_FRAME_SUPPORT
RES_ADD_IMG(IMAGE_PIC_FRAME1,"\\MMI_RES_##\\IMAG\\frame\\IMAGE_PIC_FRAME1.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_FRAME2,"\\MMI_RES_##\\IMAG\\frame\\IMAGE_PIC_FRAME2.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_FRAME3,"\\MMI_RES_##\\IMAG\\frame\\IMAGE_PIC_FRAME3.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_H_FRAME1,"\\MMI_RES_##\\IMAG\\frame\\IMAGE_PIC_H_FRAME1.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_H_FRAME2,"\\MMI_RES_##\\IMAG\\frame\\IMAGE_PIC_H_FRAME2.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_H_FRAME3,"\\MMI_RES_##\\IMAG\\frame\\IMAGE_PIC_H_FRAME3.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

#if defined(MAINLCD_SIZE_240X320) || defined(MAINLCD_SIZE_320X480) || defined(MAINLCD_SIZE_240X400)
RES_ADD_IMG(IMAGE_PIC_ADJUST_BG,"\\MMI_RES_##\\IMAG\\adjust\\IMAGE_PIC_ADJUST_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PIC_PROGRESS_COLOR,"\\MMI_RES_##\\IMAG\\adjust\\IMAGE_PIC_PROGRESS_COLOR.png",IMG_CMP_PNG_SABM_RLE,0)
RES_ADD_IMG(IMAGE_PIC_DOWN,"\\MMI_RES_##\\IMAG\\adjust\\IMAGE_PIC_DOWN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PIC_FOCUS_DOWN,"\\MMI_RES_##\\IMAG\\adjust\\IMAGE_PIC_FOCUS_DOWN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PIC_FOCUS_UP,"\\MMI_RES_##\\IMAG\\adjust\\IMAGE_PIC_FOCUS_UP.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PIC_UP,"\\MMI_RES_##\\IMAG\\adjust\\IMAGE_PIC_UP.png",IMG_CMP_PNG_ARGB_RLE,0)
#else
RES_ADD_IMG(IMAGE_PIC_ADJUST_BG,"\\MMI_RES_##\\IMAG\\adjust\\IMAGE_PIC_ADJUST_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_COLOR_BG,"\\MMI_RES_##\\IMAG\\adjust\\IMAGE_PIC_COLOR_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_DOWN,"\\MMI_RES_##\\IMAG\\adjust\\IMAGE_PIC_DOWN.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_FOCUS_DOWN,"\\MMI_RES_##\\IMAG\\adjust\\IMAGE_PIC_FOCUS_DOWN.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_FOCUS_UP,"\\MMI_RES_##\\IMAG\\adjust\\IMAGE_PIC_FOCUS_UP.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_PIC_UP,"\\MMI_RES_##\\IMAG\\adjust\\IMAGE_PIC_UP.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

#ifdef PIC_EDIT_U200_SUPPORT
RES_ADD_IMG(IMAGE_PIC_ADJUST_SIZE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PIC_ADJUST_SIZE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PIC_BRIGHTNESS_CONSTRACT,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PIC_BRIGHTNESS_CONSTRACT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PIC_EFFECT,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PIC_EFFECT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PIC_HUE_SATURATION,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PIC_HUE_SATURATION.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PIC_ROTATE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PIC_ROTATE.png",IMG_CMP_PNG_ARGB_RLE,0)
//return icon
//RES_ADD_IMG(IMAG_PS_RETURN,"\\MMI_RES_##\\IMAG\\IMAG_PS_RETURN.png",IMG_CMP_PNG_ARGB_RLE,0)

//pic_edit bg
RES_ADD_IMG(IMAG_PS_MAIN_TITLE_BG,"\\MMI_RES_##\\IMAG\\IMAG_PS_TITLE_TOOLS.png",IMG_CMP_PNG_SABM_RLE|SABM_CEN_STRETCH,0)
#endif
RES_ADD_IMG(IMAG_PS_BG,"\\MMI_RES_##\\IMAG\\IMAG_PS_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAG_PS_ROTATE_BG,"\\MMI_RES_##\\IMAG\\IMAG_PS_ROTATE_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_CEN_STRETCH,0) 
RES_ADD_IMG(IMAG_PS_ADJUST_BG,"\\MMI_RES_##\\IMAG\\IMAG_PS_ADJUST_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAG_PS_EFFECT_BG,"\\MMI_RES_##\\IMAG\\IMAG_PS_EFFECT_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_CEN_STRETCH,0)
#ifdef PIC_EDIT_FRAME_SUPPORT
RES_ADD_IMG(IMAG_PS_FRAME_BG,"\\MMI_RES_##\\IMAG\\IMAG_PS_FRAME_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_CEN_STRETCH,0)
#endif
RES_ADD_IMG(IMAG_PS_TEXT_BG,"\\MMI_RES_##\\IMAG\\IMAG_PS_TEXT_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAG_PS_CLIP_BG,"\\MMI_RES_##\\IMAG\\IMAG_PS_CLIP_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAG_PS_ADJUST_OSD_BG,"\\MMI_RES_##\\IMAG\\adjust\\IMAG_PS_ADJUST_OSD_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_CEN_STRETCH,0)

//common menu icon
RES_ADD_IMG(IMAG_PS_OK,"\\MMI_RES_##\\IMAG\\IMAG_PS_OK.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_CANCLE,"\\MMI_RES_##\\IMAG\\IMAG_PS_CANCLE.png",IMG_CMP_PNG_ARGB_RLE,0)

//lijinghua modify and add it
//edit option icon
RES_ADD_IMG(IMAG_PS_ICON_BRIGHTNESS,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_BRIGHTNESS.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_CONTRAST,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_CONTRAST.png",IMG_CMP_PNG_ARGB_RLE,0) 
//RES_ADD_IMG(IMAG_PS_ICON_ROTATE,"\\MMI_RES_##\\IMAG\\IMAG_PS_ICON_ROTATE.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ADJUST,"\\MMI_RES_##\\IMAG\\IMAG_PS_ICON_ADJUST.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAG_PS_ICON_EFFECT,"\\MMI_RES_##\\IMAG\\IMAG_PS_ICON_EFFECT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ICON_EFFECT,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_EFFECT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ICON_CROP,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_CROP.png",IMG_CMP_PNG_ARGB_RLE,0)

#ifdef MMI_COMPILE_E//8910UIX
//blue theme focused edit option icon
RES_ADD_IMG(IMAG_PS_ICON_BRIGHTNESS_BLUE,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_BRIGHTNESS_FOCUSED_BLUE.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_CONTRAST_BLUE,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_CONTRAST_FOCUSED_BLUE.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_BLUE,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_BLUE.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_EFFECT_BLUE,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_EFFECT_BLUE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ICON_CROP_BLUE,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_CROP_BLUE.png",IMG_CMP_PNG_ARGB_RLE,0)

//copper theme focused edit option icon
RES_ADD_IMG(IMAG_PS_ICON_BRIGHTNESS_COPPER,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_BRIGHTNESS_FOCUSED_COPPER.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_CONTRAST_COPPER,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_CONTRAST_FOCUSED_COPPER.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_COPPER,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_COPPER.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_EFFECT_COPPER,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_EFFECT_COPPER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ICON_CROP_COPPER,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_CROP_COPPER.png",IMG_CMP_PNG_ARGB_RLE,0)

//green theme focused edit option icon
RES_ADD_IMG(IMAG_PS_ICON_BRIGHTNESS_GREEN,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_BRIGHTNESS_FOCUSED_GREEN.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_CONTRAST_GREEN,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_CONTRAST_FOCUSED_GREEN.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_GREEN,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_GREEN.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_EFFECT_GREEN,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_EFFECT_GREEN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ICON_CROP_GREEN,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_CROP_GREEN.png",IMG_CMP_PNG_ARGB_RLE,0)

//red theme focused edit option icon
RES_ADD_IMG(IMAG_PS_ICON_BRIGHTNESS_RED,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_BRIGHTNESS_FOCUSED_RED.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_CONTRAST_RED,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_CONTRAST_FOCUSED_RED.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_RED,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_RED.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_EFFECT_RED,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_EFFECT_RED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ICON_CROP_RED,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_CROP_RED.png",IMG_CMP_PNG_ARGB_RLE,0)

//violet theme focused edit option icon
RES_ADD_IMG(IMAG_PS_ICON_BRIGHTNESS_VIOLET,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_BRIGHTNESS_FOCUSED_VIOLET.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_CONTRAST_VIOLET,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_CONTRAST_FOCUSED_VIOLET.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_VIOLET,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_VIOLET.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_EFFECT_VIOLET,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_EFFECT_VIOLET.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ICON_CROP_VIOLET,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_CROP_VIOLET.png",IMG_CMP_PNG_ARGB_RLE,0)

//yellow theme focused edit option icon
RES_ADD_IMG(IMAG_PS_ICON_BRIGHTNESS_YELLOW,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_BRIGHTNESS_FOCUSED_YELLOW.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_CONTRAST_YELLOW,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_CONTRAST_FOCUSED_YELLOW.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_YELLOW,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_YELLOW.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_EFFECT_YELLOW,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_EFFECT_YELLOW.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ICON_CROP_YELLOW,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_CROP_YELLOW.png",IMG_CMP_PNG_ARGB_RLE,0)

//rotate mirror horizontal option icon
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_VERTICAL.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_BLUE,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_VERTICAL_BLUE.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_COPPER,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_VERTICAL_COPPER.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_GREEN,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_VERTICAL_GREEN.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_RED,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_VERTICAL_RED.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_VIOLET,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_VERTICAL_VIOLET.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_YELLOW,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_VERTICAL_YELLOW.png",IMG_CMP_PNG_ARGB_RLE,0) 

//rotate mirror vertical option icon
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_HORIZONTAL.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_BLUE,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_HORIZONTAL_BLUE.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_COPPER,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_HORIZONTAL_COPPER.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_GREEN,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_HORIZONTAL_GREEN.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_RED,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_HORIZONTAL_RED.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_VIOLET,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_HORIZONTAL_VIOLET.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_YELLOW,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_HORIZONTAL_YELLOW.png",IMG_CMP_PNG_ARGB_RLE,0) 

#else
//red theme focused edit option icon
RES_ADD_IMG(IMAG_PS_ICON_BRIGHTNESS_RED,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_BRIGHTNESS_FOCUSED_RED.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_CONTRAST_RED,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_CONTRAST_FOCUSED_RED.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_RED,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_RED.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_EFFECT_RED,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_EFFECT_RED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ICON_CROP_RED,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_CROP_RED.png",IMG_CMP_PNG_ARGB_RLE,0)

#define IMAG_PS_ICON_BRIGHTNESS_BLUE IMAG_PS_ICON_BRIGHTNESS_RED
#define IMAG_PS_ICON_BRIGHTNESS_COPPER IMAG_PS_ICON_BRIGHTNESS_RED
#define IMAG_PS_ICON_BRIGHTNESS_GREEN IMAG_PS_ICON_BRIGHTNESS_RED
#define IMAG_PS_ICON_BRIGHTNESS_VIOLET IMAG_PS_ICON_BRIGHTNESS_RED
#define IMAG_PS_ICON_BRIGHTNESS_YELLOW IMAG_PS_ICON_BRIGHTNESS_RED

#define IMAG_PS_ICON_CONTRAST_BLUE IMAG_PS_ICON_CONTRAST_RED
#define IMAG_PS_ICON_CONTRAST_COPPER IMAG_PS_ICON_CONTRAST_RED
#define IMAG_PS_ICON_CONTRAST_GREEN IMAG_PS_ICON_CONTRAST_RED
#define IMAG_PS_ICON_CONTRAST_VIOLET IMAG_PS_ICON_CONTRAST_RED
#define IMAG_PS_ICON_CONTRAST_YELLOW IMAG_PS_ICON_CONTRAST_RED

#define IMAG_PS_ICON_ROTATE_BLUE IMAG_PS_ICON_ROTATE_RED
#define IMAG_PS_ICON_ROTATE_COPPER IMAG_PS_ICON_ROTATE_RED
#define IMAG_PS_ICON_ROTATE_GREEN IMAG_PS_ICON_ROTATE_RED
#define IMAG_PS_ICON_ROTATE_VIOLET IMAG_PS_ICON_ROTATE_RED
#define IMAG_PS_ICON_ROTATE_YELLOW IMAG_PS_ICON_ROTATE_RED

#define IMAG_PS_ICON_EFFECT_BLUE IMAG_PS_ICON_EFFECT_RED
#define IMAG_PS_ICON_EFFECT_COPPER IMAG_PS_ICON_EFFECT_RED
#define IMAG_PS_ICON_EFFECT_GREEN IMAG_PS_ICON_EFFECT_RED
#define IMAG_PS_ICON_EFFECT_VIOLET IMAG_PS_ICON_EFFECT_RED
#define IMAG_PS_ICON_EFFECT_YELLOW IMAG_PS_ICON_EFFECT_RED

#define IMAG_PS_ICON_CROP_BLUE IMAG_PS_ICON_CROP_RED
#define IMAG_PS_ICON_CROP_COPPER IMAG_PS_ICON_CROP_RED
#define IMAG_PS_ICON_CROP_GREEN IMAG_PS_ICON_CROP_RED
#define IMAG_PS_ICON_CROP_VIOLET IMAG_PS_ICON_CROP_RED
#define IMAG_PS_ICON_CROP_YELLOW IMAG_PS_ICON_CROP_RED

//rotate mirror horizontal option icon
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_VERTICAL.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_RED,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_VERTICAL_RED.png",IMG_CMP_PNG_ARGB_RLE,0) 
#define IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_BLUE IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_RED
#define IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_COPPER IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_RED
#define IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_GREEN IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_RED
#define IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_VIOLET IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_RED
#define IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_YELLOW IMAG_PS_ICON_ROTATE_MIRROR_HORIZONTAL_RED
//rotate mirror vertical option icon
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_HORIZONTAL.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_RED,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_MIRROR_HORIZONTAL_RED.png",IMG_CMP_PNG_ARGB_RLE,0) 
#define IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_BLUE IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_RED
#define IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_COPPER IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_RED
#define IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_GREEN IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_RED
#define IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_VIOLET IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_RED
#define IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_YELLOW IMAG_PS_ICON_ROTATE_MIRROR_VERTICAL_RED
#endif

RES_ADD_IMG(IMAG_PS_ICON_SLIDER_MINUS,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_SLIDER_MINUS.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_SLIDER_PLUS,"\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_SLIDER_PLUS.png",IMG_CMP_PNG_ARGB_RLE,0) 
RES_ADD_IMG(IMAG_PS_ICON_ROTATE_SAVE,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_EDIT_ROTATE_SAVE.png",IMG_CMP_PNG_ARGB_RLE,0) 

//lijinghua end
#ifdef PIC_EDIT_FRAME_SUPPORT
RES_ADD_IMG(IMAG_PS_ICON_FRAME,"\\MMI_RES_##\\IMAG\\IMAG_PS_ICON_FRAME.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
RES_ADD_IMG(IMAG_PS_ICON_TEXT,"\\MMI_RES_##\\IMAG\\IMAG_PS_ICON_TEXT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ICON_CLIP,"\\MMI_RES_##\\IMAG\\IMAG_PS_ICON_CLIP.png",IMG_CMP_PNG_ARGB_RLE,0)

//adjust menu icon
RES_ADD_IMG(IMAG_PS_ADJUST_ATTRIBUTE,"\\MMI_RES_##\\IMAG\\adjust\\IMAG_PS_ADJUST_ATTRIBUTE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ADJUST_COLOR,"\\MMI_RES_##\\IMAG\\adjust\\IMAG_PS_ADJUST_COLOR.png",IMG_CMP_PNG_ARGB_RLE,0)

//adjust menu icon
RES_ADD_IMG(IMAG_PS_ADJUST_ICON_BRIGHTNESS,"\\MMI_RES_##\\IMAG\\adjust\\IMAG_PS_ADJUST_ICON_BRIGHTNESS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ADJUST_ICON_CONTRAST,"\\MMI_RES_##\\IMAG\\adjust\\IMAG_PS_ADJUST_ICON_CONTRAST.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ADJUST_ICON_HUE,"\\MMI_RES_##\\IMAG\\adjust\\IMAG_PS_ADJUST_ICON_HUE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAG_PS_ADJUST_ICON_SATURATION,"\\MMI_RES_##\\IMAG\\adjust\\IMAG_PS_ADJUST_ICON_SATURATION.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAG_PS_ADJUST_PROCESS,"\\MMI_RES_##\\IMAG\\adjust\\IMAG_PS_ADJUST_PROCESS.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)
RES_ADD_IMG(IMAG_PS_ADJUST_PROCESS_SLIDE,"\\MMI_RES_##\\IMAG\\adjust\\IMAG_PS_ADJUST_PROCESS_SLIDE.png",IMG_CMP_PNG_ARGB_RLE,0)

//effect icon
RES_ADD_IMG(IMAGE_EFFECT_GRAY,"\\MMI_RES_##\\IMAG\\effect\\IMAG_PS_EFFECT_GRAYSCALE.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_COMPILE_E
RES_ADD_IMG(IMAGE_EFFECT_SEPIA,"\\MMI_RES_##\\IMAG\\effect\\IMAG_PS_EFFECT_SEPIA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EFFECT_SHARPEN,"\\MMI_RES_##\\IMAG\\effect\\IMAG_PS_EFFECT_SHARPEN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EFFECT_SMOOTH,"\\MMI_RES_##\\IMAG\\effect\\IMAG_PS_EFFECT_SMOOTH.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EFFECT_DIFFUSION,"\\MMI_RES_##\\IMAG\\effect\\IMAG_PS_EFFECT_DILATION.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EFFECT_EMBOSS,"\\MMI_RES_##\\IMAG\\effect\\IMAG_PS_EFFECT_EMBOSSMENT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EFFECT_EXPOSURE,"\\MMI_RES_##\\IMAG\\effect\\IMAG_PS_EFFECT_EXPOSURE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EFFECT_NEGATIVE_RGB,"\\MMI_RES_##\\IMAG\\effect\\IMAG_PS_EFFECT_NEGATIVE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_EFFECT_DENOISE,"\\MMI_RES_##\\IMAG\\effect\\IMAG_PS_EFFECT_MEDIAN.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
//frame icon
RES_ADD_IMG(IMAGE_PS_PREVIEW_FRAME1,"\\MMI_RES_##\\IMAG\\frame\\IMAGE_PS_PREVIEW_FRAME1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PS_PREVIEW_FRAME2,"\\MMI_RES_##\\IMAG\\frame\\IMAGE_PS_PREVIEW_FRAME2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PS_PREVIEW_FRAME3,"\\MMI_RES_##\\IMAG\\frame\\IMAGE_PS_PREVIEW_FRAME3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PS_PREVIEW_FRAME2_H,"\\MMI_RES_##\\IMAG\\frame\\IMAGE_PS_PREVIEW_FRAME2_H.png",IMG_CMP_PNG_ARGB_RLE,0)
//]]define image infomation


//[[define anim infomation
//]]define anim infomation


//[[define string infomation
//RES_ADD_STRING(TXT_PIC_SAVE,"Save") //replaced by common ID STXT_SOFTKEY_SAVE_MK
//RES_ADD_STRING(TXT_PIC_SAVEAS,"Save as")           //replaced by common ID TXT_COMMON_SAVE_AS  
RES_ADD_STRING(TXT_PIC_UNDO,"Undo")
//RES_ADD_STRING(TXT_PIC_ZOOM,"Zoom")    //replaced by common ID TXT_ZOOM
RES_ADD_STRING(TXT_PIC_ROTATE,"Rotate")
//RES_ADD_STRING(TXT_PIC_INSERT,"Insert")  //replaced by common ID STXT_SOFTKEY_ADD_MK
RES_ADD_STRING(TXT_PIC_ADJUST,"Adjust Image")
//RES_ADD_STRING(TXT_PIC_EFFECT,"Effect")    //replaced by common ID TXT_EFFECT
RES_ADD_STRING(TXT_PIC_CLIP,"Clip")
RES_ADD_STRING(TXT_PIC_FRAME,"Frame")
//RES_ADD_STRING(TXT_PIC_COLOR,"color")    //replaced by common ID TXT_COLOR
//RES_ADD_STRING(TXT_PIC_BRIGHTNESS,"Brightness")     //replaced by common ID TXT_COMMON_COMMON_BRIGHTNESS
//RES_ADD_STRING(TXT_PIC_CONSTRACT,"Constract")  //replaced by common ID TXT_COMM_CONTRAST
RES_ADD_STRING(TXT_PIC_SATURATION,"Saturation")
RES_ADD_STRING(TXT_PIC_HUE,"Hue")
RES_ADD_STRING(TXT_PIC_GRAY,"Gray")
RES_ADD_STRING(TXT_PIC_SMOOTH,"Smooth")
RES_ADD_STRING(TXT_PIC_EMBOSS,"Emboss")
RES_ADD_STRING(TXT_PIC_SHARPEN,"Sharpen")
RES_ADD_STRING(TXT_PIC_EXPOSURE,"Exposure")
//RES_ADD_STRING(TXT_PIC_IMAGE_DENOISE,"Image Denoise")    //case3: defined but not used
RES_ADD_STRING(TXT_PIC_DIFFUSION,"Diffusion")
RES_ADD_STRING(TXT_PIC_CHARACTER,"Character")
RES_ADD_STRING(TXT_PIC_ADJUST_SIZE,"Adjust Size")
RES_ADD_STRING(TXT_PIC_FRAME_1,"Frame1")
RES_ADD_STRING(TXT_PIC_FRAME_2,"Frame 2")
RES_ADD_STRING(TXT_PIC_FRAME_3,"Frame3")
//RES_ADD_STRING(TXT_PIC_BIG,"Big")  //replaced by common ID TXT_COMM_LARGE
//RES_ADD_STRING(TXT_PIC_MIDDLE,"Middle")  //replaced by common ID TXT_COMMON_MID
//RES_ADD_STRING(TXT_PIC_LITTLE,"Little")    //replaced by common ID TXT_FONT_SMALL
//RES_ADD_STRING(TXT_PIC_SIZE,"Size")  //replaced by common ID TXT_COMMON_SIZE
//RES_ADD_STRING(TXT_PIC_CONTENT,"Content")  //replaced by common ID TXT_COMMON_CONTENTS
//RES_ADD_STRING(TXT_PIC_CHAR_SIZE,"size")  //replaced by common ID TXT_COMMON_FONT_SIZE
//RES_ADD_STRING(TXT_PIC_CHAR_COLOR,"Color")  //replaced by common ID TXT_COMMON_FONT_COLOR
RES_ADD_STRING(TXT_PIC_CHAR_FRAME_COLOR,"Frame Color")
RES_ADD_STRING(TXT_PIC_CHAR_DIRECTION,"Direction")
RES_ADD_STRING(TXT_PIC_INPUT_CHAR,"Input Word")
RES_ADD_STRING(TXT_PIC_HORIZONTAL,"Horizontal")
RES_ADD_STRING(TXT_PIC_VERTICAL,"Vertical")
//RES_ADD_STRING(TXT_PIC_QUERY_OVERWRITE,"File exist, Overwrite?")  //replaced by common ID TXT_FILE_EXIST_OVERWRITE
RES_ADD_STRING(TXT_PIC_RED,"Red")
RES_ADD_STRING(TXT_PIC_GREEN,"Green")
RES_ADD_STRING(TXT_PIC_BLUE,"Blue")
RES_ADD_STRING(TXT_PIC_CYAN,"Cyan")
RES_ADD_STRING(TXT_PIC_MAGENTA,"Magenta")
RES_ADD_STRING(TXT_PIC_YELLOW,"Yellow")
RES_ADD_STRING(TXT_PIC_BRIGHT_DOWN_LIMIT,"-100")
RES_ADD_STRING(TXT_PIC_BRIGHT_UP_LIMIT,"100")
RES_ADD_STRING(TXT_PIC_CONSTRACT_DOWN_LIMIT,"0")
RES_ADD_STRING(TXT_PIC_CONSTRACT_UP_LIMIT,"128")
RES_ADD_STRING(TXT_PIC_HUE_DOWN_LIMIT,"0")
RES_ADD_STRING(TXT_PIC_HUE_UP_LIMIT,"315")
RES_ADD_STRING(TXT_PIC_SEPIA,"Sepia")
RES_ADD_STRING(TXT_PIC_NEGATIVE_RGB,"Negative")
RES_ADD_STRING(TXT_PIC_DENOISE,"Denoise")
RES_ADD_STRING(TXT_PIC_NOSAVE,"Picture is changed, exit?")
//RES_ADD_STRING(TXT_PIC_ERROR_OCCUR,"Error Occurs！")  //replaced by common ID TXT_ERROR_OCCUR
RES_ADD_STRING(TXT_PIC_ADD_CHAR,"Add Character")
RES_ADD_STRING(TXT_PIC_NOT_SUPPORTED_SIZE,"Not Supported Size")
//RES_ADD_STRING(TXT_PIC_MAX_DEPTH,"Max Depth")    //replaced by common ID TXT_MAX_DEPTH
RES_ADD_STRING(TXT_PIC_READ_FAIL,"Read file fail")
RES_ADD_STRING(TXT_PIC_TOO_SMALL,"Image too small")

RES_ADD_STRING(TXT_PIC_BRIGHT_CONSTRACT,"Brightness Constract") //亮度对比度
RES_ADD_STRING(TXT_PIC_HUE_SATURATION,"Hue Saturation") //色相饱和度
RES_ADD_STRING(TXT_PIC_PDA_ADJUST_SIZE,"Adjust Size")
RES_ADD_STRING(TXT_PIC_PDA_ADJUST_COLOR,"Adjust color")

RES_ADD_STRING(TXT_PIC_BRI_CON_HUE,"Brightness,Constract,Hue") //亮度、对比度、色度
#ifdef PIC_EDIT_U200_SUPPORT
RES_ADD_STRING(TXT_PIC_ROTATE_TITLE,"Image Rotate")
RES_ADD_STRING(TXT_PIC_CLIP_TITLE,"Clip Insert")
RES_ADD_STRING(TXT_PIC_ADJUST_TITLE,"Image Adjust")
RES_ADD_STRING(TXT_PIC_EFFECT_TITLE,"Image Effect")
RES_ADD_STRING(TXT_PIC_FRAME_TITLE,"Image Frame")
#endif
RES_ADD_STRING(TXT_PIC_ADJUST_ICON,"Adjust")
RES_ADD_STRING(TXT_PIC_CLIP_ICON,"Clip")
//]]define string infomation
RES_ADD_STRING(TXT_PIC_TOO_SMALL_SIZE,"This Picture is too small to paste!")

//lijinghua add for edit menu
RES_ADD_STRING(STR_PHOTO_EDIT_BRIGHTNESS_EXT01,"Brightness")
RES_ADD_STRING(STR_PHOTO_EDIT_CONTRAST_EXT01,"Contrast")
RES_ADD_STRING(STR_PHOTO_EDIT_EFFECT_EXT01,"Effects")
RES_ADD_STRING(STR_PHOTO_EDIT_CROP_EXT01,"Crop")
RES_ADD_STRING(STR_PHOTO_EDIT_ROTATE_EXT01,"Rotate")
RES_ADD_STRING(STXT_SOFTKEY_APPLY_MK,"Apply")
RES_ADD_STRING(STR_PHOTO_PORTRAIT_EXT01,"Portrait")
RES_ADD_STRING(STR_PHOTO_SQUARE_EXT01,"Square")
RES_ADD_STRING(STR_PHOTO_LANDSCAPE_EXT01,"Landscape")
RES_ADD_STRING(STR_PHOTO_EFFECT_BOX_BLUR_EXT01,"Box blur")
RES_ADD_STRING(STR_PHOTO_EFFECT_BW_EXT01,"Black & white")
RES_ADD_STRING(STR_PHOTO_EFFECT_DILATION_EXT01,"Dilation")
RES_ADD_STRING(STR_PHOTO_EFFECT_EMBOSSMENT_EXT01,"Embossment")
RES_ADD_STRING(STR_PHOTO_EFFECT_EXPOSURE_EXT01,"Exposure")
RES_ADD_STRING(STR_PHOTO_EFFECT_GRAYSCALE,"Greyscale")
RES_ADD_STRING(STR_PHOTO_EFFECT_MEDIAN_EXT01,"Median")
RES_ADD_STRING(STR_PHOTO_EFFECT_NEGATIVE_EXT01,"Negative")
RES_ADD_STRING(STR_PHOTO_EFFECT_POSTERISE_EXT01,"Posterise")
RES_ADD_STRING(STR_PHOTO_EFFECT_SEPIA,"Sepia")
RES_ADD_STRING(STR_PHOTO_EFFECT_SHARPEN_EXT01,"Sharpen")
RES_ADD_STRING(STR_PHOTO_EFFECT_SMOOTH_EXT01,"Smooth")
RES_ADD_STRING(STR_PHOTO_EFFECT_SOLARISE_B,"Solarise")
RES_ADD_STRING(STR_PHOTO_EFFECT_VINTAGE_EXT01,"Vintage")

//lijinghua end

//[[define data infomation
//]]define data infomation

#endif  //PIC_EDITOR_SUPPORT
