
#ifdef JAVA_SUPPORT_IA

//[[define image infomation

RES_ADD_IMG(JAVA_ICON,"\\MMI_RES_##\\IMAG\\JAVA_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(JAVA_ICON_SD,"\\MMI_RES_##\\IMAG\\JAVA_ICON_SD.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IA_JAVA_LOGO,"\\MMI_RES_##\\IMAG\\IA_JAVA_LOGO.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_DOWNLOAD_ENTER,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_DOWNLOAD_ENTER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_DOWNLOAD_ENTER_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_DOWNLOAD_ENTER_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)


#ifdef MMI_PDA_SUPPORT
//RES_ADD_IMG(IMG_JAVA_MENU_REFRESH_ICON,"\\MMI_RES_##\\IMAG\\IMG_JAVA_MENU_REFRESH_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_JAVA_MENU_LOCATION_INSTALL_ICON,"\\MMI_RES_##\\IMAG\\IMG_JAVA_MENU_LOCATION_INSTALL_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_JAVA_MENU_RESET_SYSTEM_ICON,"\\MMI_RES_##\\IMAG\\IMG_JAVA_MENU_RESET_SYSTEM_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_JAVA_MENU_DOWNLOAD_ICON,"\\MMI_RES_##\\IMAG\\IMG_JAVA_MENU_DOWNLOAD_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_JAVA_MENU_SETTING_ICON,"\\MMI_RES_##\\IMAG\\IMG_JAVA_MENU_SETTING_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef MMI_PDA_SUPPORT
#if defined (MAINLCD_SIZE_320X480) ||defined (MAINLCD_SIZE_240X400)||defined (MAINLCD_SIZE_240X320)
//KEYBOARD bg
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD_BG,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD_BG.png",IMG_CMP_PNG_SABM_RLE |SABM_HOR_STRETCH,0)

//KEYBOARD1
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_LS_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_LS_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_LS_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_LS_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_UP_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_UP_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_UP_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_UP_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_RS_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_RS_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_RS_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_RS_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_NUM_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_NUM_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_NUM_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_NUM_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_LEFT_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_LEFT_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_LEFT_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_LEFT_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_DOWN_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_DOWN_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_DOWN_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_DOWN_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_RIGHT_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_RIGHT_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_RIGHT_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_RIGHT_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_OK_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_OK_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_OK_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_OK_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)

//KEYBOARD2
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_LS_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_LS_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_LS_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_LS_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM1_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM1_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM1_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM1_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM2_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM2_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM2_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM2_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM3_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM3_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM3_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM3_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM4_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM4_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM4_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM4_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM5_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM5_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM5_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM5_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM6_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM6_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM6_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM6_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_RS_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_RS_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_RS_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_RS_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_RETURN_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_RETURN_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_RETURN_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_RETURN_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM7_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM7_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM7_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM7_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM8_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM8_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM8_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM8_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM9_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM9_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM9_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM9_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM0_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM0_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM0_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM0_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_ASTERISK_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_ASTERISK_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_ASTERISK_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_ASTERISK_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_POUND_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_POUND_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_POUND_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_POUND_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif

//]]define image infomation





//[[define anim infomation

//]]define anim infomation





//[[define string infomation

RES_ADD_STRING(TXT_COMM_JAVAAPP,"Java application")

//RES_ADD_STRING(TXT_JAVA_AMS,"App Manager Machine")    //replaced by common ID TXT_APP_MANAGER

//RES_ADD_STRING(TXT_JAVA_DOWNLOAD,"Download Link")  //replaced by common ID TXT_COMMON_DOWNLOAD_COMN

RES_ADD_STRING(TXT_JAVA_AMS_OPTION_PLAY,"Play")

//RES_ADD_STRING(TXT_JAVA_AMS_OPTION_DELETE,"Delete")      //replaced by common ID TXT_DELETE

// RES_ADD_STRING(TXT_JAVA_AMS_OPTION_INFO,"Infomation") //case 3:defined but not used

RES_ADD_STRING(TXT_JAVA_AMS_OPTION_PERMITION_SET,"Permition Set")
//RES_ADD_STRING(TXT_JAVA_LINKSET,"Linkset")        //replaced by common ID TXT_COMMON_LINKSETTING

//RES_ADD_STRING(TXT_JAVA_AMS_OPTION_SET_CALL,"Allow Call")  //replaced by common ID TXT_COMM_CALL

RES_ADD_STRING(TXT_JAVA_AMS_OPTION_SET_LINK,"Allow Visit Internet")

//RES_ADD_STRING(TXT_JAVA_AMS_OPTION_SET_MESSAGE,"Allow Send Message")    //replaced by common ID TXT_MSG_SETTINGS

RES_ADD_STRING(TXT_JAVA_AMS_OPTION_SET_AUTOPLAY,"Allow Autoplay")

RES_ADD_STRING(TXT_JAVA_AMS_OPTION_SET_LOCATION,"Allow Native Link")

RES_ADD_STRING(TXT_JAVA_AMS_OPTION_SET_MULTIM,"Allow REC")

RES_ADD_STRING(TXT_JAVA_AMS_OPTION_SET_USERDATAREAD,"Allow Read User Infomation")

RES_ADD_STRING(TXT_JAVA_AMS_OPTION_SET_USERDATAWRITE,"Allow Write User Infomation")

//RES_ADD_STRING(TXT_MMIJAVA_AMS_OPTION_SET_0,"Ask Every Time")    //replaced by common ID TXT_COMMON_ASK_EVERYTIME

RES_ADD_STRING(TXT_MMIJAVA_AMS_OPTION_SET_1,"Ask Only Once")

//RES_ADD_STRING(TXT_MMIJAVA_AMS_OPTION_SET_2,"No Allow") //replaced by common ID TXT_COMM_NOT_ALLOWED

RES_ADD_STRING(TXT_MMIJAVA_AMS_OPTION_SET_3,"Ask Never")

//RES_ADD_STRING(TXT_JAVA_APP_INSTALL,"Install Application") //replaced by common ID TXT_COM_LOCALINSTALL

//RES_ADD_STRING(TXT_JAVA_APP_INSTALL_FAIL,"Install Fail") //replaced by common ID TXT_COMM_INSTALL_FAILED

RES_ADD_STRING(TXT_JAVA_APP_INSTALL_UPDATE,"Application exists,Will be installed version is newer,update?")

RES_ADD_STRING(TXT_JAVA_APP_INSTALL_REPLACE,"Application exists, Will be installed version is the same,update?")

//RES_ADD_STRING(TXT_JAVA_APP_INSTALLING,"Installing,Please Wait...")  //replaced by common ID TXT_COMMON_INSTALL

//RES_ADD_STRING(TXT_JAVA_APP_INSTALL_COMPLETE,"Install Complete")   //replaced by common ID TXT_COMM_INSTALL_COMPLETE

//RES_ADD_STRING(TXT_JAVA_APP_NAME,"App Name")//case3:defined but not used

//S_ADD_STRING(TXT_JAVA_APP_VERSION,"App Version")//case3:defined but not used

//RES_ADD_STRING(TXT_JAVA_APP_VENDOR,"App Vendor")//case3:defined but not used

//RES_ADD_STRING(TXT_JAVA_APP_JARSIZE,"Jar Size")//case3:defined but not used

//RES_ADD_STRING(TXT_JAVA_DETAIL_NAME,"App Name")  //replaced by common ID TXT_INPUT_NAME

//RES_ADD_STRING(TXT_JAVA_DETAIL_VERSION,"App Version") //replaced by common id TXT_COMM_VERSION_1

RES_ADD_STRING(TXT_JAVA_DETAIL_VENDOR,"App Vendor")
//RES_ADD_STRING(TXT_JAVA_DETAIL_SIZE,"App Size")  //replaced by common ID TXT_DETAIL_SIZE
RES_ADD_STRING(TXT_JAVA_DETAIL_DOMAIN,"Domain")
RES_ADD_STRING(TXT_TVOUT_FORBID_JAVA,"TV-OUT is in use,The Java is forbid!")

//RES_ADD_STRING(TXT_JAVA_LOCALINSTALL,"Install") //replaced by common ID TXT_COM_LOCALINSTALL

//RES_ADD_STRING(TXT_JAVA_USER1,	"SIM1 network account")      //replaced by common ID TXT_COMMON_SET_NET_SIM1
//RES_ADD_STRING(TXT_JAVA_USER2,	"SIM2 network account")      //replaced by common ID TXT_COMMON_SET_NET_SIM2
#if defined(MMI_MULTI_SIM_SYS_TRI)||defined(MMI_MULTI_SIM_SYS_QUAD)
//RES_ADD_STRING(TXT_JAVA_USER3,	"SIM3 network account")      //replaced by common ID TXT_COMMON_SET_NET_SIM3
#endif
#if defined(MMI_MULTI_SIM_SYS_QUAD)
//RES_ADD_STRING(TXT_JAVA_USER4,	"SIM4 network account")      //replaced by common ID TXT_COMMON_SET_NET_SIM4 
#endif
RES_ADD_STRING(TXT_JAVA_USER,	"Please select network type")
RES_ADD_STRING(TXT_JAVA_CHECKRMS, "Keep the information?")
//RES_ADD_STRING(TXT_JAVA_LOCAL_INSTALL,"Local Install") //replaced by common ID TXT_COMM_LOCAL_INSTALL
RES_ADD_STRING(TXT_JAVA_FILE_FULL,"JAVA File Full")
//RES_ADD_STRING(TXT_JAVA_OUT_MEMORY,"Out of Memory")//case 3:defined but not used
RES_ADD_STRING(TXT_JAVA_FILE_TOO_BIG,"File too big,can't install")

RES_ADD_STRING(TXT_PIM_PHONE_CONTACT,	"PhoneConatct")
RES_ADD_STRING(TXT_PIM_SIM_CONTACT,	"SimContact")
RES_ADD_STRING(TXT_PIM_FIELD_TEL,	"Tel.")
RES_ADD_STRING(TXT_PIM_FIELD_FORMATTED_NAME,	"Name")
RES_ADD_STRING(TXT_PIM_FIELD_EMAIL,	"E-Mail")
RES_ADD_STRING(TXT_PIM_FIELD_PHO,	"InComming-Pho")
RES_ADD_STRING(TXT_PIM_FIELD_NOTE,	"Note")
RES_ADD_STRING(TXT_PIM_FIELD_TITLE,	"Title")
RES_ADD_STRING(TXT_PIM_FIELD_ORG,	"Org")
RES_ADD_STRING(TXT_PIM_FIELD_WORK_ADR,	"WorkAddress")
RES_ADD_STRING(TXT_PIM_FIELD_PHOTO_URL,	"Photo-URL")
RES_ADD_STRING(TXT_PIM_ATTR_MOBILE,	"Mobile")
RES_ADD_STRING(TXT_PIM_ATTR_HOME,	"Home")
RES_ADD_STRING(TXT_PIM_ATTR_WORK,	"Work")
RES_ADD_STRING(TXT_JAVA_WAIT,"Java state Switch, please wait...")
RES_ADD_STRING(TXT_JAVA_WAITQUIT,"Java Quit, please wait...")
RES_ADD_STRING(TXT_JAVA_FORCEQUIT,"Forcely quit may cause exception,Are you sure to quit?")

//hanker add for java bge begin
//RES_ADD_STRING(TXT_JAVA_BGE_RESUME,	"Resume")       //replaced by common ID TXT_COMMON_COMMON_CONTINUE
//RES_ADD_STRING(TXT_JAVA_BGE_MINIMIZE,	"Minimize")  //replaced by common ID TXT_MINIMIZE
//RES_ADD_STRING(TXT_JAVA_BGE_PAUSE,		"Pause")    //replaced by common ID  TXT_PAUSE
//RES_ADD_STRING(TXT_JAVA_BGE_EXIT,		"Exit")    //replaced by common ID  STXT_EXIT

RES_ADD_STRING(TXT_JAVA_INSTALL_SELECT_DISK,"Select Disk")
//RES_ADD_STRING(TXT_JAVA_INSTALL_SELECT_DISK_D,"Phone Disk")//case 3:defined but not used
//RES_ADD_STRING(TXT_JAVA_INSTALL_SELECT_DISK_E,"T Disk")//case 3:defined but not used
RES_ADD_STRING(TXT_JAVA_INSTALL_SELECT_DISK_C,"System Disk")
RES_ADD_STRING(TXT_JAVA_DELETE_MIDLET_SUIT,"Have some sub-midlet, and RMS, delete?")
RES_ADD_STRING(TXT_JAVA_DELETE_MIDLET_RMS,"Has RMS, delete?")//case 3:defined but not used

//RES_ADD_STRING(TXT_JAVA_ERR_OTA_NO_ENOUGH_SPACE,"No Enough Space")  //replaced by common ID TXT_COMMON_NO_MEMORY
//RES_ADD_STRING(TXT_JAVA_ERR_OTA_USER_CANCEL,"User Cancelled")    //replaced by common ID TXT_USER_CANCEL
RES_ADD_STRING(TXT_JAVA_ERR_OTA_LOSS_OF_SERVICE,"Loss of Service")
RES_ADD_STRING(TXT_JAVA_ERR_OTA_JAR_SIZE_MISMATCH,"JAR size Mismatch")
RES_ADD_STRING(TXT_JAVA_ERR_OTA_ATTRIBUTE_MISMATCH,"Attribute Mismatch")
RES_ADD_STRING(TXT_JAVA_ERR_OTA_INVALID_JAD,"Invalid Descriptor")
RES_ADD_STRING(TXT_JAVA_ERR_OTA_INVALID_JAR,"Invalid JAR")
RES_ADD_STRING(TXT_JAVA_ERR_OTA_CLDC_MIDP_VERSION,"Incompatible Configuration or Profile")
RES_ADD_STRING(TXT_JAVA_ERR_OTA_AUTHENTICATION_FAILURE,"Application authetication failure")
RES_ADD_STRING(TXT_JAVA_ERR_OTA_AUTHORIZATION_FAILURE,"Application authorization failure")
RES_ADD_STRING(TXT_JAVA_ERR_OTA_PUSH_REGISTRATION_FALIURE,"Push registration failure")
RES_ADD_STRING(TXT_JAVA_ERR_OTA_UNDEFINED,"999 Non-defined OTA error code")

RES_ADD_STRING(TXT_JAVA_VMEXIT_EXCEPTION_NULL_POINT,"EXCEPTION NULL POINT")
RES_ADD_STRING(TXT_JAVA_VMEXIT_EXCEPTION_ARITHMETIC,"EXCEPTION ARITHMETIC")
RES_ADD_STRING(TXT_JAVA_VMEXIT_EXCEPTION_ARRRYINDEX_OUTOFBOUNDS,"EXCEPTION OUTOFBOUNDS")
RES_ADD_STRING(TXT_JAVA_VMEXIT_EXCEPTION_NO_CLASS_DEF_FOUND,"NO CLASS DEF FOUND")
//RES_ADD_STRING(TXT_JAVA_VMEXIT_EXCEPTION_OUT_OF_MEMORY,"OUT OF MEMORY")  //replaced by common ID TXT_COMMON_NO_MEMORY
RES_ADD_STRING(TXT_JAVA_VMEXIT_INTERNALERROR_FATAL_ERROR,"FATAL ERROR")
//RES_ADD_STRING(TXT_JAVA_VMEXIT_EXCEPTION_UNDEFINED,"Exception Occur")  //replaced by common ID TXT_ERROR_OCCUR
RES_ADD_STRING(TXT_EXIT_BACKGROUND_JAVA, "Java is background running, Pls quit it")
RES_ADD_STRING(TXT_JAVA_DOMAIN_UNSPECIFIED,"Untrusted")
RES_ADD_STRING(TXT_JAVA_DOMAIN_MANUFACTURER,"Manufacturer")
RES_ADD_STRING(TXT_JAVA_DOMAIN_OPERATOR,"Operator")
RES_ADD_STRING(TXT_JAVA_DOMAIN_THIRD_PARTY,"Trusted Third Party")
RES_ADD_STRING(TXT_JAVA_FILE_DAMAGED,"Java file damaged,reinstall it please")

RES_ADD_STRING(TXT_JAVA_AMS_OPTION_APPLICATION_SET,"Application Set")
RES_ADD_STRING(TXT_JAVA_SELECT_NET_SIM1_NOT_OK,"SIM1 Can't be used")
RES_ADD_STRING(TXT_JAVA_SELECT_NET_SIM2_NOT_OK,"SIM2 Can't be used")
#if defined(MMI_MULTI_SIM_SYS_TRI)||defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_JAVA_SELECT_NET_SIM3_NOT_OK,"SIM3 Can't be used")
#endif
#if defined(MMI_MULTI_SIM_SYS_QUAD)
RES_ADD_STRING(TXT_JAVA_SELECT_NET_SIM4_NOT_OK,"SIM4 Can't be used")
#endif


RES_ADD_STRING(TXT_DOWNLOAD_EBOOK,"Ebook Download")
RES_ADD_STRING(TXT_DOWNLOAD_GAME,"Game Download")
RES_ADD_STRING(TXT_DOWNLOAD_OTHER,"Other Download")
//RES_ADD_STRING(TXT_DOWNLOAD_SET,"Download Set")    //replaced by common ID TXT_DOWNLOAD_SETINGS

RES_ADD_STRING(TXT_JAVA_DOWNLOAD_GAME_URL,"Game URL")
RES_ADD_STRING(TXT_JAVA_DOWNLOAD_EBOOK_URL,"Ebook URL")
RES_ADD_STRING(TXT_JAVA_DOWNLOAD_OTHER_URL,"Other URL")
//RES_ADD_STRING(TXT_JAVA_DOWNLOAD_INVALID_URL,"Invalid URL")    //replaced by common ID TXT_INVALID_URL
RES_ADD_STRING(TXT_JAVA_LOCAL_CHECK,"Local checking...")
//RES_ADD_STRING(TXT_JAVA_UPDATE,"Application Update")      //replaced by common ID TXT_COMMON_UPDATE
RES_ADD_STRING(TXT_JAVA_CANNOT_UPDATE,"NO valid url,can't update!")
RES_ADD_STRING(TXT_JAVA_LAUNCH_MIDLET_SUITE,"Launch Midlet Suite?")
RES_ADD_STRING(TXT_JAVA_OTA_NOTIFY_SENDING,"OTA Notify Sending,Quit")
RES_ADD_STRING(TXT_JAVA_RESUME_WIN_TITLE,"Java is running,please select")
RES_ADD_STRING(TXT_JAVA_INSTALL_IN_RUNNING,"Java is running.Quit to install?")
RES_ADD_STRING(TXT_JAVA_PUSH_IN_RUNNING,"Java push is running.Quit to install?")
RES_ADD_STRING(TXT_JAVA_PREVIOUS_INSTALL_NOT_COMPLETED,"Previous install process has not completed.")
RES_ADD_STRING(TXT_JAVA_APP_INSTALL_ROLLBACK,"Application exists, Will be installed version is older,update?")
RES_ADD_STRING(TXT_JAVA_APP_RESET_SYSTEM_PROMPT,"Reset the system,will back to init state,Are you sure?")
RES_ADD_STRING(TXT_JAVA_APP_RESET_SYSTEM,"Reset system")
#ifdef DRM_SUPPORT
RES_ADD_STRING(TXT_JAVA_DRM_NOT_JAVA,"not include java midlet")
RES_ADD_STRING(TXT_JAVA_DRM_INVALID_COPYRIGHTS,"Invalid CopyRights")
#endif
RES_ADD_STRING(TXT_JAVA_SUITE_NOT_EXIST,"This suite is not exist!")
RES_ADD_STRING(TXT_JAVA_SUITE_IS_RUNING_PLEASE_STOP," is running,please stop it!")

RES_ADD_STRING(TXT_JVM_IS_RUNNING_CANNOT_DELETE_SUITE,"Jvm is runing, can't execute delete action!")
RES_ADD_STRING(TXT_JAVA_PREINSTALL_SUITE_CANNOT_DELETE,"Preinstall suite can't be  deleted")

#endif

