//[[define image infomation
//RES_ADD_IMG(IMAGE_CLOCK_ALARM_ALERT,"\\MMI_RES_##\\IMAG\\Alarm\\IMAGE_CLOCK_ALARM_ALERT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_ALARM_WEEK_PRESSED,"\\MMI_RES_##\\IMAG\\Alarm\\IMAGE_CLOCK_ALARM_WEEK_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_ALARM_WEEK_ENABLED,"\\MMI_RES_##\\IMAG\\Alarm\\IMAGE_CLOCK_ALARM_WEEK_ENABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_ALARM_WEEK_DISABLED,"\\MMI_RES_##\\IMAG\\Alarm\\IMAGE_CLOCK_ALARM_WEEK_DISABLED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_ALARM_WEEK_MARK,"\\MMI_RES_##\\IMAG\\Alarm\\IMAGE_CLOCK_ALARM_WEEK_MARK.png",IMG_CMP_PNG_ARGB_RLE,0)

//RES_ADD_IMG(IMAGE_CALENDAR_ALERT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_ALERT.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_SCHEDULE_ARRANGE_01,"\\MMI_RES_##\\IMAG\\Schedule\\IMAGE_SCHEDULE_ARRANGE_1.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_ALARM_ARRANGE,"\\MMI_RES_##\\IMAG\\Schedule\\IMAGE_ALARM_ARRANGE.bmp",IMG_CMP_BMP_16_565_RLE,0)

#ifndef MMI_ALARM_MINI_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_ALARM_TAB_DEFAULT,"\\MMI_RES_##\\IMAG\\Alarm\\IMAGE_CLOCK_ALARM_TAB_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_ALARM_TAB_FOCUSED,"\\MMI_RES_##\\IMAG\\Alarm\\IMAGE_CLOCK_ALARM_TAB_FOCUSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined MMI_ISTYLE_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_ALARM_ISTYLETAB_DEFAULT,"\\MMI_RES_##\\IMAG\\Alarm\\IMAGE_CLOCK_ALARM_ISTYLETAB_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_ALARM_ISTYLETAB_FOCUSED,"\\MMI_RES_##\\IMAG\\Alarm\\IMAGE_CLOCK_ALARM_ISTYLETAB_FOCUSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif

//RES_ADD_IMG(IMAGE_CALENDAR_BG,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_BG.png",IMG_CMP_PNG_SABM_RLE |SABM_HOR_STRETCH,0)
//RES_ADD_IMG(IMAGE_CALENDAR_LEFT_ARROW,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_LEFT_ARROW.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_CALENDAR_LEFT_ARROW_DOWN,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_LEFT_ARROW_DOWN.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_CALENDAR_RIGHT_ARROW,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_RIGHT_ARROW.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_CALENDAR_RIGHT_ARROW_DOWN,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_RIGHT_ARROW_DOWN.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_CALENDAR_WEEK_BG,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_WEEK_BG.png",IMG_CMP_PNG_SABM_RLE |SABM_HOR_STRETCH,0)
//RES_ADD_IMG(IMAGE_CALENDAR_UP_ARROW,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_UP_ARROW.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_CALENDAR_UP_ARROW_DOWN,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_UP_ARROW_DOWN.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_CALENDAR_DOWN_ARROW,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_DOWN_ARROW.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_CALENDAR_DOWN_ARROW_DOWN,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_DOWN_ARROW_DOWN.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_CALENDAR_WEEK_DOT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_WEEK_DOT.png",IMG_CMP_PNG_ARGB_RLE,0)

#ifdef MMI_PDA_SUPPORT
#if 0
RES_ADD_IMG(IMG_CALENDAR_YEAR_BG,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_YEAR_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH|SABM_VER_STRETCH,0)
RES_ADD_IMG(IMAGE_CALENDAR_RIGHT_OFF,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_RIGHT_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_RIGHT_ON,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_RIGHT_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_LEFT_OFF,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_LEFT_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_LEFT_ON,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_LEFT_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_COMMENT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_COMMENT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_CUR_FOCUS,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_CUR_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_CUR_DATE,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_CUR_DATE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_CUR_DATE_COMMENT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_CUR_DATE_COMMENT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_CUR_FOCUS_COMMENT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_CUR_FOCUS_COMMENT.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMG_CALENDAR_SCH_VIEW_TAB_ICON_OFF,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_SCH_VIEW_TAB_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CALENDAR_SCH_VIEW_TAB_ICON_ON,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_SCH_VIEW_TAB_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CALENDAR_WEEKLY_VIEW_TAB_ICON_OFF,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_WEEKLY_VIEW_TAB_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CALENDAR_WEEKLY_VIEW_TAB_ICON_ON,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_WEEKLY_VIEW_TAB_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CALENDAR_MONTHLY_VIEW_TAB_ICON_OFF,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_MONTHLY_VIEW_TAB_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CALENDAR_MONTHLY_VIEW_TAB_ICON_ON,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_MONTHLY_VIEW_TAB_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(ISTYLE_IMG_CALENDAR_SCH_VIEW_TAB_ICON_OFF,"\\MMI_RES_##\\IMAG\\Calendar\\istyle\\ISTYLE_IMG_CALENDAR_SCH_VIEW_TAB_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMG_CALENDAR_SCH_VIEW_TAB_ICON_ON,"\\MMI_RES_##\\IMAG\\Calendar\\istyle\\ISTYLE_IMG_CALENDAR_SCH_VIEW_TAB_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMG_CALENDAR_WEEKLY_VIEW_TAB_ICON_OFF,"\\MMI_RES_##\\IMAG\\Calendar\\istyle\\ISTYLE_IMG_CALENDAR_WEEKLY_VIEW_TAB_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMG_CALENDAR_WEEKLY_VIEW_TAB_ICON_ON,"\\MMI_RES_##\\IMAG\\Calendar\\istyle\\ISTYLE_IMG_CALENDAR_WEEKLY_VIEW_TAB_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMG_CALENDAR_MONTHLY_VIEW_TAB_ICON_OFF,"\\MMI_RES_##\\IMAG\\Calendar\\istyle\\ISTYLE_IMG_CALENDAR_MONTHLY_VIEW_TAB_ICON_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(ISTYLE_IMG_CALENDAR_MONTHLY_VIEW_TAB_ICON_ON,"\\MMI_RES_##\\IMAG\\Calendar\\istyle\\ISTYLE_IMG_CALENDAR_MONTHLY_VIEW_TAB_ICON_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

RES_ADD_IMG(IMG_CALENDAR_MENU_CLEAN_TODAY_ICON,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_MENU_CLEAN_TODAY_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CALENDAR_MENU_ADD_ICON,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_MENU_ADD_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CALENDAR_MENU_CLEAN_GOTO_DATE_ICON,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_MENU_CLEAN_GOTO_DATE_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CALENDAR_MENU_VIEW_ICON,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_MENU_VIEW_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CALENDAR_MENU_LURA_DETAIL_ICON,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_MENU_LURA_DETAIL_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_VCALENDAR_SUPPORT
RES_ADD_IMG(IMG_CALENDAR_MENU_EXPORT_ICON,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_MENU_EXPORT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
//RES_ADD_IMG(IMG_CALENDAR_LURA_BG,"\\MMI_RES_##\\IMAG\\Calendar\\IMG_CALENDAR_LURA_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_ALERT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_ALERT.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef CALENDAR_SUPPORT
//#ifndef MMI_GUI_STYLE_MINISCREEN
RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_BG,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
//#endif
//RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_BLUE_DEFAULT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_BLUE_DEFAULT.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_COMMENT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_COMMENT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_DEFAULT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_DEFAULT.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_FOCUSED,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_FOCUSED.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_GREEN_DEFAULT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_GREEN_DEFAULT.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
#ifdef MMI_CALENDAR_DAILY_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_ORANGE_DEFAULT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_ORANGE_DEFAULT.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
#endif
#ifndef MMI_CALENDAR_MINI_SUPPORT
#ifdef MMI_PDA_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_POINT_DEFAULT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_POINT_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_POINT_FOCUSED,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_POINT_FOCUSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef TOUCH_PANEL_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_LEFT_DEFAULT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_LEFT_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_RIGHT_DEFAULT,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_RIGHT_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#if 0
RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_LEFT_PRESSED,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_LEFT_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_CALENDAR_RIGHT_PRESSED,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CLOCK_CALENDAR_RIGHT_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#ifdef MMI_ALARM_GESTURE_CLOCK_SUPPORT
RES_ADD_IMG(IMG_CLOCK_AM,"\\MMI_RES_##\\IMAG\\AlmClk\\IMG_CLOCK_AM.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMG_CLOCK_BG,"\\MMI_RES_##\\IMAG\\AlmClk\\IMG_CLOCK_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLOCK_CENTER,"\\MMI_RES_##\\IMAG\\AlmClk\\IMG_CLOCK_CENTER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLOCK_DAY,"\\MMI_RES_##\\IMAG\\AlmClk\\IMG_CLOCK_DAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLOCK_HOUR_HAND,"\\MMI_RES_##\\IMAG\\AlmClk\\IMG_CLOCK_HOUR_HAND.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLOCK_MIN_HAND,"\\MMI_RES_##\\IMAG\\AlmClk\\IMG_CLOCK_MIN_HAND.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLOCK_NIGHT,"\\MMI_RES_##\\IMAG\\AlmClk\\IMG_CLOCK_NIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLOCK_PM,"\\MMI_RES_##\\IMAG\\AlmClk\\IMG_CLOCK_PM.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLOCK_TIME_BG,"\\MMI_RES_##\\IMAG\\AlmClk\\IMG_CLOCK_TIME_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifdef MMI_ALARM_JUMP_CLOCK_SUPPORT
RES_ADD_IMG(IMG_JUMP_CLK_BG,"\\MMI_RES_##\\IMAG\\AlmJump\\IMG_JUMP_CLK_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_JUMP_CLK_CENTER,"\\MMI_RES_##\\IMAG\\AlmJump\\IMG_JUMP_CLK_CENTER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_JUMP_CLK_HOUR_HANDLE,"\\MMI_RES_##\\IMAG\\AlmJump\\IMG_JUMP_CLK_HOUR_HANDLE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_JUMP_CLK_MIN_HANDLE,"\\MMI_RES_##\\IMAG\\AlmJump\\IMG_JUMP_CLK_MIN_HANDLE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_JUMP_WIN_BG,"\\MMI_RES_##\\IMAG\\AlmJump\\IMG_JUMP_WIN_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

//RES_ADD_IMG(IMG_ST_BG, "\\MMI_RES_##\\IMAG\\stopwatch\\IMG_ST_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH,0)//|SABM_HOR_STRETCH|SABM_VER_STRETCH
#ifdef MMI_RECORD_SUPPORT
RES_ADD_IMG(IMG_SCH_RECORD_ICON,"\\MMI_RES_##\\IMAG\\ALARM\\IMG_SCH_RECORD_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef COUNTEDTIME_SUPPORT
#ifdef TOUCH_PANEL_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_TIMER_START,"\\MMI_RES_##\\IMAG\\timer\\IMAGE_CLOCK_TIMER_START.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_CLOCK_TIMER_STOP,"\\MMI_RES_##\\IMAG\\timer\\IMAGE_CLOCK_TIMER_STOP.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_CLOCK_TIMER_START_PRESSED,"\\MMI_RES_##\\IMAG\\timer\\IMAGE_CLOCK_TIMER_START_PRESSED.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_CLOCK_TIMER_STOP_PRESSED,"\\MMI_RES_##\\IMAG\\timer\\IMAGE_CLOCK_TIMER_STOP_PRESSED.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
#endif
#ifndef MMI_COUNTEDTIME_MINI_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_ALARM_TIMER_DEFAULT,"\\MMI_RES_##\\IMAG\\timer\\IMAGE_CLOCK_ALARM_TIMER_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_ALARM_TIMER_FOCUSED,"\\MMI_RES_##\\IMAG\\timer\\IMAGE_CLOCK_ALARM_TIMER_FOCUSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined MMI_ISTYLE_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_TIMER_ISTYLETAB_DEFAULT,"\\MMI_RES_##\\IMAG\\timer\\IMAGE_CLOCK_TIMER_ISTYLETAB_DEFAULT.png",IMG_CMP_PNG_SABM_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_TIMER_ISTYLETAB_FOCUSED,"\\MMI_RES_##\\IMAG\\timer\\IMAGE_CLOCK_TIMER_ISTYLETAB_FOCUSED.png",IMG_CMP_PNG_SABM_RLE,0)
#endif
#endif
#endif

#ifdef STOPWATCH_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_STOPWATCH_RESET_DEFAULT,"\\MMI_RES_##\\IMAG\\stopwatch\\IMAGE_CLOCK_STOPWATCH_RESET_DEFAULT.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_CLOCK_STOPWATCH_RESET_PRESSED,"\\MMI_RES_##\\IMAG\\stopwatch\\IMAGE_CLOCK_STOPWATCH_RESET_PRESSED.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_CLOCK_STOPWATCH_START_PRESSED,"\\MMI_RES_##\\IMAG\\stopwatch\\IMAGE_CLOCK_STOPWATCH_START_PRESSED.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_CLOCK_STOPWATCH_START,"\\MMI_RES_##\\IMAG\\stopwatch\\IMAGE_CLOCK_STOPWATCH_START.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_CLOCK_STOPWATCH_STOP,"\\MMI_RES_##\\IMAG\\stopwatch\\IMAGE_CLOCK_STOPWATCH_STOP.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_CLOCK_STOPWATCH_STOP_PRESSED,"\\MMI_RES_##\\IMAG\\stopwatch\\IMAGE_CLOCK_STOPWATCH_STOP_PRESSED.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_IMG(IMAGE_CLOCK_ALARM_STOPWATCH_DEFAULT,"\\MMI_RES_##\\IMAG\\stopwatch\\IMAGE_CLOCK_ALARM_STOPWATCH_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_ALARM_STOPWATCH_FOCUSED,"\\MMI_RES_##\\IMAG\\stopwatch\\IMAGE_CLOCK_ALARM_STOPWATCH_FOCUSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_ISTYLE_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_STOPWATCH_ISTYLETAB_DEFAULT,"\\MMI_RES_##\\IMAG\\stopwatch\\IMAGE_CLOCK_STOPWATCH_ISTYLETAB_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_STOPWATCH_ISTYLETAB_FOCUSED,"\\MMI_RES_##\\IMAG\\stopwatch\\IMAGE_CLOCK_STOPWATCH_ISTYLETAB_FOCUSED.png",IMG_CMP_PNG_SABM_RLE,0)
#endif
#endif

#ifdef MMI_JEWISH_CALENDAR
RES_ADD_IMG(IMAGE_JEWISH_CALENDAR_ARROWS_ITEM,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_JEWISH_CALENDAR_ARROWS_ITEM.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JEWISH_CALENDAR_ARROWS_ITEM_FOCUS,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_JEWISH_CALENDAR_ARROWS_ITEM_FOCUS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_ARROWS_ITEM_LEFT,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_ARROWS_ITEM_LEFT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_ARROWS_ITEM_LEFT_PRESSED,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_ARROWS_ITEM_LEFT_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_ARROWS_ITEM_RIGHT,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_ARROWS_ITEM_RIGHT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_ARROWS_ITEM_RIGHT_PRESSED,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_ARROWS_ITEM_RIGHT_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_ARROWS_ITEM_TEXT,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_ARROWS_ITEM_TEXT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JEWISH_CALENDAR_CALITEMBG,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_JEWISH_CALENDAR_CALITEMBG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JEWISH_CALENDAR_CALITEMBG_FOCUSED,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_JEWISH_CALENDAR_CALITEMBG_FOCUSED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JEWISH_CALENDAR_CITY_ITEM_BOTTOM,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_JEWISH_CALENDAR_CITY_ITEM_BOTTOM.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JEWISH_CALENDAR_CITY_ITEM_MIDDLE,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_JEWISH_CALENDAR_CITY_ITEM_MIDDLE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JEWISH_CALENDAR_CITY_ITEM_TOP,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_JEWISH_CALENDAR_CITY_ITEM_TOP.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JEWISH_CALENDAR_DLS_SUMMER,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_JEWISH_CALENDAR_DLS_SUMMER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JEWISH_CALENDAR_DLS_WINTER,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_JEWISH_CALENDAR_DLS_WINTER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JEWISH_CALENDAR_LINE_SEPARATOR,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_JEWISH_CALENDAR_LINE_SEPARATOR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JEWISH_CALENDAR_UP_ARROW,"\\MMI_RES_##\\IMAG\\Jewish_calendar\\IMAGE_JEWISH_CALENDAR_UP_ARROW.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

//[[define string infomation
#if 1
RES_ADD_STRING(TXT_ALARM_CLOCK1,"Alarm1")

RES_ADD_STRING(TXT_ALARM_CLOCK2,"Alarm2")

//RES_ADD_STRING(TXT_ALARM_ENABLE,"Activate")               //replaced by common ID TXT_COMMON_ENABLE_ON

//RES_ADD_STRING(TXT_ALARM_DISABLE,"Deactivate")            //replaced by common ID TXT_CLOSE          

RES_ADD_STRING(TXT_ALARM_CLOCK3,"Alarm3")
RES_ADD_STRING(TXT_ALARM_CLOCK4,"Alarm4")
RES_ADD_STRING(TXT_ALARM_CLOCK5,"Alarm5")
RES_ADD_STRING(TXT_ALARM_CLOCK6,"Alarm6")
RES_ADD_STRING(TXT_ALARM_CLOCK7,"Alarm7")
RES_ADD_STRING(TXT_ALARM_CLOCK8,"Alarm8")
RES_ADD_STRING(TXT_ALARM_CLOCK9,"Alarm9")
RES_ADD_STRING(TXT_ALARM_CLOCK10,"Alarm10")

//RES_ADD_STRING(TXT_ALARM_EXPIRED_MSG,"Smart event expired, please check")    //case3: defined but not used

//RES_ADD_STRING(TXT_ALARM_START_ALARM,"Set alarm")    //case3: defined but not used

//RES_ADD_STRING(TXT_ALARM_STOP_ALARM,"Stop alarm")    //case3: defined but not used

//RES_ADD_STRING(TXT_ALARM_MODE_CUSTOMED,"Customized")    //case3: defined but not used

RES_ADD_STRING(TXT_AUTOPOWER_ON,"Auto power on")

RES_ADD_STRING(TXT_AUTOPOWER_OFF,"Auto power off")

RES_ADD_STRING(TXT_CALENDAR_LOOK,"View schedules")

RES_ADD_STRING(TXT_CALENDAR_NEW,"Add new schedule")

RES_ADD_STRING(TXT_CALENDAR_ALL,"All schedules")

//RES_ADD_STRING(TXT_CALENDAR_QUERY,"Find date")    //case3: defined but not used

//RES_ADD_STRING(TXT_CALENDAR_MEMO,"Feast")    //case3: defined but not used

RES_ADD_STRING(TXT_CALENDAR_WEEKLY,"Weekly")

RES_ADD_STRING(TXT_CALENDAR_MONTHLY,"Monthly")

//RES_ADD_STRING(TXT_CALENDAR_SOLAR,"Solar")    //case3: defined but not used
//#if defined (IM_SIMP_CHINESE_SUPPORT) || defined (IM_TRAD_CHINESE_SUPPORT) || defined(MMI_DISPLAY_SIMP_CHINESE_SUPPORT) || defined(MMI_DISPLAY_TRAD_CHINESE_SUPPORT)
RES_ADD_STRING(TXT_CALENDAR_LUNAR,"Lunar") 
//#endif
//RES_ADD_STRING(TXT_CALENDAR_CAPRICORN,"Capricorn")

//RES_ADD_STRING(TXT_CALENDAR_AQUARIUS,"Aquarius")

//RES_ADD_STRING(TXT_CALENDAR_PISCES,"Pisces")

//RES_ADD_STRING(TXT_CALENDAR_ARIES,"Aries")

//RES_ADD_STRING(TXT_CALENDAR_TAURUS,"Taurus")

//RES_ADD_STRING(TXT_CALENDAR_GEMINI,"Gemini")

//RES_ADD_STRING(TXT_CALENDAR_CANCER,"Cancer")

//RES_ADD_STRING(TXT_CALENDAR_LEO,"Leo")

//RES_ADD_STRING(TXT_CALENDAR_VIRGO,"Virgo")

//RES_ADD_STRING(TXT_CALENDAR_LIBRA,"Libra")

//RES_ADD_STRING(TXT_CALENDAR_SCORPIO,"Scorpio")

//RES_ADD_STRING(TXT_CALENDAR_SAGITTARIUS,"Sagittarius")

//RES_ADD_STRING(TXT_CALENDAR_XH,"–°∫Æ")

//RES_ADD_STRING(TXT_CALENDAR_DH,"¥Û∫Æ")

//RES_ADD_STRING(TXT_CALENDAR_LC,"¡¢¥∫")

//RES_ADD_STRING(TXT_CALENDAR_YS,"”ÍÀÆ")

//RES_ADD_STRING(TXT_CALENDAR_JZ,"æ™’›")

//RES_ADD_STRING(TXT_CALENDAR_CF,"¥∫∑÷")

//RES_ADD_STRING(TXT_CALENDAR_QM,"«Â√˜")

//RES_ADD_STRING(TXT_CALENDAR_GY,"π»”Í")

//RES_ADD_STRING(TXT_CALENDAR_LX,"¡¢œƒ")

//RES_ADD_STRING(TXT_CALENDAR_XM,"–°¬˙")

//RES_ADD_STRING(TXT_CALENDAR_MZ,"√¢÷÷")

//RES_ADD_STRING(TXT_CALENDAR_XZ,"œƒ÷¡")

//RES_ADD_STRING(TXT_CALENDAR_XS,"–° Ó")

//RES_ADD_STRING(TXT_CALENDAR_DS,"¥Û Ó")

//RES_ADD_STRING(TXT_CALENDAR_LQ,"¡¢«Ô")

//RES_ADD_STRING(TXT_CALENDAR_CS,"¥¶ Ó")

//RES_ADD_STRING(TXT_CALENDAR_BL,"∞◊¬∂")

//RES_ADD_STRING(TXT_CALENDAR_QF,"«Ô∑÷")

//RES_ADD_STRING(TXT_CALENDAR_HL,"∫Æ¬∂")

//RES_ADD_STRING(TXT_CALENDAR_SJ,"À™Ωµ")

//RES_ADD_STRING(TXT_CALENDAR_LD,"¡¢∂¨")

//RES_ADD_STRING(TXT_CALENDAR_XX,"–°—©")

//RES_ADD_STRING(TXT_CALENDAR_DX,"¥Û—©")

//RES_ADD_STRING(TXT_CALENDAR_DZ,"∂¨÷¡")

//RES_ADD_STRING(TXT_SCH_TITLE_TIME,"Time:")    //case3: defined but not used

//RES_ADD_STRING(TXT_SCH_TITLE_RING,"Ring:")    //case3: defined but not used

//RES_ADD_STRING(TXT_SCH_TITLE_FREQ,"Period:")    //case3: defined but not used

//RES_ADD_STRING(TXT_SCH_TITLE_CONTENT,"Content:")    //case3: defined but not used

//RES_ADD_STRING(TXT_SCH_SCH,"Schedule")         //replaced by common ID TXT_IDLE_CALENDAR
#if defined(CMCC_UI_STYLE) || defined(CALENDAR_REMINDER_TYPE_SUPPORT)
RES_ADD_STRING(TXT_SCH_AWAKE_TIME,"Awake time") 
RES_ADD_STRING(TXT_RING_DUR_TIME,"Ring duration")
RES_ADD_STRING(TXT_SCH_REMIND_ONTIME,"On time")
RES_ADD_STRING(TXT_SCH_REMIND_FIVE_MIN,"Five minutes")
RES_ADD_STRING(TXT_SCH_REMIND_FIFTEEN_MIN,"Fifteen minutes")
RES_ADD_STRING(TXT_SCH_REMIND_ONE_HOUR,"One hour")
RES_ADD_STRING(TXT_SCH_REMIND_ONE_DAY,"One day")
RES_ADD_STRING(TXT_SCH_REMIND_ONE_WEEK,"One week")
#endif
//RES_ADD_STRING(TXT_SCH_AWAKE_FREQ,"Awake period")    //case3: defined but not used

//RES_ADD_STRING(TXT_SCH_INPUT_DATE,"Input date")    //case3: defined but not used

//RES_ADD_STRING(TXT_SCH_INPUT_TIME,"Input time")    //case3: defined but not used

//RES_ADD_STRING(TXT_SCH_AWAKE_ONCE,"Once")  //replaced by common ID TXT_ALARM_MODE_ONCE

RES_ADD_STRING(TXT_SCH_AWAKE_EVERYDAY,"Everyday")

RES_ADD_STRING(TXT_SCH_AWAKE_EVERYWEEK,"Every week")

RES_ADD_STRING(TXT_SCH_AWAKE_EVERYMONTH,"Every month")

RES_ADD_STRING(TXT_SCH_AWAKE_EVERYYEAR,"Every year")

RES_ADD_STRING(TXT_SCH_AWAKE_NO,"No awake")

//RES_ADD_STRING(TXT_SCH_CONTENT,"Content")    //case3: defined but not used

//RES_ADD_STRING(TXT_SCH_ICON,"Icon")    //case3: defined but not used

//RES_ADD_STRING(TXT_SCH_NEW,"New")    //replaced by common ID TXT_NEW

//RES_ADD_STRING(TXT_SCH_ALLSCH,"All schedule")    //replaced by local common ID TXT_CALENDAR_ALL

//RES_ADD_STRING(TXT_FEAST_FEASTNAME,"Feast name")    //case3: defined but not used

//RES_ADD_STRING(TXT_ALARM_NO_RECORD,"No schedule")    //case3: defined but not used

//RES_ADD_STRING(TXT_ALARM_MORE_RING,"More rings")                 //replaced by common ID TXT_COMMON_MORE_RING

//RES_ADD_STRING(TXT_ALARM_NO_MATCH_RECORD,"No match record")    //case3: defined but not used

//RES_ADD_STRING(TXT_ALARM_MEMORY_FULL,"Memory full")    //case3: defined but not used

//RES_ADD_STRING(TXT_ALARM_NAME_EMPTY,"Name is empty")    //case3: defined but not used

//RES_ADD_STRING(TXT_ALARM_EDIT,"Edit")  //replaced by common ID TXT_EDIT

//RES_ADD_STRING(TXT_ALARM_EDIT_HEADING,"Heading")    //case3: defined but not used

//RES_ADD_STRING(TXT_ALARM_EDIT_RING,"Ring")  //replaced by common ID TXT_RING

RES_ADD_STRING(TXT_ALARM_EDIT_MODE,"Repeat mode")

//RES_ADD_STRING(TXT_ALARM_INHEAR_RING_TYPE,"Inhear ring")

//RES_ADD_STRING(TXT_ALARM_SELFHOOD_RING_TYPE,"Selfhood ring")

//RES_ADD_STRING(TXT_ALARM_MP3_RING_TYPE,"MP3 ring")

RES_ADD_STRING(TXT_ALARM_RECORD_RING_TYPE,"Record ring")

//RES_ADD_STRING(TXT_ALARM_MUST_SEL_ONE_DAY,"Select one day")  //replaced by common ID TXT_ALARM_SELECT_ONE_DAY

//RES_ADD_STRING(TXT_ALARM_EDIT_TIME,"Time")  //replaced by common ID TXT_TIME

RES_ADD_STRING(TXT_ALARM_DELAY,"Delay")

#ifdef MMI_ALARM_MINI_SUPPORT
RES_ADD_STRING(TXT_ALARM_DELAY_MINI,"Delay")
#endif


RES_ADD_STRING(TXT_SCH_INVALID_DEADLINE,"Invalid deadline")

RES_ADD_STRING(TXT_ALARM_WILL_TO,"Will shut down")

RES_ADD_STRING(TXT_ALARM_SHUT_DOWN,"s later")

//RES_ADD_STRING(TXT_SCH_INVALID_DATE_TIME,"Invalid date and time")    //case3: defined but not used

RES_ADD_STRING(TXT_ALARM_DELAY_1,"Delay alarm1")

RES_ADD_STRING(TXT_ALARM_DELAY_2,"Delay alarm2")

RES_ADD_STRING(TXT_ALARM_DELAY_3,"Delay alarm3")
RES_ADD_STRING(TXT_ALARM_DELAY_4,"Delay alarm4")
RES_ADD_STRING(TXT_ALARM_DELAY_5,"Delay alarm5")
RES_ADD_STRING(TXT_ALARM_DELAY_6,"Delay alarm6")
RES_ADD_STRING(TXT_ALARM_DELAY_7,"Delay alarm7")
RES_ADD_STRING(TXT_ALARM_DELAY_8,"Delay alarm8")
RES_ADD_STRING(TXT_ALARM_DELAY_9,"Delay alarm9")
RES_ADD_STRING(TXT_ALARM_DELAY_10,"Delay alarm10")

//RES_ADD_STRING(TXT_ALARM_CLOSE,"Close")           //replaced by common ID TXT_CLOSE

RES_ADD_STRING(TXT_SCH_INVALID_TITLE,"Invalid title")

//RES_ADD_STRING(TXT_ALARM_EDIT_NAME,"Name")    //replaced by common ID STXT_MAIN_MESSAGE 

RES_ADD_STRING(TXT_CALENDAR_DEL_CDR_DAY_PERIODSCH,"Current day has period schedule,also delete")

//RES_ADD_STRING(TXT_SCH_TITLE_NOT_NULL,"Title can't be null")  //replaced by common ID TXT_COMM_NO_TITLE

RES_ADD_STRING(TXT_CALENDAR_UNREAD_SCH,"Missed events")

//calendar
RES_ADD_STRING(TXT_CALENDAR_CLEAR_TODAY,"Clear today's schedules")
RES_ADD_STRING(TXT_CALENDAR_CLEAR_TODAY_QUERY,"Clear today's schedules?")
RES_ADD_STRING(TXT_CALENDAR_CLEAR_ALL,"Clear all")
RES_ADD_STRING(TXT_CALENDAR_CLEAR_ALL_QUERY,"Clear all?")
RES_ADD_STRING(TXT_CALENDAR_EMPTY,"No record")
RES_ADD_STRING(TXT_CALENDAR_NAME,"Name:")
//RES_ADD_STRING(TXT_CALENDAR_DATE,"Date:")  //replaced by common ID TXT_COMMON_DATE
//RES_ADD_STRING(TXT_CALENDAR_TIME,"Time:")  //replaced by common ID TXT_COMMON_TIME
RES_ADD_STRING(TXT_CALENDAR_RING,"Ring:")
//RES_ADD_STRING(TXT_CALENDAR_FREQ,"Freq:")  //replaced by common ID TXT_TYPE
RES_ADD_STRING(TXT_CALENDAR_DEADLINE,"Deadline:")
RES_ADD_STRING(TXT_CALENDAR_TO_DATE,"Go to date")
//RES_ADD_STRING(TXT_CALENDAR_QUERY_SOLAR,"Solar:")  //replaced by common ID TXT_COMMON_DATE
//RES_ADD_STRING(TXT_CALENDAR_QUERY_LUNAR,"Lunar:")
//RES_ADD_STRING(TXT_CALENDAR_WEEK_NO,"NO.")
RES_ADD_STRING(TXT_CALENDAR_WEEK,"Week")    
//RES_ADD_STRING(TXT_CALENDAR_EDIT_NAME,"Name")  //replaced by common ID TXT_COMMON_SUBJECT
//RES_ADD_STRING(TXT_CALENDAR_EDIT_DATE,"Date")  //replaced by common ID TXT_DATE
//RES_ADD_STRING(TXT_CALENDAR_EDIT_TIME,"Time")  //replaced by common ID TXT_TIME
//RES_ADD_STRING(TXT_CALENDAR_EDIT_RING,"Ring")  //replaced by common ID TXT_RING
//RES_ADD_STRING(TXT_CALENDAR_EDIT_FREQ,"Freq")  //replaced by common ID TXT_COMMON_TYPE
RES_ADD_STRING(TXT_CALENDAR_EDIT_DEADLINE,"Deadline")
RES_ADD_STRING(TXT_CALENDAR_LUNAR_DETAIL, "Lunar detail")

#ifdef  TOUCH_PANEL_SUPPORT
RES_ADD_STRING(TXT_CALENDAR_NEW_SCHEDULE, "Touch to create a new schedule")
#else
RES_ADD_STRING(TXT_CALENDAR_NEW_SCHEDULE, "Create a new schedule")
#endif
#ifdef MMI_CALENDAR_DAILY_SUPPORT
RES_ADD_STRING(TXT_CALENDAR_DAILY, "Daily")
#endif

//end of calendar

#ifdef MMI_VCALENDAR_SUPPORT
RES_ADD_STRING(TXT_SCH_DESCRIPTION,"Description:")
RES_ADD_STRING(TXT_SCH_CLASSIFICATION,"Classification:")
RES_ADD_STRING(TXT_SCH_START_DATE,"Start date:")
RES_ADD_STRING(TXT_SCH_START_TIME,"Start time:")
RES_ADD_STRING(TXT_CALENDAR_DEADLINE_TIME,"Mature time:")
RES_ADD_STRING(TXT_CALENDAR_DUE_DATE,"Due date:")
RES_ADD_STRING(TXT_CALENDAR_DUE_TIME,"Due time:")
RES_ADD_STRING(TXT_CALENDAR_COMPLETED_DATE,"Completed date:")
RES_ADD_STRING(TXT_CALENDAR_COMPLETED_TIME,"Completed time:")
RES_ADD_STRING(TXT_SAVE_CALENDAR,"Save calendar")
#endif
//RES_ADD_STRING(TXT_ALARM_FM_TAB,"Station list")  //replaced by common ID TXT_COMM_CHANNEL_LIST
#ifndef MMI_GUI_STYLE_MINISCREEN
RES_ADD_STRING(TXT_ALARM_CUSTOM_FM,"Custom freq.:(87.5-108.0)")
#else
RES_ADD_STRING(TXT_ALARM_CUSTOM_FM_TEXT,"Custom frequency:")
RES_ADD_STRING(TXT_ALARM_CUSTOM_FM_FREQ,"87.5-108.0")
#endif
RES_ADD_STRING(TXT_ALARM_FM_RING,"FM broadcast ring")
#endif
//]]define string infomation


#ifdef WORLD_CLOCK_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_DST,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_DST.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifndef MMI_WORLDCLOCK_MINI_SUPPORT
RES_ADD_IMG(IMAGE_WT_OPTION_SET_LOCAL,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_WT_OPTION_SET_LOCAL.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WT_OPTION_SET_OTHER,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_WT_OPTION_SET_OTHER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_WT_OPTION_SET_SUMMER,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_WT_OPTION_SET_SUMMER.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_WT_OPTION_CANCEL_SUMMER,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_WT_OPTION_CANCEL_SUMMER.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef ANALOG_CLK_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_DAYTIME_BG,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_DAYTIME_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_DAYTIME_HOUR,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_DAYTIME_HOUR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_DAYTIME_MINUTE,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_DAYTIME_MINUTE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_DAYTIME_CENTER,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_DAYTIME_CENTER.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_NIGHT_BG,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_NIGHT_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_NIGHT_HOUR,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_NIGHT_HOUR.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_NIGHT_MINUTE,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_NIGHT_MINUTE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_NIGHT_CENTER,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_NIGHT_CENTER.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef TOUCH_PANEL_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_ADD_ICON,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_ADD_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifndef MMI_WORLDCLOCK_MINI_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_TAB_DEFAULT,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_TAB_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_TAB_FOCUSED,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_TAB_FOCUSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#if defined MMI_ISTYLE_SUPPORT
RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_ISTYLETAB_DEFAULT,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_ISTYLETAB_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CLOCK_WORLDCLOCK_ISTYLETAB_FOCUSED,"\\MMI_RES_##\\IMAG\\worldclock\\IMAGE_CLOCK_WORLDCLOCK_ISTYLETAB_FOCUSED.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#endif

//world clock
#ifdef WORLD_CLOCK_SUPPORT
//attention please,œ¬√Êµƒ◊÷¥Æ≤ªƒ‹ÀÊ“‚…æ≥˝∫Õ∏ƒ±‰À≥–Ú!!!
RES_ADD_STRING(TXT_ACC_WORLD_GMT_0,"GMT0")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P,"GMT+1")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P,"GMT+2")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3_P,"GMT+3")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3P5_P,"GMT+3.5")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_4_P,"GMT+4")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_4P5_P,"GMT+4.5")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_5_P,"GMT+5")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_5P5_P,"GMT+5.5")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_5P75_P,"GMT+5.75")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_6_P,"GMT+6")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_6P5_P,"GMT+6.5")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_7_P,"GMT+7")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_8_P,"GMT+8")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_9_P,"GMT+9")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_9P5_P,"GMT+9.5")    //case3: defined but not used
RES_ADD_STRING(TXT_ACC_WORLD_GMT_10_P,"GMT+10")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_10P5_P,"GMT+10.5")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_11_P,"GMT+11")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_11P5_P,"GMT+11.5")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_12_P,"GMT+12")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_12P75_P,"GMT+12.75")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_13_P,"GMT+13")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_14_P,"GMT+14")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_12_N,"GMT-12")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_11_N,"GMT-11")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_10_N,"GMT-10")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_9P5_N,"GMT-9.5")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_9_N,"GMT-9")
//RES_ADD_STRING(TXT_ACC_WORLD_GMT_8P5_N,"GMT-8.5")    //case3: defined but not used
RES_ADD_STRING(TXT_ACC_WORLD_GMT_8_N,"GMT-8")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_7_N,"GMT-7")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_6_N,"GMT-6")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_5_N,"GMT-5")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_4P5_N,"GMT-4.5")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_4_N,"GMT-4")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3P5_N,"GMT-3.5")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3_N,"GMT-3")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_N,"GMT-2")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_N,"GMT-1")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_0_LISBON,"Lisbon")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_0_CASABLANCA,"Casablanca")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_0_RABAT,"Rabat")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_0_LONDON,"London")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_0_ACCRA,"Accra")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_MADRID,"Madrid")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_BRUSSELS,"Brussels")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_PARIS,"Paris")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_ZURICH,"Zurich")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_GENEVA,"Geneva")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_COPENHAGEN,"Copenhagen")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_BERLIN,"Berlin")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_ROME,"Rome")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_STOCKHOLM,"Stockholm")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_AMSTERDAM,"Amsterdam")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_LUXEMBOURG,"Luxembourg")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_PRAGUE,"Prague")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_WARSAW,"Warsaw")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_VIENNA,"Vienna")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_BUDAPEST,"Budapest")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_P_LAGOS,"Lagos")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P_HELSINKI,"Helsinki")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P_PRETORIA,"Pretoria")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P_JERUSALEM,"Jerusalem")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P_CAPE_TOWN,"Cape Town")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P_JOHANNESBURG,"Johannesburg")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P_SOFIA,"Sofia")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P_BUCHAREST,"Bucharest")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P_ISTANBUL,"Istanbul")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P_KIEV,"Kiev")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P_CAIRO,"Cairo")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P_ATHENS,"Athens")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P_AMMAN,"Amman")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_P_KYIV,"Kyiv")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3_P_MOSCOW,"Moscow")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3_P_BAGHDAD,"Baghdad")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3_P_KUWAIT,"Kuwait")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3_P_NAIROBI,"Nairobi")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3_P_DOHA,"Doha")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3_P_KAMPALA,"Kampala")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3_P_RIYADH,"Riyadh")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3_P_SANA,"Sana")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3P5_P_TEHRAN,"Tehran")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_4_P_ABUDHABI,"Abudhabi")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_4_P_MUSCAT,"Muscat")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_4P5_P_KABUL,"Kabul")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_4P5_P_TASHKENT,"Tashkent")

RES_ADD_STRING(TXT_ACC_WORLD_GMT_5_P_ISLAMABAD,"Islamabad")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_5P5_P_NEWDELHI,"New Delhi")

RES_ADD_STRING(TXT_ACC_WORLD_GMT_5P5_P_MUMBAI,"Mumbai")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_5P5_P_BANGALORE,"Bangalore")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_5P5_P_KOLKATA,"Kolkata")

RES_ADD_STRING(TXT_ACC_WORLD_GMT_5P75_P_KATHMANDU,"Kathmandu")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_6_P_DHAKA,"Dhaka")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_6_P_ALMATY,"Almaty")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_6_P_EKATERINBURG,"Ekaterinburg")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_6_P_NOVOSIBIRSK,"Novosibirsk")

RES_ADD_STRING(TXT_ACC_WORLD_GMT_6P5_P_YANGON,"Yangon")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_7_P_BANGKOK,"Bangkok")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_7_P_JAKARTA,"Jakarta")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_7_P_HANOI,"Hanoi")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_7_P_PHNOMPENH,"Phnom Penh")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_8_P_KUALA_LUMPUR,"Kuala Lumpur")
//RES_ADD_STRING(TXT_ACC_WORLD_GMT_8_P_SINGAPORE,"Singapore")    //replaced by common ID TXT_SINGAPORE
RES_ADD_STRING(TXT_ACC_WORLD_GMT_8_P_BEIJING,"Beijing")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_8_P_HONGKONG,"Hongkong")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_8_P_TAIPEI,"Taipei")

RES_ADD_STRING(TXT_ACC_WORLD_GMT_8_P_MANILA,"Manila")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_9_P_TOKYO,"Tokyo")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_9_P_SEOUL,"Seoul")

RES_ADD_STRING(TXT_ACC_WORLD_GMT_9P5_P_MELBOURNE,"Melbourne")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_9P5_P_ADELAIDE,"Adelaide")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_9P5_P_DARWIN,"Darwin")

RES_ADD_STRING(TXT_ACC_WORLD_GMT_10_P_VLADIVOSTOK,"Vladivostok")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_10_P_GUAM,"Guam")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_10_P_CANBERRA,"Canberra")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_10_P_SYDNEY,"Sydney")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_10P5_P_BRISBANE,"Brisbane")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_10P5_P_LDH,"LDH")

RES_ADD_STRING(TXT_ACC_WORLD_GMT_11_P_SOLOMON,"Solomon")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_11P5_P_NORFOLD_ISLAND,"Norfold Island")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_12_P_AUCKLAND,"Auckland")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_12_P_WELLINGTON,"Wellington")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_12_P_ANADYR,"Anadyr")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_12_P_MAGADAN,"Magadan")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_12_P_FIJI,"Fiji")

RES_ADD_STRING(TXT_ACC_WORLD_GMT_12P75_P_TONGA,"Tonga")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_12_N_IDL_WEST,"IDL West")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_12_N_KWAJALEIN,"Kwajalein")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_11_N_MIDWAY,"midway")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_11_N_APIA,"Apia")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_10_N_HONOLULU,"Honolulu")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_9P5_N_POLYNESIA,"Polynesia")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_9_N_ALASKA,"Alaska")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_9_N_ANCHORAGE,"Anchorage")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_8P5_N_EASTER_ISLAND,"Easter Island")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_8_N_SEATTLE,"Seattle")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_8_N_VANCOUVER,"Vancouver")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_8_N_SAN_FRANCISCO,"San Francisco")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_8_N_LOSANGELES,"Losangeles")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_7_N_PHOENIX,"Phoenix")
//RES_ADD_STRING(TXT_ACC_WORLD_GMT_6_N_MEXICO,"Mexico")     //replaced by common ID TXT_COMMON_WORLD_MEXICO
RES_ADD_STRING(TXT_ACC_WORLD_GMT_6_N_CHICAGO,"Chicago")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_5_N_WASHINGTON,"Washington D.C")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_5_N_TORONTO,"Toronto")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_5_N_BOGOTA,"Bogota")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_5_N_MONTREAL,"Montreal")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_5_N_NEWYORK,"Newyork")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_4P5_N_CARACAS,"Caracas")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_4_N_SANTIAGO,"Santiago")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3P5_N_LAPAZ,"Lapaz")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3P5_N_SAINIT_JOHN,"Saint John's")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3_N_BUENOS_AIRES,"Buenos Aires")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_3_N_BRASILIA,"Brasilia")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_2_N_CENTRAL_ATLANTIC,"Central Atlantic")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_N_PRAIA,"Praia")
RES_ADD_STRING(TXT_ACC_WORLD_GMT_1_N_AZORES,"Azores")

//RES_ADD_STRING(TXT_LOCAL,"Local")
//RES_ADD_STRING(TXT_ACC_WORLD_SELECT_GMT,"Select GMT")    //case3: defined but not used
//RES_ADD_STRING(TXT_ACC_WORLD_SELECT_CITY,"Select City")    //case3: defined but not used

RES_ADD_STRING(TXT_ACC_WORLD_CITY_LIST_ORDER,"City List Order")    //case3: defined but not used
RES_ADD_STRING(TXT_ACC_WORLD_CITY_LIST_ORDER_BY_GMT,"Order By GMT")    //case3: defined but not used
RES_ADD_STRING(TXT_ACC_WORLD_CITY_LIST_ORDER_BY_ALPHABET,"Order By Alphabet")    //case3: defined but not used

// end of world clock
#endif


//schedule
#ifdef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_SCH_PREVIOUS_DAY, "Previous day")
RES_ADD_STRING(TXT_SCH_NEXT_DAY, "Next day")
#endif

//yaye.jiang stopwatch
#if defined ( STOPWATCH_SUPPORT ) 
RES_ADD_STRING(TXT_ACC_STOPWATCH,"Stopwatch")
RES_ADD_STRING(TXT_ACC_COUNT,"Count")
#endif
//RES_ADD_STRING(TXT_RESET, "Reset")

#ifdef SCH_ASSISTANT_WIDGET
RES_ADD_STRING(TXT_SCH_ADD_SCH_ASSIITANT,"The schedule assistant will be added to desktop")
#endif

#ifdef PDA_UI_DROPDOWN_WIN
RES_ADD_STRING(TXT_UNREAD_ALARM,"Unsettled alarm")
RES_ADD_STRING(TXT_UNREAD_ALARMS,"Unsettled alarms")
#endif

RES_ADD_STRING(TXT_SCH_TITLE_CONTENT,"Content:")
#define TXT_ALM_CONFLIT STR_ID_OPERA_V11_24//CR177677
RES_ADD_STRING(TXT_ALM_CONFLIT,"Settings conflicted")

RES_ADD_STRING(STR_HDR_MONTH_EXT01, "Month")
RES_ADD_STRING(TXT_CALENDAR_MONTH_JAN, "January")
RES_ADD_STRING(TXT_CALENDAR_MONTH_FEB, "February")
RES_ADD_STRING(TXT_CALENDAR_MONTH_MAR, "March")
RES_ADD_STRING(TXT_CALENDAR_MONTH_APR, "April")
RES_ADD_STRING(TXT_CALENDAR_MONTH_MAY, "May")
RES_ADD_STRING(TXT_CALENDAR_MONTH_JUN, "June")
RES_ADD_STRING(TXT_CALENDAR_MONTH_JUL, "July")
RES_ADD_STRING(TXT_CALENDAR_MONTH_AUG, "August")
RES_ADD_STRING(TXT_CALENDAR_MONTH_SEP, "September")
RES_ADD_STRING(TXT_CALENDAR_MONTH_OCT, "October")
RES_ADD_STRING(TXT_CALENDAR_MONTH_NOV, "November")
RES_ADD_STRING(TXT_CALENDAR_MONTH_DEC, "December")
RES_ADD_STRING(STXT_CALENDAR_WEEK_MONDAY, "Mo")
RES_ADD_STRING(STXT_CALENDAR_WEEK_TUESDAY, "Tu")
RES_ADD_STRING(STXT_CALENDAR_WEEK_WEDNESDAY, "We")    
RES_ADD_STRING(STXT_CALENDAR_WEEK_THURSDAY, "Th")
RES_ADD_STRING(STXT_CALENDAR_WEEK_FRIDAY, "Fr")
RES_ADD_STRING(STXT_CALENDAR_WEEK_SATURDAY, "Sa")
RES_ADD_STRING(STXT_CALENDAR_WEEK_SUNDAY, "Su")
RES_ADD_STRING(STXT_CALENDAR_MONDAY, "Monday")
RES_ADD_STRING(STXT_CALENDAR_TUESDAY, "Tuesday")
RES_ADD_STRING(STXT_CALENDAR_WEDNESDAY, "Wednesday")    
RES_ADD_STRING(STXT_CALENDAR_THURSDAY, "Thursday")
RES_ADD_STRING(STXT_CALENDAR_FRIDAY, "Friday")
RES_ADD_STRING(STXT_CALENDAR_SATURDAY, "Saturday")
RES_ADD_STRING(STXT_CALENDAR_SUNDAY, "Sunday")
RES_ADD_STRING(STR_CALE_NOTE_EMPTY_A_EXT02, "Your calendar looks a bit empty. Got any new events to add?")
RES_ADD_STRING(STR_CALE_NEW_EVENT_EXT01, "New event")
RES_ADD_STRING(TXT_CALENDAR_ADD_EVENT, "Add")
RES_ADD_STRING(STR_ADD_NEW_EVENT_EXT01, "Add new event")
RES_ADD_STRING(STR_CALE_DELETE_ALL_EXT01, "Delete all until today")
RES_ADD_STRING(STR_CALE_ADD_SUBJECT_EXT01, "Add title")
RES_ADD_STRING(STR_CALE_REMINDER_EXT01, "Reminder")
RES_ADD_STRING(STR_CALE_LOCATION_EXT01, "Location")
RES_ADD_STRING(STR_CALE_ADD_PLACE_EXT01, "Add place")
RES_ADD_STRING(STR_CALE_NOTES_EXT01, "Notes")
RES_ADD_STRING(STR_CALE_ADD_NOTE_EXT01, "Add text")
RES_ADD_STRING(STR_ILIST_NOT_REPEATED, "Never")
RES_ADD_STRING(STR_ILIST_DAILY, "Every day")
RES_ADD_STRING(STR_ILIST_WEEKLY, "Every week")
RES_ADD_STRING(STR_ILIST_MONTHLY, "Every month")
RES_ADD_STRING(STR_ILIST_YEARLY, "Every year")
//RES_ADD_STRING(STR_CALE_LIST_RMD_NONE_EXT01, "None")
RES_ADD_STRING(STR_CALE_LIST_RMD_START_EXT02, "At start time")
RES_ADD_STRING(STR_CALE_LIST_RMD_15_EXT02, "15 minutes before")
RES_ADD_STRING(STR_CALE_LIST_RMD_1H_EXT02, "1 hour before")
RES_ADD_STRING(STR_CALE_LIST_RMD_1D_EXT02, "1 day before")
RES_ADD_STRING(STR_CALE_REPEAT_EXT01, "Repeat")
RES_ADD_STRING(TXT_CALENDAR_EVENT, "Event")
RES_ADD_STRING(STR_DELETE_EVENT_EXT01, "Delete this event?")
RES_ADD_STRING(STR_DELETE_EVENTS_EXT01	, "Delete %N events?")
RES_ADD_STRING(STXT_CLEARING_PERSONAL_DIR, "Deleting...")
RES_ADD_STRING(STR_EVENT_DELETED_EXT01, "Event deleted.")
RES_ADD_STRING(STR_EVENTS_DELETED_EXT01, "%N events deleted.")
RES_ADD_STRING(STXT_CALENDAR_GOTO_DATE, "Go to date")
RES_ADD_STRING(STR_LIST_SAVE_EXT01, "Save")
RES_ADD_STRING(STR_HDR_NEW_EVENT_EXT01, "New event")
RES_ADD_STRING(STR_CALE_SUBJECT_EXT01, "Subject")
RES_ADD_STRING(STR_CALE_HDR_REPEAT_EXT01, "Repeat")
RES_ADD_STRING(STR_CALE_HDR_REMINDER_EXT02, "Reminder")
RES_ADD_STRING(STXT_CALENDAR_DATE_EXT01, "Go to date")
RES_ADD_STRING(STR_VCALENDAR_SAVE_FAIL, "Vcalendar saving failed")
RES_ADD_STRING(STR_VCALENDAR_SAVED, "Vcalendar saved")
RES_ADD_STRING(STXT_LUNAR_DATE_0101, "√÷¿’∑ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_0106, "∂®π‚∑ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_0208, " ÕÂ»ƒ≤ƒ·∑≥ˆº“")
RES_ADD_STRING(STXT_LUNAR_DATE_0215, " ÕÂ»ƒ≤ƒ·∑ƒ˘≈Ã ")
RES_ADD_STRING(STXT_LUNAR_DATE_0219, "π€ ¿“Ù∆–»¯ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_0221, "∆’œÕ∆–»¯ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_0316, "◊ºÃ·∆–»¯ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_0404, "Œƒ ‚∆–»¯ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_0408, " ÕÂ»ƒ≤ƒ·∑ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_0415, "∑º™œÈ»’")
RES_ADD_STRING(STXT_LUNAR_DATE_0513, "Ÿ§¿∂∆–»¯ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_0603, "ª§∑®Œ§Õ‘◊ÃÏ∆–»¯ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_0619, "π€ ¿“Ù∆–»¯≥…µ¿")
RES_ADD_STRING(STXT_LUNAR_DATE_0713, "¥Û ∆÷¡∆–»¯ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_0715, "Ullambana")
RES_ADD_STRING(STXT_LUNAR_DATE_0724, "¡˙ ˜∆–»¯ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_0730, "µÿ≤ÿ∆–»¯ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_0822, "»ºµ∆∑ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_0919, "π€ ¿“Ù∆–»¯≥ˆº“ºÕƒÓ»’")
RES_ADD_STRING(STXT_LUNAR_DATE_0930, "“© ¶¡¡ßπ‚»Á¿¥ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_1005, "¥Ôƒ¶◊Ê ¶ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_1117, "∞¢√÷Õ”∑ •µÆ")
RES_ADD_STRING(STXT_LUNAR_DATE_1208, " ÕÂ»»Á¿¥≥…µ¿»’")
RES_ADD_STRING(STXT_LUNAR_DATE_1229, "ª™—œ∆–»¯ •µÆ")

#if 0 
#ifdef MMI_COMPILE_E//8910UIX
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REMINDER_BLUE,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REMINDER_BLUE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REMINDER_COPPER,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REMINDER_COPPER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REMINDER_GREEN,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REMINDER_GREEN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REMINDER_RED,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REMINDER_RED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REMINDER_VIOLET,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REMINDER_VIOLET.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REMINDER_YELLOW,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REMINDER_YELLOW.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REPEATING_BLUE,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REPEATING_BLUE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REPEATING_COPPER,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REPEATING_COPPER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REPEATING_GREEN,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REPEATING_GREEN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REPEATING_RED,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REPEATING_RED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REPEATING_VIOLET,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REPEATING_VIOLET.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REPEATING_YELLOW,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REPEATING_YELLOW.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_BLUE_2,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_BLUE-2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_COPPER_2,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_COPPER-2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_GREEN_2,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_GREEN-2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_RED_2,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_RED-2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_TODAY_BLUE,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_TODAY_BLUE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_TODAY_COPPER,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_TODAY_COPPER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_TODAY_GREEN,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_TODAY_GREEN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_TODAY_RED,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_TODAY_RED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_TODAY_VIOLET,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_TODAY_VIOLET.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_TODAY_YELLOW,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_TODAY_YELLOW.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_VIOLET_2 ,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_VIOLET-2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_YELLOW_2,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_YELLOW-2.png",IMG_CMP_PNG_ARGB_RLE,0)
#else
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REMINDER_RED,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REMINDER_RED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_EVENT_REPEATING_RED,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_EVENT_REPEATING_RED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_RED_2,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_RED-2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_CALENDAR_FOCUSED_TODAY_RED,"\\MMI_RES_##\\IMAG\\Calendar\\IMAGE_CALENDAR_FOCUSED_TODAY_RED.png",IMG_CMP_PNG_ARGB_RLE,0)

#define IMAGE_CALENDAR_EVENT_REMINDER_BLUE IMAGE_CALENDAR_EVENT_REMINDER_RED
#define IMAGE_CALENDAR_EVENT_REMINDER_COPPER IMAGE_CALENDAR_EVENT_REMINDER_RED
#define IMAGE_CALENDAR_EVENT_REMINDER_GREEN IMAGE_CALENDAR_EVENT_REMINDER_RED
#define IMAGE_CALENDAR_EVENT_REMINDER_VIOLET IMAGE_CALENDAR_EVENT_REMINDER_RED
#define IMAGE_CALENDAR_EVENT_REMINDER_YELLOW IMAGE_CALENDAR_EVENT_REMINDER_RED

#define IMAGE_CALENDAR_EVENT_REPEATING_BLUE IMAGE_CALENDAR_EVENT_REPEATING_RED
#define IMAGE_CALENDAR_EVENT_REPEATING_COPPER IMAGE_CALENDAR_EVENT_REPEATING_RED
#define IMAGE_CALENDAR_EVENT_REPEATING_GREEN IMAGE_CALENDAR_EVENT_REPEATING_RED
#define IMAGE_CALENDAR_EVENT_REPEATING_VIOLET IMAGE_CALENDAR_EVENT_REPEATING_RED
#define IMAGE_CALENDAR_EVENT_REPEATING_YELLOW IMAGE_CALENDAR_EVENT_REPEATING_RED

#define IMAGE_CALENDAR_FOCUSED_BLUE_2 IMAGE_CALENDAR_FOCUSED_RED_2
#define IMAGE_CALENDAR_FOCUSED_COPPER_2 IMAGE_CALENDAR_FOCUSED_RED_2
#define IMAGE_CALENDAR_FOCUSED_GREEN_2 IMAGE_CALENDAR_FOCUSED_RED_2
#define IMAGE_CALENDAR_FOCUSED_VIOLET_2 IMAGE_CALENDAR_FOCUSED_RED_2
#define IMAGE_CALENDAR_FOCUSED_YELLOW_2 IMAGE_CALENDAR_FOCUSED_RED_2

#define IMAGE_CALENDAR_FOCUSED_TODAY_BLUE IMAGE_CALENDAR_FOCUSED_TODAY_RED
#define IMAGE_CALENDAR_FOCUSED_TODAY_COPPER IMAGE_CALENDAR_FOCUSED_TODAY_RED
#define IMAGE_CALENDAR_FOCUSED_TODAY_GREEN IMAGE_CALENDAR_FOCUSED_TODAY_RED
#define IMAGE_CALENDAR_FOCUSED_TODAY_VIOLET IMAGE_CALENDAR_FOCUSED_TODAY_RED
#define IMAGE_CALENDAR_FOCUSED_TODAY_YELLOW IMAGE_CALENDAR_FOCUSED_TODAY_RED

#endif
#endif
//[add new alarm list UI]
RES_ADD_STRING(STR_ALARM_HDR_NEW_EXT01, "New alarm")
RES_ADD_STRING(STXT_SOFTKEY_ADD_ALARM_EXT01,"Add")
RES_ADD_STRING(STR_ALARM_EMPTY_EXT01,"No alarms")
RES_ADD_STRING(STR_LABEL_SET_TIME_EXT01,"Set time")
RES_ADD_STRING(STR_LABEL_ALARM_NAME_EXT01,"Alarm name")
RES_ADD_STRING(STR_LABEL_REPEAT_EXT01,"Repeat")
RES_ADD_STRING(STR_LABEL_ALARM_TONE_EXT01,"Alarm tone")
RES_ADD_STRING(STR_LABEL_SNOOZE_TIME_EXT01,"Snooze time")
RES_ADD_STRING(STXT_ALARM_CLOCK_REP_MON,"Monday")
RES_ADD_STRING(STXT_ALARM_CLOCK_REP_TUE,"Tuesday")
RES_ADD_STRING(STXT_ALARM_CLOCK_REP_WED,"Wednesday")
RES_ADD_STRING(STXT_ALARM_CLOCK_REP_THU,"Thursday")
RES_ADD_STRING(STXT_ALARM_CLOCK_REP_FRI,"Friday")
RES_ADD_STRING(STXT_ALARM_CLOCK_REP_SAT,"Saturday")
RES_ADD_STRING(STXT_ALARM_CLOCK_REP_SUN,"Sunday")
RES_ADD_STRING(STR_DEFAULT_ALARM_NAME,"Alarm")
RES_ADD_STRING(STR_ALARM_LIST_RP_WKD_EXT02,"Weekdays")
RES_ADD_STRING(STR_ALARM_LIST_RP_EVD_EXT02,"Every day")
RES_ADD_STRING(STR_LIST_REPEAT_WEEKENDS_EXT01,"Weekends")
RES_ADD_STRING(STR_ALARM_REPEAT_MO_EXT01,"Mo")
RES_ADD_STRING(STR_ALARM_REPEAT_TU_EXT01,"Tu")
RES_ADD_STRING(STR_ALARM_REPEAT_WE_EXT01,"We")
RES_ADD_STRING(STR_ALARM_REPEAT_TH_EXT01,"Th")
RES_ADD_STRING(STR_ALARM_REPEAT_FR_EXT01,"Fr")
RES_ADD_STRING(STR_ALARM_REPEAT_SA_EXT01,"Sa")
RES_ADD_STRING(STR_ALARM_REPEAT_SU_EXT01,"Su")
RES_ADD_STRING(STR_ILIST_2_MINUTES_EXT01,"2 minutes")
RES_ADD_STRING(STR_ILIST_5_MINUTES_EXT01,"5 minutes")
RES_ADD_STRING(STR_ILIST_10_MINUTES_EXT01,"10 minutes")
RES_ADD_STRING(STR_ILIST_15_MINUTES_EXT01,"15 minutes")
RES_ADD_STRING(STR_ILIST_20_MINUTES_EXT01,"20 minutes")
RES_ADD_STRING(STR_ALARM_LIST_EDIT_EXT01,"Edit")
RES_ADD_STRING(STR_ALARM_LIST_DELETE_ALL_EXT01,"Delete all")
RES_ADD_STRING(STR_SETT_LIST_POWER_ON_EXT01,"Power on")
RES_ADD_STRING(STR_SETT_LIST_POWER_OFF_EXT01,"Power off")
RES_ADD_STRING(STR_SETT_LABEL_TIME_EXT01,"Time")
RES_ADD_STRING(STR_SETT_LIST_REPEAT_EXT01,"Repeat mode")
RES_ADD_STRING(STR_SETT_HDR_REPEAT_EXT01,"Repeat mode")
RES_ADD_STRING(STR_ALARM_NEW_ALARM_EXT01,"New alarm")
RES_ADD_STRING(STR_QUERY_DELETE_ALL_ALARMS_EXT01,"Delete all alarms?")
RES_ADD_STRING(STR_HDR_SNOOZE_TIME_EXT01,"Snooze time")
RES_ADD_STRING(STR_INPUT_ALARM_NAME_EXT01,"Alarm name")
RES_ADD_STRING(STR_ALARM_NOTE_MAX_NUM_EXT02,"You can only have up to 5 alarms.")
RES_ADD_STRING(STR_CALE_HDR_REPEAT_EXT02,"Repeat every")
//[end]

//NHL ADD STRING
RES_ADD_STRING(STR_LIST_GMTP1_ROME,"GMT +1 Rome")
RES_ADD_STRING(STR_LIST_GMTP1_WARSAW,"GMT +1 Warsaw")
RES_ADD_STRING(STR_LIST_GMTP1_PARIS,"GMT +1 Paris")
RES_ADD_STRING(STR_LIST_GMTP1_BERLIN,"GMT +1 Berlin")
RES_ADD_STRING(STR_LIST_GMTP1_LAGOS,"GMT +1 Lagos")
RES_ADD_STRING(STR_LIST_GMTP2_PRETORIA,"GMT +2 Pretoria")
RES_ADD_STRING(STR_LIST_GMTP2_JERUSALEM,"GMT +2 Jerusalem")
RES_ADD_STRING(STR_LIST_GMTP2_HELSINKI,"GMT +2 Helsinki")
RES_ADD_STRING(STR_LIST_GMTP2_ISTABUL,"GMT +2 Istanbul")
RES_ADD_STRING(STR_LIST_GMTP2_CAIRO,"GMT +2 Cairo")
RES_ADD_STRING(STR_LIST_GMTP2_ATHENS,"GMT +2 Athens")
RES_ADD_STRING(STR_LIST_GMTP330_TEHRAN,"GMT +3:30 Tehran")

RES_ADD_STRING(STR_LIST_GMTP3_NAIROBI,"GMT +3 Nairobi")
RES_ADD_STRING(STR_LIST_GMTP3_KUWAIT,"GMT +3 Kuwait")
RES_ADD_STRING(STR_LIST_GMTP3_BAGHDAD,"GMT +3 Baghdad")
RES_ADD_STRING(STR_LIST_GMTP3_MOSCOW,"GMT +3 Moscow")
RES_ADD_STRING(STR_LIST_GMTP4_DUBAI,"GMT +4 Dubai")
RES_ADD_STRING(STR_LIST_GMTP4_MUSCAT,"GMT +4 Muscat")
RES_ADD_STRING(STR_LIST_GMTP430_TASHKENT,"GMT +4:30 Tashkent")
RES_ADD_STRING(STR_LIST_GMTP430_KABUL,"GMT +4:30 Kabul")
RES_ADD_STRING(STR_LIST_GMTP5_ISLAMABAD,"GMT +5 Islamabad")
RES_ADD_STRING(STR_LIST_GMTP530_MUMBAI,"GMT +5:30 Mumbai")
RES_ADD_STRING(STR_LIST_GMTP530_KOLKATA,"GMT +5:30 Kolkata")
RES_ADD_STRING(STR_LIST_GMTP6_DHAKA,"GMT +6 Dhaka")
RES_ADD_STRING(STR_LIST_GMTP6_ALMATY,"GMT +6 Almaty")
RES_ADD_STRING(STR_LIST_GMTP6_EKATERINBURG,"GMT +6 Ekaterinburg")
RES_ADD_STRING(STR_LIST_GMTP6_NOVOSIBIRSK,"GMT +6 Novosibirsk")

RES_ADD_STRING(STR_LIST_GMTP630_YANGON,"GMT +6:30 Yangon")
RES_ADD_STRING(STR_LIST_GMTP7_BANGKOK,"GMT +7 Bangkok")
RES_ADD_STRING(STR_LIST_GMTP7_HANOI,"GMT +7 Hanoi")
RES_ADD_STRING(STR_LIST_GMTP7_JAKARTA,"GMT +7 Jakarta")
RES_ADD_STRING(STR_LIST_GMTP8_BEIJING,"GMT +8 Beijing")
RES_ADD_STRING(STR_LIST_GMTP8_HONGKONG,"GMT +8 Hong Kong")
RES_ADD_STRING(STR_LIST_GMTP9_TOKYO,"GMT +9 Tokyo")
RES_ADD_STRING(STR_LIST_GMTP9_SEOUL,"GMT +9 Seoul")
RES_ADD_STRING(STR_LIST_GMTP930_ADELAIDE,"GMT +9:30 Adelaide")
RES_ADD_STRING(STR_LIST_GMTP930_DARWIN,"GMT +9:30 Darwin")
RES_ADD_STRING(STR_LIST_GMTP10_CANBERRA,"GMT +10 Canberra")
RES_ADD_STRING(STR_LIST_GMTP10_BRISBANE,"GMT +10 Brisbane")
RES_ADD_STRING(STR_LIST_GMTP1030_LORD_HOWE,"GMT +10:30 LDH")
RES_ADD_STRING(STR_LIST_GMTP1130_NORFOLK,"GMT +11:30 Norfolk Is.")
RES_ADD_STRING(STR_LIST_GMTP12_AUCKLAND,"GMT +12 Auckland")
RES_ADD_STRING(STR_LIST_GMTP12_ANADYR,"GMT +12 Anadyr")
RES_ADD_STRING(STR_LIST_GMTP12_MAGADAN,"GMT +12 Magadan")
RES_ADD_STRING(STR_LIST_GMTP12_FIJI,"GMT +12 Fiji")

RES_ADD_STRING(STR_LIST_GMTN12_INTLDATELINE,"GMT -12 IDL West")

RES_ADD_STRING(STR_LIST_GMTN11_SAMOA,"GMT -11 Samoa")
RES_ADD_STRING(STR_LIST_GMTN11_MIDWAY,"GMT -11 Mid. Isl.")

RES_ADD_STRING(STR_LIST_GMTN10_HONOLULU,"GMT -10 Honolulu")
RES_ADD_STRING(STR_LIST_GMTN930_MARQUESAS,"GMT -9:30 Ma. Isl.")
RES_ADD_STRING(STR_LIST_GMTN9_ANCHORAGE,"GMT -9 Anchorage")
RES_ADD_STRING(STR_LIST_GMTN9_ALASKA,"GMT -9 Alaska")

RES_ADD_STRING(STR_LIST_GMTN8_SAN_FRANCISCO,"GMT -8 San Francisco")
RES_ADD_STRING(STR_LIST_GMTN8_VANCOUVER,"GMT -8 Vancouver")
RES_ADD_STRING(STR_LIST_GMTN8_SEATTLE,"GMT -8 Seattle")

RES_ADD_STRING(STR_LIST_GMTN7_PHOENIX,"GMT -7 Phoenix")
RES_ADD_STRING(STR_LIST_GMTN6_MEXICO,"GMT -6 Mexico City")
RES_ADD_STRING(STR_LIST_GMTN6_CHICAGO,"GMT -6 Chicago")
RES_ADD_STRING(STR_LIST_GMTN5_TORONTO,"GMT -5 Toronto")
RES_ADD_STRING(STR_LIST_GMTN5_NEWYORK,"GMT -5 New York")
RES_ADD_STRING(STR_LIST_GMTN5_WASHINGTON_DC,"GMT -5 Washington D.C")

RES_ADD_STRING(STR_LIST_GMTN430_CARACAS,"GMT -4:30 Caracas")
RES_ADD_STRING(STR_LIST_GMTN4_SANTIAGO,"GMT -4 Santiago")
RES_ADD_STRING(STR_LIST_GMTN4_LAPAZ,"GMT -4 La Paz")
RES_ADD_STRING(STR_LIST_GMTN330_STJOHNS,"GMT -3:30 Saint John's")
RES_ADD_STRING(STR_LIST_GMTN3_BUENOSAIRES,"GMT -3 Bs. As. City")
RES_ADD_STRING(STR_LIST_GMTN3_BRASILIA,"GMT -3 Brasilia")
RES_ADD_STRING(STR_LIST_GMTN2_MIDATLANTIC,"GMT -2 Mid-Atlantic")
RES_ADD_STRING(STR_LIST_GMTN1_CAPE_VERDE,"GMT -1 Cape Verde")
RES_ADD_STRING(STR_LIST_GMTN1_AZORES,"GMT -1 Azores")
RES_ADD_STRING(STR_LIST_GMT_CASABLANCA,"GMT Casablanca")
RES_ADD_STRING(STR_LIST_GMT_LONDON,"GMT London")
RES_ADD_STRING(STR_LIST_GMTP1_MADRID,"GMT +1 Madrid")
RES_ADD_STRING(STR_LIST_GMTP10_SYDNEY,"GMT +10 Sydney")
RES_ADD_STRING(STR_LIST_GMTP2_AMMAN,"GMT +2 Amman")
RES_ADD_STRING(STR_LIST_GMTP2_BUCHAREST,"GMT +2 Bucharest")
RES_ADD_STRING(STR_LIST_GMTP2_KYIV,"GMT +2 Kyiv")
RES_ADD_STRING(STR_LIST_GMTP3_DOHA,"GMT +3 Doha")
RES_ADD_STRING(STR_LIST_GMTP3_KAMPALA,"GMT +3 Kampala")
RES_ADD_STRING(STR_LIST_GMTP3_RIYADH,"GMT +3 Riyadh")
RES_ADD_STRING(STR_LIST_GMTP3_SANA,"GMT +3 Sana")
RES_ADD_STRING(STR_LIST_GMTP530_NEW_DELHI,"GMT +5:30 New Delhi")
RES_ADD_STRING(STR_LIST_GMTP545_KATHMANDU,"GMT +5:45 Kathmandu")
RES_ADD_STRING(STR_LIST_GMTP7_PHNOM_PENH,"GMT +7 Phnom Penh")
RES_ADD_STRING(STR_LIST_GMTP8_KUALA_LUMPUR,"GMT +8 Kuala Lumpur")
RES_ADD_STRING(STR_LIST_GMTP8_TAIPEI,"GMT +8 Taipei")
RES_ADD_STRING(STR_LIST_GMTP8_MANILA,"GMT +8 Manila")
RES_ADD_STRING(STR_LIST_GMTN5_BOGOTA,"GMT -5 Bogota")
RES_ADD_STRING(STR_LIST_GMT_ACCRA,"GMT Accra")

#ifdef MMI_JEWISH_CALENDAR
RES_ADD_STRING(TXT_SK_CLOSE, "Close")
RES_ADD_STRING(TXT_SK_DELETE, "Delete")
RES_ADD_STRING(TXT_SK_SELECT, "Select")
RES_ADD_STRING(TXT_SK_LOGIN, "Sign in")
RES_ADD_STRING(TXT_SK_MENU, "Menu")
RES_ADD_STRING(TXT_SK_SELECT_LOC, "Select location")
RES_ADD_STRING(TXT_SK_SELECT_DATE, "Select date")
RES_ADD_STRING(TXT_SK_SETTINGS, "Settings")
RES_ADD_STRING(TXT_SK_ABOUT, "About")
RES_ADD_STRING(TXT_SK_HELP, "Help")
RES_ADD_STRING(TXT_SK_SAVE, "Save")
RES_ADD_STRING(TXT_SPLASH_SCR_WELCOME_TEXT, "Welcome to the Jewish Calendar")
RES_ADD_STRING(TXT_SETTINGS_SCR_DLS_LABEL, "Select a clock type")
RES_ADD_STRING(TXT_SETTINGS_SCR_DLS_OPTION_0, "Automatic")
RES_ADD_STRING(TXT_SETTINGS_SCR_DLS_OPTION_1, "Winter time")
RES_ADD_STRING(TXT_SETTINGS_SCR_DLS_OPTION_2, "Summer time")
RES_ADD_STRING(TXT_ABOUT_SCR_ABOUT_TEXT, "About text")
RES_ADD_STRING(TXT_HELP_SCR_HELP_TEXT, "Help text")
RES_ADD_STRING(TXT_ERR_NETWORK, "Network Error. Please try again later.")
RES_ADD_STRING(TXT_ERR_LOW_MEMORY, "Application free memory is running low. In case this message returns you are advised to close application and re-launch it again.")

/*------------------- Location ------------------------------------*/
RES_ADD_STRING(TXT_SELECT_LOCATION_SCREEN_TITLE, "Select a city from the list")
RES_ADD_STRING(TXT_LOCATION_BNEY_BRAK, "Bney Brak")
RES_ADD_STRING(TXT_LOCATION_JERUSALEM, "Jerusalem")
RES_ADD_STRING(TXT_LOCATION_HAIFA, "Haifa")
RES_ADD_STRING(TXT_LOCATION_MODIIN_ILIT, "Modiin Ilit")
RES_ADD_STRING(TXT_LOCATION_BET_SHEMESH, "Bet Shemesh")
RES_ADD_STRING(TXT_LOCATION_BEITAR_ILIT, "Beitar Ilit")
RES_ADD_STRING(TXT_LOCATION_ELAD, "Elad")
RES_ADD_STRING(TXT_LOCATION_NETIVOT, "Netivot")
RES_ADD_STRING(TXT_LOCATION_TSFAT, "Tsfat")
RES_ADD_STRING(TXT_LOCATION_LONDON, "London")
RES_ADD_STRING(TXT_LOCATION_NEW_YORK, "New York")
RES_ADD_STRING(TXT_LOCATION_PARIS, "Paris")
RES_ADD_STRING(TXT_LOCATION_ZIRICH, "Zirich")
RES_ADD_STRING(TXT_LOCATION_ANTVERPEN, "Antverpen")

/*------------------- Day details------------------------------------*/
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_TITLE, "{0}{1}{2}")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_HOLIDAYS_TITLE, "Holidays")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_LOAZI, "Gregorian Date")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_90MIN, "90 min.")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_72MIN, "72 min.")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_TFILIN, "Tfilin")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_HANETZ, "Hanetz")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_KS_MGA, "Ks mga")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_KS_GRA, "Ks gra")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_TFILA_MGA, "Tfila mga")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_TFILA_GRA, "Tfila gra")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_HATZOT, "Hatzot")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_MINCHA_G, "Mincha G")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_MINCH_K, "Minch K")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_MINCHA_P, "Mincha P")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_SHKIAH, "Shkiah")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_SHKIAH_HEIGHT, "Shkiah height")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_LIGHT_CANDLE, "Light candle")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_STARS, "Stars")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_STARS_TAM, "Stars tam")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_BAVLI, "Bavli")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_JERUSHALMI, "Jerushalmi")
RES_ADD_STRING(TXT_JEWISH_DAY_DETAILS_SCREEN_SHAA_ZMANIT, "Shaa zmanit")

/*------------------- Holidays------------------------------------*/
RES_ADD_STRING(TXT_HOLIDAY_SHABAT_GADOL, "Shabat gadol")
RES_ADD_STRING(TXT_HOLIDAY_EREV_PESACH, "Erev pesach")
RES_ADD_STRING(TXT_HOLIDAY_PESACH, "Pesach")
RES_ADD_STRING(TXT_HOLIDAY_CHOL_HAMOED_PESACH, "Chol hamoed pesach")
RES_ADD_STRING(TXT_HOLIDAY_SHVII_PESACH, "Shvii pesach")
RES_ADD_STRING(TXT_HOLIDAY_SHVII_PESACH_YIZKOR, "Shvii pesach yizkor")
RES_ADD_STRING(TXT_HOLIDAY_YOM_SHOA, "Yom shoa")
RES_ADD_STRING(TXT_HOLIDAY_YOM_ZIKARON, "Yom zikaron")
RES_ADD_STRING(TXT_HOLIDAY_YOM_ATZMAUT, "Yom atzmaut")
RES_ADD_STRING(TXT_HOLIDAY_PESACH_SHENI, "Pesach sheni")
RES_ADD_STRING(TXT_HOLIDAY_LAG_BAOMER, "Lag baomer")
RES_ADD_STRING(TXT_HOLIDAY_YOM_YERUSHALAYIM, "Yom yerushalayim")
RES_ADD_STRING(TXT_HOLIDAY_EREV_SHAVUOT, "Erev shavuot")
RES_ADD_STRING(TXT_HOLIDAY_SHAVUOT, "Shavuot")
RES_ADD_STRING(TXT_HOLIDAY_SHAVUOT_YIZKOR, "Shavuot yizkor")
RES_ADD_STRING(TXT_HOLIDAY_TZOM_TAMUZ, "Tzom tamuz")
RES_ADD_STRING(TXT_HOLIDAY_TISHA_BEAV, "Tisha beav")
RES_ADD_STRING(TXT_HOLIDAY_TU_BEAV, "Tu beav")
RES_ADD_STRING(TXT_HOLIDAY_EREV_ROSH_HSANA, "Erev rosh hsana")
RES_ADD_STRING(TXT_HOLIDAY_ROSH_SHANA_A, "Rosh shana I")
RES_ADD_STRING(TXT_HOLIDAY_ROSH_SHANA_B, "Rosh shana II")
RES_ADD_STRING(TXT_HOLIDAY_TZOM_GEDALYA, "Tzom gedalya")
RES_ADD_STRING(TXT_HOLIDAY_EREV_KIPUR, "Erev kipur")
RES_ADD_STRING(TXT_HOLIDAY_KIPUR_YIZKOR, "Kipur yizkor")
RES_ADD_STRING(TXT_HOLIDAY_EREV_SUKOT, "Erev sukot")
RES_ADD_STRING(TXT_HOLIDAY_SUKOT, "Sukot")
RES_ADD_STRING(TXT_HOLIDAY_CHOL_MOED_SUKOT, "Chol moed sukot")
RES_ADD_STRING(TXT_HOLIDAY_HOSHANA_RABA, "Hoshana raba")
RES_ADD_STRING(TXT_HOLIDAY_SHMINI_ATZERET_YIZKOR, "Shmini atzeret yizkor")
RES_ADD_STRING(TXT_HOLIDAY_SIMCHAT_TORA, "Simchat tora")
RES_ADD_STRING(TXT_HOLIDAY_HANUKA_1, "Hanuka I")
RES_ADD_STRING(TXT_HOLIDAY_HANUKA_2, "Hanuka II")
RES_ADD_STRING(TXT_HOLIDAY_HANUKA_3, "Hanuka III")
RES_ADD_STRING(TXT_HOLIDAY_HANUKA_4, "Hanuka IV")
RES_ADD_STRING(TXT_HOLIDAY_HANUKA_5, "Hanuka V")
RES_ADD_STRING(TXT_HOLIDAY_HANUKA_6, "Hanuka VI")
RES_ADD_STRING(TXT_HOLIDAY_HANUKA_7, "Hanuka VII")
RES_ADD_STRING(TXT_HOLIDAY_HANUKA_8, "Hanuka VIII")
RES_ADD_STRING(TXT_HOLIDAY_TZOM_TEVET, "Tzom tevet")
RES_ADD_STRING(TXT_HOLIDAY_TU_BISHVAT, "Tu bishvat")
RES_ADD_STRING(TXT_HOLIDAY_TAANIT_ESTER, "Taanit ester")
RES_ADD_STRING(TXT_HOLIDAY_PURIM, "Purim")
RES_ADD_STRING(TXT_HOLIDAY_SHUSHAN_PURIM, "Shushan purim")
RES_ADD_STRING(TXT_HOLIDAY_PURIM_KATAN, "Purim katan")
RES_ADD_STRING(TXT_HOLIDAY_SHUSHAN_PURIM_KATAN, "Shushan purim katan")

/*------------------- Masechet ------------------------------------*/
RES_ADD_STRING(TXT_MASECHET_BRACHOT, "Brachot")
RES_ADD_STRING(TXT_MASECHET_SHABAT, "Shabat")
RES_ADD_STRING(TXT_MASECHET_IRUVIN, "Iruvin")
RES_ADD_STRING(TXT_MASECHET_PSACHIM, "Psachim")
RES_ADD_STRING(TXT_MASECHET_SHKALIM, "Shkalim")
RES_ADD_STRING(TXT_MASECHET_YOMA, "Yoma")
RES_ADD_STRING(TXT_MASECHET_SUCA, "Suca")
RES_ADD_STRING(TXT_MASECHET_BEYTZA, "Beytza")
RES_ADD_STRING(TXT_MASECHET_ROSH_HASHANA, "Rosh hashana")
RES_ADD_STRING(TXT_MASECHET_TAANIT, "Taanit")
RES_ADD_STRING(TXT_MASECHET_MEGILA, "Megila")
RES_ADD_STRING(TXT_MASECHET_MOED_KATAN, "Moed katan")
RES_ADD_STRING(TXT_MASECHET_CHAGIGA, "Chagiga")
RES_ADD_STRING(TXT_MASECHET_YEVAMOT, "Yevamot")
RES_ADD_STRING(TXT_MASECHET_KTUBOT, "Ktubot")
RES_ADD_STRING(TXT_MASECHET_NEDARIM, "Nedarim")
RES_ADD_STRING(TXT_MASECHET_NAZIR, "Nazir")
RES_ADD_STRING(TXT_MASECHET_SOTA, "Sota")
RES_ADD_STRING(TXT_MASECHET_GITIN, "Gitin")
RES_ADD_STRING(TXT_MASECHET_KIDUSHIN, "Kidushin")
RES_ADD_STRING(TXT_MASECHET_BABA_KAMA, "Baba kama")
RES_ADD_STRING(TXT_MASECHET_BABA_METZIA, "Baba metzia")
RES_ADD_STRING(TXT_MASECHET_BABA_BATRA, "Baba batra")
RES_ADD_STRING(TXT_MASECHET_SANHEDRIN, "Sanhedrin")
RES_ADD_STRING(TXT_MASECHET_MAKOT, "Makot")
RES_ADD_STRING(TXT_MASECHET_SHVUOT, "Shvuot")
RES_ADD_STRING(TXT_MASECHET_AVODA_ZARA, "Avoda zara")
RES_ADD_STRING(TXT_MASECHET_HORAYOT, "Horayot")
RES_ADD_STRING(TXT_MASECHET_ZEVACHIM, "Zevachim")
RES_ADD_STRING(TXT_MASECHET_MENACHOT, "Menachot")
RES_ADD_STRING(TXT_MASECHET_CHULIN, "Chulin")
RES_ADD_STRING(TXT_MASECHET_BECHOROT, "Bechorot")
RES_ADD_STRING(TXT_MASECHET_ARACHIN, "Arachin")
RES_ADD_STRING(TXT_MASECHET_TMURA, "Tmura")
RES_ADD_STRING(TXT_MASECHET_KRITUT, "Kritut")
RES_ADD_STRING(TXT_MASECHET_MEILA, "Meila")
RES_ADD_STRING(TXT_MASECHET_KINIM, "Kinim")
RES_ADD_STRING(TXT_MASECHET_TAMID, "Tamid")
RES_ADD_STRING(TXT_MASECHET_MIDOT, "Midot")
RES_ADD_STRING(TXT_MASECHET_NIDA, "Nida")
RES_ADD_STRING(TXT_MASECHET_PEAH, "Peah")
RES_ADD_STRING(TXT_MASECHET_DMAY, "Dmay")
RES_ADD_STRING(TXT_MASECHET_KILAYIM, "Kilayim")
RES_ADD_STRING(TXT_MASECHET_SHVIIT, "Shviit")
RES_ADD_STRING(TXT_MASECHET_TRUMOT, "Trumot")
RES_ADD_STRING(TXT_MASECHET_MAASROT, "Maasrot")
RES_ADD_STRING(TXT_MASECHET_MAASER_SHENI, "Maaser sheni")
RES_ADD_STRING(TXT_MASECHET_CHALA, "Chala")
RES_ADD_STRING(TXT_MASECHET_ORLA, "Orla")
RES_ADD_STRING(TXT_MASECHET_BIKURIM, "Bikurim")

/*-------------------  Months ------------------------------------*/
RES_ADD_STRING(STXT_NISAN, "Nisan")
RES_ADD_STRING(STXT_IYAR, "Iyar")
RES_ADD_STRING(STXT_SIVAN, "Sivan")
RES_ADD_STRING(STXT_TAMUZ, "Tamuz")
RES_ADD_STRING(STXT_AV, "Av")
RES_ADD_STRING(STXT_ELUL, "Elul")
RES_ADD_STRING(STXT_TISHREI, "Tishrei")
RES_ADD_STRING(STXT_CHESHVAN, "Cheshvan")
RES_ADD_STRING(STXT_KISLEV, "Kislev")
RES_ADD_STRING(STXT_TEVET, "Tevet")
RES_ADD_STRING(STXT_SHVAT,"Shevat")
RES_ADD_STRING(STXT_ADAR,"Adar")
RES_ADD_STRING(STXT_ADAR_A,"Adar I")
RES_ADD_STRING(STXT_ADAR_B,"Adar II")
RES_ADD_STRING(STXT_ALEF,"Alef")
RES_ADD_STRING(STXT_YUD,"Yud")
RES_ADD_STRING(STXT_QUF,"Quf")
RES_ADD_STRING(STXT_TAF,"Taf")
RES_ADD_STRING(STXT_TU,"Tu")
RES_ADD_STRING(STXT_TZ,"Tz")
#endif
