#ifdef GAME_LINK_SUPPORT

//[[define image infomation
RES_ADD_IMG(IMAGE_PAUSE_BACKGROUND_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PAUSE_BACKGROUND_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_TIP_BACKGROUND_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_TIP_BACKGROUND_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(TIME_BACKGROUND,"\\MMI_RES_##\\IMAG\\time_background.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMAGE_LINKS_RETURN_BUTTON_BACKGROUND,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_RETURN_BUTTON_BACKGROUND.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMAGE_WASHCARD_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_WASHCARD_ICON.png",IMG_CMP_PNG_SABM_RLE,0)
RES_ADD_IMG(IMAGE_TIP_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_TIP_ICON.png",IMG_CMP_PNG_SABM_RLE,0)
RES_ADD_IMG(IMAGE_PAUSE_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PAUSE_ICON.png",IMG_CMP_PNG_SABM_RLE,0)
RES_ADD_IMG(IMAGE_RESUME_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_RESUME_ICON.png",IMG_CMP_PNG_SABM_RLE,0)
RES_ADD_IMG(IMAGE_EPISODE_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_EPISODE_ICON.png",IMG_CMP_PNG_SABM_RLE,0)
RES_ADD_IMG(IMAGE_SCORE_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_SCORE_ICON.png",IMG_CMP_PNG_SABM_RLE,0)
RES_ADD_IMG(IMAGE_TIME_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_TIME_ICON.png",IMG_CMP_PNG_SABM_RLE,0)

RES_ADD_IMG(IMAGE_LINKS_01,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_01.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_02,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_02.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_03,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_03.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_04,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_04.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_05,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_05.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_06,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_06.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_07,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_07.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_08,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_08.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_09,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_09.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_10,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_10.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_11,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_11.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_12,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_12.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_13,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_13.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_14,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_14.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_15,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_15.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_LINKS_16,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_16.bmp",IMG_CMP_BMP_16_565_RLE,0)
//#ifdef JPG_DEC_SUPPORT_JPG_HW
//RES_ADD_IMG(IMAGE_GMLINK_BACKGROUD,"\\MMI_RES_##\\IMAG\\IMAGE_GMLINK_BACKGROUD.jpg",IMG_CMP_JPG_SCI,0)
//RES_ADD_IMG(IMAGE_LINKS_PAUSE,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_PAUSE.jpg",IMG_CMP_JPG_SCI,0)
//RES_ADD_IMG(IMAGE_LINKS_PAUSE_ENG,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_PAUSE_ENG.jpg",IMG_CMP_JPG_SCI,0)
//#else
//RES_ADD_IMG(IMAGE_GMLINK_BACKGROUD,"\\MMI_RES_##\\IMAG\\IMAGE_GMLINK_BACKGROUD.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_LINKS_PAUSE,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_PAUSE.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_LINKS_PAUSE_ENG,"\\MMI_RES_##\\IMAG\\IMAGE_LINKS_PAUSE_ENG.bmp",IMG_CMP_BMP_16_565_RLE,0)
// #endif
//]]define image infomation


//[[define anim infomation
//]]define anim infomation


//[[define string infomation
#if 1
//RES_ADD_STRING(TXT_GAME,"Games")
//RES_ADD_STRING(TXT_GM_LIST,"Game list")//defined but not used
//RES_ADD_STRING(TXT_GM_SET,"Game set")//defined but not used
RES_ADD_STRING(TXT_CLASS,"Class")
//RES_ADD_STRING(TXT_RESET,"Reset")
//RES_ADD_STRING(TXT_GM_MUSIC,"Music")//defined but not used
//RES_ADD_STRING(TXT_GM_MUSIC_ON,"Game music opened")//case3 :defined but not used
//RES_ADD_STRING(TXT_GM_MUSIC_OFF,"Game music closed")//case3 :defined but not used
//RES_ADD_STRING(TXT_GAME_LAST,"Last view")//case3 :defined but not used
//RES_ADD_STRING(TXT_SETTING,"Setting")     //replaced by common ID STXT_MAIN_SETTING
//RES_ADD_STRING(TXT_CANCEL,"Cancel")//case3 :defined but not used
//RES_ADD_STRING(TXT_LINKS,"Links")        //replaced by common ID TXT_COMMON_GAME_LINK
RES_ADD_STRING(TXT_CLASS_EASY,"Easy")
RES_ADD_STRING(TXT_CLASS_NORMAL,"Normal")
RES_ADD_STRING(TXT_CLASS_HARD,"Hard")
//RES_ADD_STRING(TXT_EPISODE,"Episode")//case3 :defined but not used
//RES_ADD_STRING(TXT_WASHCARD,"Wash")//case3 :defined but not used
//RES_ADD_STRING(TXT_TIP,"Tip")//case3 :defined but not used
//RES_ADD_STRING(TXT_RESUME,"Resume")    //replaced by common ID TXT_COMMON_COMMON_CONTINUE
RES_ADD_STRING(TXT_GAME_OVER,"Game over")
RES_ADD_STRING(TXT_LINKS_HELP,"Matching different tiles, two tiles can be eliminated when the two tiles have a connect path less than two corners.")
//RES_ADD_STRING(TXT_SCORE,"Score")//case3 :defined but not used
RES_ADD_STRING(TXT_HIGH_SCORE,"High score")
//RES_ADD_STRING(TXT_GAMELINKS_EPISODE,"Ep")//case3 :defined but not used
//RES_ADD_STRING(TXT_GAMELINKS_WASHCARD,"Wash")//case3 :defined but not used
//RES_ADD_STRING(TXT_GAMELINKS_TIP,"Tip")//case3 :defined but not used
//RES_ADD_STRING(TXT_GAMELINKS_PAUSE,"Pause")    //replaced by common ID  TXT_PAUSE
//RES_ADD_STRING(TXT_GAMELINKS_RESUME,"Resume")     //replaced by common ID TXT_COMMON_COMMON_CONTINUE
//RES_ADD_STRING(TXT_GAMELINKS_SCORE,"Score")//case3 :defined but not used
//RES_ADD_STRING(TXT_GAMELINKS_TIME,"Time")//case3 :defined but not used
#endif
//]]define string infomation


//[[define data infomation
//]]define data infomation
#endif
