#define MMI_PICVIEW_MINI_SUPPORT TRUE //zhuyongjing add for gallary UI 20150707
//[[define image infomation
#ifdef PIC_PREVIEW_U200_SUPPORT
RES_ADD_IMG(IMAGE_PICVIEW_OPTION,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_OPTION.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#if defined( PICVIEW_VIEW_ZOOM) || defined(PIC_PREVIEW_U200_SUPPORT)
//RES_ADD_IMG(IMAGE_PICVIEW_PLAY,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_PLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_RETURN,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_RETURN.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#ifdef PICVIEW_VIEW_ZOOM
#if 0 //8910UIX delete
RES_ADD_IMG(IMAGE_PICVIEW_ZOOM_IN,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_ZOOM_IN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_ZOOM_IN_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_ZOOM_IN_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_ZOOM_OUT,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_ZOOM_OUT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_ZOOM_OUT_GRAY,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_ZOOM_OUT_GRAY.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#if defined ( PIC_VIEWER_SUPPORT )
#ifndef MMI_PICVIEW_MINI_SUPPORT
RES_ADD_IMG(IMAGE_PICVIEW_CHANGE_FOLDER,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_CHANGE_FOLDER.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
#ifdef PIC_PREVIEW_U200_SUPPORT
#ifdef PIC_EDITOR_SUPPORT
RES_ADD_IMG(IMAGE_PICVIEW_EDIT_IMAGE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_EDIT_IMAGE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
//RES_ADD_IMG(IMAGE_PICVIEW_ZOOM,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_ZOOM.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_SLIDEPLAY_ICON,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_SLIDEPLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PICVIEW_FOLDER_DEFAULT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_FOLDER_DEFAULT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PICVIEW_FOLDER_LIST_TITLE_BG,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_FOLDER_LIST_TITLE_BG.png",IMG_CMP_PNG_SABM_RLE |SABM_HOR_STRETCH,0)
//RES_ADD_IMG(IMAGE_PICVIEW_CAMERA_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_CAMERA_BUTTON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_PICVIEW_CAMERA_BUTTON_SELECTED,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_CAMERA_BUTTON_SELECTED.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#if defined ( PIC_VIEWER_SUPPORT )
#ifdef PIC_PREVIEW_U200_SUPPORT
RES_ADD_IMG(IMAGE_PICVIEW_FOLDER_LIST_BG,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_FOLDER_LIST_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif
#endif
#ifdef PIC_PREVIEW_U200_SUPPORT
#ifdef PIC_GLIDE_SUPPORT
RES_ADD_IMG(IMAGE_DECODE_ON,"\\MMI_RES_##\\IMAG\\IMAGE_DECODE_ON.gif",IMG_CMP_GIF_SCI,0)
#endif
#endif
//]]define image infomation
#if defined ( PIC_VIEWER_SUPPORT )
RES_ADD_IMG(IMAGE_PICVIEW_OSD_BG,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_OSD_BG.png",IMG_CMP_PNG_SABM_RLE|SABM_CEN_STRETCH,0)
#endif
#ifdef PIC_PREVIEW_U200_SUPPORT
RES_ADD_IMG(IMAGE_PICVIEW_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_BUTTON.png",IMG_CMP_PNG_SABM_RLE|SABM_CEN_STRETCH,0)
RES_ADD_IMG(IMAGE_PICVIEW_CAMERA,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_CAMERA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_SET,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_SET.png",IMG_CMP_PNG_ARGB_RLE,0)  

RES_ADD_IMG(IMAGE_PICVIEW_MARK_DEFAULT,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_MARK_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_PICVIEW_PLAY_DEFAULT,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_PLAY_DEFAULT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_DELETE,"\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_PICVIEW_DELETE.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

#ifndef PIC_PREVIEW_U200_SUPPORT
#ifndef MMI_RES_LOW_COST
RES_ADD_IMG(IMAGE_PICVIEW_CAMERA_FOLDER,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_CAMERA.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
#endif
RES_ADD_IMG(IMAGE_PICVIEW_FOLDER_DEFAULT_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_FOLDER_DEFAULT_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_PIC_ERROR_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_PIC_ERROR_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_GUI_STYLE_MINISCREEN
RES_ADD_IMG(IMAGE_PICVIEW_TIME_BG, "\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_TIME_BG.png", IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH, 0)
RES_ADD_IMG(IMAGE_PICVIEW_TITLE_OSD_BG, "\\MMI_RES_##\\IMAG\\IMAGE_PICVIEW_OSD_BG.png", IMG_CMP_PNG_SABM_RLE|SABM_HOR_STRETCH, 0)
#endif

//[[define anim infomation
//]]define anim infomation

#if 1
//[[define string infomation
//RES_ADD_STRING(TXT_PICVIEW_SHORT,"Pictures")    //case3: defined but not used
//RES_ADD_STRING(TXT_PICVIEW_NO_PIC,"No picture")    //case3: defined but not used
//RES_ADD_STRING(TXT_PICVIEW_PREVIEW,"Preview")    //case3: defined but not used
#if defined ( PIC_VIEWER_SUPPORT )
#ifndef MMI_PICVIEW_MINI_SUPPORT
RES_ADD_STRING(TXT_PICVIEW_CHANGE_FOLDER,"Change folder")
#endif
#endif
//RES_ADD_STRING(TXT_PICVIEW_SEND,"Send")
//RES_ADD_STRING(TXT_PICVIEW_WALLPAPER,"Wallpaper")          //replaced by common ID TXT_COMMON_SETAS_WALLPAPER
//RES_ADD_STRING(TXT_PICVIEW_ZOOM,"Zoom")    //replaced by common ID TXT_ZOOM
//RES_ADD_STRING(TXT_PICVIEW_MARK,"Mark")  //replaced by common ID STXT_SOFTKEY_MARK_MK
//RES_ADD_STRING(TXT_PICVIEW_DELETE,"Delete")        //replaced by common ID TXT_DELETE
//RES_ADD_STRING(TXT_PICVIEW_RENAME,"Rename")  //replaced by common ID TXT_COMMON_RENAME
//RES_ADD_STRING(TXT_PICVIEW_DETAIL,"Detail")    //replaced by common ID STXT_DETAIL
//RES_ADD_STRING(TXT_PICVIEW_MMS,"MMS") //replaced by common ID TXT_MMS
//RES_ADD_STRING(TXT_PICVIEW_BT,"Blue tooth")        //replaced by common ID TXT_BLUETOOTH
#ifdef SNS_SUPPORT 
//RES_ADD_STRING(TXT_PICVIEW_TO_SNS,"Share to Sinaweibo")    //case3: defined but not used
#endif
//RES_ADD_STRING(TXT_PICVIEW_MARK_CANCEL,"Cancel mark")     //replaced by common ID TXT_CANCEL_MARK
//RES_ADD_STRING(TXT_PICVIEW_MARK_ALL,"Mark all")  //replaced by common ID TXT_MARK_ALL
//RES_ADD_STRING(TXT_PICVIEW_MARK_ALL_CANCEL,"Cancel all mark")      //replaced by common ID TXT_CANCEL_MARK_ALL
#if defined ( PIC_VIEWER_SUPPORT ) 
RES_ADD_STRING(TXT_PICVIEW_SLIDE_PREVIEW,"Slide play")
#ifndef MMI_RES_LOW_COST
RES_ADD_STRING(TXT_PICVIEW_SLIDE_SET,"Slide setting")
//RES_ADD_STRING(TXT_PICVIEW_PLAY,"Play")    //case3: defined but not used
RES_ADD_STRING(TXT_PICVIEW_VIEW,"View")
#endif
//RES_ADD_STRING(TXT_PICVIEW_VIEW_LIST,"List")     //replaced by common ID TXT_COMMON_LIST
RES_ADD_STRING(TXT_PICVIEW_VIEW_ICONLIST,"Thumbnail")
//RES_ADD_STRING(TXT_PICVIEW_EFFECT,"Select effect")    //replaced by common ID TXT_EFFECT
//RES_ADD_STRING(TXT_PICVIEW_EFFECT_NONE,"None")    //replaced by common ID TXT_NONE
#ifndef MMI_RES_LOW_COST
RES_ADD_STRING(TXT_PICVIEW_EFFECT_ENLARGE,"Box enlarge")
RES_ADD_STRING(TXT_PICVIEW_EFFECT_GRID,"Grid extend")
//RES_ADD_STRING(TXT_PICVIEW_EFFECT_WHIRL,"Whirl extend")    //case3: defined but not used
RES_ADD_STRING(TXT_PICVIEW_EFFECT_RIGHTWARD,"Rightward extend")
RES_ADD_STRING(TXT_PICVIEW_EFFECT_LEFTWARD,"Leftward extend")
RES_ADD_STRING(TXT_PICVIEW_EFFECT_UPWARD,"Upward extend")
RES_ADD_STRING(TXT_PICVIEW_EFFECT_DOWNWARD,"Downward extend")
RES_ADD_STRING(TXT_PICVIEW_EFFECT_ORDER,"Order effect")
#endif
RES_ADD_STRING(TXT_PICVIEW_NOPHOTO,"No Photo!")
#if (!defined MMI_RES_LOW_COST||defined SLIDESHOW_WALLPAPER_SUPPORT)
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME,"Slide time")
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME_16S,"16s")
#endif
#endif
#ifdef EFFECT_RIPPLE_SUPPORT  
RES_ADD_STRING(TXT_PICVIEW_EFFECT_RIPPLE,"Ripple effect")
#endif
#ifdef SLIDESHOW_WALLPAPER_SUPPORT
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME_4S,"4s")//replaced by common ID TXT_COMM_2_SECONDS
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME_6S,"6s")  //replaced by common ID TXT_COMM_3_SECONDS
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME_8S,"8s")  //replaced by common ID TXT_COMM_6_SECONDS
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME_10S,"10s") //replaced by common ID TXT_COMM_10_SECONDS
RES_ADD_STRING(TXT_PICVIEW_SLIDE_TIME_20S,"20s")  //replaced by common ID TXT_COMM_20_SECONDS
#endif
//RES_ADD_STRING(TXT_PICVIEW_FILE_NAME,"File name:")  //replaced by common ID TXT_INPUT_FILE_NAME
//RES_ADD_STRING(TXT_PICVIEW_DATE,"Date:")  //replaced by common ID TXT_COMMON_DATE
//RES_ADD_STRING(TXT_PICVIEW_TIME,"Time:")  //replaced by common ID TXT_COMMON_TIME
//RES_ADD_STRING(TXT_PICVIEW_SIZE,"Size:")  //replaced by common ID TXT_DETAIL_SIZE
//RES_ADD_STRING(TXT_PICVIEW_LOCATION,"Location:")    //replaced by common ID TXT_LOCATION   
//RES_ADD_STRING(TXT_PICVIEW_RESOLUTION,"Resolution:")  //replaced by common ID TXT_COMM_RESOLUTION
//RES_ADD_STRING(TXT_PICVIEW_FOLDER_NAME,"Folder name:")    //case3: defined but not used

#ifdef PIC_PREVIEW_U200_SUPPORT
RES_ADD_STRING(TXT_PICVIEW_VIEW_SETTING,"View setting")
//RES_ADD_STRING(TXT_PICVIEW_MMS_SEND,"Send by MMS")    //case3: defined but not used
//RES_ADD_STRING(TXT_PICVIEW_BT_SEND,"Send by BT")    //case3: defined but not used
#endif
RES_ADD_STRING(TXT_DC_MY_PICTURE,"My picture")

//RES_ADD_STRING(TXT_ZERO_SIZE_FILE_ALARM,"The size of this file is 0 !")
//RES_ADD_STRING(TXT_PICVIEW_TAKE_PHOTO,"Take Photo")      //replaced by common ID TXT_COMMON_CAPTURE
#if defined ( PIC_VIEWER_SUPPORT ) 
RES_ADD_STRING(TXT_PICVIEW_SHARE,"Share")
#ifdef MMIPB_ADD_EXIST_CONTACT_SUPPORT
RES_ADD_STRING(TXT_PICVIEW_PB,"Set as Phone Book icon")
#endif
#if defined (TOUCH_GESTURE_ENABLE) && defined(PICVIEW_F_VIEW_ZOOM)
RES_ADD_STRING(TXT_PICVIEW_ZOOM_INMAX,"Zoom in to the max!")
RES_ADD_STRING(TXT_PICVIEW_ZOOM_OUTMIN,"Zoom out to the min!")
#endif
#endif
//]]define string infomation
#ifdef MMI_GUI_STYLE_MINISCREEN
RES_ADD_STRING(TXT_PICVIEW_TITLE,"My Photos")
#endif
//zhuyongjing add for gallary UI 20150707
RES_ADD_STRING(STR_GAL_HDR_SHOW_EXT01,"Show")
RES_ADD_STRING(STR_GAL_LIST_DELETE_ITEMS_EXT01,"Delete items")
RES_ADD_STRING(STR_GAL_LIST_SHARE_ITEMS_EXT01,"Share items")
RES_ADD_STRING(STR_ONEDRIVE_LIST_ONEDRIVE,"OneDrive")
RES_ADD_STRING(STR_GAL_LIST_ALL_EXT01,"All local")
RES_ADD_STRING(STR_GALLERY_CAPTURED_PHOTOS_MK,"Captured")
RES_ADD_STRING(STR_GAL_LIST_ONEDRIVE_EXT01,"OneDrive only")
RES_ADD_STRING(STR_GALLERY_DOWNLOADED_EXT01,"Downloaded")
RES_ADD_STRING(STR_GAL_NOTE_FOLDER_EMPTY_EXT01,"Nothing here. Go to Camera and start shooting your own masterpieces.")
RES_ADD_STRING(STR_PHOTO_EMPTY_HINT_MK, "No photos. Use your camera to get snapping.")
RES_ADD_STRING(STR_ONEDRIVE_LIST_SAVE,"Save to OneDrive")
RES_ADD_STRING(STR_ONEDRIVE_NOTE_SAVING_EXT01,"Saving image to OneDrive. This requires mobile data connection. Do you want to continue?")
RES_ADD_STRING(STR_ONEDRIVE_LIST_SAVE_ITEMS_EXT01,"Save items to OneDrive")
RES_ADD_STRING(STR_GAL_NOTE_DELETE_PHOTO_EXT01,"The photo will be deleted only from the phone but will remain available in OneDrive. Delete selected item?")
RES_ADD_STRING(STR_DELETE_SELECTED_EXT01,"Delete selected item?")
RES_ADD_STRING(STR_GAL_LIST_SLIDE_PLAY_EXT01,"Slide play")
RES_ADD_STRING(STR_ONEDRIVE_LIST_SHARE_EXT01,"Share link")
RES_ADD_STRING(STR_ONEDRIVE_NOTE_DOWNLOAD_EXT01,"Downloading image from OneDrive uses data connection. Do you want to continue?")
RES_ADD_STRING(STR_ID_UMMS_DOWNLOAD_IN_PROGRESS,"Downloading...")
RES_ADD_STRING(STR_ONEDRIVE_DOWNLOAD_FAILED_EXT01,"Downloading image from OneDrive failed. Try again.")

RES_ADD_STRING(STR_GAL_NOTE_DOWN_SUC_EXT02,"Download successful")
RES_ADD_STRING(STR_ONEDRIVE_CONF_UPLOADED_EXT01,"Image uploaded to OneDrive.")
RES_ADD_STRING(STR_ONEDRIVE_UPLOAD_FAILED_EXT01,"Could not upload to OneDrive. Try again.")
RES_ADD_STRING(STR_ONEDRIVE_ERROR_SYNC_EXT01,"You have images that have not been sync. Check your data connection.")
RES_ADD_STRING(STR_GAL_HDR_DELETE_EXT02,"Delete")
RES_ADD_STRING(STR_GAL_HDR_SHARE_EXT02,"Share")
RES_ADD_STRING(STR_GAL_LIST_VIDEO_ALBUM,"Video")
RES_ADD_STRING(STR_OPTIONS_SEND_VIA_SMS,"Via text message")
RES_ADD_STRING(STR_TITLE_PHOTOS_SAFE,"Keep your photos safe")
RES_ADD_STRING(STR_QUERY_PHOTOS_SAFE,"Do you want to connect your photo library with Microsoft OneDrive?")
RES_ADD_STRING(STR_DOWNLOAD_CANCELLED_EXT01,"Download cancelled")
RES_ADD_STRING(STR_GAL_STATUS_UPLOADING_EXT01,"Uploading")
RES_ADD_STRING(STR_NO_DATA_CONNECTION,"Network connect failed. Check your data connection. Try later.")
RES_ADD_STRING(STR_MSA_SIGNIN_UNSUCCESS,"Account sign-in unsuccessful. Please check it.")
RES_ADD_STRING(STR_ONEDRIVE_HDR_SAVE_EXT01,"Save")

RES_ADD_IMG(IMAGE_GALLERY_ONEDRIVE_UPLOADED_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ONEDRIVE_UPLOAD.png ",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GALLERY_ONEDRIVE_FAILED_UPLOAD_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ONEDRIVE_UPLOAD_FAILED.png ",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef MMI_COMPILE_E//8910UIX
RES_ADD_IMG(IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_BLUE,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ONEDRIVE_SYNCED_BLUE.png ",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_COPPER,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ONEDRIVE_SYNCED_COPPER.png ",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_GREEN,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ONEDRIVE_SYNCED_GREEN.png ",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_RED,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ONEDRIVE_SYNCED_RED.png ",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_VIOLET,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ONEDRIVE_SYNCED_VIOLET.png ",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_YELLOW,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ONEDRIVE_SYNCED_YELLOW.png ",IMG_CMP_PNG_ARGB_RLE,0)
#else
RES_ADD_IMG(IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_RED,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ONEDRIVE_SYNCED_RED.png ",IMG_CMP_PNG_ARGB_RLE,0)
#define IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_BLUE IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_RED
#define IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_COPPER IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_RED
#define IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_GREEN IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_RED
#define IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_VIOLET IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_RED
#define IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_YELLOW IMAGE_GALLERY_ONEDRIVE_SYNCED_ICON_RED
#endif
//RES_ADD_IMG(IMAGE_ONEDRIVE_UPLOADING_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ONEDRIVE_UPLOADING.png ",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_ONEDRIVE_UPLOADING_RSK,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ONEDRIVE_UPLOADING_RSK.png ",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_PICVIEW_VIDEO_PLAY,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_PLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_ONEDRIVE_DEFAULT_PIC,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ONEDRIVE_DEFAULT_PIC.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GALLERY_PROMO_PHOTOS,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_PROMO_PHOTOS.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_ONEDRIVE_INFO,"\\MMI_RES_##\\IMAG\\IMAGE_COMMON_INFO.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GALLERY_ZOOM_IN_DIM,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ZOOM_IN_DIMMED.png",IMG_CMP_PNG_ARGB_RLE,0)

//lijinghua add for pic zoom
RES_ADD_IMG(IMAGE_GALLERY_ZOOM_IN,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ZOOM_IN.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_GALLERY_ZOOM_OUT,"\\MMI_RES_##\\IMAG\\IMAGE_GALLERY_ZOOM_OUT.png",IMG_CMP_PNG_ARGB_RLE,0)
//add end

//lijinghua add for Gallery UI 20150720
RES_ADD_STRING(STR_GAL_CONF_ITEM_REMOVED,"Deleted.")
RES_ADD_STRING(STR_QUEST_DELETE_ITEMS,"Delete N% items?")
RES_ADD_STRING(STR_QUEST_DELETE_ITEM,"Delete 1 item?")
//lijinghua add end

//lijinghua add for gallery UI 20150720
RES_ADD_STRING(STR_GAL_HDR_DETAILS_EXT01, "Details")
//RES_ADD_STRING(STR_MCD_DTAIL_COD_NAME, "Name:")
RES_ADD_STRING(STR_GAL_LAST_MODIFIED_EXT01, "Last modified:")
RES_ADD_STRING(STR_GAL_EXTENSION_EXT01, "Extension:")
//RES_ADD_STRING(STR_MCD_DTAIL_COD_SIZE, "Size:")
RES_ADD_STRING(STR_GAL_FILE_TYPE_EXT01, "File type:")
RES_ADD_STRING(STR_GAL_RESOLUTION_EXT01, "Resolution:")
RES_ADD_STRING(STR_GAL_PATH_EXT01, "Path:")
//RES_ADD_STRING(STR_GAL_HDR_SHARE_EXT02,"Share")

//RES_ADD_STRING(STXT_STORED,"Saved.")
RES_ADD_STRING(STR_GAL_CONF_RENAMED_EXT01, "Renamed.")
RES_ADD_STRING(STR_GAL_SET_SCREEN_DONE_EXT01, "Done.")
RES_ADD_STRING(STR_GAL_LIST_DURATION,"Length:")
RES_ADD_STRING(STR_PHOTO_EDIT_ZOOM_EXT01,"Zoom")
RES_ADD_STRING(STR_GAL_UPLOADING_NUMBER_EXT01,"Uploading %0N/%1N...")
//lijinghua end

RES_ADD_STRING(STR_PHOTO_EMPTY, "No photos")//add by James li

#endif

//[[define data infomation
//]]define data infomation
