/** Generated file, DO NOT edit it manually */
#ifndef OPERAFUNCRENAME_H
#define OPERAFUNCRENAME_H

#ifdef __cplusplus
extern "C" {
#endif

// OD_API_RENAME_PREFIX is a prefix of the APIs, for example, OPERA_MINI_
#ifdef OD_API_RENAME_PREFIX

/*
* FIXME: Currently OD_API_RENAME_PREFIX is not used when rename symbols,
* because following code don't work on ADS12:
* 
* #define OD_API_RENAME_PREFIX _OperaMini_
* #define OPERA_API_RENAME(x, y) x##y
* #define OD_FileOpen OPERA_API_RENAME(OD_API_RENAME_PREFIX, OD_FileOpen)
* 
* OD_FileOpen will be replaced to "_OperaMini_  OD_FileOpen". It will add some spaces btween the two names.
* 
* So we hardcoded to "#define OPERA_API_RENAME(x)	_OperaMini_##x"
*/
	#undef OPERA_API_RENAME
	#define OPERA_API_RENAME(x)	_OperaMini_##x

	#define OD_BookmarkImportIsAvailable OPERA_API_RENAME(OD_BookmarkImportIsAvailable)
	#define OD_BookmarkImportEnumBegin OPERA_API_RENAME(OD_BookmarkImportEnumBegin)
	#define OD_BookmarkImportEnumEnd OPERA_API_RENAME(OD_BookmarkImportEnumEnd)
	#define OD_BookmarkImportGetNextDataSize OPERA_API_RENAME(OD_BookmarkImportGetNextDataSize)
	#define OD_BookmarkImportGetNext OPERA_API_RENAME(OD_BookmarkImportGetNext)
	#define OD_InitDebugger OPERA_API_RENAME(OD_InitDebugger)
	#define OD_DeinitDebugger OPERA_API_RENAME(OD_DeinitDebugger)
	#define OD_WriteLogFile OPERA_API_RENAME(OD_WriteLogFile)
	#define OD_Trace OPERA_API_RENAME(OD_Trace)
	#define OD_TraceWString OPERA_API_RENAME(OD_TraceWString)
	#define OD_PrintStackTrace OPERA_API_RENAME(OD_PrintStackTrace)
	#define OD_SetDataBreakPoint OPERA_API_RENAME(OD_SetDataBreakPoint)
	#define OD_Assert OPERA_API_RENAME(OD_Assert)
	#define OD_DASRequestSavePath OPERA_API_RENAME(OD_DASRequestSavePath)
	#define OD_DASReportProgress OPERA_API_RENAME(OD_DASReportProgress)
	#define OD_DASResponseCancelPrefetch OPERA_API_RENAME(OD_DASResponseCancelPrefetch)
	#define OD_DASAbortPrefetch OPERA_API_RENAME(OD_DASAbortPrefetch)
	#define OD_DASStopResponse OPERA_API_RENAME(OD_DASStopResponse)
	#define OD_DASShowDownloadList OPERA_API_RENAME(OD_DASShowDownloadList)
	#define OD_DASStartBrowser OPERA_API_RENAME(OD_DASStartBrowser)
	#define OD_DASExitBrowser OPERA_API_RENAME(OD_DASExitBrowser)
	#define OD_DASSendAuthenticationData OPERA_API_RENAME(OD_DASSendAuthenticationData)
	#define OD_DownloadIsMimeTypeSupport OPERA_API_RENAME(OD_DownloadIsMimeTypeSupport)
	#define OD_DownloadIsDDMimeType OPERA_API_RENAME(OD_DownloadIsDDMimeType)
	#define OD_DownloadHandleMIMEDownloaded OPERA_API_RENAME(OD_DownloadHandleMIMEDownloaded)
	#define OD_FileInit OPERA_API_RENAME(OD_FileInit)
	#define OD_FileDeinit OPERA_API_RENAME(OD_FileDeinit)
	#define OD_CountFileHandles OPERA_API_RENAME(OD_CountFileHandles)
	#define OD_FileOpen OPERA_API_RENAME(OD_FileOpen)
	#define OD_FileClose OPERA_API_RENAME(OD_FileClose)
	#define OD_FileCommit OPERA_API_RENAME(OD_FileCommit)
	#define OD_FileDelete OPERA_API_RENAME(OD_FileDelete)
	#define OD_FileExtend OPERA_API_RENAME(OD_FileExtend)
	#define OD_FileExist OPERA_API_RENAME(OD_FileExist)
	#define OD_FileGetAttributes OPERA_API_RENAME(OD_FileGetAttributes)
	#define OD_FileGetLength OPERA_API_RENAME(OD_FileGetLength)
	#define OD_FileGetPosition OPERA_API_RENAME(OD_FileGetPosition)
	#define OD_FileGetTimestampsFromHandle OPERA_API_RENAME(OD_FileGetTimestampsFromHandle)
	#define OD_FileGetTimestampsFromAttributes OPERA_API_RENAME(OD_FileGetTimestampsFromAttributes)
	#define OD_FileIsForwardable OPERA_API_RENAME(OD_FileIsForwardable)
	#define OD_FileRead OPERA_API_RENAME(OD_FileRead)
	#define OD_FileRename OPERA_API_RENAME(OD_FileRename)
	#define OD_FileSetAttributes OPERA_API_RENAME(OD_FileSetAttributes)
	#define OD_FileSetPosition OPERA_API_RENAME(OD_FileSetPosition)
	#define OD_FileTruncate OPERA_API_RENAME(OD_FileTruncate)
	#define OD_FileWrite OPERA_API_RENAME(OD_FileWrite)
	#define OD_FindFirst OPERA_API_RENAME(OD_FindFirst)
	#define OD_FindNext OPERA_API_RENAME(OD_FindNext)
	#define OD_FindClose OPERA_API_RENAME(OD_FindClose)
	#define OD_DirectoryCreate OPERA_API_RENAME(OD_DirectoryCreate)
	#define OD_DirectoryRemove OPERA_API_RENAME(OD_DirectoryRemove)
	#define OD_DirectoryGetSize OPERA_API_RENAME(OD_DirectoryGetSize)
	#define OD_DirectoryGetPredefined OPERA_API_RENAME(OD_DirectoryGetPredefined)
	#define OD_GetCardDriveLetter OPERA_API_RENAME(OD_GetCardDriveLetter)
	#define OD_GetPublicDriveLetter OPERA_API_RENAME(OD_GetPublicDriveLetter)
	#define OD_GetSystemDriveLetter OPERA_API_RENAME(OD_GetSystemDriveLetter)
	#define OD_GetStorageDriveLetter OPERA_API_RENAME(OD_GetStorageDriveLetter)
	#define OD_DriveGetAllVisibleLetters OPERA_API_RENAME(OD_DriveGetAllVisibleLetters)
	#define OD_DriveGetCurrentLetter OPERA_API_RENAME(OD_DriveGetCurrentLetter)
	#define OD_DriveGetSystemLetters OPERA_API_RENAME(OD_DriveGetSystemLetters)
	#define OD_GetPrestorageFolder OPERA_API_RENAME(OD_GetPrestorageFolder)
	#define OD_GetStorageFolder OPERA_API_RENAME(OD_GetStorageFolder)
	#define OD_DriveIsWritable OPERA_API_RENAME(OD_DriveIsWritable)
	#define OD_GetDriveFreeSpace OPERA_API_RENAME(OD_GetDriveFreeSpace)
	#define OD_PathsEqual OPERA_API_RENAME(OD_PathsEqual)
	#define OD_XDelete OPERA_API_RENAME(OD_XDelete)
	#define OD_FontInit OPERA_API_RENAME(OD_FontInit)
	#define OD_FontDeinit OPERA_API_RENAME(OD_FontDeinit)
	#define OD_GetFontMetrics OPERA_API_RENAME(OD_GetFontMetrics)
	#define OD_GetCharMetrics OPERA_API_RENAME(OD_GetCharMetrics)
	#define OD_GetTextWidth OPERA_API_RENAME(OD_GetTextWidth)
	#define OD_MeasureString OPERA_API_RENAME(OD_MeasureString)
	#define OD_DrawText OPERA_API_RENAME(OD_DrawText)
	#define OD_GetTextData OPERA_API_RENAME(OD_GetTextData)
	#define OD_GDIInit OPERA_API_RENAME(OD_GDIInit)
	#define OD_GDIDeinit OPERA_API_RENAME(OD_GDIDeinit)
	#define OD_GDIUseNativeMemory OPERA_API_RENAME(OD_GDIUseNativeMemory)
	#define OD_GDIAllocMemory OPERA_API_RENAME(OD_GDIAllocMemory)
	#define OD_GDIFreeMemory OPERA_API_RENAME(OD_GDIFreeMemory)
	#define OD_GDICreateLayer OPERA_API_RENAME(OD_GDICreateLayer)
	#define OD_GDIDestroyLayer OPERA_API_RENAME(OD_GDIDestroyLayer)
	#define OD_ShowOpera OPERA_API_RENAME(OD_ShowOpera)
	#define OD_HideOpera OPERA_API_RENAME(OD_HideOpera)
	#define OD_Paint OPERA_API_RENAME(OD_Paint)
	#define OD_GetScreenBuffer OPERA_API_RENAME(OD_GetScreenBuffer)
	#define OD_GetViewportArea OPERA_API_RENAME(OD_GetViewportArea)
	#define OD_GetLayerDimension OPERA_API_RENAME(OD_GetLayerDimension)
	#define OD_GetLayerPixelFormat OPERA_API_RENAME(OD_GetLayerPixelFormat)
	#define OD_GetLayerBPP OPERA_API_RENAME(OD_GetLayerBPP)
	#define OD_GetScreenDPI OPERA_API_RENAME(OD_GetScreenDPI)
	#define OD_GetRotationAngle OPERA_API_RENAME(OD_GetRotationAngle)
	#define OD_RotateScreen OPERA_API_RENAME(OD_RotateScreen)
	#define OD_GetScreenMode OPERA_API_RENAME(OD_GetScreenMode)
	#define OD_ToggleFullScreen OPERA_API_RENAME(OD_ToggleFullScreen)
	#define OD_EnterFullScreenEditor OPERA_API_RENAME(OD_EnterFullScreenEditor)
	#define OD_CloseFullScreenEditor OPERA_API_RENAME(OD_CloseFullScreenEditor)
	#define OD_ImeEnterScreen OPERA_API_RENAME(OD_ImeEnterScreen)
	#define OD_ImeExitScreen OPERA_API_RENAME(OD_ImeExitScreen)
	#define OD_ImeConnect OPERA_API_RENAME(OD_ImeConnect)
	#define OD_ImeDisconnect OPERA_API_RENAME(OD_ImeDisconnect)
	#define OD_ImeBeforeEditorOrCaretChanged OPERA_API_RENAME(OD_ImeBeforeEditorOrCaretChanged)
	#define OD_ImeGetImuiHeight OPERA_API_RENAME(OD_ImeGetImuiHeight)
	#define OD_DrawImePart OPERA_API_RENAME(OD_DrawImePart)
	#define OD_ImeSetSoftKeyLabel OPERA_API_RENAME(OD_ImeSetSoftKeyLabel)
	#define OD_TranslateKeyCode OPERA_API_RENAME(OD_TranslateKeyCode)
	#define OD_TranslatePenEvent OPERA_API_RENAME(OD_TranslatePenEvent)
	#define KeyPenTracker_init OPERA_API_RENAME(KeyPenTracker_init)
	#define KeyPenTracker_destroy OPERA_API_RENAME(KeyPenTracker_destroy)
	#define KeyPenTracker_resetStatus OPERA_API_RENAME(KeyPenTracker_resetStatus)
	#define KeyPenTracker_handleEvent OPERA_API_RENAME(KeyPenTracker_handleEvent)
	#define OD_ExitUI OPERA_API_RENAME(OD_ExitUI)
	#define OD_InitApp OPERA_API_RENAME(OD_InitApp)
	#define OD_DeinitApp OPERA_API_RENAME(OD_DeinitApp)
	#define OD_MemoryCreatePool OPERA_API_RENAME(OD_MemoryCreatePool)
	#define OD_MemoryDestroyPool OPERA_API_RENAME(OD_MemoryDestroyPool)
	#define OD_MemoryGetPoolSize OPERA_API_RENAME(OD_MemoryGetPoolSize)
	#define OD_MemoryGetPoolBase OPERA_API_RENAME(OD_MemoryGetPoolBase)
	#define OD_MemoryBlocksInit OPERA_API_RENAME(OD_MemoryBlocksInit)
	#define OD_MemoryBlocksDeinit OPERA_API_RENAME(OD_MemoryBlocksDeinit)
	#define OD_Malloc OPERA_API_RENAME(OD_Malloc)
	#define OD_Free OPERA_API_RENAME(OD_Free)
	#define OD_NetGetID OPERA_API_RENAME(OD_NetGetID)
	#define OD_NetGetProxy OPERA_API_RENAME(OD_NetGetProxy)
	#define OD_NetInit OPERA_API_RENAME(OD_NetInit)
	#define OD_NetDeinit OPERA_API_RENAME(OD_NetDeinit)
	#define OD_NetActivateBearer OPERA_API_RENAME(OD_NetActivateBearer)
	#define OD_NetDeactivateBearer OPERA_API_RENAME(OD_NetDeactivateBearer)
	#define OD_NetGetActiveSimSlots OPERA_API_RENAME(OD_NetGetActiveSimSlots)
	#define OD_NetSelectSim OPERA_API_RENAME(OD_NetSelectSim)
	#define OD_NetSelectApn OPERA_API_RENAME(OD_NetSelectApn)
	#define OD_BearerIsWifi OPERA_API_RENAME(OD_BearerIsWifi)
	#define OD_NetCloseWin OPERA_API_RENAME(OD_NetCloseWin)
	#define OD_MobileResInit OPERA_API_RENAME(OD_MobileResInit)
	#define OD_MiniResInit OPERA_API_RENAME(OD_MiniResInit)
	#define OD_GetBreamStringCount OPERA_API_RENAME(OD_GetBreamStringCount)
	#define OD_GetBreamString OPERA_API_RENAME(OD_GetBreamString)
	#define OD_GetOperaString OPERA_API_RENAME(OD_GetOperaString)
	#define OD_GetStaticFiles OPERA_API_RENAME(OD_GetStaticFiles)
	#define OD_GetDeployFiles OPERA_API_RENAME(OD_GetDeployFiles)
	#define OD_SchemeInit OPERA_API_RENAME(OD_SchemeInit)
	#define OD_SchemeDeinit OPERA_API_RENAME(OD_SchemeDeinit)
	#define OD_SchemeHandle OPERA_API_RENAME(OD_SchemeHandle)
	#define OD_HostResolve OPERA_API_RENAME(OD_HostResolve)
	#define OD_SocketCreate OPERA_API_RENAME(OD_SocketCreate)
	#define OD_SocketConnect OPERA_API_RENAME(OD_SocketConnect)
	#define OD_SocketClose OPERA_API_RENAME(OD_SocketClose)
	#define OD_SocketSend OPERA_API_RENAME(OD_SocketSend)
	#define OD_SocketReceive OPERA_API_RENAME(OD_SocketReceive)
	#define od_inet_aton OPERA_API_RENAME(od_inet_aton)
	#define od_inet_ntoa OPERA_API_RENAME(od_inet_ntoa)
	#define OD_SystemInit OPERA_API_RENAME(OD_SystemInit)
	#define OD_SystemDeinit OPERA_API_RENAME(OD_SystemDeinit)
	#define OD_ClipboardSetData OPERA_API_RENAME(OD_ClipboardSetData)
	#define OD_ClipboardGetData OPERA_API_RENAME(OD_ClipboardGetData)
	#define OD_ClipboardHasData OPERA_API_RENAME(OD_ClipboardHasData)
	#define OD_GetTickCount OPERA_API_RENAME(OD_GetTickCount)
	#define OD_GetUTCTime OPERA_API_RENAME(OD_GetUTCTime)
	#define OD_GetLocalTime OPERA_API_RENAME(OD_GetLocalTime)
	#define OD_GetTimeZone OPERA_API_RENAME(OD_GetTimeZone)
	#define OD_GetSystemProperty OPERA_API_RENAME(OD_GetSystemProperty)
	#define OD_GetLangCountryCode OPERA_API_RENAME(OD_GetLangCountryCode)
	#define OD_GetPlatformName OPERA_API_RENAME(OD_GetPlatformName)
	#define OD_GetIMEI OPERA_API_RENAME(OD_GetIMEI)
	#define OD_GetIMSI OPERA_API_RENAME(OD_GetIMSI)
	#define OD_TimerCreate OPERA_API_RENAME(OD_TimerCreate)
	#define OD_TimerDestroy OPERA_API_RENAME(OD_TimerDestroy)
	#define OD_TimerStart OPERA_API_RENAME(OD_TimerStart)
	#define OD_TimerStop OPERA_API_RENAME(OD_TimerStop)
	#define OD_IsTimerStarted OPERA_API_RENAME(OD_IsTimerStarted)
	#define OD_PlatformOpenDocument OPERA_API_RENAME(OD_PlatformOpenDocument)
	#define OD_PlatformCanOpenDocument OPERA_API_RENAME(OD_PlatformCanOpenDocument)
	#define OD_GetNativeString OPERA_API_RENAME(OD_GetNativeString)
	#define OD_AtomicInit OPERA_API_RENAME(OD_AtomicInit)
	#define OD_AtomicDestroy OPERA_API_RENAME(OD_AtomicDestroy)
	#define OD_AtomicIncrement OPERA_API_RENAME(OD_AtomicIncrement)
	#define OD_AtomicDecrement OPERA_API_RENAME(OD_AtomicDecrement)
	#define OD_CreateMutex OPERA_API_RENAME(OD_CreateMutex)
	#define OD_ReleaseMutex OPERA_API_RENAME(OD_ReleaseMutex)
	#define OD_EnterMutex OPERA_API_RENAME(OD_EnterMutex)
	#define OD_LeaveMutex OPERA_API_RENAME(OD_LeaveMutex)
	#define OD_CreateSemaphore OPERA_API_RENAME(OD_CreateSemaphore)
	#define OD_ReleaseSemaphore OPERA_API_RENAME(OD_ReleaseSemaphore)
	#define OD_TakeSemaphore OPERA_API_RENAME(OD_TakeSemaphore)
	#define OD_GiveSemaphore OPERA_API_RENAME(OD_GiveSemaphore)
	#define OD_GetCurrentTaskID OPERA_API_RENAME(OD_GetCurrentTaskID)
	#define OD_GetMMITaskID OPERA_API_RENAME(OD_GetMMITaskID)
	#define OD_GetGogiTaskID OPERA_API_RENAME(OD_GetGogiTaskID)
	#define OD_InitMMITaskContext OPERA_API_RENAME(OD_InitMMITaskContext)
	#define OD_InitGogiTaskContext OPERA_API_RENAME(OD_InitGogiTaskContext)
	#define OD_CreateGogiTask OPERA_API_RENAME(OD_CreateGogiTask)
	#define OD_DestroyGogiTask OPERA_API_RENAME(OD_DestroyGogiTask)
	#define OD_PostCall OPERA_API_RENAME(OD_PostCall)
	#define OD_Yield OPERA_API_RENAME(OD_Yield)
	#define od_stricmp OPERA_API_RENAME(od_stricmp)
	#define od_strnicmp OPERA_API_RENAME(od_strnicmp)
	#define od_wcslen OPERA_API_RENAME(od_wcslen)
	#define od_wcsncpy OPERA_API_RENAME(od_wcsncpy)
	#define od_wcsncat OPERA_API_RENAME(od_wcsncat)
	#define od_wcschr OPERA_API_RENAME(od_wcschr)
	#define od_wcsrchr OPERA_API_RENAME(od_wcsrchr)
	#define od_wcsstr OPERA_API_RENAME(od_wcsstr)
	#define od_wcscmp OPERA_API_RENAME(od_wcscmp)
	#define od_wcsncmp OPERA_API_RENAME(od_wcsncmp)
	#define od_wcsicmp OPERA_API_RENAME(od_wcsicmp)
	#define od_wcsendwith OPERA_API_RENAME(od_wcsendwith)

#endif // OD_API_RENAME_PREFIX

#ifdef __cplusplus
}
#endif

#endif // OPERAFUNCRENAME_H
