#ifndef __TSC_DB_CMN_H__
#define __TSC_DB_CMN_H__

#include "tsc_db_types.h"

#define _TSC_ID_NUM_PER_MOD (1<<22)

/* Module start-id list */
enum {
    _TSC_GLOBAL_STARTID = _TSC_GLOBAL_DEFAULT_STARTID,
    _TSC_GLOBAL_ENDID = _TSC_GLOBAL_STARTID + 4 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_SDI_STARTID,
    _TSC_MOD_SDI_ENDID = _TSC_MOD_SDI_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_SIM_STARTID,
    _TSC_MOD_SIM_ENDID = _TSC_MOD_SIM_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_TL1_STARTID,
    _TSC_MOD_TL1_ENDID = _TSC_MOD_TL1_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_TL2_STARTID,
    _TSC_MOD_TL2_ENDID = _TSC_MOD_TL2_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_RRCC_STARTID,
    _TSC_MOD_RRCC_ENDID = _TSC_MOD_RRCC_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_RRCD_STARTID,
    _TSC_MOD_RRCD_ENDID = _TSC_MOD_RRCD_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_RRCA_STARTID,
    _TSC_MOD_RRCA_ENDID = _TSC_MOD_RRCA_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_CC_STARTID,
    _TSC_MOD_CC_ENDID = _TSC_MOD_CC_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_MM_STARTID,
    _TSC_MOD_MM_ENDID = _TSC_MOD_MM_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_NAS_SWTH_STARTID,
    _TSC_MOD_NAS_SWTH_ENDID = _TSC_MOD_NAS_SWTH_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_PLM_STARTID,
    _TSC_MOD_PLM_ENDID = _TSC_MOD_PLM_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_RABM_STARTID,
    _TSC_MOD_RABM_ENDID = _TSC_MOD_RABM_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_SM_STARTID,
    _TSC_MOD_SM_ENDID = _TSC_MOD_SM_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_SMS_STARTID,
    _TSC_MOD_SMS_ENDID = _TSC_MOD_SMS_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_SS_STARTID,
    _TSC_MOD_SS_ENDID = _TSC_MOD_SS_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_MN_AL_STARTID,
    _TSC_MOD_MN_AL_ENDID = _TSC_MOD_MN_AL_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_MNC_STARTID,
    _TSC_MOD_MNC_ENDID = _TSC_MOD_MNC_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_MNM_STARTID,
    _TSC_MOD_MNM_ENDID = _TSC_MOD_MNM_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_ATC_STARTID,
    _TSC_MOD_ATC_ENDID = _TSC_MOD_ATC_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_GAS_STARTID,
    _TSC_MOD_GAS_ENDID = _TSC_MOD_GAS_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_GL1_STARTID,
    _TSC_MOD_GL1_ENDID = _TSC_MOD_GL1_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1,

    _TSC_MOD_BT_STARTID,
    _TSC_MOD_BT_ENDID = _TSC_MOD_BT_STARTID + 1 * _TSC_ID_NUM_PER_MOD - 1
};

#endif /* __TSC_DB_CMN_H__ */
