//#line 1 "MS_MMI/source/mmi_app/app/game/game_snake/h/game_snake_mdu_def.h"
#ifdef GAME_SNAKE_SUPPORT


RES_ADD_IMG(IMAGE_GAME_SNAKE_HEAD,"\\MMI_RES_##\\IMAG\\IMAGE_GAME_SNAKE_HEAD.png",IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_GAME_SNAKE_BODY,"\\MMI_RES_##\\IMAG\\IMAGE_GAME_SNAKE_BODY.png",IMG_CMP_PNG_ARGB,0)
RES_ADD_IMG(IMAGE_GAME_SNAKE_FLOG,"\\MMI_RES_##\\IMAG\\IMAGE_GAME_SNAKE_FLOG.png",IMG_CMP_PNG_ARGB,0)
//define image infomation
//#if !defined(LOW_MEMORY_SUPPORT_16X16) && !defined(LOW_MEMORY_SUPPORT_32X16) && !defined(LOW_MEMORY_SUPPORT_32X32)
#if !defined(MAINLCD_SIZE_128X160) && !defined(MAINLCD_SIZE_176X220)
RES_ADD_IMG(IMAGE_GAME_SNAKE_BG,"\\MMI_RES_##\\IMAG\\IMAGE_GAME_SNAKE_BG.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

//define string infomation
RES_ADD_STRING(TXT_SNAKE,"Snake")
RES_ADD_STRING(TXT_SNAKE_NEW_GAME,"New game")
RES_ADD_STRING(TXT_SNAKE_GAME_INFO,"Help")
RES_ADD_STRING(TXT_SNAKE_SCORE,"Score")
RES_ADD_STRING(TXT_SNAKE_LEVEL,"Level")
RES_ADD_STRING(TXT_SNAKE_LEVEL_EASY,"Easy")
RES_ADD_STRING(TXT_SNAKE_LEVEL_NORMAL,"Normal")
RES_ADD_STRING(TXT_SNAKE_LEVEL_HARD,"Hard")
RES_ADD_STRING(TXT_SNAKE_HELP,"Up key:Up; Down key:Down; Left key:Left; Right key:Right; OK key:Pause/Start.")
RES_ADD_STRING(TXT_SNAKE_GAMEOVER,"Game over! Restart?")
RES_ADD_STRING(TXT_SNAKE_GAMEPAUSED,"Paused!Continue?")
RES_ADD_STRING(TXT_SNAKE_RESET,"Reset")
RES_ADD_STRING(TXT_SNAKE_HIGHSCORE,"High Score")
RES_ADD_STRING(TXT_SNAKE_PAUSE,"Pause")
#endif

