#ifndef __SMART_DUAL_SIM_ID__
#define __SMART_DUAL_SIM_ID__

/**--------------------------------------------------------------------------*
 **                         Include Files                                    *
 **--------------------------------------------------------------------------*/
#include "sci_types.h"
#include "os_api.h"
#include "mmk_type.h"
#include "mmi_module.h"
#include "mmiwclk_export.h"
/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef __cplusplus
    extern   "C"
    {
#endif

#define WIN_ID_DEF(win_id)          win_id
//windowns id
typedef enum
{
	MMI_DATACOUNTER_START_WIN_ID = (MMI_MODULE_DATA_COUNTER << 16),
	MMIACC_DATA_COUNTER_WIN_ID,
	MMIACC_DATA_COUNTER_WIN_RESULT_ID,
	MMIACC_DATA_COUNTER_WIN_PUPMENU_ID,
	MMIACC_DATA_COUNTER_WIN_PEROID_ID,
	MMIACC_DATA_COUNTER_WIN_DATA_ID,
	MMIACC_DATA_COUNTER_WIN_CALL_ID,
	MMIACC_DATA_COUNTER_WIN_SMS_ID,
	MMIACC_DATA_COUNTER_WIN_MMS_ID,
	MMIACC_DATA_COUNTER_WIN_DATA_MENU_ID,
	MMIACC_DATA_COUNTER_WIN_CALL_MENU_ID,
	MMIACC_DATA_COUNTER_WIN_SMS_MENU_ID,
	MMIACC_DATA_COUNTER_WIN_MMS_MENU_ID,
	MMIACC_DATA_COUNTER_WIN_SET_DATA_MENU_ID,
	MMIACC_DATA_COUNTER_WIN_SET_CALL_MENU_ID,
	MMIACC_DATA_COUNTER_WIN_SET_SMS_MENU_ID,
	MMIACC_DATA_COUNTER_WIN_SET_MMS_MENU_ID,
	MMIACC_DATA_COUNTER_WIN_DATA_LIMIT_ID,
	MMIACC_DATA_COUNTER_WIN_CALL_LIMIT_ID,
	MMIACC_DATA_COUNTER_WIN_SMS_LIMIT_ID,
	MMIACC_DATA_COUNTER_WIN_MMS_LIMIT_ID,
	MMIACC_DATA_COUNTER_WIN_CLEAR_ALL_ID,
	MMIACC_DATA_COUNTER_WIN_CLEAR_DATA_ID,
	MMIACC_DATA_COUNTER_WIN_CLEAR_CALL_ID,
	MMIACC_DATA_COUNTER_WIN_CLEAR_SMS_ID,
	MMIACC_DATA_COUNTER_WIN_CLEAR_MMS_ID,
	MMIACC_DATA_COUNTER_WIN_OPEN_ID,
	MMI_DATACOUNTER_MAX_WID_ID
}MMI_DATACOUNTER_WIN_ID_E;

#undef WIN_ID_DEF

//control id
typedef enum
{
	MMI_DATACOUNTER_START_CTRL_ID = MMI_DATACOUNTER_MAX_WID_ID,
	MMI_DATACOUNTER_SIM_SETTINGS_CTRL_ID,
       MMI_DATACOUNTER_SIM_RESULT_CTRL_ID,
       MMI_DATACOUNTER_CLEAR_ALL_COUNTER_MENU_CTRL_ID,
       MMI_DATACOUNTER_CLEAR_DATA_COUNTER_MENU_CTRL_ID,
       MMI_DATACOUNTER_CLEAR_CALL_COUNTER_MENU_CTRL_ID,
       MMI_DATACOUNTER_CLEAR_SMS_COUNTER_MENU_CTRL_ID,
       MMI_DATACOUNTER_CLEAR_MMS_COUNTER_MENU_CTRL_ID,
       MMI_DATACOUNTER_PEROID_FORM_CTRL_ID,
       MMI_DATACOUNTER_PEROID_SET_CTRL_ID,
       MMI_DATACOUNTER_PEROID_DATE_CTRL_ID,
       MMI_DATACOUNTER_SIM_DATA_ALERT_CTRL_ID,
       MMI_DATACOUNTER_SIM_CALL_ALERT_CTRL_ID,
       MMI_DATACOUNTER_SIM_SMS_ALERT_CTRL_ID,
       MMI_DATACOUNTER_SIM_MMS_ALERT_CTRL_ID,
       MMI_DATACOUNTER_DATA_SET_CTRL_ID,
       MMI_DATACOUNTER_CALL_SET_CTRL_ID,
       MMI_DATACOUNTER_SMS_SET_CTRL_ID,
       MMI_DATACOUNTER_MMS_SET_CTRL_ID,
	MMI_DATACOUNTER_MAX_CTRL_ID
}MMI_DATACOUNTER_CTRL_ID_E;

//data label
typedef enum
{
	MMI_DATACOUNTER_DATA_LABEL_START = MMI_DATACOUNTER_MAX_CTRL_ID,
	MMI_DATACOUNTER_DATA_LABEL_ALL,
	MMI_DATACOUNTER_DATA_LABEL_ALL_TEXT,
	MMI_DATACOUNTER_DATA_LABEL_SENT,
	MMI_DATACOUNTER_DATA_LABEL_SENT_TEXT,
	MMI_DATACOUNTER_DATA_LABEL_RECEIVED,
	MMI_DATACOUNTER_DATA_LABEL_RECEIVED_TEXT,
	MMI_DATACOUNTER_DATA_ALERT_LABEL_TEXT,
	MMI_DATACOUNTER_DATA_ALERT_LABEL_EDIT,
	MMI_DATACOUNTER_DATA_ALERT_LABEL_MB_GB,
	MMI_DATACOUNTER_DATA_FORM_CTRL_ID,
	MMI_DATACOUNTER_DATA_SUB_FORM_CTRL_ID,
	MMI_DATACOUNTER_DATA_LABEL_MAX_CTRL_ID
}MMI_DATACOUNTER_DATA_LABEL_E;

//call label
typedef enum
{
	MMI_DATACOUNTER_CALL_LABEL_START = MMI_DATACOUNTER_DATA_LABEL_MAX_CTRL_ID,
	MMI_DATACOUNTER_CALL_LABEL_ALL,
	MMI_DATACOUNTER_CALL_LABEL_ALL_TEXT,
	MMI_DATACOUNTER_CALL_LABEL_OUTGOING,
	MMI_DATACOUNTER_CALL_LABEL_OUTGOING_TEXT,
	MMI_DATACOUNTER_CALL_LABEL_INCOMING,
	MMI_DATACOUNTER_CALL_LABEL_INCOMING_TEXT,
	MMI_DATACOUNTER_CALL_ALERT_LABEL_TEXT,
	MMI_DATACOUNTER_CALL_ALERT_LABEL_EDIT,
	MMI_DATACOUNTER_CALL_ALERT_LABEL_HM,
	MMI_DATACOUNTER_CALL_FORM_CTRL_ID,
	MMI_DATACOUNTER_CALL_SUB_FORM_CTRL_ID,
	MMI_DATACOUNTER_CALL_LABEL_MAX_CTRL_ID
}MMI_DATACOUNTER_CALL_LABEL_E;

//sms label
typedef enum
{
	MMI_DATACOUNTER_SMS_LABEL_START = MMI_DATACOUNTER_CALL_LABEL_MAX_CTRL_ID,
	MMI_DATACOUNTER_SMS_LABEL_ALL,
	MMI_DATACOUNTER_SMS_LABEL_ALL_TEXT,
	MMI_DATACOUNTER_SMS_LABEL_SENT,
	MMI_DATACOUNTER_SMS_LABEL_SENT_TEXT,
	MMI_DATACOUNTER_SMS_LABEL_RECEIVED,
	MMI_DATACOUNTER_SMS_LABEL_RECEIVED_TEXT,
	MMI_DATACOUNTER_SMS_ALERT_LABEL_TEXT,
	MMI_DATACOUNTER_SMS_ALERT_LABEL_EDIT,
	MMI_DATACOUNTER_SMS_FORM_CTRL_ID,
	MMI_DATACOUNTER_SMS_LABEL_MAX_CTRL_ID
}MMI_DATACOUNTER_SMS_LABEL_E;

//mms label
typedef enum
{
	MMI_DATACOUNTER_MMS_LABEL_START = MMI_DATACOUNTER_SMS_LABEL_MAX_CTRL_ID,
	MMI_DATACOUNTER_MMS_LABEL_ALL,
	MMI_DATACOUNTER_MMS_LABEL_ALL_TEXT,
	MMI_DATACOUNTER_MMS_LABEL_SENT,
	MMI_DATACOUNTER_MMS_LABEL_SENT_TEXT,
	MMI_DATACOUNTER_MMS_LABEL_RECEIVED,
	MMI_DATACOUNTER_MMS_LABEL_RECEIVED_TEXT,
	MMI_DATACOUNTER_MMS_ALERT_LABEL_TEXT,
	MMI_DATACOUNTER_MMS_ALERT_LABEL_EDIT,
	MMI_DATACOUNTER_MMS_FORM_CTRL_ID,
	MMI_DATACOUNTER_MMS_LABEL_MAX_CTRL_ID
}MMI_DATACOUNTER_MMS_LABEL_E;

typedef enum
{
	MMI_DATACOUNTER_PEROID_LABEL_START = MMI_DATACOUNTER_MMS_LABEL_MAX_CTRL_ID,
	MMI_DATACOUNTER_PEROID_LABEL,
	MMI_DATACOUNTER_PEROID_DATE,
	MMI_DATACOUNTER_PEROID_LABEL_MAX_CTRL_ID
}MMI_DATACOUNTER_PEROID_LABEL_E;

/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef   __cplusplus
    }
#endif
#endif //__SMART_DUAL_SIM_ID__
