#if 1
//[[define string information
//RES_ADD_STRING(STR_ILIST_SIM_ONE, "SIM1")
//RES_ADD_STRING(STR_ILIST_SIM_TWO, "SIM2")

RES_ADD_STRING(STR_COUN_LIST_PERIOD_EXT01, "Counter period")
RES_ADD_STRING(STR_COUN_PERIOD_SINCE_EXT01, "Since ")
RES_ADD_STRING(STR_SIM_MANAGER_DATA, "Data")
RES_ADD_STRING(STR_SIM_MANAGER_CALL, "Calls")
RES_ADD_STRING(STR_SIM_MANAGER_SMS, "SMS")
RES_ADD_STRING(STR_SIM_MANAGER_MMS, "MMS")

RES_ADD_STRING(STR_COUN_MONTHLY_RESET_EXT01, "Monthly reset")
RES_ADD_STRING(STR_COUN_RESET_DATE_EXT01, "Choose a montly reset date for your counters:")
RES_ADD_STRING(STR_COUN_LIST_ALERT_EXT02, "Alert")
RES_ADD_STRING(STR_COUN_ALERT_OFF_EXT01, "Off")
RES_ADD_STRING(STR_DATA_ALERT_SETTINGS_ALL, "All")
RES_ADD_STRING(STR_COUN_LIST_CL_DIAL_EXT02, "Outgoing")
RES_ADD_STRING(STR_COUN_LIST_CL_RECEI_EXT02, "Incoming")
RES_ADD_STRING(STR_DATA_ALERT_SETTINGS_SENT, "Sent")
RES_ADD_STRING(STR_DATA_ALERT_SETTINGS_RECV, "Received")
RES_ADD_STRING(STR_COUN_LIST_LIMIT_EXT02, "Limit")

RES_ADD_STRING(STR_COUN_CLEAR_ALL_EXT01, "Clear all counters")
RES_ADD_STRING(STR_COUN_LIST_CLEAR_EXT02, "Clear counter")
RES_ADD_STRING(STR_COUN_QUERY_ALL_EXT01, "Do you want to clear all counters?")

RES_ADD_STRING(STR_COUN_CLEAR_SMS_EXT01, "Do you want to clear the counter for SMS?")
RES_ADD_STRING(STR_COUN_CLEAR_MMS_EXT01, "Do you want to clear the counter for MMS?")
RES_ADD_STRING(STR_COUN_CLEAR_DATA_EXT01, "Do you want to clear the counter for data?")
RES_ADD_STRING(STR_COUN_CLEAR_CALL_EXT01, "Do you want to clear the counter for call?")


RES_ADD_IMG(IMAGE_FOCUSED_RED_2,"\\MMI_RES_##\\IMAG\\IMAGE_CALENDAR_FOCUSED_RED-2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_FOCUSED_TODAY_RED,"\\MMI_RES_##\\IMAG\\IMAGE_CALENDAR_FOCUSED_TODAY_RED.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_ALERT_DATACOUNTER_TIPS,"\\MMI_RES_##\\IMAG\\IMAGE_DIALOG_ALERT_NOTIFICATION.png",IMG_CMP_PNG_SABM_RLE|SABM_TILE,0)
RES_ADD_STRING(STR_COUN_LIMIT_REACHED_EXT01, "You have reached the limit:")
RES_ADD_STRING(STR_COUN_LIMIT_ALL_CALLS_EXT01, "All calls")
RES_ADD_STRING(STR_COUN_LIMIT_DIALLED_CALLS_EXT01, "Dialled calls")
RES_ADD_STRING(STR_COUN_LIMIT_RECEIV_CALLS_EXT01, "Received calls")
RES_ADD_STRING(STR_COUN_LIMIT_ALL_DATA_EXT01, "All data")
RES_ADD_STRING(STR_COUN_LIMIT_SENT_DATA_EXT01, "Sent data")
RES_ADD_STRING(STR_COUN_LIMIT_RECEIV_DATA_EXT01, "Received data")
RES_ADD_STRING(STR_COUN_LIMIT_ALL_SMS_EXT01, "All SMS")
RES_ADD_STRING(STR_COUN_LIMIT_SENT_SMS_EXT01, "Sent SMS")
RES_ADD_STRING(STR_COUN_LIMIT_RECEIV_SMS_EXT01, "Received SMS")
RES_ADD_STRING(STR_COUN_LIMIT_ALL_MMS_EXT01, "All MMS")
RES_ADD_STRING(STR_COUN_LIMIT_SENT_MMS_EXT01, "Sent MMS")
RES_ADD_STRING(STR_COUN_LIMIT_RECEIV_MMS_EXT01, "Received MMS")
RES_ADD_STRING(STR_COUN_UNIT_H_EXT02, "h")
RES_ADD_STRING(STR_START_DEALY_MIN, "min")
RES_ADD_STRING(STR_ALERT_VALUE_INPUT_FORMAT, "MB")
RES_ADD_STRING(STR_COUN_UNIT_GB_EXT02, "GB")

RES_ADD_STRING(STR_GAL_LIST_MB, "%U MB")
RES_ADD_STRING(STR_GAL_LIST_GB, "%U GB")
RES_ADD_STRING(STR_TIME_H_EXT01, "%U h")
RES_ADD_STRING(STR_TIME_MIN_EXT01, "%U min")
RES_ADD_STRING(STR_TIME_H_MIN_EXT01, "%0U h %1U min")

RES_ADD_STRING(STR_HDR_SET_ALERT	, "Set alert")

RES_ADD_STRING(STR_LIST_SIM_EXT01, "SIM")
//]]define string information
#endif