#! perl -w
$^I = ".bak";
while (<>){
	s/^SPRD_CUSTOMER.*=.*FALSE/SPRD_CUSTOMER = TRUE/g;
	s/^JAVA_SUPPORT.*=.*IA/JAVA_SUPPORT = NONE/g;
	s/^JAVA_SUPPORT.*=.*SUN/JAVA_SUPPORT = NONE/g;
	s/^BLUETOOTH_SUPPORT.*=.*CSR_BC4_6/BLUETOOTH_SUPPORT = NONE/g;
	s/^BLUETOOTH_SUPPORT.*=.*CSR_BC4/BLUETOOTH_SUPPORT = NONE/g;
	s/^BLUETOOTH_SUPPORT.*=.*CSR_BC6/BLUETOOTH_SUPPORT = NONE/g;
	
	s/^QQ_SUPPORT.*=.*2009/QQ_SUPPORT = NONE/g;
	s/^IM_SIMP_CHINESE_SUPPORT.*=.*TRUE/IM_SIMP_CHINESE_SUPPORT = FALSE/g;
	s/^IM_TRAD_CHINESE_SUPPORT.*=.*TRUE/IM_TRAD_CHINESE_SUPPORT = FALSE/g;
	
	s/^FLASH_SUPPORT.*=.*TRUE/FLASH_SUPPORT = FALSE/g;
	s/^IM_ENGINE.*=.*SOGOU/IM_ENGINE = CSTAR/g;
	s/^IM_HANDWRITING.*=.*SOGOU/IM_HANDWRITING = HANWANG/g;
	
	
	s/^WEATHER_SUPPORT.*=.*TRUE/WEATHER_SUPPORT = FALSE/g;
	s/^MCARE_MINI_SUPPORT.*=.*TRUE/MCARE_MINI_SUPPORT = FALSE/g;
	
	s/^MCARE_USE_HTTP_SUPPORT.*=.*TRUE/MCARE_USE_HTTP_SUPPORT = FALSE/g;	
	s/^MMIEMAIL_SUPPORT.*=.*TRUE/MMIEMAIL_SUPPORT = FALSE/g;
	
	s/^RMVB_DEC_SUPPORT.*=.*TRUE/RMVB_DEC_SUPPORT = FALSE/g;
	s/^RA8LBR_SUPPORT.*=.*TRUE/RA8LBR_SUPPORT = FALSE/g;
	s/^WMA_A2DP_SUPPORT.*=.*TRUE/WMA_A2DP_SUPPORT = FALSE/g;
	s/^WMA_SUPPORT.*=.*TRUE/WMA_SUPPORT = FALSE/g;
	s/^WMA_BACKGROUND_SUPPORT.*=.*TRUE/WMA_BACKGROUND_SUPPORT = FALSE/g;
	s/^WMA_SEEK_SUPPORT.*=.*TRUE/WMA_SEEK_SUPPORT = FALSE/g;
	s/^WMA_DEC_SUPPORT.*=.*TRUE/WMA_DEC_SUPPORT = FALSE/g;
   
	print;
}
