/****************************************************************************
** File Name:      mmigame_position.h                            
** Author:                                                                  
** Date:            2009/03/04
** Copyright:      2007 Spreadtrum, Incorporated. All Rights Reserved.       
** Description:    This file is used to be included by  the file mmialarm.c
****************************************************************************
**                         Important Edit History                          *
** ------------------------------------------------------------------------*
** DATE               NAME             DESCRIPTION                             
** 03/04/2009        zhaohui          Create
**  
****************************************************************************/
#ifndef _MMIGAME_POSITION_H     
#define _MMIGAME_POSITION_H
#ifdef GAME_SUPPORT
/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef __cplusplus
    extern   "C"
    {
#endif
/**--------------------------------------------------------------------------*
**                         MACRO DEFINITION                                 *
**--------------------------------------------------------------------------*/
#if defined MAINLCD_SIZE_128X160
	//game
	#define LINKS_TEXT_FONT 	15
	//#define LINKS_TILE_WIDTH        20//MODIFY  BY MARY 2010/12/08
	//#define LINKS_TILE_HEIGHT       20
	#define LINKS_TILE_WIDTH        19
	#define LINKS_TILE_HEIGHT       19

	//#define LINKS_TILES_RECT_LEFT_S   16  //×ÓÍ¼Æ¬¿ò×ó
	//#define LINKS_TILES_RECT_TOP_S    30  //×ÓÍ¼Æ¬¿òÉÏ
	#define LINKS_TILES_RECT_LEFT_S   12  //×ÓÍ¼Æ¬¿ò×ó
	#define LINKS_TILES_RECT_TOP_S    23  //×ÓÍ¼Æ¬¿òÉÏ
	
	#define LINKS_PAUSE_IMAGE_LEFT   7   //ÔÝÍ£Í¼Æ¬×óÎ»ÖÃ
	#define LINKS_PAUSE_IMAGE_TOP    (MMI_TITLE_HEIGHT+2)  //ÔÝÍ£Í¼Æ¬¿òÉÏÎ»ÖÃ

/*	#define LINKS_WASHCARD_STRING_RECT_LEFT 		4
	#define LINKS_WASHCARD_STRING_RECT_TOP		7
	#define LINKS_WASHCARD_STRING_RECT_RIGHT  	(LINKS_WASHCARD_STRING_RECT_LEFT + 48)
	#define LINKS_WASHCARD_STRING_RECT_BOTTOM  	27*/
	#define LINKS_WASHCARD_STRING_RECT_LEFT 		12
	#define LINKS_WASHCARD_STRING_RECT_TOP		2
	#define LINKS_WASHCARD_STRING_RECT_RIGHT  	(LINKS_WASHCARD_STRING_RECT_LEFT + 18)
	#define LINKS_WASHCARD_STRING_RECT_BOTTOM  	(LINKS_WASHCARD_STRING_RECT_TOP+18)
	
	//#define LINKS_WASHCARD_NUMBER_RECT_LEFT   	(LINKS_WASHCARD_STRING_RECT_RIGHT + 1)
	#define LINKS_WASHCARD_NUMBER_RECT_LEFT   	(LINKS_WASHCARD_STRING_RECT_RIGHT + 8)
	#define LINKS_WASHCARD_NUMBER_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_WASHCARD_NUMBER_RECT_RIGHT   	(LINKS_WASHCARD_NUMBER_RECT_LEFT + 20)
	#define LINKS_WASHCARD_NUMBER_RECT_BOTTOM   LINKS_WASHCARD_STRING_RECT_BOTTOM
	
	//#define LINKS_TIP_STRING_RECT_LEFT 	(LINKS_WASHCARD_NUMBER_RECT_RIGHT + 1)
	#define LINKS_TIP_STRING_RECT_LEFT 	62
	#define LINKS_TIP_STRING_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_TIP_STRING_RECT_RIGHT	(LINKS_TIP_STRING_RECT_LEFT + 18)
	#define LINKS_TIP_STRING_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM)
	
	//#define LINKS_TIP_NUMBER_RECT_LEFT 	(LINKS_TIP_STRING_RECT_RIGHT + 2)
	#define LINKS_TIP_NUMBER_RECT_LEFT 	(LINKS_TIP_STRING_RECT_RIGHT + 8)
	#define LINKS_TIP_NUMBER_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_TIP_NUMBER_RECT_RIGHT	(LINKS_TIP_NUMBER_RECT_LEFT + 20)
	#define LINKS_TIP_NUMBER_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM)
	
	//#define LINKS_PAUSE_STRING_RECT_LEFT 		(LINKS_TIP_NUMBER_RECT_RIGHT + 1)
	#define LINKS_PAUSE_STRING_RECT_LEFT 	 128
	#define LINKS_PAUSE_STRING_RECT_TOP	 	LINKS_WASHCARD_STRING_RECT_TOP
	//#define LINKS_PAUSE_STRING_RECT_RIGHT	175
	#define LINKS_PAUSE_STRING_RECT_RIGHT  (LINKS_PAUSE_STRING_RECT_LEFT+35)
	#define LINKS_PAUSE_STRING_RECT_BOTTOM	LINKS_WASHCARD_STRING_RECT_BOTTOM	
	
	//#define LINKS_EPISODE_TITLE_RECT_LEFT 		2
	#define LINKS_EPISODE_TITLE_RECT_LEFT				12
	//#define LINKS_EPISODE_TITLE_RECT_BOTTOM	(219 - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT)
	//#define LINKS_EPISODE_TITLE_RECT_TOP	 	(LINKS_EPISODE_TITLE_RECT_BOTTOM - LINKS_TEXT_FONT)
	#define LINKS_EPISODE_TITLE_RECT_TOP     177
	#define LINKS_EPISODE_TITLE_RECT_BOTTOM  (LINKS_EPISODE_TITLE_RECT_TOP+18)
	//#define LINKS_EPISODE_TITLE_RECT_RIGHT	(LINKS_EPISODE_TITLE_RECT_LEFT + 32)
	#define LINKS_EPISODE_TITLE_RECT_RIGHT	(LINKS_EPISODE_TITLE_RECT_LEFT + 18)
	
	
	//#define LINKS_EPISODE_STRING_RECT_LEFT 		(LINKS_EPISODE_TITLE_RECT_RIGHT  + 1)
	#define LINKS_EPISODE_STRING_RECT_LEFT 		(LINKS_EPISODE_TITLE_RECT_RIGHT  + 8)
	#define LINKS_EPISODE_STRING_RECT_TOP	 		LINKS_EPISODE_TITLE_RECT_TOP
	#define LINKS_EPISODE_STRING_RECT_RIGHT		(LINKS_EPISODE_STRING_RECT_LEFT + 16)
	#define LINKS_EPISODE_STRING_RECT_BOTTOM		LINKS_EPISODE_TITLE_RECT_BOTTOM

	//#define LINKS_SCORE_TITLE_RECT_LEFT 		(LINKS_EPISODE_STRING_RECT_RIGHT +1 )
	#define LINKS_SCORE_TITLE_RECT_LEFT 		62
	#define LINKS_SCORE_TITLE_RECT_TOP		LINKS_EPISODE_TITLE_RECT_TOP 
	//#define LINKS_SCORE_TITLE_RECT_RIGHT		( LINKS_SCORE_TITLE_RECT_LEFT + 32)
	#define LINKS_SCORE_TITLE_RECT_RIGHT		( LINKS_SCORE_TITLE_RECT_LEFT + 18)
	#define LINKS_SCORE_TITLE_RECT_BOTTOM	LINKS_EPISODE_TITLE_RECT_BOTTOM
					
	//#define LINKS_SCORE_STRING_RECT_LEFT 		(LINKS_SCORE_TITLE_RECT_RIGHT + 1  )
	#define LINKS_SCORE_STRING_RECT_LEFT 		(LINKS_SCORE_TITLE_RECT_RIGHT + 8  )
	#define LINKS_SCORE_STRING_RECT_TOP		LINKS_EPISODE_TITLE_RECT_TOP 
	#define LINKS_SCORE_STRING_RECT_RIGHT		(LINKS_SCORE_STRING_RECT_LEFT + 24)
	#define LINKS_SCORE_STRING_RECT_BOTTOM	LINKS_EPISODE_TITLE_RECT_BOTTOM

	//#define LINKS_TIME_TITLE_RECT_LEFT  		(LINKS_SCORE_STRING_RECT_RIGHT +1 )
	#define LINKS_TIME_TITLE_RECT_LEFT  		112
	#define LINKS_TIME_TITLE_RECT_TOP	   		LINKS_EPISODE_TITLE_RECT_TOP
	#define LINKS_TIME_TITLE_RECT_RIGHT 		(LINKS_TIME_TITLE_RECT_LEFT + 18)
	#define LINKS_TIME_TITLE_RECT_BOTTOM  		LINKS_EPISODE_TITLE_RECT_BOTTOM
	
	//#define LINKS_TIME_STRING_RECT_LEFT  			(LINKS_TIME_TITLE_RECT_RIGHT + 2)
	#define LINKS_TIME_STRING_RECT_LEFT  		(LINKS_TIME_TITLE_RECT_RIGHT +8)
	#define LINKS_TIME_STRING_RECT_TOP			LINKS_EPISODE_TITLE_RECT_TOP	  
	//#define LINKS_TIME_STRING_RECT_RIGHT 			175
	#define LINKS_TIME_STRING_RECT_RIGHT     	LINKS_TIME_STRING_RECT_LEFT+26
	#define LINKS_TIME_STRING_RECT_BOTTOM 		LINKS_EPISODE_TITLE_RECT_BOTTOM
			        
	//#define LINKS_TILES_RECT_LEFT_H    8   //×ÓÍ¼Æ¬¿ò×ó
	#define LINKS_TILES_RECT_LEFT_H    6   //×ÓÍ¼Æ¬¿ò×ó
	//#define LINKS_TILES_RECT_TOP_H    8 //×ÓÍ¼Æ¬¿òÉÏ
	#define LINKS_TILES_RECT_TOP_H    13 //×ÓÍ¼Æ¬¿òÉÏ
	
	//#define LINKS_PAUSE_IMAGE_LEFT_H   128   //ÔÝÍ£Í¼Æ¬×óÎ»ÖÃ
	#define LINKS_PAUSE_IMAGE_LEFT_H   171   //ÔÝÍ£Í¼Æ¬×óÎ»ÖÃ
	//#define LINKS_PAUSE_IMAGE_TOP_H     2  //ÔÝÍ£Í¼Æ¬¿òÉÏÎ»ÖÃ
	#define LINKS_PAUSE_IMAGE_TOP_H     121 //ÔÝÍ£Í¼Æ¬¿òÉÏÎ»ÖÃ

	#define LINKS_FULLSCREEN_WIDTH_H  220
  	#define TEXT_RECT_H_LEFT	190
	
    #define LINKS_PAUSE_STRING_RECT_H_LEFT 		LINKS_PAUSE_IMAGE_LEFT_H
	//#define LINKS_PAUSE_STRING_RECT_H_TOP	 	(LINKS_PAUSE_IMAGE_TOP_H+1)	
	#define LINKS_PAUSE_STRING_RECT_H_TOP	 		LINKS_PAUSE_IMAGE_TOP_H
	//#define LINKS_PAUSE_STRING_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_PAUSE_STRING_RECT_H_RIGHT		(LINKS_PAUSE_IMAGE_LEFT_H+35)
	//#define LINKS_PAUSE_STRING_RECT_H_BOTTOM	(LINKS_PAUSE_IMAGE_TOP_H + LINKS_TEXT_FONT)	
	#define LINKS_PAUSE_STRING_RECT_H_BOTTOM	(LINKS_PAUSE_IMAGE_TOP_H + 18)

	/*#define LINKS_WASHCARD_STRING_RECT_H_LEFT 		LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_WASHCARD_STRING_RECT_H_TOP		(LINKS_PAUSE_IMAGE_TOP_H + LINKS_TEXT_FONT+1)
	#define LINKS_WASHCARD_STRING_RECT_H_RIGHT  		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_WASHCARD_STRING_RECT_H_BOTTOM  	(LINKS_PAUSE_IMAGE_TOP_H+ LINKS_TEXT_FONT*2)*/
	#define LINKS_WASHCARD_STRING_RECT_H_LEFT 		168
	#define LINKS_WASHCARD_STRING_RECT_H_TOP		9
	#define LINKS_WASHCARD_STRING_RECT_H_RIGHT  		(LINKS_WASHCARD_STRING_RECT_H_LEFT+18)
	#define LINKS_WASHCARD_STRING_RECT_H_BOTTOM  	(LINKS_WASHCARD_STRING_RECT_H_TOP+18)
		
	/*#define LINKS_WASHCARD_NUMBER_RECT_H_LEFT   		LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_WASHCARD_NUMBER_RECT_H_TOP	 	(LINKS_PAUSE_IMAGE_TOP_H + LINKS_TEXT_FONT*2+1)
	#define LINKS_WASHCARD_NUMBER_RECT_H_RIGHT   	LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_WASHCARD_NUMBER_RECT_H_BOTTOM    (LINKS_PAUSE_IMAGE_TOP_H+ LINKS_TEXT_FONT*3)*/
	#define LINKS_WASHCARD_NUMBER_RECT_H_LEFT   	(LINKS_WASHCARD_STRING_RECT_H_RIGHT+4)
	#define LINKS_WASHCARD_NUMBER_RECT_H_TOP	 		LINKS_WASHCARD_STRING_RECT_H_TOP
	#define LINKS_WASHCARD_NUMBER_RECT_H_RIGHT   	(LINKS_WASHCARD_NUMBER_RECT_H_LEFT+20)
	#define LINKS_WASHCARD_NUMBER_RECT_H_BOTTOM    LINKS_WASHCARD_STRING_RECT_H_BOTTOM

/*	#define LINKS_TIP_STRING_RECT_H_LEFT 		LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_TIP_STRING_RECT_H_TOP	 	(LINKS_PAUSE_IMAGE_TOP_H + LINKS_TEXT_FONT*3+1)
	#define LINKS_TIP_STRING_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_TIP_STRING_RECT_H_BOTTOM	(LINKS_PAUSE_IMAGE_TOP_H+ LINKS_TEXT_FONT*4)*/
	#define LINKS_TIP_STRING_RECT_H_LEFT 	LINKS_WASHCARD_STRING_RECT_H_LEFT
	#define LINKS_TIP_STRING_RECT_H_TOP	 	(LINKS_WASHCARD_STRING_RECT_H_BOTTOM + 4)
	#define LINKS_TIP_STRING_RECT_H_RIGHT		(LINKS_TIP_STRING_RECT_H_LEFT+18)
	#define LINKS_TIP_STRING_RECT_H_BOTTOM	(LINKS_TIP_STRING_RECT_H_TOP+18)

  /*#define LINKS_TIP_NUMBER_RECT_H_LEFT   		LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_TIP_NUMBER_RECT_H_TOP	   	(LINKS_PAUSE_IMAGE_TOP_H + LINKS_TEXT_FONT*4+1)
	#define LINKS_TIP_NUMBER_RECT_H_RIGHT  	LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_TIP_NUMBER_RECT_H_BOTTOM  	(LINKS_PAUSE_IMAGE_TOP_H+ LINKS_TEXT_FONT*5)*/
  #define LINKS_TIP_NUMBER_RECT_H_LEFT   	(LINKS_TIP_STRING_RECT_H_RIGHT+4)
	#define LINKS_TIP_NUMBER_RECT_H_TOP	   	LINKS_TIP_STRING_RECT_H_TOP
	#define LINKS_TIP_NUMBER_RECT_H_RIGHT  	(LINKS_TIP_NUMBER_RECT_H_LEFT+20)
	#define LINKS_TIP_NUMBER_RECT_H_BOTTOM  	(LINKS_TIP_NUMBER_RECT_H_TOP+18)
	
	/*#define LINKS_EPISODE_TITLE_RECT_H_LEFT 		LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_EPISODE_TITLE_RECT_H_TOP	 	(LINKS_PAUSE_IMAGE_TOP_H + LINKS_TEXT_FONT*5+1)
	#define LINKS_EPISODE_TITLE_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_EPISODE_TITLE_RECT_H_BOTTOM	(LINKS_PAUSE_IMAGE_TOP_H+ LINKS_TEXT_FONT*6)*/
	#define LINKS_EPISODE_TITLE_RECT_H_LEFT 		LINKS_WASHCARD_STRING_RECT_H_LEFT
	#define LINKS_EPISODE_TITLE_RECT_H_TOP	 	(LINKS_TIP_STRING_RECT_H_BOTTOM + 4)
	#define LINKS_EPISODE_TITLE_RECT_H_RIGHT		(LINKS_EPISODE_TITLE_RECT_H_LEFT+18)
	#define LINKS_EPISODE_TITLE_RECT_H_BOTTOM	(LINKS_EPISODE_TITLE_RECT_H_TOP+18)
	
	/*#define LINKS_EPISODE_STRING_RECT_H_LEFT 			LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_EPISODE_STRING_RECT_H_TOP	 		(LINKS_PAUSE_IMAGE_TOP_H + LINKS_TEXT_FONT*6+1)
	#define LINKS_EPISODE_STRING_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_EPISODE_STRING_RECT_H_BOTTOM		(LINKS_PAUSE_IMAGE_TOP_H+ LINKS_TEXT_FONT*7)*/
	#define LINKS_EPISODE_STRING_RECT_H_LEFT 			(LINKS_EPISODE_TITLE_RECT_H_RIGHT + 4)
	#define LINKS_EPISODE_STRING_RECT_H_TOP	 		LINKS_EPISODE_TITLE_RECT_H_TOP
	#define LINKS_EPISODE_STRING_RECT_H_RIGHT		(LINKS_EPISODE_STRING_RECT_H_LEFT + 24)
	#define LINKS_EPISODE_STRING_RECT_H_BOTTOM	LINKS_EPISODE_TITLE_RECT_H_BOTTOM
	
	/*#define LINKS_SCORE_TITLE_RECT_H_LEFT 		LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_SCORE_TITLE_RECT_H_TOP		(LINKS_PAUSE_IMAGE_TOP_H + LINKS_TEXT_FONT*7+1)
	#define LINKS_SCORE_TITLE_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_SCORE_TITLE_RECT_H_BOTTOM	(LINKS_PAUSE_IMAGE_TOP_H+ LINKS_TEXT_FONT*8)*/
	#define LINKS_SCORE_TITLE_RECT_H_LEFT 		LINKS_WASHCARD_STRING_RECT_H_LEFT
	#define LINKS_SCORE_TITLE_RECT_H_TOP		(LINKS_EPISODE_TITLE_RECT_H_BOTTOM+4)
	#define LINKS_SCORE_TITLE_RECT_H_RIGHT	(LINKS_SCORE_TITLE_RECT_H_LEFT + 18)
	#define LINKS_SCORE_TITLE_RECT_H_BOTTOM	(LINKS_SCORE_TITLE_RECT_H_TOP + 18)
										
	/*#define LINKS_SCORE_STRING_RECT_H_LEFT 		LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_SCORE_STRING_RECT_H_TOP		(LINKS_PAUSE_IMAGE_TOP_H + LINKS_TEXT_FONT*8+1)
	#define LINKS_SCORE_STRING_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_SCORE_STRING_RECT_H_BOTTOM	(LINKS_PAUSE_IMAGE_TOP_H+ LINKS_TEXT_FONT*9)*/
	#define LINKS_SCORE_STRING_RECT_H_LEFT 	(LINKS_SCORE_TITLE_RECT_H_RIGHT+4)
	#define LINKS_SCORE_STRING_RECT_H_TOP		LINKS_SCORE_TITLE_RECT_H_TOP
	#define LINKS_SCORE_STRING_RECT_H_RIGHT		(LINKS_SCORE_STRING_RECT_H_LEFT+24)
	#define LINKS_SCORE_STRING_RECT_H_BOTTOM	(LINKS_SCORE_STRING_RECT_H_TOP+18)
	
	/*#define LINKS_TIME_TITLE_RECT_H_LEFT  			LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_TIME_TITLE_RECT_H_TOP	   		(LINKS_PAUSE_IMAGE_TOP_H + LINKS_TEXT_FONT*9+1)
	#define LINKS_TIME_TITLE_RECT_H_RIGHT 		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_TIME_TITLE_RECT_H_BOTTOM  		(LINKS_PAUSE_IMAGE_TOP_H+ LINKS_TEXT_FONT*10)*/
	#define LINKS_TIME_TITLE_RECT_H_LEFT  			LINKS_WASHCARD_STRING_RECT_H_LEFT
	#define LINKS_TIME_TITLE_RECT_H_TOP	   		(LINKS_SCORE_TITLE_RECT_H_BOTTOM+4)
	#define LINKS_TIME_TITLE_RECT_H_RIGHT 		(LINKS_TIME_TITLE_RECT_H_LEFT+18)
	#define LINKS_TIME_TITLE_RECT_H_BOTTOM  		(LINKS_TIME_TITLE_RECT_H_TOP+18)
										
	/*#define LINKS_TIME_STRING_RECT_H_LEFT  		LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_TIME_STRING_RECT_H_TOP			(LINKS_PAUSE_IMAGE_TOP_H + LINKS_TEXT_FONT*10+1)  
	#define LINKS_TIME_STRING_RECT_H_RIGHT 		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_TIME_STRING_RECT_H_BOTTOM 		(LINKS_PAUSE_IMAGE_TOP_H+ LINKS_TEXT_FONT*11)*/
	#define LINKS_TIME_STRING_RECT_H_LEFT  		(LINKS_TIME_TITLE_RECT_H_RIGHT+4)
	#define LINKS_TIME_STRING_RECT_H_TOP			LINKS_TIME_TITLE_RECT_H_TOP  
	#define LINKS_TIME_STRING_RECT_H_RIGHT 		(LINKS_TIME_STRING_RECT_H_LEFT+24)
	#define LINKS_TIME_STRING_RECT_H_BOTTOM 		LINKS_TIME_TITLE_RECT_H_BOTTOM

	/*#define LINKS_RETURN_BUTTON_RECT_H_LEFT  		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_RETURN_BUTTON_RECT_H_TOP		(LINKS_TIME_STRING_RECT_H_BOTTOM + LINKS_TEXT_FONT*11+1)  
	#define LINKS_RETURN_BUTTON_RECT_H_RIGHT 		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_RETURN_BUTTON_RECT_H_BOTTOM 	(LINKS_RETURN_BUTTON_RECT_H_TOP + LINKS_TEXT_FONT*12)*/
	#define LINKS_RETURN_BUTTON_RECT_H_LEFT  		167
	#define LINKS_RETURN_BUTTON_RECT_H_TOP		145 
	#define LINKS_RETURN_BUTTON_RECT_H_RIGHT 		(LINKS_RETURN_BUTTON_RECT_H_LEFT+43)
	#define LINKS_RETURN_BUTTON_RECT_H_BOTTOM 	(LINKS_RETURN_BUTTON_RECT_H_TOP+22)
  
	//game boxman

	#define	BOXMAN_MAP_LEFT_UP_X 	1
	#define 	BOXMAN_MAP_LEFT_UP_Y 	1 
	#define	BOXMAN_MAP_LEFT_UP_H_X 	1
	#define 	BOXMAN_MAP_LEFT_UP_H_Y 	1 
	#define BOXMAN_SUB_MAP_BORDER_HIGHT	    14  //×ÓÍ¼±ß³¤,µ¥Î»pixel
	#define BOXMAN_SUB_MAP_BORDER_WIDTH     14  //×ÓÍ¼±ß¿í¶È
    #define BOXMAN_LABEL_WIDTH		20  //10
	
#elif defined MAINLCD_SIZE_176X220 
	#define LINKS_TEXT_FONT 	15
	#define LINKS_TILE_WIDTH        19
	#define LINKS_TILE_HEIGHT       19
	#define LINKS_TILES_RECT_LEFT_S   12  //×ÓÍ¼Æ¬¿ò×ó
	#define LINKS_TILES_RECT_TOP_S    23  //×ÓÍ¼Æ¬¿òÉÏ
	#define LINKS_PAUSE_IMAGE_LEFT   7   //ÔÝÍ£Í¼Æ¬×óÎ»ÖÃ
	#define LINKS_PAUSE_IMAGE_TOP    (MMI_TITLE_HEIGHT+2)  //ÔÝÍ£Í¼Æ¬¿òÉÏÎ»ÖÃ
	#define LINKS_WASHCARD_STRING_RECT_LEFT 		12
	#define LINKS_WASHCARD_STRING_RECT_TOP		2
	#define LINKS_WASHCARD_STRING_RECT_RIGHT  	(LINKS_WASHCARD_STRING_RECT_LEFT + 18)
	#define LINKS_WASHCARD_STRING_RECT_BOTTOM  	(LINKS_WASHCARD_STRING_RECT_TOP+18)
	#define LINKS_WASHCARD_NUMBER_RECT_LEFT   	(LINKS_WASHCARD_STRING_RECT_RIGHT + 8)
	#define LINKS_WASHCARD_NUMBER_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_WASHCARD_NUMBER_RECT_RIGHT   	(LINKS_WASHCARD_NUMBER_RECT_LEFT + 20)
	#define LINKS_WASHCARD_NUMBER_RECT_BOTTOM   LINKS_WASHCARD_STRING_RECT_BOTTOM
	#define LINKS_TIP_STRING_RECT_LEFT 	62
	#define LINKS_TIP_STRING_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_TIP_STRING_RECT_RIGHT	(LINKS_TIP_STRING_RECT_LEFT + 18)
	#define LINKS_TIP_STRING_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM)
	#define LINKS_TIP_NUMBER_RECT_LEFT 	(LINKS_TIP_STRING_RECT_RIGHT + 8)
	#define LINKS_TIP_NUMBER_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_TIP_NUMBER_RECT_RIGHT	(LINKS_TIP_NUMBER_RECT_LEFT + 20)
	#define LINKS_TIP_NUMBER_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM)
	#define LINKS_PAUSE_STRING_RECT_LEFT 	 128
	#define LINKS_PAUSE_STRING_RECT_TOP	 	LINKS_WASHCARD_STRING_RECT_TOP
	#define LINKS_PAUSE_STRING_RECT_RIGHT  (LINKS_PAUSE_STRING_RECT_LEFT+35)
	#define LINKS_PAUSE_STRING_RECT_BOTTOM	LINKS_WASHCARD_STRING_RECT_BOTTOM	
	#define LINKS_EPISODE_TITLE_RECT_LEFT				12
	#define LINKS_EPISODE_TITLE_RECT_TOP     177
	#define LINKS_EPISODE_TITLE_RECT_BOTTOM  (LINKS_EPISODE_TITLE_RECT_TOP+18)
	#define LINKS_EPISODE_TITLE_RECT_RIGHT	(LINKS_EPISODE_TITLE_RECT_LEFT + 18)
	#define LINKS_EPISODE_STRING_RECT_LEFT 		(LINKS_EPISODE_TITLE_RECT_RIGHT  + 8)
	#define LINKS_EPISODE_STRING_RECT_TOP	 		LINKS_EPISODE_TITLE_RECT_TOP
	#define LINKS_EPISODE_STRING_RECT_RIGHT		(LINKS_EPISODE_STRING_RECT_LEFT + 16)
	#define LINKS_EPISODE_STRING_RECT_BOTTOM		LINKS_EPISODE_TITLE_RECT_BOTTOM
	#define LINKS_SCORE_TITLE_RECT_LEFT 		62
	#define LINKS_SCORE_TITLE_RECT_TOP		LINKS_EPISODE_TITLE_RECT_TOP 
	#define LINKS_SCORE_TITLE_RECT_RIGHT		( LINKS_SCORE_TITLE_RECT_LEFT + 18)
	#define LINKS_SCORE_TITLE_RECT_BOTTOM	LINKS_EPISODE_TITLE_RECT_BOTTOM
	#define LINKS_SCORE_STRING_RECT_LEFT 		(LINKS_SCORE_TITLE_RECT_RIGHT + 8  )
	#define LINKS_SCORE_STRING_RECT_TOP		LINKS_EPISODE_TITLE_RECT_TOP 
	#define LINKS_SCORE_STRING_RECT_RIGHT		(LINKS_SCORE_STRING_RECT_LEFT + 24)
	#define LINKS_SCORE_STRING_RECT_BOTTOM	LINKS_EPISODE_TITLE_RECT_BOTTOM
	#define LINKS_TIME_TITLE_RECT_LEFT  		112
	#define LINKS_TIME_TITLE_RECT_TOP	   		LINKS_EPISODE_TITLE_RECT_TOP
	#define LINKS_TIME_TITLE_RECT_RIGHT 		(LINKS_TIME_TITLE_RECT_LEFT + 18)
	#define LINKS_TIME_TITLE_RECT_BOTTOM  		LINKS_EPISODE_TITLE_RECT_BOTTOM
	#define LINKS_TIME_STRING_RECT_LEFT  		(LINKS_TIME_TITLE_RECT_RIGHT +8)
	#define LINKS_TIME_STRING_RECT_TOP			LINKS_EPISODE_TITLE_RECT_TOP	  
	#define LINKS_TIME_STRING_RECT_RIGHT     	LINKS_TIME_STRING_RECT_LEFT+26
	#define LINKS_TIME_STRING_RECT_BOTTOM 		LINKS_EPISODE_TITLE_RECT_BOTTOM
	#define LINKS_TILES_RECT_LEFT_H    6   //×ÓÍ¼Æ¬¿ò×ó
	#define LINKS_TILES_RECT_TOP_H    13 //×ÓÍ¼Æ¬¿òÉÏ
	#define LINKS_PAUSE_IMAGE_LEFT_H   171   //ÔÝÍ£Í¼Æ¬×óÎ»ÖÃ
	#define LINKS_PAUSE_IMAGE_TOP_H     121 //ÔÝÍ£Í¼Æ¬¿òÉÏÎ»ÖÃ
	#define LINKS_FULLSCREEN_WIDTH_H  220
  	#define TEXT_RECT_H_LEFT	190
    #define LINKS_PAUSE_STRING_RECT_H_LEFT 		LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_PAUSE_STRING_RECT_H_TOP	 		LINKS_PAUSE_IMAGE_TOP_H
	#define LINKS_PAUSE_STRING_RECT_H_RIGHT		(LINKS_PAUSE_IMAGE_LEFT_H+35)
	#define LINKS_PAUSE_STRING_RECT_H_BOTTOM	(LINKS_PAUSE_IMAGE_TOP_H + 18)
	#define LINKS_WASHCARD_STRING_RECT_H_LEFT 		168
	#define LINKS_WASHCARD_STRING_RECT_H_TOP		9
	#define LINKS_WASHCARD_STRING_RECT_H_RIGHT  		(LINKS_WASHCARD_STRING_RECT_H_LEFT+18)
	#define LINKS_WASHCARD_STRING_RECT_H_BOTTOM  	(LINKS_WASHCARD_STRING_RECT_H_TOP+18)
	#define LINKS_WASHCARD_NUMBER_RECT_H_LEFT   	(LINKS_WASHCARD_STRING_RECT_H_RIGHT+4)
	#define LINKS_WASHCARD_NUMBER_RECT_H_TOP	 		LINKS_WASHCARD_STRING_RECT_H_TOP
	#define LINKS_WASHCARD_NUMBER_RECT_H_RIGHT   	(LINKS_WASHCARD_NUMBER_RECT_H_LEFT+20)
	#define LINKS_WASHCARD_NUMBER_RECT_H_BOTTOM    LINKS_WASHCARD_STRING_RECT_H_BOTTOM
	#define LINKS_TIP_STRING_RECT_H_LEFT 	LINKS_WASHCARD_STRING_RECT_H_LEFT
	#define LINKS_TIP_STRING_RECT_H_TOP	 	(LINKS_WASHCARD_STRING_RECT_H_BOTTOM + 4)
	#define LINKS_TIP_STRING_RECT_H_RIGHT		(LINKS_TIP_STRING_RECT_H_LEFT+18)
	#define LINKS_TIP_STRING_RECT_H_BOTTOM	(LINKS_TIP_STRING_RECT_H_TOP+18)
  #define LINKS_TIP_NUMBER_RECT_H_LEFT   	(LINKS_TIP_STRING_RECT_H_RIGHT+4)
	#define LINKS_TIP_NUMBER_RECT_H_TOP	   	LINKS_TIP_STRING_RECT_H_TOP
	#define LINKS_TIP_NUMBER_RECT_H_RIGHT  	(LINKS_TIP_NUMBER_RECT_H_LEFT+20)
	#define LINKS_TIP_NUMBER_RECT_H_BOTTOM  	(LINKS_TIP_NUMBER_RECT_H_TOP+18)
	#define LINKS_EPISODE_TITLE_RECT_H_LEFT 		LINKS_WASHCARD_STRING_RECT_H_LEFT
	#define LINKS_EPISODE_TITLE_RECT_H_TOP	 	(LINKS_TIP_STRING_RECT_H_BOTTOM + 4)
	#define LINKS_EPISODE_TITLE_RECT_H_RIGHT		(LINKS_EPISODE_TITLE_RECT_H_LEFT+18)
	#define LINKS_EPISODE_TITLE_RECT_H_BOTTOM	(LINKS_EPISODE_TITLE_RECT_H_TOP+18)
	#define LINKS_EPISODE_STRING_RECT_H_LEFT 			(LINKS_EPISODE_TITLE_RECT_H_RIGHT + 4)
	#define LINKS_EPISODE_STRING_RECT_H_TOP	 		LINKS_EPISODE_TITLE_RECT_H_TOP
	#define LINKS_EPISODE_STRING_RECT_H_RIGHT		(LINKS_EPISODE_STRING_RECT_H_LEFT + 24)
	#define LINKS_EPISODE_STRING_RECT_H_BOTTOM	LINKS_EPISODE_TITLE_RECT_H_BOTTOM
	#define LINKS_SCORE_TITLE_RECT_H_LEFT 		LINKS_WASHCARD_STRING_RECT_H_LEFT
	#define LINKS_SCORE_TITLE_RECT_H_TOP		(LINKS_EPISODE_TITLE_RECT_H_BOTTOM+4)
	#define LINKS_SCORE_TITLE_RECT_H_RIGHT	(LINKS_SCORE_TITLE_RECT_H_LEFT + 18)
	#define LINKS_SCORE_TITLE_RECT_H_BOTTOM	(LINKS_SCORE_TITLE_RECT_H_TOP + 18)
		#define LINKS_SCORE_STRING_RECT_H_LEFT 	(LINKS_SCORE_TITLE_RECT_H_RIGHT+4)
	#define LINKS_SCORE_STRING_RECT_H_TOP		LINKS_SCORE_TITLE_RECT_H_TOP
	#define LINKS_SCORE_STRING_RECT_H_RIGHT		(LINKS_SCORE_STRING_RECT_H_LEFT+24)
	#define LINKS_SCORE_STRING_RECT_H_BOTTOM	(LINKS_SCORE_STRING_RECT_H_TOP+18)
	#define LINKS_TIME_TITLE_RECT_H_LEFT  			LINKS_WASHCARD_STRING_RECT_H_LEFT
	#define LINKS_TIME_TITLE_RECT_H_TOP	   		(LINKS_SCORE_TITLE_RECT_H_BOTTOM+4)
	#define LINKS_TIME_TITLE_RECT_H_RIGHT 		(LINKS_TIME_TITLE_RECT_H_LEFT+18)
	#define LINKS_TIME_TITLE_RECT_H_BOTTOM  		(LINKS_TIME_TITLE_RECT_H_TOP+18)
		#define LINKS_TIME_STRING_RECT_H_LEFT  		(LINKS_TIME_TITLE_RECT_H_RIGHT+4)
	#define LINKS_TIME_STRING_RECT_H_TOP			LINKS_TIME_TITLE_RECT_H_TOP  
	#define LINKS_TIME_STRING_RECT_H_RIGHT 		(LINKS_TIME_STRING_RECT_H_LEFT+24)
	#define LINKS_TIME_STRING_RECT_H_BOTTOM 		LINKS_TIME_TITLE_RECT_H_BOTTOM
	#define LINKS_RETURN_BUTTON_RECT_H_LEFT  		167
	#define LINKS_RETURN_BUTTON_RECT_H_TOP		145 
	#define LINKS_RETURN_BUTTON_RECT_H_RIGHT 		(LINKS_RETURN_BUTTON_RECT_H_LEFT+43)
	#define LINKS_RETURN_BUTTON_RECT_H_BOTTOM 	(LINKS_RETURN_BUTTON_RECT_H_TOP+22)
	#define	BOXMAN_MAP_LEFT_UP_X 	7//2
	#define 	BOXMAN_MAP_LEFT_UP_Y 	2 
	#define	BOXMAN_MAP_LEFT_UP_H_X 	5//2
	#define 	BOXMAN_MAP_LEFT_UP_H_Y 	6 

	
	#define BOXMAN_SUB_MAP_BORDER_HIGHT	    18  //×ÓÍ¼±ß³¤,µ¥Î»pixel
	#define BOXMAN_SUB_MAP_BORDER_WIDTH     18  //×ÓÍ¼±ß¿í¶È
    #define BOXMAN_LABEL_WIDTH		50
	
#elif defined MAINLCD_SIZE_240X320
	//game link
      #define LINK_PIXEL_BETWEEN_ICON_TEXT     5
      
	#define LINKS_TEXT_FONT 	20
	#define LINKS_TILE_WIDTH        29
	#define LINKS_TILE_HEIGHT      29
	        
	#define LINKS_TILES_RECT_LEFT_S   4   //×ÓÍ¼Æ¬¿ò×ó
	#define LINKS_TILES_RECT_TOP_S    34  //×ÓÍ¼Æ¬¿òÉÏ       

	#define LINKS_WASHCARD_STRING_RECT_LEFT 		20
	#define LINKS_WASHCARD_STRING_RECT_TOP		6
	#define LINKS_WASHCARD_STRING_RECT_RIGHT  	39
	#define LINKS_WASHCARD_STRING_RECT_BOTTOM  	25
	
     #define LINKS_WASHCARD_NUMBER_RECT_LEFT   	(LINKS_WASHCARD_STRING_RECT_RIGHT + LINK_PIXEL_BETWEEN_ICON_TEXT)
	#define LINKS_WASHCARD_NUMBER_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_WASHCARD_NUMBER_RECT_RIGHT   	(LINKS_WASHCARD_NUMBER_RECT_LEFT + 30)
	#define LINKS_WASHCARD_NUMBER_RECT_BOTTOM   (LINKS_WASHCARD_STRING_RECT_BOTTOM)
	
	#define LINKS_TIP_STRING_RECT_LEFT 	     98 
	#define LINKS_TIP_STRING_RECT_TOP	 	 6
	#define LINKS_TIP_STRING_RECT_RIGHT	(LINKS_TIP_STRING_RECT_LEFT + 20)
	#define LINKS_TIP_STRING_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM)
	
	#define LINKS_TIP_NUMBER_RECT_LEFT 	(LINKS_TIP_STRING_RECT_RIGHT)
	#define LINKS_TIP_NUMBER_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_TIP_NUMBER_RECT_RIGHT	(LINKS_TIP_NUMBER_RECT_LEFT + 30)
	#define LINKS_TIP_NUMBER_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM)
	
	#define LINKS_PAUSE_STRING_RECT_LEFT 		(LINKS_PAUSE_STRING_RECT_RIGHT -48)
	#define LINKS_PAUSE_STRING_RECT_TOP	 	     4
	#define LINKS_PAUSE_STRING_RECT_RIGHT	(MMI_MAINSCREEN_WIDTH - 5)
	#define LINKS_PAUSE_STRING_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM+3)
	
	#define LINKS_EPISODE_TITLE_RECT_LEFT 		20
	#define LINKS_EPISODE_TITLE_RECT_TOP	 	268
	#define LINKS_EPISODE_TITLE_RECT_RIGHT	(LINKS_EPISODE_TITLE_RECT_LEFT+20-1)
	#define LINKS_EPISODE_TITLE_RECT_BOTTOM	(LINKS_EPISODE_TITLE_RECT_TOP+20-1)
	
	#define LINKS_EPISODE_STRING_RECT_LEFT 		(LINKS_EPISODE_TITLE_RECT_RIGHT  + 5)
	#define LINKS_EPISODE_STRING_RECT_TOP	 		LINKS_EPISODE_TITLE_RECT_TOP
	#define LINKS_EPISODE_STRING_RECT_RIGHT		(LINKS_EPISODE_STRING_RECT_LEFT + 30)
	#define LINKS_EPISODE_STRING_RECT_BOTTOM		LINKS_EPISODE_TITLE_RECT_BOTTOM

	#define LINKS_SCORE_TITLE_RECT_LEFT 		LINKS_TIP_STRING_RECT_LEFT
	#define LINKS_SCORE_TITLE_RECT_TOP		LINKS_EPISODE_TITLE_RECT_TOP 
	#define LINKS_SCORE_TITLE_RECT_RIGHT		( LINKS_SCORE_TITLE_RECT_LEFT + 20-1)
	#define LINKS_SCORE_TITLE_RECT_BOTTOM	(LINKS_SCORE_TITLE_RECT_TOP+20-1)
					
	#define LINKS_SCORE_STRING_RECT_LEFT 		(LINKS_SCORE_TITLE_RECT_RIGHT +5 )
	#define LINKS_SCORE_STRING_RECT_TOP		LINKS_EPISODE_TITLE_RECT_TOP 
	#define LINKS_SCORE_STRING_RECT_RIGHT		(LINKS_SCORE_STRING_RECT_LEFT + 50)
	#define LINKS_SCORE_STRING_RECT_BOTTOM	LINKS_EPISODE_TITLE_RECT_BOTTOM

	#define LINKS_TIME_TITLE_RECT_LEFT  		178
	#define LINKS_TIME_TITLE_RECT_TOP	   		LINKS_EPISODE_TITLE_RECT_TOP
	#define LINKS_TIME_TITLE_RECT_RIGHT 	    (LINKS_TIME_TITLE_RECT_LEFT + 20-1)
	#define LINKS_TIME_TITLE_RECT_BOTTOM  		LINKS_EPISODE_TITLE_RECT_BOTTOM
	
	#define LINKS_TIME_STRING_RECT_LEFT  		(LINKS_TIME_TITLE_RECT_RIGHT+2)
	#define LINKS_TIME_STRING_RECT_TOP			LINKS_EPISODE_TITLE_RECT_TOP	  
	#define LINKS_TIME_STRING_RECT_RIGHT 		(MMI_MAINSCREEN_WIDTH - 5)
	#define LINKS_TIME_STRING_RECT_BOTTOM 		LINKS_EPISODE_TITLE_RECT_BOTTOM
	
		        
	#define LINKS_TILES_RECT_LEFT_H    4   
	#define LINKS_TILES_RECT_TOP_H    4

	#define TEXT_RECT_H_LEFT	250
	#define LINKS_FULLSCREEN_WIDTH_H  320 	
   	
    #define LINKS_PAUSE_STRING_RECT_H_LEFT 		245
	#define LINKS_PAUSE_STRING_RECT_H_TOP	 	4	
	#define LINKS_PAUSE_STRING_RECT_H_RIGHT		(LINKS_PAUSE_STRING_RECT_H_LEFT +48)
	#define LINKS_PAUSE_STRING_RECT_H_BOTTOM	(LINKS_PAUSE_STRING_RECT_H_TOP + 30)	

	#define LINKS_WASHCARD_STRING_RECT_H_LEFT 		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_WASHCARD_STRING_RECT_H_TOP		(LINKS_PAUSE_STRING_RECT_H_BOTTOM + 10)
	#define LINKS_WASHCARD_STRING_RECT_H_RIGHT  		(LINKS_WASHCARD_STRING_RECT_H_LEFT +19)
	#define LINKS_WASHCARD_STRING_RECT_H_BOTTOM  	(LINKS_WASHCARD_STRING_RECT_H_TOP  + 19)
		
	#define LINKS_WASHCARD_NUMBER_RECT_H_LEFT   		(LINKS_WASHCARD_STRING_RECT_H_RIGHT + 9)
	#define LINKS_WASHCARD_NUMBER_RECT_H_TOP	 	LINKS_WASHCARD_STRING_RECT_H_TOP
	#define LINKS_WASHCARD_NUMBER_RECT_H_RIGHT   	(LINKS_FULLSCREEN_WIDTH_H -20)
	#define LINKS_WASHCARD_NUMBER_RECT_H_BOTTOM    LINKS_WASHCARD_STRING_RECT_H_BOTTOM

	#define LINKS_TIP_STRING_RECT_H_LEFT 		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_TIP_STRING_RECT_H_TOP	 	(LINKS_WASHCARD_NUMBER_RECT_H_BOTTOM + 10)
	#define LINKS_TIP_STRING_RECT_H_RIGHT		(LINKS_TIP_STRING_RECT_H_LEFT + 19)
	#define LINKS_TIP_STRING_RECT_H_BOTTOM	(LINKS_TIP_STRING_RECT_H_TOP+ 19)

  	#define LINKS_TIP_NUMBER_RECT_H_LEFT   	(LINKS_TIP_STRING_RECT_H_RIGHT + 1) 
	#define LINKS_TIP_NUMBER_RECT_H_TOP	   	(LINKS_TIP_STRING_RECT_H_TOP )
	#define LINKS_TIP_NUMBER_RECT_H_RIGHT  	(LINKS_FULLSCREEN_WIDTH_H - 20) 
	#define LINKS_TIP_NUMBER_RECT_H_BOTTOM  	(LINKS_TIP_STRING_RECT_H_BOTTOM)
	
	#define LINKS_EPISODE_TITLE_RECT_H_LEFT 		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_EPISODE_TITLE_RECT_H_TOP	 	(LINKS_TIP_NUMBER_RECT_H_BOTTOM + 10)
	#define LINKS_EPISODE_TITLE_RECT_H_RIGHT		(LINKS_PAUSE_STRING_RECT_H_LEFT + 19)
	#define LINKS_EPISODE_TITLE_RECT_H_BOTTOM	(LINKS_EPISODE_TITLE_RECT_H_TOP + 19)
	
	#define LINKS_EPISODE_STRING_RECT_H_LEFT 		(LINKS_EPISODE_TITLE_RECT_H_RIGHT + 10) 
	#define LINKS_EPISODE_STRING_RECT_H_TOP	 		(LINKS_EPISODE_TITLE_RECT_H_TOP)
	#define LINKS_EPISODE_STRING_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_EPISODE_STRING_RECT_H_BOTTOM		(LINKS_EPISODE_TITLE_RECT_H_BOTTOM)
	
	#define LINKS_SCORE_TITLE_RECT_H_LEFT 		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_SCORE_TITLE_RECT_H_TOP		(LINKS_EPISODE_STRING_RECT_H_BOTTOM + 10)
	#define LINKS_SCORE_TITLE_RECT_H_RIGHT		(LINKS_SCORE_TITLE_RECT_H_LEFT + 19)
	#define LINKS_SCORE_TITLE_RECT_H_BOTTOM	    (LINKS_SCORE_TITLE_RECT_H_TOP+ 19)
										
	#define LINKS_SCORE_STRING_RECT_H_LEFT 		(LINKS_SCORE_TITLE_RECT_H_RIGHT + 5)
	#define LINKS_SCORE_STRING_RECT_H_TOP		LINKS_SCORE_TITLE_RECT_H_TOP
	#define LINKS_SCORE_STRING_RECT_H_RIGHT		 LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_SCORE_STRING_RECT_H_BOTTOM	(LINKS_SCORE_STRING_RECT_H_TOP+ LINKS_TEXT_FONT)
	
	#define LINKS_TIME_TITLE_RECT_H_LEFT  		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_TIME_TITLE_RECT_H_TOP	   		(LINKS_SCORE_STRING_RECT_H_BOTTOM + 10)
	#define LINKS_TIME_TITLE_RECT_H_RIGHT 		(LINKS_TIME_TITLE_RECT_H_LEFT + 19)
	#define LINKS_TIME_TITLE_RECT_H_BOTTOM  	(LINKS_TIME_TITLE_RECT_H_TOP + 19)
										
	#define LINKS_TIME_STRING_RECT_H_LEFT  		(LINKS_TIME_TITLE_RECT_H_RIGHT +10)
	#define LINKS_TIME_STRING_RECT_H_TOP		LINKS_TIME_TITLE_RECT_H_TOP  
	#define LINKS_TIME_STRING_RECT_H_RIGHT 		(LINKS_FULLSCREEN_WIDTH_H -10)
	#define LINKS_TIME_STRING_RECT_H_BOTTOM 	(LINKS_TIME_STRING_RECT_H_TOP + LINKS_TEXT_FONT)

	#define LINKS_RETURN_BUTTON_RECT_H_LEFT  		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_RETURN_BUTTON_RECT_H_TOP		(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT*11+1)  
	#define LINKS_RETURN_BUTTON_RECT_H_RIGHT 		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_RETURN_BUTTON_RECT_H_BOTTOM 	(239)
  

	#define	BOXMAN_MAP_LEFT_UP_X 	2
	#define 	BOXMAN_MAP_LEFT_UP_Y 	2 
	#define	BOXMAN_MAP_LEFT_UP_H_X 	2
	#define 	BOXMAN_MAP_LEFT_UP_H_Y 	2
	
  	#define BOXMAN_SUB_MAP_BORDER_HIGHT	    26  //×ÓÍ¼±ß³¤,µ¥Î»pixel
	#define BOXMAN_SUB_MAP_BORDER_WIDTH     26  //×ÓÍ¼±ß¿í¶È,	
	
    #define BOXMAN_LABEL_WIDTH      80
#elif defined MAINLCD_SIZE_128X64
	//game link
      #define LINK_PIXEL_BETWEEN_ICON_TEXT     5
      
	#define LINKS_TEXT_FONT 	20
	#define LINKS_TILE_WIDTH        29
	#define LINKS_TILE_HEIGHT      29
	        
	#define LINKS_TILES_RECT_LEFT_S   4   //×ÓÍ¼Æ¬¿ò×ó
	#define LINKS_TILES_RECT_TOP_S    34  //×ÓÍ¼Æ¬¿òÉÏ       

	#define LINKS_WASHCARD_STRING_RECT_LEFT 		20
	#define LINKS_WASHCARD_STRING_RECT_TOP		6
	#define LINKS_WASHCARD_STRING_RECT_RIGHT  	39
	#define LINKS_WASHCARD_STRING_RECT_BOTTOM  	25
	
     #define LINKS_WASHCARD_NUMBER_RECT_LEFT   	(LINKS_WASHCARD_STRING_RECT_RIGHT + LINK_PIXEL_BETWEEN_ICON_TEXT)
	#define LINKS_WASHCARD_NUMBER_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_WASHCARD_NUMBER_RECT_RIGHT   	(LINKS_WASHCARD_NUMBER_RECT_LEFT + 30)
	#define LINKS_WASHCARD_NUMBER_RECT_BOTTOM   (LINKS_WASHCARD_STRING_RECT_BOTTOM)
	
	#define LINKS_TIP_STRING_RECT_LEFT 	     98 
	#define LINKS_TIP_STRING_RECT_TOP	 	 6
	#define LINKS_TIP_STRING_RECT_RIGHT	(LINKS_TIP_STRING_RECT_LEFT + 20)
	#define LINKS_TIP_STRING_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM)
	
	#define LINKS_TIP_NUMBER_RECT_LEFT 	(LINKS_TIP_STRING_RECT_RIGHT)
	#define LINKS_TIP_NUMBER_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_TIP_NUMBER_RECT_RIGHT	(LINKS_TIP_NUMBER_RECT_LEFT + 30)
	#define LINKS_TIP_NUMBER_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM)
	
	#define LINKS_PAUSE_STRING_RECT_LEFT 		(LINKS_PAUSE_STRING_RECT_RIGHT -48)
	#define LINKS_PAUSE_STRING_RECT_TOP	 	     4
	#define LINKS_PAUSE_STRING_RECT_RIGHT	(MMI_MAINSCREEN_WIDTH - 5)
	#define LINKS_PAUSE_STRING_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM+3)
	
	#define LINKS_EPISODE_TITLE_RECT_LEFT 		20
	#define LINKS_EPISODE_TITLE_RECT_TOP	 	268
	#define LINKS_EPISODE_TITLE_RECT_RIGHT	(LINKS_EPISODE_TITLE_RECT_LEFT+20-1)
	#define LINKS_EPISODE_TITLE_RECT_BOTTOM	(LINKS_EPISODE_TITLE_RECT_TOP+20-1)
	
	#define LINKS_EPISODE_STRING_RECT_LEFT 		(LINKS_EPISODE_TITLE_RECT_RIGHT  + 5)
	#define LINKS_EPISODE_STRING_RECT_TOP	 		LINKS_EPISODE_TITLE_RECT_TOP
	#define LINKS_EPISODE_STRING_RECT_RIGHT		(LINKS_EPISODE_STRING_RECT_LEFT + 30)
	#define LINKS_EPISODE_STRING_RECT_BOTTOM		LINKS_EPISODE_TITLE_RECT_BOTTOM

	#define LINKS_SCORE_TITLE_RECT_LEFT 		LINKS_TIP_STRING_RECT_LEFT
	#define LINKS_SCORE_TITLE_RECT_TOP		LINKS_EPISODE_TITLE_RECT_TOP 
	#define LINKS_SCORE_TITLE_RECT_RIGHT		( LINKS_SCORE_TITLE_RECT_LEFT + 20-1)
	#define LINKS_SCORE_TITLE_RECT_BOTTOM	(LINKS_SCORE_TITLE_RECT_TOP+20-1)
					
	#define LINKS_SCORE_STRING_RECT_LEFT 		(LINKS_SCORE_TITLE_RECT_RIGHT +5 )
	#define LINKS_SCORE_STRING_RECT_TOP		LINKS_EPISODE_TITLE_RECT_TOP 
	#define LINKS_SCORE_STRING_RECT_RIGHT		(LINKS_SCORE_STRING_RECT_LEFT + 40)
	#define LINKS_SCORE_STRING_RECT_BOTTOM	LINKS_EPISODE_TITLE_RECT_BOTTOM

	#define LINKS_TIME_TITLE_RECT_LEFT  		178
	#define LINKS_TIME_TITLE_RECT_TOP	   		LINKS_EPISODE_TITLE_RECT_TOP
	#define LINKS_TIME_TITLE_RECT_RIGHT 	    (LINKS_TIME_TITLE_RECT_LEFT + 20-1)
	#define LINKS_TIME_TITLE_RECT_BOTTOM  		LINKS_EPISODE_TITLE_RECT_BOTTOM
	
	#define LINKS_TIME_STRING_RECT_LEFT  			(LINKS_TIME_TITLE_RECT_RIGHT + 2)
	#define LINKS_TIME_STRING_RECT_TOP			LINKS_EPISODE_TITLE_RECT_TOP	  
	#define LINKS_TIME_STRING_RECT_RIGHT 		(MMI_MAINSCREEN_WIDTH - 5)
	#define LINKS_TIME_STRING_RECT_BOTTOM 		LINKS_EPISODE_TITLE_RECT_BOTTOM
	
		        
	#define LINKS_TILES_RECT_LEFT_H    4   
	#define LINKS_TILES_RECT_TOP_H    4

	#define TEXT_RECT_H_LEFT	250
	#define LINKS_FULLSCREEN_WIDTH_H  320 	
   	
    #define LINKS_PAUSE_STRING_RECT_H_LEFT 		245
	#define LINKS_PAUSE_STRING_RECT_H_TOP	 	4	
	#define LINKS_PAUSE_STRING_RECT_H_RIGHT		(LINKS_PAUSE_STRING_RECT_H_LEFT +48)
	#define LINKS_PAUSE_STRING_RECT_H_BOTTOM	(LINKS_PAUSE_STRING_RECT_H_TOP + 30)	

	#define LINKS_WASHCARD_STRING_RECT_H_LEFT 		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_WASHCARD_STRING_RECT_H_TOP		(LINKS_PAUSE_STRING_RECT_H_BOTTOM + 10)
	#define LINKS_WASHCARD_STRING_RECT_H_RIGHT  		(LINKS_WASHCARD_STRING_RECT_H_LEFT +19)
	#define LINKS_WASHCARD_STRING_RECT_H_BOTTOM  	(LINKS_WASHCARD_STRING_RECT_H_TOP  + 19)
		
	#define LINKS_WASHCARD_NUMBER_RECT_H_LEFT   		(LINKS_WASHCARD_STRING_RECT_H_RIGHT + 9)
	#define LINKS_WASHCARD_NUMBER_RECT_H_TOP	 	LINKS_WASHCARD_STRING_RECT_H_TOP
	#define LINKS_WASHCARD_NUMBER_RECT_H_RIGHT   	(LINKS_FULLSCREEN_WIDTH_H -20)
	#define LINKS_WASHCARD_NUMBER_RECT_H_BOTTOM    LINKS_WASHCARD_STRING_RECT_H_BOTTOM

	#define LINKS_TIP_STRING_RECT_H_LEFT 		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_TIP_STRING_RECT_H_TOP	 	(LINKS_WASHCARD_NUMBER_RECT_H_BOTTOM + 10)
	#define LINKS_TIP_STRING_RECT_H_RIGHT		(LINKS_TIP_STRING_RECT_H_LEFT + 19)
	#define LINKS_TIP_STRING_RECT_H_BOTTOM	(LINKS_TIP_STRING_RECT_H_TOP+ 19)

  	#define LINKS_TIP_NUMBER_RECT_H_LEFT   	(LINKS_TIP_STRING_RECT_H_RIGHT + 1) 
	#define LINKS_TIP_NUMBER_RECT_H_TOP	   	(LINKS_TIP_STRING_RECT_H_TOP )
	#define LINKS_TIP_NUMBER_RECT_H_RIGHT  	(LINKS_FULLSCREEN_WIDTH_H - 20) 
	#define LINKS_TIP_NUMBER_RECT_H_BOTTOM  	(LINKS_TIP_STRING_RECT_H_BOTTOM)
	
	#define LINKS_EPISODE_TITLE_RECT_H_LEFT 		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_EPISODE_TITLE_RECT_H_TOP	 	(LINKS_TIP_NUMBER_RECT_H_BOTTOM + 10)
	#define LINKS_EPISODE_TITLE_RECT_H_RIGHT		(LINKS_PAUSE_STRING_RECT_H_LEFT + 19)
	#define LINKS_EPISODE_TITLE_RECT_H_BOTTOM	(LINKS_EPISODE_TITLE_RECT_H_TOP + 19)
	
	#define LINKS_EPISODE_STRING_RECT_H_LEFT 		(LINKS_EPISODE_TITLE_RECT_H_RIGHT + 10) 
	#define LINKS_EPISODE_STRING_RECT_H_TOP	 		(LINKS_EPISODE_TITLE_RECT_H_TOP)
	#define LINKS_EPISODE_STRING_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_EPISODE_STRING_RECT_H_BOTTOM		(LINKS_EPISODE_TITLE_RECT_H_BOTTOM)
	
	#define LINKS_SCORE_TITLE_RECT_H_LEFT 		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_SCORE_TITLE_RECT_H_TOP		(LINKS_EPISODE_STRING_RECT_H_BOTTOM + 10)
	#define LINKS_SCORE_TITLE_RECT_H_RIGHT		(LINKS_SCORE_TITLE_RECT_H_LEFT + 19)
	#define LINKS_SCORE_TITLE_RECT_H_BOTTOM	    (LINKS_SCORE_TITLE_RECT_H_TOP+ 19)
										
	#define LINKS_SCORE_STRING_RECT_H_LEFT 		(LINKS_SCORE_TITLE_RECT_H_RIGHT + 10)
	#define LINKS_SCORE_STRING_RECT_H_TOP		LINKS_SCORE_TITLE_RECT_H_TOP
	#define LINKS_SCORE_STRING_RECT_H_RIGHT		 LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_SCORE_STRING_RECT_H_BOTTOM	(LINKS_SCORE_STRING_RECT_H_TOP+ LINKS_TEXT_FONT)
	
	#define LINKS_TIME_TITLE_RECT_H_LEFT  		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_TIME_TITLE_RECT_H_TOP	   		(LINKS_SCORE_STRING_RECT_H_BOTTOM + 10)
	#define LINKS_TIME_TITLE_RECT_H_RIGHT 		(LINKS_TIME_TITLE_RECT_H_LEFT + 19)
	#define LINKS_TIME_TITLE_RECT_H_BOTTOM  	(LINKS_TIME_TITLE_RECT_H_TOP + 19)
										
	#define LINKS_TIME_STRING_RECT_H_LEFT  		(LINKS_TIME_TITLE_RECT_H_RIGHT +10)
	#define LINKS_TIME_STRING_RECT_H_TOP		LINKS_TIME_TITLE_RECT_H_TOP  
	#define LINKS_TIME_STRING_RECT_H_RIGHT 		(LINKS_FULLSCREEN_WIDTH_H -10)
	#define LINKS_TIME_STRING_RECT_H_BOTTOM 	(LINKS_TIME_STRING_RECT_H_TOP + LINKS_TEXT_FONT)

	#define LINKS_RETURN_BUTTON_RECT_H_LEFT  		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_RETURN_BUTTON_RECT_H_TOP		(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT*11+1)  
	#define LINKS_RETURN_BUTTON_RECT_H_RIGHT 		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_RETURN_BUTTON_RECT_H_BOTTOM 	(239)
  

	#define	BOXMAN_MAP_LEFT_UP_X 	2
	#define 	BOXMAN_MAP_LEFT_UP_Y 	2 
	#define	BOXMAN_MAP_LEFT_UP_H_X 	2
	#define 	BOXMAN_MAP_LEFT_UP_H_Y 	2	

	
  	#define BOXMAN_SUB_MAP_BORDER_HIGHT	    26  //×ÓÍ¼±ß³¤,µ¥Î»pixel
	#define BOXMAN_SUB_MAP_BORDER_WIDTH     26  //×ÓÍ¼±ß¿í¶È,	
	
    #define BOXMAN_LABEL_WIDTH      80

#elif defined MAINLCD_SIZE_240X400

	#define LINKS_TEXT_FONT 	18   //modify by mary 2010/12/10
	//game link
//	#define LINKS_TILE_WIDTH        28
//	#define LINKS_TILE_HEIGHT       28
	#define LINKS_TILE_WIDTH        29
	#define LINKS_TILE_HEIGHT       29
	        
//	#define LINKS_TILES_RECT_LEFT_S   8   //×ÓÍ¼Æ¬¿ò×ó
//	#define LINKS_TILES_RECT_TOP_S    34  //×ÓÍ¼Æ¬¿òÉÏ
	#define LINKS_TILES_RECT_LEFT_S   4   //×ÓÍ¼Æ¬¿ò×ó
	#define LINKS_TILES_RECT_TOP_S    77  //×ÓÍ¼Æ¬¿òÉÏ

	//#define LINKS_PAUSE_IMAGE_LEFT   8   //ÔÝÍ£Í¼Æ¬×óÎ»ÖÃ
	//#define LINKS_PAUSE_IMAGE_TOP    34  //ÔÝÍ£Í¼Æ¬¿òÉÏÎ»ÖÃ   
	#define LINKS_PAUSE_IMAGE_LEFT   174   //ÔÝÍ£Í¼Æ¬×óÎ»ÖÃ
	#define LINKS_PAUSE_IMAGE_TOP    28  //ÔÝÍ£Í¼Æ¬¿òÉÏÎ»ÖÃ   
        
	//#define LINKS_WASHCARD_STRING_RECT_LEFT 		8
	//#define LINKS_WASHCARD_STRING_RECT_TOP		7
	//#define LINKS_WASHCARD_STRING_RECT_RIGHT  	(LINKS_WASHCARD_STRING_RECT_LEFT + 60)
	//#define LINKS_WASHCARD_STRING_RECT_BOTTOM  	27
	#define LINKS_WASHCARD_STRING_RECT_LEFT 		5
	#define LINKS_WASHCARD_STRING_RECT_TOP		28
	#define LINKS_WASHCARD_STRING_RECT_RIGHT  	(LINKS_WASHCARD_STRING_RECT_LEFT + 20)
	#define LINKS_WASHCARD_STRING_RECT_BOTTOM  	(LINKS_WASHCARD_STRING_RECT_TOP+20)
	
    // #define LINKS_WASHCARD_NUMBER_RECT_LEFT   	(LINKS_WASHCARD_STRING_RECT_RIGHT + 2)
	//#define LINKS_WASHCARD_NUMBER_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	//#define LINKS_WASHCARD_NUMBER_RECT_RIGHT   	(LINKS_WASHCARD_NUMBER_RECT_LEFT + 30)
	//#define LINKS_WASHCARD_NUMBER_RECT_BOTTOM   (LINKS_WASHCARD_STRING_RECT_BOTTOM-2)
     #define LINKS_WASHCARD_NUMBER_RECT_LEFT   	(LINKS_WASHCARD_STRING_RECT_RIGHT + 2)
	#define LINKS_WASHCARD_NUMBER_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_WASHCARD_NUMBER_RECT_RIGHT   	(LINKS_WASHCARD_NUMBER_RECT_LEFT + 30)
	#define LINKS_WASHCARD_NUMBER_RECT_BOTTOM   (LINKS_WASHCARD_STRING_RECT_BOTTOM-2)
	
	//#define LINKS_TIP_STRING_RECT_LEFT 	(LINKS_WASHCARD_NUMBER_RECT_RIGHT + 2)
	//#define LINKS_TIP_STRING_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	//#define LINKS_TIP_STRING_RECT_RIGHT	(LINKS_TIP_STRING_RECT_LEFT + 40)
	//#define LINKS_TIP_STRING_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM)
	#define LINKS_TIP_STRING_RECT_LEFT 	(LINKS_WASHCARD_NUMBER_RECT_RIGHT + 25)
	#define LINKS_TIP_STRING_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_TIP_STRING_RECT_RIGHT	(LINKS_TIP_STRING_RECT_LEFT + 20)
	#define LINKS_TIP_STRING_RECT_BOTTOM	(LINKS_TIP_STRING_RECT_TOP+20)
	
	#define LINKS_TIP_NUMBER_RECT_LEFT 	(LINKS_TIP_STRING_RECT_RIGHT + 2)
	#define LINKS_TIP_NUMBER_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_TIP_NUMBER_RECT_RIGHT	(LINKS_TIP_NUMBER_RECT_LEFT + 30)
	#define LINKS_TIP_NUMBER_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM)
	
	/*#define LINKS_PAUSE_STRING_RECT_LEFT 		(LINKS_TIP_NUMBER_RECT_RIGHT + 2)
	#define LINKS_PAUSE_STRING_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP+1)	
	#define LINKS_PAUSE_STRING_RECT_RIGHT	238
	#define LINKS_PAUSE_STRING_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM-2)*/ 
	#define LINKS_PAUSE_STRING_RECT_LEFT 		174
	#define LINKS_PAUSE_STRING_RECT_TOP	 	28	
	#define LINKS_PAUSE_STRING_RECT_RIGHT	(LINKS_PAUSE_STRING_RECT_LEFT+60)
	#define LINKS_PAUSE_STRING_RECT_BOTTOM	(LINKS_PAUSE_STRING_RECT_TOP+24) 
	
	/*#define LINKS_EPISODE_TITLE_RECT_LEFT 		2
	#define LINKS_EPISODE_TITLE_RECT_BOTTOM	(300)
	#define LINKS_EPISODE_TITLE_RECT_TOP	 	(LINKS_EPISODE_TITLE_RECT_BOTTOM - LINKS_TEXT_FONT)
	#define LINKS_EPISODE_TITLE_RECT_RIGHT	(LINKS_EPISODE_TITLE_RECT_LEFT + 40)*/
	#define LINKS_EPISODE_TITLE_RECT_LEFT 		5
	#define LINKS_EPISODE_TITLE_RECT_TOP	 	334
		#define LINKS_EPISODE_TITLE_RECT_BOTTOM	(LINKS_EPISODE_TITLE_RECT_TOP+20)
	#define LINKS_EPISODE_TITLE_RECT_RIGHT	(LINKS_EPISODE_TITLE_RECT_LEFT + 20)
	
	
	#define LINKS_EPISODE_STRING_RECT_LEFT 		(LINKS_EPISODE_TITLE_RECT_RIGHT  + 2)
	#define LINKS_EPISODE_STRING_RECT_TOP	 		LINKS_EPISODE_TITLE_RECT_TOP
	#define LINKS_EPISODE_STRING_RECT_RIGHT		(LINKS_EPISODE_STRING_RECT_LEFT + 30)
	#define LINKS_EPISODE_STRING_RECT_BOTTOM		LINKS_EPISODE_TITLE_RECT_BOTTOM

	/*#define LINKS_SCORE_TITLE_RECT_LEFT 		(LINKS_EPISODE_STRING_RECT_RIGHT   + 2)
	#define LINKS_SCORE_TITLE_RECT_TOP		LINKS_EPISODE_TITLE_RECT_TOP 
	#define LINKS_SCORE_TITLE_RECT_RIGHT		( LINKS_SCORE_TITLE_RECT_LEFT + 40)
	#define LINKS_SCORE_TITLE_RECT_BOTTOM	LINKS_EPISODE_TITLE_RECT_BOTTOM*/
	#define LINKS_SCORE_TITLE_RECT_LEFT 		(LINKS_EPISODE_STRING_RECT_RIGHT   + 25)
	#define LINKS_SCORE_TITLE_RECT_TOP		LINKS_EPISODE_TITLE_RECT_TOP 
	#define LINKS_SCORE_TITLE_RECT_RIGHT		( LINKS_SCORE_TITLE_RECT_LEFT + 20)
	#define LINKS_SCORE_TITLE_RECT_BOTTOM	(LINKS_SCORE_TITLE_RECT_TOP+20)
					
	#define LINKS_SCORE_STRING_RECT_LEFT 		(LINKS_SCORE_TITLE_RECT_RIGHT +2 )
	#define LINKS_SCORE_STRING_RECT_TOP		LINKS_EPISODE_TITLE_RECT_TOP 
	#define LINKS_SCORE_STRING_RECT_RIGHT		(LINKS_SCORE_STRING_RECT_LEFT + 40)
	#define LINKS_SCORE_STRING_RECT_BOTTOM	LINKS_EPISODE_TITLE_RECT_BOTTOM

	#define LINKS_TIME_TITLE_RECT_LEFT  		174
	#define LINKS_TIME_TITLE_RECT_TOP	   		LINKS_EPISODE_TITLE_RECT_TOP
	#define LINKS_TIME_TITLE_RECT_RIGHT 		(LINKS_TIME_TITLE_RECT_LEFT + 20)
	#define LINKS_TIME_TITLE_RECT_BOTTOM  		LINKS_EPISODE_TITLE_RECT_BOTTOM
	
	#define LINKS_TIME_STRING_RECT_LEFT  			(LINKS_TIME_TITLE_RECT_RIGHT + 2)
	#define LINKS_TIME_STRING_RECT_TOP			LINKS_EPISODE_TITLE_RECT_TOP	  
	#define LINKS_TIME_STRING_RECT_RIGHT 			(LINKS_TIME_TITLE_RECT_RIGHT+40)
	#define LINKS_TIME_STRING_RECT_BOTTOM 		LINKS_EPISODE_TITLE_RECT_BOTTOM

		        
	//#define LINKS_TILES_RECT_LEFT_H    8   //×ÓÍ¼Æ¬¿ò×ó
	//#define LINKS_TILES_RECT_TOP_H    8 //×ÓÍ¼Æ¬¿òÉÏ
	#define LINKS_TILES_RECT_LEFT_H    36   //×ÓÍ¼Æ¬¿ò×ó
	#define LINKS_TILES_RECT_TOP_H    4 //×ÓÍ¼Æ¬¿òÉÏ

	#define LINKS_FULLSCREEN_WIDTH_H  320
  	#define TEXT_RECT_H_LEFT	300
	
    /*#define LINKS_PAUSE_STRING_RECT_H_LEFT 		240
	#define LINKS_PAUSE_STRING_RECT_H_TOP	 	8	
	#define LINKS_PAUSE_STRING_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_PAUSE_STRING_RECT_H_BOTTOM	(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT)*/	
	    #define LINKS_PAUSE_STRING_RECT_H_LEFT 		300
	#define LINKS_PAUSE_STRING_RECT_H_TOP	 	87	
	#define LINKS_PAUSE_STRING_RECT_H_RIGHT		(LINKS_PAUSE_STRING_RECT_H_LEFT+60)
	#define LINKS_PAUSE_STRING_RECT_H_BOTTOM	(LINKS_PAUSE_STRING_RECT_H_TOP+24)	

	/*#define LINKS_WASHCARD_STRING_RECT_H_LEFT 		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_WASHCARD_STRING_RECT_H_TOP		(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT+1)
	#define LINKS_WASHCARD_STRING_RECT_H_RIGHT  		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_WASHCARD_STRING_RECT_H_BOTTOM  	(LINKS_PAUSE_STRING_RECT_H_TOP+ LINKS_TEXT_FONT*2)*/
	#define LINKS_WASHCARD_STRING_RECT_H_LEFT 		300
	#define LINKS_WASHCARD_STRING_RECT_H_TOP			11
	#define LINKS_WASHCARD_STRING_RECT_H_RIGHT  		(LINKS_WASHCARD_STRING_RECT_H_LEFT+20)
	#define LINKS_WASHCARD_STRING_RECT_H_BOTTOM  	(LINKS_WASHCARD_STRING_RECT_H_TOP+20)
		
	/*#define LINKS_WASHCARD_NUMBER_RECT_H_LEFT   		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_WASHCARD_NUMBER_RECT_H_TOP	 	(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT*2+1)
	#define LINKS_WASHCARD_NUMBER_RECT_H_RIGHT   	LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_WASHCARD_NUMBER_RECT_H_BOTTOM    (LINKS_PAUSE_STRING_RECT_H_TOP+ LINKS_TEXT_FONT*3)*/
	#define LINKS_WASHCARD_NUMBER_RECT_H_LEFT   		(LINKS_WASHCARD_STRING_RECT_H_RIGHT+2)
	#define LINKS_WASHCARD_NUMBER_RECT_H_TOP	 	(LINKS_WASHCARD_STRING_RECT_H_TOP )
	#define LINKS_WASHCARD_NUMBER_RECT_H_RIGHT   	(LINKS_WASHCARD_NUMBER_RECT_H_LEFT+30)
	#define LINKS_WASHCARD_NUMBER_RECT_H_BOTTOM    LINKS_WASHCARD_STRING_RECT_H_BOTTOM

	/*#define LINKS_TIP_STRING_RECT_H_LEFT 		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_TIP_STRING_RECT_H_TOP	 	(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT*3+1)
	#define LINKS_TIP_STRING_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_TIP_STRING_RECT_H_BOTTOM	(LINKS_PAUSE_STRING_RECT_H_TOP+ LINKS_TEXT_FONT*4)*/
		#define LINKS_TIP_STRING_RECT_H_LEFT 		300
	#define LINKS_TIP_STRING_RECT_H_TOP	 	49
	#define LINKS_TIP_STRING_RECT_H_RIGHT		(LINKS_TIP_STRING_RECT_H_LEFT+20)
	#define LINKS_TIP_STRING_RECT_H_BOTTOM	(LINKS_TIP_STRING_RECT_H_TOP+20)

  	/* #define LINKS_TIP_NUMBER_RECT_H_LEFT   		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_TIP_NUMBER_RECT_H_TOP	   	(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT*4+1)
	#define LINKS_TIP_NUMBER_RECT_H_RIGHT  	LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_TIP_NUMBER_RECT_H_BOTTOM  	(LINKS_PAUSE_STRING_RECT_H_TOP+ LINKS_TEXT_FONT*5)*/
	  	 #define LINKS_TIP_NUMBER_RECT_H_LEFT   		(LINKS_TIP_STRING_RECT_H_RIGHT+2)
	#define LINKS_TIP_NUMBER_RECT_H_TOP	   	LINKS_TIP_STRING_RECT_H_TOP
	#define LINKS_TIP_NUMBER_RECT_H_RIGHT  	(LINKS_TIP_NUMBER_RECT_H_LEFT+30)
	#define LINKS_TIP_NUMBER_RECT_H_BOTTOM  	LINKS_TIP_STRING_RECT_H_BOTTOM
	
	/*#define LINKS_EPISODE_TITLE_RECT_H_LEFT 		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_EPISODE_TITLE_RECT_H_TOP	 	(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT*5+1)
	#define LINKS_EPISODE_TITLE_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_EPISODE_TITLE_RECT_H_BOTTOM	(LINKS_PAUSE_STRING_RECT_H_TOP+ LINKS_TEXT_FONT*6)*/
	#define LINKS_EPISODE_TITLE_RECT_H_LEFT 		300
	#define LINKS_EPISODE_TITLE_RECT_H_TOP	 	(LINKS_PAUSE_STRING_RECT_H_BOTTOM+10)
	#define LINKS_EPISODE_TITLE_RECT_H_RIGHT		(LINKS_EPISODE_TITLE_RECT_H_LEFT+20)
	#define LINKS_EPISODE_TITLE_RECT_H_BOTTOM	(LINKS_EPISODE_TITLE_RECT_H_TOP+ 20)
	
	/*#define LINKS_EPISODE_STRING_RECT_H_LEFT 			LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_EPISODE_STRING_RECT_H_TOP	 		(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT*6+1)
	#define LINKS_EPISODE_STRING_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_EPISODE_STRING_RECT_H_BOTTOM		(LINKS_PAUSE_STRING_RECT_H_TOP+ LINKS_TEXT_FONT*7)*/
	#define LINKS_EPISODE_STRING_RECT_H_LEFT 			(LINKS_EPISODE_TITLE_RECT_H_RIGHT+2)
	#define LINKS_EPISODE_STRING_RECT_H_TOP	 		LINKS_EPISODE_TITLE_RECT_H_TOP
	#define LINKS_EPISODE_STRING_RECT_H_RIGHT		(LINKS_EPISODE_STRING_RECT_H_LEFT+30)
	#define LINKS_EPISODE_STRING_RECT_H_BOTTOM	LINKS_EPISODE_TITLE_RECT_H_BOTTOM
	
	/*#define LINKS_SCORE_TITLE_RECT_H_LEFT 		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_SCORE_TITLE_RECT_H_TOP		(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT*7+1)
	#define LINKS_SCORE_TITLE_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_SCORE_TITLE_RECT_H_BOTTOM	    (LINKS_PAUSE_STRING_RECT_H_TOP+ LINKS_TEXT_FONT*8)*/
	#define LINKS_SCORE_TITLE_RECT_H_LEFT 		300
	#define LINKS_SCORE_TITLE_RECT_H_TOP		(LINKS_EPISODE_TITLE_RECT_H_BOTTOM+10)
	#define LINKS_SCORE_TITLE_RECT_H_RIGHT		(LINKS_SCORE_TITLE_RECT_H_LEFT+20)
	#define LINKS_SCORE_TITLE_RECT_H_BOTTOM	    (LINKS_SCORE_TITLE_RECT_H_TOP+20)
										
	/*#define LINKS_SCORE_STRING_RECT_H_LEFT 		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_SCORE_STRING_RECT_H_TOP		(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT*8+1)
	#define LINKS_SCORE_STRING_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_SCORE_STRING_RECT_H_BOTTOM	(LINKS_PAUSE_STRING_RECT_H_TOP+ LINKS_TEXT_FONT*9)*/
		#define LINKS_SCORE_STRING_RECT_H_LEFT 		(LINKS_SCORE_TITLE_RECT_H_RIGHT+2)
	#define LINKS_SCORE_STRING_RECT_H_TOP		LINKS_SCORE_TITLE_RECT_H_TOP
	#define LINKS_SCORE_STRING_RECT_H_RIGHT		(LINKS_SCORE_TITLE_RECT_H_LEFT+30)
	#define LINKS_SCORE_STRING_RECT_H_BOTTOM	LINKS_SCORE_TITLE_RECT_H_BOTTOM
	
	/*#define LINKS_TIME_TITLE_RECT_H_LEFT  		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_TIME_TITLE_RECT_H_TOP	   		(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT*9+1)
	#define LINKS_TIME_TITLE_RECT_H_RIGHT 		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_TIME_TITLE_RECT_H_BOTTOM  	(LINKS_PAUSE_STRING_RECT_H_TOP+ LINKS_TEXT_FONT*10)*/
	#define LINKS_TIME_TITLE_RECT_H_LEFT  		300
	#define LINKS_TIME_TITLE_RECT_H_TOP	   		(LINKS_SCORE_STRING_RECT_H_BOTTOM+10)
	#define LINKS_TIME_TITLE_RECT_H_RIGHT 		(LINKS_TIME_TITLE_RECT_H_LEFT+20)
	#define LINKS_TIME_TITLE_RECT_H_BOTTOM  	(LINKS_TIME_TITLE_RECT_H_TOP+20)
										
	/*#define LINKS_TIME_STRING_RECT_H_LEFT  		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_TIME_STRING_RECT_H_TOP		(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT*10+1)  
	#define LINKS_TIME_STRING_RECT_H_RIGHT 		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_TIME_STRING_RECT_H_BOTTOM 	(LINKS_PAUSE_STRING_RECT_H_TOP + LINKS_TEXT_FONT*11)*/
	#define LINKS_TIME_STRING_RECT_H_LEFT  		(LINKS_TIME_TITLE_RECT_H_RIGHT+2)
	#define LINKS_TIME_STRING_RECT_H_TOP		LINKS_TIME_TITLE_RECT_H_TOP 
	#define LINKS_TIME_STRING_RECT_H_RIGHT 		(LINKS_TIME_STRING_RECT_H_LEFT+40 )
	#define LINKS_TIME_STRING_RECT_H_BOTTOM 	LINKS_TIME_TITLE_RECT_H_BOTTOM

	/*#define LINKS_RETURN_BUTTON_RECT_H_LEFT  		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_RETURN_BUTTON_RECT_H_TOP		(LINKS_TIME_STRING_RECT_H_BOTTOM + LINKS_TEXT_FONT*11+1)  
	#define LINKS_RETURN_BUTTON_RECT_H_RIGHT 		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_RETURN_BUTTON_RECT_H_BOTTOM 	(LINKS_RETURN_BUTTON_RECT_H_TOP + LINKS_TEXT_FONT*12)*/
	#define LINKS_RETURN_BUTTON_RECT_H_LEFT  		300
	#define LINKS_RETURN_BUTTON_RECT_H_TOP		207 
	#define LINKS_RETURN_BUTTON_RECT_H_RIGHT 		(LINKS_RETURN_BUTTON_RECT_H_LEFT+65)
	#define LINKS_RETURN_BUTTON_RECT_H_BOTTOM 	(LINKS_RETURN_BUTTON_RECT_H_TOP+29)
  

	//#define	BOXMAN_MAP_LEFT_UP_X 	2
	//#define 	BOXMAN_MAP_LEFT_UP_Y 	2 	
	#define	BOXMAN_MAP_LEFT_UP_X 	2
	#define 	BOXMAN_MAP_LEFT_UP_Y 	43 	
	
	#define	BOXMAN_MAP_LEFT_UP_H_X 	38
	#define 	BOXMAN_MAP_LEFT_UP_H_Y 	3 
	
	#define BOXMAN_BUTTON_LAST_RECT_LEFT 10
		#define BOXMAN_BUTTON_LAST_RECT_TOP 316
		
	#define	BOXMAN_BUTTON_GOBACK_RECT_LEFT  167
	#define	BOXMAN_BUTTON_GOBACK_RECT_TOP  320
	
		#define	BOXMAN_BUTTON_NEXT_RECT_LEFT  119
	#define	BOXMAN_BUTTON_NEXT_RECT_TOP  316
	
			#define	BOXMAN_BUTTON_RETURN_RECT_LEFT  300
	#define	BOXMAN_BUTTON_RETURN_RECT_TOP  203
	
		#define BOXMAN_BUTTON_LAST_RECT_H_LEFT 316
		#define BOXMAN_BUTTON_LAST_RECT_H_TOP 17
		
	#define	BOXMAN_BUTTON_GOBACK_RECT_H_LEFT  302
	#define	BOXMAN_BUTTON_GOBACK_RECT_H_TOP  160
	
		#define	BOXMAN_BUTTON_NEXT_RECT_H_LEFT  316
	#define	BOXMAN_BUTTON_NEXT_RECT_H_TOP  103



	#define BOXMAN_SUB_MAP_BORDER_HIGHT	    26  //×ÓÍ¼±ß³¤,µ¥Î»pixel
	#define BOXMAN_SUB_MAP_BORDER_WIDTH     26  //×ÓÍ¼±ß¿í¶È,
	
     #define BOXMAN_LABEL_WIDTH      120  


#elif defined MAINLCD_SIZE_320X480
	//game link

	#define LINKS_TEXT_FONT 		20
	#define LINKS_TILE_WIDTH        38
	#define LINKS_TILE_HEIGHT       38
	
	#define LINKS_TILES_RECT_LEFT_S   8   //×ÓÍ¼Æ¬¿ò×ó
	#define LINKS_TILES_RECT_TOP_S    87 //×ÓÍ¼Æ¬¿òÉÏ	     
 

	#define LINKS_WASHCARD_STRING_RECT_LEFT 		10
	#define LINKS_WASHCARD_STRING_RECT_TOP		48
	#define LINKS_WASHCARD_STRING_RECT_RIGHT  	(LINKS_WASHCARD_STRING_RECT_LEFT + 29)
	#define LINKS_WASHCARD_STRING_RECT_BOTTOM  	(LINKS_WASHCARD_STRING_RECT_TOP + 29)
	
    #define LINKS_WASHCARD_NUMBER_RECT_LEFT   	(LINKS_WASHCARD_STRING_RECT_RIGHT + 2)
	#define LINKS_WASHCARD_NUMBER_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP +4)
	#define LINKS_WASHCARD_NUMBER_RECT_RIGHT   	(LINKS_WASHCARD_NUMBER_RECT_LEFT + 20)
	#define LINKS_WASHCARD_NUMBER_RECT_BOTTOM   (LINKS_WASHCARD_STRING_RECT_BOTTOM)
	
	#define LINKS_TIP_STRING_RECT_LEFT 	    140
	#define LINKS_TIP_STRING_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP)
	#define LINKS_TIP_STRING_RECT_RIGHT	    (LINKS_TIP_STRING_RECT_LEFT + 29)
	#define LINKS_TIP_STRING_RECT_BOTTOM	(LINKS_TIP_STRING_RECT_TOP+29)
	
	#define LINKS_TIP_NUMBER_RECT_LEFT 	(   LINKS_TIP_STRING_RECT_RIGHT + 2)
	#define LINKS_TIP_NUMBER_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP + 4)
	#define LINKS_TIP_NUMBER_RECT_RIGHT	    (LINKS_TIP_NUMBER_RECT_LEFT + 20)
	#define LINKS_TIP_NUMBER_RECT_BOTTOM	(LINKS_WASHCARD_STRING_RECT_BOTTOM)
	
	#define LINKS_PAUSE_STRING_RECT_LEFT 		257
	#define LINKS_PAUSE_STRING_RECT_TOP	 	(LINKS_WASHCARD_STRING_RECT_TOP+1)	
	#define LINKS_PAUSE_STRING_RECT_RIGHT	(LINKS_PAUSE_STRING_RECT_LEFT + 48)
	#define LINKS_PAUSE_STRING_RECT_BOTTOM	(LINKS_PAUSE_STRING_RECT_TOP+24)
	
	#define LINKS_EPISODE_TITLE_RECT_LEFT 		10
	#define LINKS_EPISODE_TITLE_RECT_BOTTOM	    430
	#define LINKS_EPISODE_TITLE_RECT_TOP	 	(LINKS_EPISODE_TITLE_RECT_BOTTOM - 29)
	#define LINKS_EPISODE_TITLE_RECT_RIGHT	    (LINKS_EPISODE_TITLE_RECT_LEFT + 29)
	
	
	#define LINKS_EPISODE_STRING_RECT_LEFT 		(LINKS_EPISODE_TITLE_RECT_RIGHT  + 2)
	#define LINKS_EPISODE_STRING_RECT_TOP	 	(LINKS_EPISODE_TITLE_RECT_TOP +4)
	#define LINKS_EPISODE_STRING_RECT_RIGHT		(LINKS_EPISODE_STRING_RECT_LEFT + 20)
	#define LINKS_EPISODE_STRING_RECT_BOTTOM		LINKS_EPISODE_TITLE_RECT_BOTTOM

	#define LINKS_SCORE_TITLE_RECT_LEFT 		130
	#define LINKS_SCORE_TITLE_RECT_TOP		    LINKS_EPISODE_TITLE_RECT_TOP 
	#define LINKS_SCORE_TITLE_RECT_RIGHT		(LINKS_SCORE_TITLE_RECT_LEFT +29)
	#define LINKS_SCORE_TITLE_RECT_BOTTOM	    LINKS_EPISODE_TITLE_RECT_BOTTOM
					
	#define LINKS_SCORE_STRING_RECT_LEFT 		(LINKS_SCORE_TITLE_RECT_RIGHT +2)
	#define LINKS_SCORE_STRING_RECT_TOP		    (LINKS_EPISODE_TITLE_RECT_TOP +4) 
	#define LINKS_SCORE_STRING_RECT_RIGHT		(LINKS_SCORE_STRING_RECT_LEFT + 50)
	#define LINKS_SCORE_STRING_RECT_BOTTOM	    LINKS_EPISODE_TITLE_RECT_BOTTOM

	#define LINKS_TIME_TITLE_RECT_LEFT  		241
	#define LINKS_TIME_TITLE_RECT_TOP	   		LINKS_EPISODE_TITLE_RECT_TOP
	#define LINKS_TIME_TITLE_RECT_RIGHT 		(LINKS_TIME_TITLE_RECT_LEFT +29)
	#define LINKS_TIME_TITLE_RECT_BOTTOM  		LINKS_EPISODE_TITLE_RECT_BOTTOM
	
	#define LINKS_TIME_STRING_RECT_LEFT  		(LINKS_TIME_TITLE_RECT_RIGHT +2)
	#define LINKS_TIME_STRING_RECT_TOP			(LINKS_EPISODE_TITLE_RECT_TOP +4)	  
	#define LINKS_TIME_STRING_RECT_RIGHT 		315
	#define LINKS_TIME_STRING_RECT_BOTTOM 		LINKS_EPISODE_TITLE_RECT_BOTTOM
		        
	#define LINKS_TILES_RECT_LEFT_H    8   //×ÓÍ¼Æ¬¿ò×ó
	#define LINKS_TILES_RECT_TOP_H    8 //×ÓÍ¼Æ¬¿òÉÏ
	
	#define LINKS_PAUSE_IMAGE_LEFT_H   350   //ÔÝÍ£Í¼Æ¬×óÎ»ÖÃ
	#define LINKS_PAUSE_IMAGE_TOP_H     4  //ÔÝÍ£Í¼Æ¬¿òÉÏÎ»ÖÃ

	#define LINKS_FULLSCREEN_WIDTH_H  480
	#define TEXT_RECT_H_LEFT	360
  	
    #define LINKS_PAUSE_STRING_RECT_H_LEFT 		LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_PAUSE_STRING_RECT_H_TOP	 	(LINKS_PAUSE_IMAGE_TOP_H+2)	
	#define LINKS_PAUSE_STRING_RECT_H_RIGHT		(LINKS_PAUSE_STRING_RECT_H_LEFT +48)
	#define LINKS_PAUSE_STRING_RECT_H_BOTTOM	(LINKS_PAUSE_IMAGE_TOP_H + 32)	

	#define LINKS_WASHCARD_STRING_RECT_H_LEFT 		LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_WASHCARD_STRING_RECT_H_TOP		(LINKS_PAUSE_STRING_RECT_H_BOTTOM + 21)
	#define LINKS_WASHCARD_STRING_RECT_H_RIGHT  	(LINKS_WASHCARD_STRING_RECT_H_LEFT +29)
	#define LINKS_WASHCARD_STRING_RECT_H_BOTTOM  	(LINKS_WASHCARD_STRING_RECT_H_TOP + 29)
		
	#define LINKS_WASHCARD_NUMBER_RECT_H_LEFT   	(LINKS_WASHCARD_STRING_RECT_H_RIGHT + 4)
	#define LINKS_WASHCARD_NUMBER_RECT_H_TOP	 	(LINKS_WASHCARD_STRING_RECT_H_TOP +4)
	#define LINKS_WASHCARD_NUMBER_RECT_H_RIGHT   	(LINKS_WASHCARD_NUMBER_RECT_H_LEFT + 20)
	#define LINKS_WASHCARD_NUMBER_RECT_H_BOTTOM     (LINKS_WASHCARD_NUMBER_RECT_H_TOP+ LINKS_TEXT_FONT)

	#define LINKS_TIP_STRING_RECT_H_LEFT 		LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_TIP_STRING_RECT_H_TOP	 	    (LINKS_WASHCARD_NUMBER_RECT_H_BOTTOM + 21)
	#define LINKS_TIP_STRING_RECT_H_RIGHT		(LINKS_TIP_STRING_RECT_H_LEFT +29)
	#define LINKS_TIP_STRING_RECT_H_BOTTOM	    (LINKS_TIP_STRING_RECT_H_TOP + 32)

  	#define LINKS_TIP_NUMBER_RECT_H_LEFT   	    (LINKS_TIP_STRING_RECT_H_RIGHT +4)
	#define LINKS_TIP_NUMBER_RECT_H_TOP	   	    (LINKS_TIP_STRING_RECT_H_TOP +4)
	#define LINKS_TIP_NUMBER_RECT_H_RIGHT  	    (LINKS_TIP_NUMBER_RECT_H_LEFT +20)
	#define LINKS_TIP_NUMBER_RECT_H_BOTTOM  	(LINKS_TIP_NUMBER_RECT_H_TOP+ LINKS_TEXT_FONT)
	
	#define LINKS_EPISODE_TITLE_RECT_H_LEFT 	LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_EPISODE_TITLE_RECT_H_TOP	 	(LINKS_TIP_NUMBER_RECT_H_BOTTOM + 21)
	#define LINKS_EPISODE_TITLE_RECT_H_RIGHT	(LINKS_EPISODE_TITLE_RECT_H_LEFT +29)
	#define LINKS_EPISODE_TITLE_RECT_H_BOTTOM	(LINKS_EPISODE_TITLE_RECT_H_TOP + 29)
	
	#define LINKS_EPISODE_STRING_RECT_H_LEFT 		(LINKS_EPISODE_TITLE_RECT_H_RIGHT +4)
	#define LINKS_EPISODE_STRING_RECT_H_TOP	 		(LINKS_EPISODE_TITLE_RECT_H_TOP +4)
	#define LINKS_EPISODE_STRING_RECT_H_RIGHT		(LINKS_EPISODE_STRING_RECT_H_LEFT +20)
	#define LINKS_EPISODE_STRING_RECT_H_BOTTOM		(LINKS_EPISODE_STRING_RECT_H_TOP + LINKS_TEXT_FONT)
	
	#define LINKS_SCORE_TITLE_RECT_H_LEFT 		LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_SCORE_TITLE_RECT_H_TOP		(LINKS_EPISODE_STRING_RECT_H_BOTTOM +21)
	#define LINKS_SCORE_TITLE_RECT_H_RIGHT		(LINKS_SCORE_TITLE_RECT_H_LEFT +29)
	#define LINKS_SCORE_TITLE_RECT_H_BOTTOM	    (LINKS_SCORE_TITLE_RECT_H_TOP + 29)
										
	#define LINKS_SCORE_STRING_RECT_H_LEFT 		(LINKS_SCORE_TITLE_RECT_H_RIGHT +4)
	#define LINKS_SCORE_STRING_RECT_H_TOP		(LINKS_SCORE_TITLE_RECT_H_TOP +4)
	#define LINKS_SCORE_STRING_RECT_H_RIGHT		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_SCORE_STRING_RECT_H_BOTTOM	(LINKS_SCORE_STRING_RECT_H_TOP + LINKS_TEXT_FONT)
	
	#define LINKS_TIME_TITLE_RECT_H_LEFT  			LINKS_PAUSE_IMAGE_LEFT_H
	#define LINKS_TIME_TITLE_RECT_H_TOP	   		    (LINKS_SCORE_STRING_RECT_H_BOTTOM +21)
	#define LINKS_TIME_TITLE_RECT_H_RIGHT 		    (LINKS_TIME_TITLE_RECT_H_LEFT +29)
	#define LINKS_TIME_TITLE_RECT_H_BOTTOM  		(LINKS_TIME_TITLE_RECT_H_TOP + 29)
										
	#define LINKS_TIME_STRING_RECT_H_LEFT  		    (LINKS_TIME_TITLE_RECT_H_RIGHT +6)
	#define LINKS_TIME_STRING_RECT_H_TOP			(LINKS_TIME_TITLE_RECT_H_TOP +4)  
	#define LINKS_TIME_STRING_RECT_H_RIGHT 		    (LINKS_TIME_STRING_RECT_H_LEFT +40)  
	#define LINKS_TIME_STRING_RECT_H_BOTTOM 		(LINKS_TIME_STRING_RECT_H_TOP+ LINKS_TEXT_FONT)

	#define LINKS_RETURN_BUTTON_RECT_H_LEFT  		LINKS_PAUSE_STRING_RECT_H_LEFT
	#define LINKS_RETURN_BUTTON_RECT_H_TOP		    (LINKS_TIME_STRING_RECT_H_BOTTOM +21)  
	#define LINKS_RETURN_BUTTON_RECT_H_RIGHT 		LINKS_FULLSCREEN_WIDTH_H
	#define LINKS_RETURN_BUTTON_RECT_H_BOTTOM 	    (LINKS_RETURN_BUTTON_RECT_H_TOP + LINKS_TEXT_FONT)
  

	#define	BOXMAN_MAP_LEFT_UP_X 	6
	#define 	BOXMAN_MAP_LEFT_UP_Y 	6 
	#define	BOXMAN_MAP_LEFT_UP_H_X 	6
	#define 	BOXMAN_MAP_LEFT_UP_H_Y 	6
	
	#define  BOXMAN_FULLSCREEN_WIDTH 		320
	#define  BOXMAN_FULLSCREEN_HEIGHT    	480

	#define BOXMAN_SUB_MAP_BORDER_HIGHT	    34  //×ÓÍ¼±ß³¤,µ¥Î»pixel
	#define BOXMAN_SUB_MAP_BORDER_WIDTH     34  //×ÓÍ¼±ß¿í¶È,

	
	 #define BOXMAN_LABEL_WIDTH      160
    /*	#define BOXMAN_BUTTON_HEIGHT            36	
	#define BOXMAN_BUTTON_WIDTH           50
   	
	#define BOXMAN_LEFT_BUTTON_HEIGHT    36
	#define BOXMAN_LEFT_BUTTON_WIDTH		34
	*/
/*
	#define BOXMAN_LEFT_BUTTON_RECT_LEFT    16
	#define BOXMAN_LEFT_BUTTON_RECT_RIGHT   (BOXMAN_LEFT_BUTTON_RECT_LEFT + BOXMAN_LEFT_BUTTON_WIDTH)
	#define BOXMAN_LEFT_BUTTON_RECT_BOTTOM  (BOXMAN_FULLSCREEN_HEIGHT - MMI_FULLSCREEN_SOFTKEY_BAR_HEIGHT - 1)
	#define BOXMAN_LEFT_BUTTON_RECT_TOP     (BOXMAN_LEFT_BUTTON_RECT_BOTTOM - BOXMAN_BUTTON_HEIGHT)

	#define BOXMAN_GOBACK_BUTTON_WIDTH          54
	#define BOXMAN_GOBACK_BUTTON_RECT_RIGHT     (BOXMAN_FULLSCREEN_WIDTH - 2 -16)
	#define BOXMAN_GOBACK_BUTTON_RECT_LEFT     (BOXMAN_GOBACK_BUTTON_RECT_RIGHT - BOXMAN_GOBACK_BUTTON_WIDTH)
	#define BOXMAN_GOBACK_BUTTON_RECT_TOP       BOXMAN_LEFT_BUTTON_RECT_TOP
	#define BOXMAN_GOBACK_BUTTON_RECT_BOTTOM    BOXMAN_LEFT_BUTTON_RECT_BOTTOM

	#define BOXMAN_RIGHT_BUTTON_RECT_RIGHT  (BOXMAN_GOBACK_BUTTON_RECT_LEFT - 1)
	#define BOXMAN_RIGHT_BUTTON_RECT_LEFT   (BOXMAN_RIGHT_BUTTON_RECT_RIGHT - BOXMAN_LEFT_BUTTON_WIDTH)
	#define BOXMAN_RIGHT_BUTTON_RECT_TOP    BOXMAN_LEFT_BUTTON_RECT_TOP
	#define BOXMAN_RIGHT_BUTTON_RECT_BOTTOM	 BOXMAN_LEFT_BUTTON_RECT_BOTTOM
	
	#define BOXMAN_LEVEL_LABEL_RECT_LEFT      (BOXMAN_LEFT_BUTTON_RECT_RIGHT + 1)
	#define BOXMAN_LEVEL_LABEL_RECT_TOP       BOXMAN_LEFT_BUTTON_RECT_TOP
	#define BOXMAN_LEVEL_LABEL_RECT_RIGHT     (BOXMAN_RIGHT_BUTTON_RECT_LEFT - 1)
	#define BOXMAN_LEVEL_LABEL_RECT_BOTTOM    BOXMAN_LEFT_BUTTON_RECT_BOTTOM
*/
#endif

/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef   __cplusplus
    }
#endif
#endif //GAME_SUPPORT
#endif //_MMIALARM_POSITION_H
