


//[[define image information

RES_ADD_IMG(CUSTOM_DEVICE_LOCK,"\\MMI_RES_##\\IMAG\\CUSTOM_DEVICE_LOCK.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(CUSTOM_LOCK_SCREEN_CAMERA,"\\MMI_RES_##\\IMAG\\CUSTOM_LOCK_SCREEN_CAMERA.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(CUSTOM_LOCK_SCREEN_PHONE,"\\MMI_RES_##\\IMAG\\CUSTOM_LOCK_SCREEN_PHONE.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(CUSTOM_LOCK_SCREEN_N_NEW_MESSAGE,"\\MMI_RES_##\\IMAG\\CUSTOM_LOCK_SCREEN_N_NEW_MESSAGE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(CUSTOM_LOCK_SCREEN_N_MISSED_CALL,"\\MMI_RES_##\\IMAG\\CUSTOM_LOCK_SCREEN_N_MISSED_CALL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(CUSTOM_LOCK_SCREEN_N_MUSIC_PLAYER,"\\MMI_RES_##\\IMAG\\CUSTOM_LOCK_SCREEN_N_MUSIC_PLAYER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(CUSTOM_LOCK_SCREEN_N_FM,"\\MMI_RES_##\\IMAG\\CUSTOM_LOCK_SCREEN_N_FM.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(CUSTOM_LOCK_SCREEN_N_SNOOZED_ALARM,"\\MMI_RES_##\\IMAG\\CUSTOM_LOCK_SCREEN_N_FM.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(CUSTOM_LOCK_SCREEN_N_SNOOZED_CALENAR,"\\MMI_RES_##\\IMAG\\CUSTOM_LOCK_SCREEN_N_SNOOZED_ALARM.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(CUSTOM_LOCK_SCREEN_N_VOICE_MAIL,"\\MMI_RES_##\\IMAG\\CUSTOM_LOCK_SCREEN_N_VOICE_MAIL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(CUSTOM_LOCK_SCREEN_N_MAILBOX,"\\MMI_RES_##\\IMAG\\CUSTOM_LOCK_SCREEN_N_MAILBOX.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(CUSTOM_LOCK_SCREEN_N_OPERATOR_SETTINGS,"\\MMI_RES_##\\IMAG\\CUSTOM_LOCK_SCREEN_N_OPERATOR_SETTINGS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(CUSTOM_LOCK_SCREEN_N_WINDOWS,"\\MMI_RES_##\\IMAG\\CUSTOM_LOCK_SCREEN_N_WINDOWS.png",IMG_CMP_PNG_ARGB_RLE,0)


//]]define image information





//[[define anim information

//]]define anim information





//[[define string information

//tp be continue
RES_ADD_STRING(TXT_DEVICELOCK_TITLE,"Device lock")
RES_ADD_STRING(STR_LOCK_SOFTKEY_CALL_MK,"Call")
RES_ADD_STRING(STR_LOCK_EMERGENCY_NUM_PROMPT,"Emergency number")

//RES_ADD_STRING(STR_SECUR_CODE_QUERY_EX02,"Enter security code:")

//ok
RES_ADD_STRING(STR_CLK_IDLE_AM,"am")
RES_ADD_STRING(STR_CLK_IDLE_PM,"pm")
RES_ADD_STRING(STR_CL_TIME_AM,"am")
RES_ADD_STRING(STR_CL_TIME_PM,"pm")

RES_ADD_STRING(STR_LOCK_CODE_APPR_EXT01,"Code approved")
RES_ADD_STRING(STR_LOCK_CODE_REJE_EXT01,"Code rejected. Please try again.")
//list


// text


// buttpn


// tab


//]]define string information



//[[define ring information
//RES_ADD_RING(RING_SAMPLE_TEST,"\\MMI_RES_##\\RING\\RING_SAMPLE_TEST.mid")
//]]define ring information

