#ifdef GAME_BOXMAN_SUPPORT

//[[define image infomation
//#ifdef JPG_DEC_SUPPORT_JPG_HW
//RES_ADD_IMG(IMAGE_BOXMAN_BACKGROUND_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_BACKGROUND_ICON.jpg",IMG_CMP_JPG_SCI,0)
//#else
//RES_ADD_IMG(IMAGE_BOXMAN_BACKGROUND_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_BACKGROUND_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
//#endif
//RES_ADD_IMG(IMAGE_BOXMAN_BOTTON_MIDDLE_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_BOTTON_MIDDLE_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_SET_LEFT_DOWN,"\\MMI_RES_##\\IMAG\\IMAGE_SET_LEFT_DOWN.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_SET_LEFT_NORMAL,"\\MMI_RES_##\\IMAG\\IMAGE_SET_LEFT_NORMAL.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_SET_RIGHT_DOWN,"\\MMI_RES_##\\IMAG\\IMAGE_SET_RIGHT_DOWN.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_SET_RIGHT_NORMAL,"\\MMI_RES_##\\IMAG\\IMAGE_SET_RIGHT_NORMAL.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_BOXMAN_AIM,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_AIM.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_BOXMAN_BOX,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_BOX.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_BOXMAN_BOX_IN_AIM,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_BOX_IN_AIM.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_DOWN_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_DOWN_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_GO_BACK_DOWN_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_GO_BACK_DOWN_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
#if defined (GAME_BOXMAN_SUPPORT) &&  defined (TOUCH_PANEL_SUPPORT)
RES_ADD_IMG(IMAGE_BOXMAN_GO_BACK_NORMAL_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_GO_BACK_NORMAL_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif
RES_ADD_IMG(IMAGE_BOXMAN_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_BUTTON.bmp",IMG_CMP_BMP_16_565_RLE,0)

RES_ADD_IMG(IMAGE_BOXMAN_MAN,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_MAN.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_BOXMAN_MAN_IN_AIM,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_MAN_IN_AIM.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_NORMAL_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_NORMAL_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_BOXMAN_SPACE,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_SPACE.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_BOXMAN_WALL,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_WALL.bmp",IMG_CMP_BMP_16_565_RLE,0)
RES_ADD_IMG(IMAGE_BOXMAN_WALLOUT,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_WALLOUT.bmp",IMG_CMP_BMP_16_565_RLE,0)


//]]define image infomation


//[[define anim infomation
//]]define anim infomation


//[[define string infomation

RES_ADD_STRING(TXT_BOXMAN,"Boxman")
RES_ADD_STRING(TXT_GMBOXMAN_SELECT,"Select Scene")
//RES_ADD_STRING(TXT_GMBOXMAN_NO,"No.")// case 3:defined but not used
//RES_ADD_STRING(TXT_GMBOXMAN_SCENE,"Map")// case 3:defined but not used
//RES_ADD_STRING(TXT_GMBOXMAN_LAST_MAP,"Last Map")
//RES_ADD_STRING(TXT_GMBOXMAN_NEXT_MAP,"Next Map")// case 3:defined but not used
RES_ADD_STRING(TXT_GMBOXMAN_SELECT_TIP,"Select from 1 to 15")
RES_ADD_STRING(TXT_GMBOXMAN_MAP_INVALID,"Map Invalid")
#ifndef TOUCH_PANEL_SUPPORT
RES_ADD_STRING(TXT_BOXMAN_HELP_NO_TOUCH,"Push box,move the snail,press the bordered box to move box.Press '#' will back.")//cr149801																																																																																																																																																																																																										
#else
#ifdef MMI_PDA_SUPPORT
RES_ADD_STRING(TXT_BOXMAN_HELP_PDA,"Push box,press in space to move the person,press the bordered box to move box.")
#else
RES_ADD_STRING(TXT_BOXMAN_HELP_EXT,"Push box,press in space to move the person,press the bordered box to move box.")
#endif
#endif

//]]define string infomation


//[[define data infomation
//]]define data infomation
#endif
