#ifdef MMIENG_PING_SUPPORT
RES_ADD_STRING(TXT_ENG_PING_MODE,"Ping Mode")
RES_ADD_STRING(TXT_ENG_PING_MODE_COUNT,"Ping count")
RES_ADD_STRING(TXT_ENG_PING_MODE_IPTYPE,"IP Type")
RES_ADD_STRING(TXT_ENG_PING_MODE_WEB_ADDRESS,"Website Address")
RES_ADD_STRING(TXT_ENG_PING_MODE_EMPTY_COUNT,"Empty Count!")
RES_ADD_STRING(TXT_ENG_PING_MODE_BIG_COUNT,"The count is too big!")
RES_ADD_STRING(TXT_ENG_PING_MODE_INVALID_INFO,"Invalid ping information!")
RES_ADD_STRING(TXT_ENG_PING_SELECT_MODE,"Select Ping Mode")
RES_ADD_STRING(TXT_ENG_PING_NORMAL,"Normal Ping")
RES_ADD_STRING(TXT_ENG_PING_LONG,"Long Ping")
#endif
