#ifdef GAME_QUINTET_SUPPORT
//[[define image infomation
//#ifdef JPG_DEC_SUPPORT_JPG_HW
//RES_ADD_IMG(IMAGE_BOXMAN_BACKGROUND_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_BACKGROUND_ICON.jpg",IMG_CMP_JPG_SCI,0)
//#else
//RES_ADD_IMG(IMAGE_BOXMAN_BACKGROUND_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_BACKGROUND_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
//#endif
//RES_ADD_IMG(IMAGE_BOXMAN_BOTTON_MIDDLE_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_BOTTON_MIDDLE_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_SET_LEFT_DOWN,"\\MMI_RES_##\\IMAG\\IMAGE_SET_LEFT_DOWN.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_SET_LEFT_NORMAL,"\\MMI_RES_##\\IMAG\\IMAGE_SET_LEFT_NORMAL.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_SET_RIGHT_DOWN,"\\MMI_RES_##\\IMAG\\IMAGE_SET_RIGHT_DOWN.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_SET_RIGHT_NORMAL,"\\MMI_RES_##\\IMAG\\IMAGE_SET_RIGHT_NORMAL.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_AIM,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_AIM.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_BOX,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_BOX.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_BOX_IN_AIM,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_BOX_IN_AIM.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_DOWN_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_DOWN_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_GO_BACK_DOWN_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_GO_BACK_DOWN_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_GO_BACK_NORMAL_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_GO_BACK_NORMAL_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)

//RES_ADD_IMG(IMAGE_BOXMAN_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_BUTTON.bmp",IMG_CMP_BMP_16_565_RLE,0)

//RES_ADD_IMG(IMAGE_BOXMAN_MAN,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_MAN.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_MAN_IN_AIM,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_MAN_IN_AIM.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_NORMAL_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_NORMAL_ICON.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_SPACE,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_SPACE.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_WALL,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_WALL.bmp",IMG_CMP_BMP_16_565_RLE,0)
//RES_ADD_IMG(IMAGE_BOXMAN_WALLOUT,"\\MMI_RES_##\\IMAG\\IMAGE_BOXMAN_WALLOUT.bmp",IMG_CMP_BMP_16_565_RLE,0)


//]]define image infomation


//[[define anim infomation
//]]define anim infomation


//[[define string infomation

//michael wang for5
RES_ADD_STRING(TXT_QUT,"QUT")
//RES_ADD_STRING(TXT_GAME_QUINTET,"GAME_QUINTET")
RES_ADD_STRING(TXT_GMQUT_FIRST_HAND,"FIRST HAND")
RES_ADD_STRING(TXT_GMQUT_LAST_HAND,"LAST HAND")
RES_ADD_STRING(TXT_GMQUT_LAST,"LAST")
RES_ADD_STRING(TXT_GMQUT_SETTING,"SETTING")
RES_ADD_STRING(TXT_GMQUT_CURRENT_HAND,"CURRENT HAND")
RES_ADD_STRING(TXT_GMQUT_BLACK_WIN,"BLACK WIN")
RES_ADD_STRING(TXT_GMQUT_WHITE_WIN,"WHITE WIN")
RES_ADD_STRING(TXT_GMQUT_TIE,"TIE")
RES_ADD_STRING(TXT_GMQUT_CANCEL,"CANCEL")
RES_ADD_STRING(TXT_GMQUT_HELP,"HELP")
RES_ADD_STRING(TXT_GMQUT_NEW_GAME,"NEW GAME")
RES_ADD_STRING(TXT_GMQUT_CONTINUE,"CONTINUE")
RES_ADD_STRING(TXT_GMQUT_INFO,"INFO")
RES_ADD_STRING(TXT_GMQUT_INTRODUCE,"INTRODUCE")
//michael wang
#endif
