



//[[define image infomation

//RES_ADD_IMG(MYRIAD_JAVA_LOGO,"\\MMI_RES_##\\IMAG\\MYRIAD_JAVA_LOGO.bmp",IMG_CMP_BMP_16_565_RLE,0)
//8910UIX delete
//RES_ADD_IMG(MYRIAD_JAVA_LOGO,"\\MMI_RES_##\\IMAG\\IMAGE_MY_APPLICATIONS_SPLASH.png",IMG_CMP_PNG_ARGB_RLE,0)//这张图是java库里使用的，虽然平台代码并未使用，也不能清除
RES_ADD_IMG(JAVA_ICON,"\\MMI_RES_##\\IMAG\\JAVA_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef SUPPORT_DOWNLOAD
RES_ADD_IMG(IMAGE_JAVA_DOWNLOAD_ENTER,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_DOWNLOAD_ENTER.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif
//RES_ADD_IMG(IMAGE_JAVA_DOWNLOAD_ENTER_PRESSED,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_DOWNLOAD_ENTER_PRESSED.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_FMM_FILE_UDISK_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_FMM_FILE_UDISK_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_JAVALIST_FOCUSED,"\\MMI_RES_##\\IMAG\\IMG_JAVA_MENU_RESET_SYSTEM_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_JAVA_NETWORKSETTING_FOCUSED,"\\MMI_RES_##\\IMAG\\IMG_JAVA_MENU_LOCATION_INSTALL_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_TASKMANAGER_FOCUSED,"\\MMI_RES_##\\IMAG\\IMG_JAVA_MENU_SETTING_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
#ifdef VIRTUAL_KEY_BOARD
//KEYBOARD bg
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD_BG,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD_BG.png",IMG_CMP_PNG_SABM_RLE |SABM_HOR_STRETCH,0)

//KEYBOARD1
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_LS_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_LS_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_LS_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_LS_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_UP_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_UP_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_UP_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_UP_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_RS_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_RS_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_RS_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_RS_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_NUM_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_NUM_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_NUM_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_NUM_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_LEFT_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_LEFT_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_LEFT_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_LEFT_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_DOWN_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_DOWN_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_DOWN_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_DOWN_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_RIGHT_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_RIGHT_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_RIGHT_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_RIGHT_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_OK_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_OK_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD1_OK_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD1_OK_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)

//KEYBOARD2
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_LS_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_LS_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_LS_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_LS_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM1_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM1_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM1_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM1_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM2_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM2_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM2_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM2_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM3_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM3_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM3_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM3_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM4_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM4_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM4_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM4_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM5_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM5_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM5_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM5_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM6_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM6_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM6_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM6_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_RS_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_RS_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_RS_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_RS_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_RETURN_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_RETURN_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_RETURN_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_RETURN_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM7_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM7_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM7_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM7_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM8_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM8_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM8_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM8_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM9_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM9_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM9_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM9_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM0_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM0_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_NUM0_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_NUM0_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_ASTERISK_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_ASTERISK_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_ASTERISK_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_ASTERISK_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_POUND_ON,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_POUND_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_JAVA_KEYBOARD2_POUND_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_JAVA_KEYBOARD2_POUND_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
#endif

//]]define image infomation





//[[define anim infomation

//]]define anim infomation





//[[define string infomation
RES_ADD_STRING(TXT_COMM_JAVAAPP,"Java application")

//RES_ADD_STRING(TXT_JAVA_RUN,"Run")    //replaced by common ID TXT_RUN
//#ifdef SUPPORT_UPDATE_FUNCTION
//RES_ADD_STRING(TXT_JAVA_UPDATE,"Application Update")    replaced by common ID TXT_COMMON_UPDATE
//#endif
//RES_ADD_STRING(TXT_JAVA_AMS_OPTION_DELETE,"Delete")      //replaced by common ID TXT_DELETE


//RES_ADD_STRING(TXT_JAVA_INSTALL_IOERR,"IO error")    //case3: defined but not used

//RES_ADD_STRING(TXT_JAVA_INSTALL_USERCANCELED,"Canceled")    //replaced by common ID TXT_CANCELED

//RES_ADD_STRING(TXT_JAVA_INSTALL_JARNOTFOUN,"Jar not found")    //case3: defined but not used

//RES_ADD_STRING(TXT_JAVA_INSTALL_MISSSUITENAME,"Miss midlet name")    //case3: defined but not used

//RES_ADD_STRING(TXT_JAVA_INSTALL_COMPILATIONFAILED,"Complilation failed")    //case3: defined but not used

RES_ADD_STRING(TXT_JAVA_INSTALL_INSTALLER_IS_BUSY,"Installer is busy, please wait and try again later!")



RES_ADD_STRING(TXT_JAVA_AMS_OPTION_APPLICATION_SET,"Application Set")

//RES_ADD_STRING(TXT_COMMON_LINKSETTING,"Network Settings")

//RES_ADD_STRING(TXT_JAVA_LOCALINSTALL,"Local Install")  //replaced by common ID TXT_COM_LOCALINSTALL

RES_ADD_STRING(TXT_EXIT_BACKGROUND_JAVA, "JAVA is running in background, please quit JAVA first.")


#ifdef SUPPORT_DOWNLOAD

//RES_ADD_STRING(TXT_JAVA_DOWNLOAD,"Download")  //replaced by common ID TXT_COMMON_DOWNLOAD_COMN

RES_ADD_STRING(TXT_DOWNLOAD_GAME,"Game download")

RES_ADD_STRING(TXT_DOWNLOAD_EBOOK,"Ebook download")

RES_ADD_STRING(TXT_DOWNLOAD_OTHER,"Others download")

//RES_ADD_STRING(TXT_DOWNLOAD_SETTING,"Download settings")    //replaced by common ID TXT_DOWNLOAD_SETINGS

RES_ADD_STRING(TXT_JAVA_DOWNLOAD_GAME_URL,"Game URL")
RES_ADD_STRING(TXT_JAVA_DOWNLOAD_EBOOK_URL,"Ebook URL")
RES_ADD_STRING(TXT_JAVA_DOWNLOAD_OTHER_URL,"Other URL")
//RES_ADD_STRING(TXT_JAVA_DOWNLOAD_INVALID_URL,"Invalid URL")    //replaced by common ID TXT_INVALID_URL
#endif

RES_ADD_STRING(TXT_JAVA_INSTALL_SELECT_DISK_E,"MemoryCard")
//RES_ADD_STRING(TXT_IKB_SD_1,"MemoryCard1")
//RES_ADD_STRING(TXT_IKB_SD_2,"MemoryCard2")
RES_ADD_STRING(TXT_JAVA_INSTALL_SELECT_DISK_C,"System disk")
RES_ADD_STRING(TXT_JAVA_INSTALL_SELECT_DISK_D,"Phone")

//RES_ADD_STRING(TXT_JAVA_APP_INSTALL,"Installing")  //replaced by common ID TXT_COM_LOCALINSTALL

//RES_ADD_STRING(TXT_JAVA_AMS,"Application list")    //replaced by common ID TXT_APP_MANAGER

RES_ADD_STRING(TXT_JAVA_ABOUT,"About")
#ifdef SUPPORT_DELETE_ALL_FUNCTION
RES_ADD_STRING(TXT_DELETEALL_QUERY, "Make sure to Delete ALL")
//RES_ADD_STRING(TXT_JAVA_DELETEALL,"Delete all")      //replaced by common ID TXT_DELALL
#endif

RES_ADD_STRING(TXT_DELETE_QUERY_MORE, "Are you sure to delete the MIDlet and all related user data")
RES_ADD_STRING(TXT_DELETE_SUITE_QUERY, "Are you sure to delete all MIDlet in the suite and related user data")

RES_ADD_STRING(TXT_JAVA_INSTALL_SELECT_DISK,"Store device setting")

//RES_ADD_STRING(TXT_JAVA_DETAIL_NAME,"App Name:")  //replaced by common ID TXT_INPUT_NAME
//RES_ADD_STRING(TXT_JAVA_DETAIL_VERSION,"App Version:")  //replaced by common ID TXT_COMM_VERSION_1
RES_ADD_STRING(TXT_JAVA_DETAIL_VENDOR,"App Vendor:")
//RES_ADD_STRING(TXT_JAVA_DETAIL_SIZE,"App Size:")  //replaced by common ID TXT_DETAIL_SIZE
RES_ADD_STRING(TXT_JAVA_DETAIL_URL,"Url:")
RES_ADD_STRING(TXT_JAVA_DETAIL_DOMAIN,"Domain:")
RES_ADD_STRING(TXT_JAVA_DETAIL_SIGNED_BY,"Signed by:")
RES_ADD_STRING(TXT_JAVA_DETAIL_SERIAL_NUMBER,"Serial Number:")
RES_ADD_STRING(TXT_JAVA_DETAIL_ISSUED_BY,"ISSUED_BYISSUED_BY:")
RES_ADD_STRING(TXT_JAVA_DETAIL_SUITE_AUTHORISOR,"Authenticated by:")
RES_ADD_STRING(TXT_JAVA_DETAIL_PUSHED_CONTENT,"Pushed Content:")
RES_ADD_STRING(TXT_JAVA_ABOUT_TXT_LINE_1,"Esmertec, Jbed, Jcap, Jeco, FastBCC, FastDAC, HostBCC and u@ are trademarks or registered trademarks of Myriad Group AG.")

RES_ADD_STRING(TXT_JAVA_ABOUT_TXT_LINE_2,"Copyright &copy; 1998-2009 Myriad Group AG.")

RES_ADD_STRING(TXT_JAVA_ABOUT_TXT_LINE_3,"Copyright &copy; 2000-2001 Sun Microsystems Inc.")

RES_ADD_STRING(TXT_JAVA_ABOUT_TXT_LINE_4,"Java and all Java-based marks are trademarks or registered trademarks of Sun Microsystems, Inc. Myriad is independent of, and in no manner legally affiliated with, Sun Microsystems, Inc. except as a licensee.")

RES_ADD_STRING(TXT_JAVA_ABOUT_TXT_LINE_5,"All rights reserved for all marks. All use is subject to license terms. For more information please go to <www.myriadgroup.com>.")

RES_ADD_STRING(TXT_JAVA_ABOUT_TXT_LINE_6,"Jbed Advanced (with FastBCC) is protected by U.S. Pat. Nos: 6,964,039; 6,978,451.")


RES_ADD_STRING(TXT_JAVA_NO_MEMORY,"No memory ,Please delete some java applications?")

RES_ADD_STRING(TXT_JAVA_NO_MIDLET_FILE,"MIDlet files are missing.")
RES_ADD_STRING(TXT_JAVA_LAUNCH_MIDLET_SUITE,"Installed, Launch the App?")
//RES_ADD_STRING(TXT_JAVA_INSTALL_WARNING,"Installing Information")    //case3: defined but not used
RES_ADD_STRING(TXT_JAVA_RUN_ERROR,"Java run error")

//RES_ADD_STRING(TXT_JAVA_TASK_MNGER, "Task manager")      //replaced by common ID TXT_APPLICATION_MANAGER
RES_ADD_STRING(TXT_JAVA_COMPILING, "Compiling")
RES_ADD_STRING(TXT_JAVA_OPTIMIZING_JAR_FILE, "Optimizing jar file")
RES_ADD_STRING(TXT_JAVA_GETTING_JAR_FILE, "Getting jar file")
//RES_ADD_STRING(TXT_JAVA_USERCANCELLING, "Cancelling")  //replaced by common ID TXT_COMMON_CANCELING
RES_ADD_STRING(TXT_JAVA_DESTROY, "Destroy")
RES_ADD_STRING(TXT_JAVA_DESTROYING, "Destroying")
RES_ADD_STRING(TXT_JAVA_DELETEING, "Deleting")



//RES_ADD_STRING(TXT_JAVA_CHOOSE_NETWORK,"Select network")    //replaced by common ID TXT_NETWORK_SELECT
RES_ADD_STRING(TXT_JAVA_NW_SIM1_LABEL,"SIM1 network setting")
RES_ADD_STRING(TXT_JAVA_NW_SIM2_LABEL,"SIM2 network setting")
RES_ADD_STRING(TXT_JAVA_NW_SIM3_LABEL,"SIM3 network setting")
RES_ADD_STRING(TXT_JAVA_NW_SIM4_LABEL,"SIM4 network setting")
RES_ADD_STRING(TXT_JAVA_SELECT_NET_SIM1_NOT_OK,"SIM1 can't be used")
RES_ADD_STRING(TXT_JAVA_SELECT_NET_SIM2_NOT_OK,"SIM2 can't be used")
RES_ADD_STRING(TXT_JAVA_SELECT_NET_SIM3_NOT_OK,"SIM3 can't be used")
RES_ADD_STRING(TXT_JAVA_SELECT_NET_SIM4_NOT_OK,"SIM4 can't be used")

//RES_ADD_STRING(TXT_JAVA_PERMIT_ASK_FIRST,"Ask First Time")    //case3: defined but not used
// RES_ADD_STRING(TXT_JAVA_PERMIT_ASK_ALWAYS,"Ask Every Time")      //replaced by common ID TXT_COMMON_ASK_EVERYTIME
RES_ADD_STRING(TXT_JAVA_PERMIT_ALLOW_ALWAYS,"Always Allow")
RES_ADD_STRING(TXT_JAVA_PERMIT_NOT_ALLOW,"Not Allowed")
RES_ADD_STRING(TXT_JAVA_PERMIT_THIS_SESSION,"Ask First Time")
RES_ADD_STRING(TXT_JAVA_PERMIT_ONE_SHOT,"Ask Every Time")

RES_ADD_STRING(TXT_JAVA_PERMISSION_AUTOSTART,"Auto start")
RES_ADD_STRING(TXT_JAVA_PERMISSION_LOCALCONNECT,"Local connection")
RES_ADD_STRING(TXT_JAVA_PERMIT_LOW_NET,"Low net access")
RES_ADD_STRING(TXT_JAVA_PERMISSION_MSG,"Messaging")
RES_ADD_STRING(TXT_JAVA_PERMISSION_RECORD,"Recording")
RES_ADD_STRING(TXT_JAVA_PERMISSION_ACCESSNET,"Net access")
RES_ADD_STRING(TXT_JAVA_PERMIT_READ_INFO,"Read user data")
RES_ADD_STRING(TXT_JAVA_PERMIT_WRITE_INFO,"Write user data")

#ifdef SUPPORT_BACKGROUND_RUN
RES_ADD_STRING(TXT_JAVA_BGE_RESUME,    "Resume")
RES_ADD_STRING(TXT_JAVA_RESUME_WIN_TITLE,"Please select")
RES_ADD_STRING(TXT_JAVA_BGE_EXIT,      "Exit")    //replaced by common ID  STXT_EXIT
RES_ADD_STRING(TXT_JAVA_BGE_PAUSE,     "Pause")    //replaced by common ID  TXT_PAUSE
RES_ADD_STRING(TXT_JAVA_BGE_MINIMIZE,  "Minimize")  //replaced by common ID TXT_MINIMIZE
RES_ADD_STRING(TXT_JAVA_GOTO_FOREGROUND, "Goto Foreground")
RES_ADD_STRING(TXT_JAVA_QUIT_RUNNING_MIDLET,"is running in background, please quit it first.")
#endif

RES_ADD_STRING(TXT_JAVA_NO_STORAGE_ALERT,"No mobile storage device,Cannot run java!")
#ifdef JAVA_SUPPORT_TYPE_MVM
RES_ADD_STRING(TXT_JAVA_NO_ENOUGH_MEMORY,"Not enough memory to run. Please exit some other applications and try again.")
#else
RES_ADD_STRING(TXT_JAVA_NO_ENOUGH_MEMORY,"Not enough memory to run.")
#endif
RES_ADD_STRING(TXT_JAVA_DESTROY_FAIL,"Midlet is starting, Please try later...")

//RES_ADD_STRING(TXT_JAVA_VM_IS_FOREGROUND,"JVM is running foreground.")    //case3: defined but not used
RES_ADD_STRING(TXT_JAVA_SUITE_ID_INVALID,"Remove failed ,Please try again later!")
//]]define string infomation
RES_ADD_STRING(STXT_CLEAR,"Clear")

RES_ADD_STRING(TXT_JAVA_PREINSTALL_WRONG_PATH,"The application path is null.")
RES_ADD_STRING(TXT_JAVA_START_VM_FAILED,"Start VM failed!")

//[[define data infomation

//]]define data infomation


//[[define string infomation
RES_ADD_STRING(STR_MAIN_UNINSTALL_EXT01, "Uninstall this app?")
RES_ADD_STRING(STR_MAIN_APP_NOT_FIND_EXT01,"Can't find this app. Make sure your memory card is in place or reinstall the app. Do you want to remove the application from main menu?")
RES_ADD_STRING(STR_JAVA_WARNING_EXT01, "Details")
RES_ADD_STRING(STR_HDR_SELECT_MEMORY_EXT01, "Select memory")
//RES_ADD_STRING(STXT_PHONE, "Phone")
RES_ADD_STRING(STR_LIST_MEMORY_CARD_FLDR, "Memory Card")
//RES_ADD_STRING(STR_INSTALLED_APPS_EXT01, "Installed apps")//move to common_mdu_def
RES_ADD_STRING(STR_PERMISSION_EXT01, "Permission settings")
RES_ADD_STRING(STR_CONNECTIVITY_EXT01, "Connectivity")
RES_ADD_STRING(STR_INFO_EXT01, "Info")
RES_ADD_STRING(STR_JAVA_QUERY_INSTALLED_EXT01, "Installation finished. Do you want to run the application?")

// Myriad report JAVA MMI texts.
RES_ADD_STRING(STR_JAVA_BACKGROUND, "%U is running in the background. Close it and try again.")
RES_ADD_STRING(STR_JAVA_VM_BUSY,    "The Java Virtual Machine is starting or closing right now. Try again when it's done.")
RES_ADD_STRING(STR_JAVA_CLOSING,    "Closing...")
RES_ADD_STRING(STR_JAVA_NAME,       "Name:")
RES_ADD_STRING(STR_JAVA_SIZE,       "Size:")
RES_ADD_STRING(STR_JAVA_VERSION,    "Version:")
RES_ADD_STRING(STR_JAVA_VENDOR,     "Vendor:")
RES_ADD_STRING(STR_JAVA_URL,        "URL:")
RES_ADD_STRING(STR_JAVA_DOMAIN,     "Domain:")
RES_ADD_STRING(STR_JAVA_SIGNED,     "Signed by:")
RES_ADD_STRING(STR_JAVA_SERIAL,     "Serial number:")
RES_ADD_STRING(STR_JAVA_ISSUED,     "Issued by:")
RES_ADD_STRING(STR_JAVA_AUTHENTICATED,  "Authenticated by:")
RES_ADD_STRING(STR_JAVA_PUSHED,         "Pushed content:")
RES_ADD_STRING(STR_JAVA_NETWORK,        "Network selection")
RES_ADD_STRING(STR_JAVA_SIM1_NETWORK,   "SIM1 network settings")
RES_ADD_STRING(STR_JAVA_SIM2_NETWORK,   "SIM2 network settings")
RES_ADD_STRING(STR_JAVA_SIM1_NO,        "SIM1 can't be used")
RES_ADD_STRING(STR_JAVA_SIM2_NO,        "SIM2 can't be used")
RES_ADD_STRING(STR_JAVA_ALWAYS_ALLOW,   "Always allow")
RES_ADD_STRING(STR_JAVA_NOT_ALLOW,      "Never allow")
RES_ADD_STRING(STR_JAVA_ASK_FIRST,      "Ask first time")
RES_ADD_STRING(STR_JAVA_ASK_EVERY,      "Ask every time")
RES_ADD_STRING(STR_JAVA_AUTO_START,     "Auto start")
RES_ADD_STRING(STR_JAVA_LOCAL_CONNECTION,  "Local connection")
RES_ADD_STRING(STR_JAVA_MESSAGING,      "Messaging")
RES_ADD_STRING(STR_JAVA_RECORDING,      "Recording")
RES_ADD_STRING(STR_JAVA_NET_ACCESS,     "Net access")
RES_ADD_STRING(STR_JAVA_READ_DATA,      "Read user data")
RES_ADD_STRING(STR_JAVA_WRITE_DATA,     "Write user data")
RES_ADD_STRING(STR_JAVA_SELECT,         "Select option")
RES_ADD_STRING(STR_JAVA_RESUME,         "Resume")
RES_ADD_STRING(STR_JAVA_EXIT,           "Exit")
RES_ADD_STRING(STR_JAVA_PAUSE,          "Pause")
RES_ADD_STRING(STR_JAVA_NO_STORAGE,     "Can't find the system files to run the Java Virtual Machine.")
RES_ADD_STRING(STR_JAVA_NO_MEMORY,      "No available memory.")
RES_ADD_STRING(STR_JAVA_DELETE_APPS,    "Not enough space. Try deleting some Java apps and try again.")
RES_ADD_STRING(STR_JAVA_FILE_MISSING,   "MIDlet files are missing.")
RES_ADD_STRING(STR_JAVA_RUN_ERROR,      "Something went wrong. Try again.")
RES_ADD_STRING(STR_JAVA_REMOVE_FAIL,    "Could not delete. Try again.")
RES_ADD_STRING(STR_JAVA_START_FAIL,     "The Java Virtual Machine couldn't start. Try again.")
RES_ADD_STRING(STR_JAVA_BACKGROUND_QUERY,  "%U is running in background. What would you like to do?")
RES_ADD_STRING(STR_JAVA_OPERATE_ERROR,     "Something went wrong.")
RES_ADD_STRING(STR_JAVA_OPERATE_SUCCESS,   "All done! Successfully completed.")
RES_ADD_STRING(STR_JAVA_WAITING,           "Just a moment...")
RES_ADD_STRING(STR_JAVA_UD_IN_USE,         "Can't start Java because USB mass storage in use.")
RES_ADD_STRING(STR_JAVA_IN_CALL,           "Can't start Java because you're in a call. Try later.")
RES_ADD_STRING(STR_JAVA_MINIMIZE,          "Minimise")
RES_ADD_STRING(STR_JAVA_BACKGROUND_RUNNING,  "Java is running in the background. Close it before opening another app.")

//]]define string infomation
