

#ifndef _MMIJAVA_ID_H_
#define _MMIJAVA_ID_H_

/**--------------------------------------------------------------------------*
 **                         Include Files                                     *
 **--------------------------------------------------------------------------*/
#include <sci_types.h>
#include <os_api.h>
#include <mmk_type.h>
#include <mmi_module.h>
#include <mmk_app.h>
#include <mmijava_common.h>
#include <opl_global.h>

/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef __cplusplus
    extern "C"
    {
#endif

/**--------------------------------------------------------------------------*
 **                         MACRO DEFINITION                                 *
 **--------------------------------------------------------------------------*/


/**--------------------------------------------------------------------------*
 **                         TYPE AND CONSTANT                                *
 **--------------------------------------------------------------------------*/
#define WIN_ID_DEF(win_id)          win_id
typedef enum
{
    JAVA_WIN_ID_START = (MMI_MODULE_JAVA << 16),
    #include "mmijava_id.def"
    JAVA_MAX_WIN_ID
}JAVA_WINDOW_ID_E;

#undef WIN_ID_DEF

typedef enum
{
    MMIJAVA_CTRL_ID_START = JAVA_MAX_WIN_ID,
    MMIJAVA_SELECT_NETWORK_CTRL_ID,
    MMIJAVA_MAIN_MENU_WIN_CTRL_ID,
    MMIJAVA_SUITE_LIST_CTRL_ID,
    MMIJAVA_SUITE_LIST_FORM_CTRL_ID,
#ifdef MMI_PDA_SUPPORT
    MMIJAVA_TAB_CTRL_ID,
#endif
    MMIJAVA_MIDLET_LIST_WIN_CTRL_ID,
    MMIJAVA_INSTALLING_LABLE_CTRL_ID,
    MMIJAVA_INSTALLING_PROGRESS_CTRL_ID,
    MMIJAVA_INSTALLING_INFO_CRTL_ID,
    MMIJAVA_TM_LIST_CRTL_ID,
    MMIJAVA_TM_LIST_FORM_CTRL_ID,
    MMIJAVA_MAIN_OPTION_CRTL_ID,
    MMIJAVA_LOCAL_INSTALL_FILE_DETIAL_CRTL_ID,
    MMIJAVA_COMM_INFO_CRTL_ID,

     /*-------------- network setting --------------*/
    MMIJAVA_NW_SETTING_FATHER_FORM_CRTL_ID,

    MMIJAVA_NW_SETTING_CHOOSE_NET_FORM_CTRL_ID,
    MMIJAVA_NW_SETTING_CHOOSE_NET_TITLE_LABEL_CTRL_ID,
    MMIJAVA_NW_SETTING_CHOOSE_NET_TITLE_LABEL_EDIT_ID,

    MMIJAVA_NW_SETTING_SIM1_FORM_CTRL_ID,
    MMIJAVA_NW_SETTING_SIM1_TITLE_LABEL_CTRL_ID,
    MMIJAVA_NW_SETTING_SIM1_TITLE_LABEL_EDIT_ID,

    MMIJAVA_NW_SETTING_SIM2_FORM_CTRL_ID,
    MMIJAVA_NW_SETTING_SIM2_TITLE_LABEL_CTRL_ID,
    MMIJAVA_NW_SETTING_SIM2_TITLE_LABEL_EDIT_ID,

    MMIJAVA_NW_SETTING_SIM3_FORM_CTRL_ID,
    MMIJAVA_NW_SETTING_SIM3_TITLE_LABEL_CTRL_ID,
    MMIJAVA_NW_SETTING_SIM3_TITLE_LABEL_EDIT_ID,

    MMIJAVA_NW_SETTING_SIM4_FORM_CTRL_ID,
    MMIJAVA_NW_SETTING_SIM4_TITLE_LABEL_CTRL_ID,
    MMIJAVA_NW_SETTING_SIM4_TITLE_LABEL_EDIT_ID,

    MMIJAVA_NW_RADIO_CRTL_ID,

    /*-------------- permission setting --------------*/
    //start
    MMIJAVA_PM_SETTING_START,
    MMIJAVA_PM_SETTING_FATHER_FORM_CRTL_ID = MMIJAVA_PM_SETTING_START,

    //app autoplay
    MMIJAVA_APP_AUTOPLAY_FORM_CTRL_ID,
    MMIJAVA_APP_AUTOPLAY_TITLE_LABEL_CTRL_ID,
    MMIJAVA_APP_AUTOPLAY_TITLE_LABEL_EDIT_ID,

    //local connection
    MMIJAVA_LOCAL_CONNECT_FORM_CTRL_ID,
    MMIJAVA_LOCAL_CONNECT_TITLE_LABEL_CTRL_ID,
    MMIJAVA_LOCAL_CONNECT_TITLE_LABEL_EDIT_ID,

#ifdef JBED_MIDP_21
    //low level net access
    MMIJAVA_LOW_LEVEL_NET_FORM_CTRL_ID,
    MMIJAVA_LOW_LEVEL_NET_TITLE_LABEL_CTRL_ID,
    MMIJAVA_LOW_LEVEL_NET_TITLE_LABEL_EDIT_ID,
#endif

    //message
    MMIJAVA_MESSAGE_FORM_CTRL_ID,
    MMIJAVA_MESSAGE_TITLE_LABEL_CTRL_ID,
    MMIJAVA_MESSAGE_TITLE_LABEL_EDIT_ID,

    //multimedia
    MMIJAVA_MULTIMEDIA_FORM_CTRL_ID,
    MMIJAVA_MULTIMEDIA_TITLE_LABEL_CTRL_ID,
    MMIJAVA_MULTIMEDIA_TITLE_LABEL_EDIT_ID,

    //network link in
    MMIJAVA_NETWORK_LINK_FORM_CTRL_ID,
    MMIJAVA_NETWORK_LINK_TITLE_LABEL_CTRL_ID,
    MMIJAVA_NETWORK_LINK_TITLE_LABEL_EDIT_ID,

    //read user data
    MMIJAVA_READ_USERINFO_FORM_CTRL_ID,
    MMIJAVA_READ_USERINFO_TITLE_LABEL_CTRL_ID,
    MMIJAVA_READ_USERINFO_TITLE_LABEL_EDIT_ID,

    //write user data
    MMIJAVA_WRITE_USERINFO_FORM_CTRL_ID,
    MMIJAVA_WRITE_USERINFO_TITLE_LABEL_CTRL_ID,
    MMIJAVA_WRITE_USERINFO_TITLE_LABEL_EDIT_ID,

    MMIJAVA_PM_RADIO_CRTL_ID,
    MMIJAVA_PM_SETTING_END,
    //end

    MMIJAVA_IM_TEXT_EDIT_BOX_CTRL_ID,
    MMIJAVA_IM_TEXT_EDIT_BOX_MENU_CTRL_ID,
    MMIJAVA_IM_TEXT_EDIT_BOX_TICKER_CTRL_ID,
    MMIJAVA_PERMISSION_FG_NAME_CTRL_ID,
    MMIJAVA_PERMISSION_SETTING_CTRL_ID,
    MMIJAVA_STORAGE_SELECT_CTRL_ID,
    //For download set.
        MMIJAVA_DOWNLOAD_SET_FORM_ID,
    MMIJAVA_DOWNLOAD_SET_GAME_LABEL_ID,
    MMIJAVA_DOWNLOAD_SET_GAME_URL_INPUT_ID,
    MMIJAVA_DOWNLOAD_SET_GAME_FORM_ID,
        MMIJAVA_DOWNLOAD_SET_GAME_ENTER_BOTTON_ID,
        MMIJAVA_DOWNLOAD_SET_GAME_ENTER_SPACE_ID,
    MMIJAVA_DOWNLOAD_SET_EBOOK_LABEL_ID,
    MMIJAVA_DOWNLOAD_SET_EBOOK_URL_INPUT_ID,
    MMIJAVA_DOWNLOAD_SET_EBOOK_FORM_ID,
        MMIJAVA_DOWNLOAD_SET_EBOOK_ENTER_BOTTON_ID,
        MMIJAVA_DOWNLOAD_SET_EBOOK_ENTER_SPACE_ID,
    MMIJAVA_DOWNLOAD_SET_OTHER_LABEL_ID,
    MMIJAVA_DOWNLOAD_SET_OTHER_URL_INPUT_ID,
    MMIJAVA_DOWNLOAD_SET_OTHER_FORM_ID,
        MMIJAVA_DOWNLOAD_SET_OTHER_ENTER_BOTTON_ID,
        MMIJAVA_DOWNLOAD_SET_OTHER_ENTER_SPACE_ID,
    MMIJAVA_DOWNLOAD_SET_GAME_FORM1_ID,
    MMIJAVA_DOWNLOAD_SET_EBOOK_FORM1_ID,
    MMIJAVA_DOWNLOAD_SET_OTHER_FORM1_ID,
    MMIJAVA_ABOUT_CRTL_ID,
    //For redkey dialog
    MMIJAVA_REDKEY_DIALOG_LISTBOX_CTRL_ID,
#if defined(JAVA_SUPPORT_TYPE_SVM) && defined(SUPPORT_BACKGROUND_RUN)
    //if background run,launch check list id
    MMIJAVA_RESUME_BACKGROUND_LISTBOX_CTRL_ID,
#endif
    //For local install
    MMIJAVA_LOCAL_INSTALL_LISTBOX_CRTL_ID,
    MMIJAVA_LOCAL_INSTALL_MENU_OPTION_CRTL_ID,
#ifdef  VIRTUAL_KEY_BOARD
    MMIJAVA_KEYBOARD1_FORM,
    MMIJAVA_KEYBOARD2_FORM,
    MMIJAVA_KEYBOARD1_LINE_ONE_FORM,
    MMIJAVA_KEYBOARD1_LINE_TWO_FORM,
    MMIJAVA_KEYBOARD2_LINE_ONE_FORM,
    MMIJAVA_KEYBOARD2_LINE_TWO_FORM,

    MMIJAVA_KEYBOARD1_BOTTON_LFFT_SOFTKEY,
    MMIJAVA_KEYBOARD1_BOTTON_UP_KEY,
    MMIJAVA_KEYBOARD1_BOTTON_RIGHT_SOFTKEY,
    MMIJAVA_KEYBOARD1_BOTTON_NUM_KEY,
    MMIJAVA_KEYBOARD1_BOTTON_LEFT_KEY,
    MMIJAVA_KEYBOARD1_BOTTON_DOWN_KEY,
    MMIJAVA_KEYBOARD1_BOTTON_RIGHT_KEY,
    MMIJAVA_KEYBOARD1_BOTTON_OK_KEY,

    MMIJAVA_KEYBOARD2_BOTTON_LFFT_SOFTKEY,
    MMIJAVA_KEYBOARD2_BOTTON_NUM_KEY_1,
    MMIJAVA_KEYBOARD2_BOTTON_NUM_KEY_2,
    MMIJAVA_KEYBOARD2_BOTTON_NUM_KEY_3,
    MMIJAVA_KEYBOARD2_BOTTON_NUM_KEY_4,
    MMIJAVA_KEYBOARD2_BOTTON_NUM_KEY_5,
    MMIJAVA_KEYBOARD2_BOTTON_NUM_KEY_6,
    MMIJAVA_KEYBOARD2_BOTTON_RIGHT_SOFTKEY,
    MMIJAVA_KEYBOARD2_BOTTON_RETURN_KEY,
    MMIJAVA_KEYBOARD2_BOTTON_NUM_KEY_7,
    MMIJAVA_KEYBOARD2_BOTTON_NUM_KEY_8,
    MMIJAVA_KEYBOARD2_BOTTON_NUM_KEY_9,
    MMIJAVA_KEYBOARD2_BOTTON_NUM_KEY_0,
    MMIJAVA_KEYBOARD2_BOTTON_NUM_KEY_ASTERISK,
    MMIJAVA_KEYBOARD2_BOTTON_NUM_KEY_POUND,
    MMIJAVA_KEYBOARD2_BOTTON_OK_KEY,
#endif
    MMIJAVA_RESUME_BACKGROUND_FATHER_FORM_CRTL_ID,
    MMIJAVA_RESUME_BACKGROUND_NOTE_FORM_CRTL_ID,
    MMIJAVA_RESUME_BACKGROUND_NOTE_TEXT_CTRL_ID,
    MMIJAVA_MAX_CTRL_ID
}JAVA_CONTROL_ID_E;

/**--------------------------------------------------------------------------*
 **                         FUNCTION DEFINITION                              *
 **--------------------------------------------------------------------------*/

/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef   __cplusplus
    }
#endif

#endif

