//[[define string infomation
//RES_ADD_STRING(TXT_CP_STR_SIM_NO_SERVICE_EX01,"No service")
RES_ADD_STRING(TXT_CP_STR_EMERGENCY_ONLY_EX01 ,"Emergency calls only")
//RES_ADD_STRING(TXT_CP_STR_SIM_ERROR_EX01,"SIM error")
//RES_ADD_STRING(TXT_CP_STR_NSM_IND_NO_SIM,"No SIM Found")
//RES_ADD_STRING(TXT_CP_STR_SIM_LOCKED_EX01,"SIM Locked")
//RES_ADD_STRING(TXT_CP_STXT_VOLUMN_MK,"Volume")
//RES_ADD_STRING(TXT_CP_STXT_SIMPLEX_MODE_SEL_BEEP,"Beep")
//RES_ADD_STRING(TXT_CP_STXT_SIMPLEX_MODE_SEL_SILENT,"Silent")
//RES_ADD_STRING(TXT_CP_STR_PHONE_BRIGHTNESS_EX01,"Brightness")
//RES_ADD_STRING(TXT_CP_STR_BT_BLUETOOTH_EX01,"Bluetooth")
//RES_ADD_STRING(TXT_CP_STR_BT_VISIBLE_EX01,"Visible")
//RES_ADD_STRING(TXT_CP_STR_DATA_ON_EX01,"Data on")
//RES_ADD_STRING(TXT_CP_STR_DATA_OFF_EX01,"Data off")

//RES_ADD_STRING(TXT_CP_SIM_PREFERRED_TITLE,"Dual SIM")
//RES_ADD_STRING(TXT_CP_SIM1_PREFERRED,"SIM 1")
//RES_ADD_STRING(TXT_CP_SIM2_PREFERRED,"SIM 2")
//RES_ADD_STRING(TXT_CP_SIM_ALWAYS_ASK,"Always Ask")

//]]define string infomation
//[[define image infomation

//]]define image infomation
//[[define image tag infomation

//]]efine image tag infomation
