
#ifdef MMI_RECORD_SUPPORT
//[[define image infomation
#if defined (KEYPAD_TYPE_COMPACT_KEYPAD) || defined (KEYPAD_TYPE_FOUR_KEY_UNIVERSE)
//RES_ADD_IMG(IMAGE_RECORD_RECORD_AGAIN, "\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_RECORD_RECORD_AGAIN.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_STORAGE, "\\MMI_RES_##\\IMAG\\Optionsmenu_icon\\IMAGE_RECORD_STORAGE.png", IMG_CMP_PNG_ARGB_RLE, 0)
#endif

#ifdef MMI_GUI_STYLE_TYPICAL
//RES_ADD_IMG(IMAGE_RECORD_PLAY_BG, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_PLAY_BG.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_RECORD_BTN_DIS, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_RECORD_BTN_DIS.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_RECORD_BTN_UNSEL, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_RECORD_BTN_UNSEL.png", IMG_CMP_PNG_ARGB_RLE, 0)
#endif

#if !defined (KEYPAD_TYPE_COMPACT_KEYPAD) && !defined (KEYPAD_TYPE_FOUR_KEY_UNIVERSE)
//RES_ADD_IMG(IMAGE_RECORD_OK_ICON, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_OK_ICON.png", IMG_CMP_PNG_ARGB_RLE, 0)
#endif

#if !defined MMI_GUI_STYLE_TYPICAL && !defined MMI_RECORD_MINI_SUPPORT

RES_ADD_IMG(IMAGE_RECORD_NEEDLE_BG, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NEEDLE_BG.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_NEEDLE_MASK, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NEEDLE_MASK.png", IMG_CMP_PNG_ARGB_RLE, 0)

#endif

#if !defined MMI_GUI_STYLE_TYPICAL && !defined MMI_RECORD_MINI_SUPPORT || defined TOUCHPANEL_TYPE
RES_ADD_IMG(IMAGE_RECORD_NEEDLE, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NEEDLE.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_VOLUME, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_VOLUME.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_VOLUME_MUTE, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_VOLUME_MUTE.png", IMG_CMP_PNG_ARGB_RLE, 0)

//RES_ADD_IMG(IMAGE_RECORD_RECORD_BTN_PDA_UNSEL, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_RECORD_BTN_PDA_DEFAULT.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_LIST_BTN_UNSEL, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_LIST_BTN_DEFAULT.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_BACK_BTN_UNSEL, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_BACK_BTN_UNSEL.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_OPTION_BTN_UNSEL, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_OPTION_BTN_UNSEL.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_PLAY_BTN_UNSEL, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_PLAY_BTN_DEFAULT.png", IMG_CMP_PNG_ARGB_RLE, 0)
#endif


#ifndef MMI_GUI_STYLE_TYPICAL
RES_ADD_IMG(IMAGE_RECORD_NUMBER_0, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NUMBER_0.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_NUMBER_1, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NUMBER_1.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_NUMBER_2, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NUMBER_2.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_NUMBER_3, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NUMBER_3.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_NUMBER_4, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NUMBER_4.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_NUMBER_5, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NUMBER_5.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_NUMBER_6, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NUMBER_6.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_NUMBER_7, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NUMBER_7.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_NUMBER_8, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NUMBER_8.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_NUMBER_9, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NUMBER_9.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_NUMBER_POINT, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NUMBER_POINT.png", IMG_CMP_PNG_ARGB_RLE, 0)

#if (!defined RECORD_BARPHONE_UI_STYLE_SUPPORT) || (defined MMI_RECORD_MINI_SUPPORT)
RES_ADD_IMG(IMAGE_RECORD_NUMBER_BG, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NUMBER_BG.png", IMG_CMP_PNG_SABM_RLE | SABM_HOR_STRETCH, 0)
#else
RES_ADD_IMG(IMAGE_RECORD_NUMBER_BG, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_NUMBER_BG_NEWBARUI.png", IMG_CMP_PNG_SABM_RLE | SABM_HOR_STRETCH, 0)
#endif

RES_ADD_IMG(IMAGE_RECORD_PLAY_BK_BG, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_OSD_BG.png", IMG_CMP_PNG_SABM_RLE | SABM_HOR_STRETCH, 0)
//RES_ADD_IMG(IMAGE_RECORD_RECORD_BG, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_RECORD_BG.png", IMG_CMP_PNG_SABM_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_RECORD_PDA_BG, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_BG.png", IMG_CMP_PNG_SABM_RLE | SABM_TILE, 0)

//RES_ADD_IMG(IMAGE_RECORD_BG_ANIM_FRAME_1, "\\MMI_RES_##\\ANIM\\ANIM_RECORD_PLAY\\1.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_BG_ANIM_FRAME_2, "\\MMI_RES_##\\ANIM\\ANIM_RECORD_PLAY\\2.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_BG_ANIM_FRAME_3, "\\MMI_RES_##\\ANIM\\ANIM_RECORD_PLAY\\3.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_BG_ANIM_FRAME_4, "\\MMI_RES_##\\ANIM\\ANIM_RECORD_PLAY\\4.png", IMG_CMP_PNG_ARGB_RLE, 0)
#endif

#if !defined MMI_GUI_STYLE_TYPICAL && !defined MMI_RECORD_MINI_SUPPORT
//#ifndef RECORD_BARPHONE_UI_STYLE_SUPPORT
//RES_ADD_IMG(IMAGE_RECORD_PLAY_BTN_FOCUSE, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_PLAY_BTN_PRESSED.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_PLAY_STOP_BTN_FOCUS, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_PLAY_STOP_BTN_PRESSED.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_PLAY_STOP_BTN_UNSEL, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_PLAY_STOP_BTN_DEFAULT.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_RECORD_BTN_PDA_DIS, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_RECORD_BTN_PDA_DISABLED.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_RECORD_BTN_PDA_FOCUS, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_RECORD_BTN_PDA_PRESSED.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_RECORD_PAUSE_BTN_FOCUS, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_RECORD_PAUSE_BTN_PRESSED.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_RECORD_PAUSE_BTN_UNSEL, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_RECORD_PAUSE_BTN_DEFAULT.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_STOP_BTN_DIS, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_STOP_BTN_DISABLED.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_STOP_BTN_FOCUS, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_STOP_BTN_PREESED.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_STOP_BTN_UNSEL, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_STOP_BTN_DEFAULT.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_LIST_BTN_DIS, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_LIST_BTN_DISABLED.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_LIST_BTN_FOCUS, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_LIST_BTN_PRESSED.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_OPTION_BTN_FOCUS, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_OPTION_BTN_FOCUS.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_OPTION_BTN_DIS, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_OPTION_BTN_DIS.png", IMG_CMP_PNG_ARGB_RLE, 0)
//RES_ADD_IMG(IMAGE_RECORD_BACK_BTN_FOCUS, "\\MMI_RES_##\\IMAG\\IMAGE_RECORD_BACK_BTN_FOCUS.png", IMG_CMP_PNG_ARGB_RLE, 0)
//#endif
#endif
//]]define image infomation


//[[define anim infomation
//]]define anim infomation


//[[define string infomation
//RES_ADD_STRING(TXT_RECORD_NULL,"")          //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_FILENAME,"File name")        //case3£ºdefined but not used
RES_ADD_STRING(TXT_RECORD_OPTION, "Record option")
//RES_ADD_STRING(TXT_RECORD_START,"Start record")      //replaced by common ID TXT_CC_STARTRECORD
//RES_ADD_STRING(TXT_RECORD_LIST,"Record list")            //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_PLAY,"Play record")        //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_APPEND,"Append record")        //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_DETAIL,"Detail")           //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_RENAME,"Rename")     //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_SETTORING,"Set as call ring")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_SETTOLEAVEWORD,"Set to leave word")        //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_DELETE,"Delete")          //replaced by common ID TXT_DELETE
//RES_ADD_STRING(TXT_RECORD_DELETEALL,"Delete all")          //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_PAUSE,"Pause")    //replaced by common ID  TXT_PAUSE
//RES_ADD_STRING(TXT_RECORD_RESUME,"Resume")     //replaced by common ID TXT_COMMON_COMMON_CONTINUE
//RES_ADD_STRING(TXT_RECORD_STOP,"Stop")    //replaced by common ID  STXT_STOP
//RES_ADD_STRING(TXT_RECORD_HEADERROR,"Head error")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_WRITEERROR,"Write error")     //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_PLAYCOMPLETE,"Play complete")       //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_PLAYERROR,"Play error")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_EMPTYNAME,"Name is null")        //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_SAMENAME,"Same name")         //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_NORECORD,"No record")          //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_UDISKNORECORD,"No record")    //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_RECORDING,"Recording")       //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_PAUSED,"Paused")        //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_PLAYING,"Playing")       //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_MAX_FILE,"Max file")         //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_TERMINATED,"Record terminated!")        //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_STORAGE_SETTING,"Record storage")         //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_STORAGE_UDISK,"Phone")       //replaced by common ID TXT_COMMON_UDISK
//RES_ADD_STRING(TXT_RECORD_STORAGE_SDCARD,"Storage card")  //replaced by common ID TXT_COMMON_SD_CARD
//RES_ADD_STRING(TXT_RECORD_LEAVEWORD,"Leav")        //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_LEAVEWORD_OPTION,"Option")       //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_LEAVEWORD_ITEM,"Select")        //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_LEAVEWORD_RECORD,"Listen")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_LEAVEWORD_ITEM1,"Leave word 1")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_LEAVEWORD_ITEM2,"Leave word 2")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_LEAVEWORD_OWN,"Own leave word")     //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_LEAVEWORD_PLAY,"Play")       //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_LEAVEWORD_DETAIL,"Detail")        //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_LEAVEWORD_DELETE,"Delete")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_FILE_LIST,"Record file list")    //replaced by common ID TXT_COMMON_RECORD_FILE_LIST
RES_ADD_STRING(TXT_RECORD_AGAIN, "Record again")
//RES_ADD_STRING(TXT_RECORD_SEND,"Send")   //replaced by common ID TXT_SEND
//RES_ADD_STRING(TXT_RECORD_FILE,"Record files")      //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_SAVEASASPRING,"Save successfully,if set it as asp ring now?")         //case3£ºdefined but not used
//RES_ADD_STRING(TXT_RECORD_STORE_FORMAT,"File formats")//andy.he_record  format style    //replaced by common ID TXT_FILE_FORMAT
RES_ADD_STRING(TXT_RECORD_FORMATWAV, "wav")
RES_ADD_STRING(TXT_RECORD_FORMATMP3, "mp3")
RES_ADD_STRING(TXT_RECORD_FORMATAMR, "AMR")
RES_ADD_STRING(TXT_RECORD_SAVEASCALENDARRING, "Save successfully,if set it as calendar ring now?")

RES_ADD_STRING(TXT_RECORD_SAVEASALARM, "Save successfully,if set it as alarm ring now?")
RES_ADD_STRING(TXT_RECORD_SAVEAINSERTRECORD, "Save successfully,if set it as inserted record now?")
RES_ADD_STRING(TXT_RECORD_SAVEAINSERTRECORD_TIMEOUT, "Time out!Save successfully,if set it as inserted record now?")
//RES_ADD_STRING(TXT_RECORD_SAVEAINSERTRECORD_SIZEOUT,"Size out!Save successfully,if set it as inserted record now?")        //case3£ºdefined but not used
RES_ADD_STRING(TXT_RECORD_INSERT, "Insert Record")
//]]define string infomation
//#endif
//add for recorder ms ui
RES_ADD_IMG(IMAGE_RECORD_INDICATOR, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_INDICATOR.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_LIST, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDINGS_LIST.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RECORDING_CANCEL, "\\MMI_RES_##\\IMAG\\IMAGE_COMMON_CANCEL.png", IMG_CMP_PNG_ARGB_RLE, 0)

#ifdef MMI_COMPILE_E
RES_ADD_IMG(IMAGE_RECORD_BLUE_1, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_1_BLUE.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_BLUE_2, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_2_BLUE.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_BLUE_3, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_3_BLUE.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_BLUE_4, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_4_BLUE.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_BLUE_5, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_5_BLUE.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_BLUE_6, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_6_BLUE.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_BLUE_7, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_7_BLUE.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_BLUE_8, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_8_BLUE.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_BLUE_9, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_9_BLUE.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_BLUE_10, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_10_BLUE.png", IMG_CMP_PNG_ARGB_RLE, 0)
#else//8910UIX
RES_ADD_IMG(IMAGE_RECORD_RED_1, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_1_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_2, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_2_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_3, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_3_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_4, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_4_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_5, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_5_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_6, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_6_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_7, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_7_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_8, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_8_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_9, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_9_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_10, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_10_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
#endif
/*

RES_ADD_IMG(IMAGE_RECORD_RED_1, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_1_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_2, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_2_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_3, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_3_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_4, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_4_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_5, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_5_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_6, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_6_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_7, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_7_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_8, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_8_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_9, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_9_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RED_10, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_10_RED.png", IMG_CMP_PNG_ARGB_RLE, 0)

RES_ADD_IMG(IMAGE_RECORD_COPPER_1, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_1_COPPER.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_COPPER_2, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_2_COPPER.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_COPPER_3, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_3_COPPER.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_COPPER_4, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_4_COPPER.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_COPPER_5, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_5_COPPER.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_COPPER_6, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_6_COPPER.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_COPPER_7, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_7_COPPER.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_COPPER_8, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_8_COPPER.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_COPPER_9, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_9_COPPER.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_COPPER_10, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_10_COPPER.png", IMG_CMP_PNG_ARGB_RLE, 0)

RES_ADD_IMG(IMAGE_RECORD_GREEN_1, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_1_GREEN.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_GREEN_2, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_2_GREEN.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_GREEN_3, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_3_GREEN.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_GREEN_4, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_4_GREEN.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_GREEN_5, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_5_GREEN.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_GREEN_6, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_6_GREEN.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_GREEN_7, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_7_GREEN.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_GREEN_8, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_8_GREEN.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_GREEN_9, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_9_GREEN.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_GREEN_10, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_10_GREEN.png", IMG_CMP_PNG_ARGB_RLE, 0)

RES_ADD_IMG(IMAGE_RECORD_VIOLET_1, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_1_VIOLET.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_VIOLET_2, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_2_VIOLET.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_VIOLET_3, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_3_VIOLET.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_VIOLET_4, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_4_VIOLET.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_VIOLET_5, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_5_VIOLET.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_VIOLET_6, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_6_VIOLET.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_VIOLET_7, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_7_VIOLET.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_VIOLET_8, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_8_VIOLET.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_VIOLET_9, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_9_VIOLET.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_VIOLET_10, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_10_VIOLET.png", IMG_CMP_PNG_ARGB_RLE, 0)

RES_ADD_IMG(IMAGE_RECORD_YELLOW_1, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_1_YELLOW.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_YELLOW_2, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_2_YELLOW.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_YELLOW_3, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_3_YELLOW.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_YELLOW_4, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_4_YELLOW.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_YELLOW_5, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_5_YELLOW.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_YELLOW_6, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_6_YELLOW.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_YELLOW_7, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_7_YELLOW.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_YELLOW_8, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_8_YELLOW.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_YELLOW_9, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_9_YELLOW.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_YELLOW_10, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDING_10_YELLOW.png", IMG_CMP_PNG_ARGB_RLE, 0)
*/
RES_ADD_IMG(IMAGE_RECORD_PAUSE, "\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_PAUSE.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RECORD, "\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_RECORD.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_STOP, "\\MMI_RES_##\\IMAG\\IMAGE_CAMERA_STOP.png", IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_RECORD_RECORDING_BACK, "\\MMI_RES_##\\IMAG\\IMAGE_VOICE_RECORDER_RECORDINGS_BACK.png", IMG_CMP_PNG_ARGB_RLE, 0)

RES_ADD_STRING(TXT_RECORD_MS_RECORDING,"Recording")
RES_ADD_STRING(TXT_RECORD_MS_RECORDINGS,"Recordings")
RES_ADD_STRING(TXT_RECORD_MS_RECORDINGG,"Recording...")
RES_ADD_STRING(TXT_RECORD_MS_PAUSED,"Paused")
RES_ADD_STRING(TXT_RECORD_MS_SAVE,"Recording saved.")
RES_ADD_STRING(TXT_RECORD_MS_RECORDER,"Recorder")
RES_ADD_STRING(TXT_RECORD_MS_NO_RECORD,"You have not recorded anything yet.")
RES_ADD_STRING(TXT_RECORD_MS_DELETE_RECORD,"Delete this recording?")
RES_ADD_STRING(TXT_RECORD_MS_SHARE,"Share")
RES_ADD_STRING(TXT_RECORD_MS_RENAME,"Rename")
RES_ADD_STRING(TXT_RECORD_MS_DELETE_ALL,"Delete all")
RES_ADD_STRING(TXT_RECORD_MS_IS_DELETE_ALL,"Delete all recordings?")
RES_ADD_STRING(TXT_RECORD_MS_DELETED,"Recordings deleted.")
//end

//longjunhao
RES_ADD_STRING(STR_RADIO_PRMPT_NAME_REC_EXT01,"Recording")
//RES_ADD_STRING(STR_MENU_SINGLE_GAL_VOICE_MEMO,"Recordings")
//RES_ADD_STRING(STR_RECORDINGS_FOLDER_EMPTY_EXT01,"You have not recorded anything yet.")
RES_ADD_STRING(STR_HDR_RECORDING_EXT01,"Recording...")
RES_ADD_STRING(STR_HDR_PAUSED_EXT01,"Paused")
RES_ADD_STRING(STR_RECORDING_SAVED_EXT01,"Recording saved.")
RES_ADD_STRING(STR_RECORDING_DELETED_EXT01,"Recording deleted.")
RES_ADD_STRING(STR_RECORDING_CANCEL_EXT01,"Do you want to cancel this recording?")
//RES_ADD_STRING(STR_RECORDINGS_DELETED_EXT01,"Recordings deleted.")
//end
#endif
//[[define data infomation
//]]define data infomation
