
//JPG_DEC_SUPPORT macro is different in simulator and arm.
#ifdef JPG_DEC_SUPPORT_JPG_HW
#define WALLPAPER_FMT   IMG_CMP_JPG_SCI
#else
#define WALLPAPER_FMT   IMG_CMP_JPG_STD
#endif

#ifdef MMI_SETTING_CUTDOWN_WALLPAPER
#define MMISET_WALLPAPER_USER_MAX_NUM      1
#else
#define MMISET_WALLPAPER_USER_MAX_NUM      3
#endif

#define MMISET_WALLPAPER_OPER_MAX_NUM      3
#define MMISET_WALLPAPER_RES_MAX_NUM      5

#ifdef NEW_RESOURCE_SUPPORT
RES_ADD_IMG_RANGE(IMAGE_WALLPAPER, MMISET_WALLPAPER_USER_MAX_NUM, "\\MMI_RES_##\\IMAG2\\staticwallpaper\\IMAGE_WALLPAPER_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG_RANGE(IMAGE_WALLPAPER_THUMB, MMISET_WALLPAPER_USER_MAX_NUM, "\\MMI_RES_##\\IMAG2\\staticwallpaper\\IMAGE_WALLPAPER_THUMB_1.jpg",WALLPAPER_FMT,0)
RES_ADD_IMG_TAG_RANGE(IMAGE_WALLPAPER, MMISET_WALLPAPER_USER_MAX_NUM, "IMAGE_WALLPAPER")
#else
RES_ADD_IMG_RANGE(IMAGE_WALLPAPER, MMISET_WALLPAPER_USER_MAX_NUM, "\\MMI_RES_##\\IMAG\\staticwallpaper\\IMAGE_WALLPAPER_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG_RANGE(IMAGE_WALLPAPER_THUMB, MMISET_WALLPAPER_USER_MAX_NUM, "\\MMI_RES_##\\IMAG\\staticwallpaper\\IMAGE_WALLPAPER_THUMB_1.jpg",WALLPAPER_FMT,0)
RES_ADD_IMG_TAG_RANGE(IMAGE_WALLPAPER, MMISET_WALLPAPER_USER_MAX_NUM, "IMAGE_WALLPAPER")
#endif

#ifdef QBTHEME_SUPPORT
//RES_ADD_IMG(IMAGE_WALLPAPER_1_PREVIEW,"\\MMI_RES_##\\IMAG\\staticwallpaper\\IMAGE_WALLPAPER_1_PREVIEW.bmp",IMG_CMP_BMP_16_565_RLE,0)
#endif

//background

RES_ADD_IMG_QBTHEME_MAP(IMAGE_WALLPAPER_1, MMISET_WALLPAPER_USER_MAX_NUM,  L"\\Desktop\\Wallpaper", -1)
